cmd/agent/main.go
=> exit process after error validating config or starting server

example/grafana/dashboards/agent-operational.json, production/grafana-agent-mixin/mixin.libsonnet, production/kubernetes/agent.yaml
This to puts all dashboards in a Agent folder by default.
Signed-off-by: Cyril Tovena <cyril.tovena@gmail.com>
=> Add grafanaDashboardFolder in the mixin

cmd/agent/Dockerfile
=> cmd/agent: Dockerfile should be a release build by default

cmd/agent/main.go, docs/api.md
These are the same as the Prometheus implementation, except with `s/Prometheus/Agent/g`.
Closes #52. 
Blocked by #53. I've set the base branch to #53's to make the diff reviewable, but this should **not** be merged until it's set to merge to master.
=> Add healthiness and readiness handlers

pkg/prometheus/ha/codec.go, pkg/prometheus/ha/codec_test.go, pkg/prometheus/ha/sharding.go, pkg/prometheus/ha/sharding_test.go
Fixes #62.
/cc @gotjosh, @hoenn: no rush on getting this merged, waiting until Monday is fine
=> pkg/prometheus/ha: store and hash secrets properly

Makefile, pkg/prom/ha/http_test.go, pkg/prom/ha/server.go, pkg/prom/ha/server_test.go, pkg/prom/ha/sharding_test.go
This PR fixes the various flakes CI has been having lately.
=> Fix race conditions and flaky CI

pkg/prom/instance/instance.go
A data race started showing up for the macOS CI builds. It turns out that `scrape.NewManager` sets a value for a global when called. To prevent a data race, we're now protecting that call with a global mutex.
=> fix data race in pkg/prom/instance

pkg/integrations/node_exporter/config.go
=> fix default settings for filesystem collector on linux

pkg/prom/instance/instance.go
This doesn't do anything right now, but it sets up the groundwork for calling ApplyConfig against components from outside of the Run method. 
Related to #140.
=> Store prometheus components in Instance

CHANGELOG.md, docs/configuration-reference.md, docs/getting-started.md, production/README.md, production/kubernetes/README.md, production/kubernetes/agent.yaml, production/kubernetes/build/template/main.jsonnet, production/kubernetes/install.sh
First step of the release per the [release guide](https://github.com/grafana/agent/blob/master/docs/maintaining.md#performing-the-release)
=> prepare for 0.5.0 release

docs/configuration-reference.md, pkg/config/config.go, pkg/integrations/manager.go
=> Add flag to replace instance label with agent hostname

production/README.md
=> Modify README with up-to-date tanka instructions

docs/overview.md, docs/scraping-service.md
Just some increased clarity and typo fixes I found.
=> Minor documentation cleanup

docs/README.md, docs/getting-started.md, docs/overview.md
This PR makes reference to the Loki/Promtail support throughout the docs and includes a full configuration example.
=> Document loki support

Makefile, cmd/agent/Dockerfile, cmd/agentctl/Dockerfile
There's no compelling reason we need to upgrade, but why not? 🤷‍♂️
=> update to go 1.15

docs/configuration-reference.md
=> Typo fix in configuration-reference.md

CHANGELOG.md, Makefile, docs/configuration-reference.md, docs/getting-started.md, production/README.md, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-tempo.yaml, production/kubernetes/agent.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/kubernetes/install-loki.sh, production/kubernetes/install-tempo.sh, production/kubernetes/install.sh, production/tanka/grafana-agent/v1/main.libsonnet
v0.7.0 wasn't building the ARM binaries on `make dist`, need to do a small patch release.
=> prepare for v0.7.1 release and fix arm binaries

CHANGELOG.md, packaging/deb/control/prerm, tools/test-packages
Also adds package removal to the `test-packages` script.
=> fix: Use correct removal check in deb prerm script

CHANGELOG.md, cmd/agent/agent-integrations-config.yaml, docs/configuration-reference.md, example/docker-compose/docker-compose.integrations.yaml, go.mod, go.sum, pkg/integrations/dnsmasq_exporter/config.go, pkg/integrations/dnsmasq_exporter/dnsmasq_exporter.go, pkg/integrations/manager.go, vendor/github.com/google/dnsmasq_exporter/LICENSE, vendor/github.com/google/dnsmasq_exporter/collector/collector.go, vendor/modules.txt
If you use `examples/docker-compose/docker-compose.integrations.yaml` and `cmd/agent/agent-integrations-config.yaml`, you can test this and verify that it's working.
=> embed dnsmasq_exporter

docs/maintaining.md
Updates the release instructions to more accurately represent the current process, including a bit of prerelease testing.
=> Update release instructions

CHANGELOG.md, cmd/agentctl/main.go, pkg/agentctl/samples.go
This helped investigating which series/samples are within a WAL file.
=> Add samples cmd to agentctl

docs/overview.md
whoops double "to"
Typo fix in overview doc
- [NA] CHANGELOG updated 
=> Fix typo in Overview doc

.github/depcheck.yml, CHANGELOG.md, cmd/agent/agent-integrations-config.yaml, docs/configuration-reference.md, example/docker-compose/docker-compose.integrations.yaml, go.mod, go.sum, pkg/integrations/consul_exporter/consul_exporter.go, pkg/integrations/manager.go, vendor/github.com/prometheus/consul_exporter/LICENSE, vendor/github.com/prometheus/consul_exporter/NOTICE, vendor/github.com/prometheus/consul_exporter/pkg/exporter/consul_exporter.go, vendor/modules.txt
Adds [`consul_exporter`](https://github.com/prometheus/consul_exporter) as an integration.
In draft until Consul is added to the test environment.
=> add consul_exporter integration

CHANGELOG.md, go.mod, go.sum, pkg/config/config.go, pkg/config/config_test.go, vendor/github.com/drone/envsubst/.drone.yml, vendor/github.com/drone/envsubst/.gitignore, vendor/github.com/drone/envsubst/LICENSE, vendor/github.com/drone/envsubst/README, vendor/github.com/drone/envsubst/eval.go, vendor/github.com/drone/envsubst/funcs.go, vendor/github.com/drone/envsubst/go.mod, vendor/github.com/drone/envsubst/go.sum, vendor/github.com/drone/envsubst/parse/node.go, vendor/github.com/drone/envsubst/parse/parse.go, vendor/github.com/drone/envsubst/parse/scan.go, vendor/github.com/drone/envsubst/path/match.go, vendor/github.com/drone/envsubst/template.go, vendor/modules.txt
It would be a great feature to expand the configuration file with environment variables like described in issue #280.
Fixes #280 Expand config file with environment variables
=> Config file environment expansion

CHANGELOG.md, docs/configuration-reference.md, docs/getting-started.md, production/README.md, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-tempo.yaml, production/kubernetes/agent.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/kubernetes/install-loki.sh, production/kubernetes/install-tempo.sh, production/kubernetes/install.sh, production/tanka/grafana-agent/v1/main.libsonnet
=> prepare for 0.9.0 release

CHANGELOG.md, docs/configuration-reference.md, docs/getting-started.md, production/README.md, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-tempo.yaml, production/kubernetes/agent.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/kubernetes/install-loki.sh, production/kubernetes/install-tempo.sh, production/kubernetes/install.sh, production/tanka/grafana-agent/v1/main.libsonnet
New release that supports the new Grafana Cloud install script.
=> prepare for 0.9.1 release

CHANGELOG.md, Makefile, docs/configuration-reference.md, docs/getting-started.md, production/README.md, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-sigv4.yaml, production/kubernetes/agent-tempo.yaml, production/kubernetes/agent.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/kubernetes/install-loki.sh, production/kubernetes/install-sigv4.sh, production/kubernetes/install-tempo.sh, production/kubernetes/install.sh, production/tanka/grafana-agent/v1/main.libsonnet
Release testing looks good. Found one hidden problem from #336 which is fixed by disabling the unneeded CGO_ENABLED=1 in agentctl builds.
=> prepare for v0.11.0 release

README.md
Adds "and traces" to the main readme so readers will know that grafana-agent will handle trace data as well.
=> And Traces!

.github/depcheck.yml
This documents depcheck.yml slightly better so contributors know where to add new dependencies.
=> document depcheck.yml file better

.github/workflows/scripts.yml, production/grafanacloud-install.sh, production/kubernetes/build/build.sh, production/kubernetes/install-bare.sh, production/kubernetes/install-loki.sh, production/kubernetes/install-sigv4.sh, production/kubernetes/install-tempo.sh, production/kubernetes/install.sh
This is just a small change that enables linting with ShellCheck for the Agent install script.
=> Lint scripts with ShellCheck.

CHANGELOG.md, cmd/agent/main.go, docs/configuration-reference.md, docs/getting-started.md, docs/migration-guide.md, example/docker-compose/agent/config/agent.yaml, example/docker-compose/docker-compose.yaml, pkg/loki/loki.go, pkg/tempo/config.go, pkg/tempo/config_test.go, pkg/tempo/instance.go, pkg/tempo/tempo.go, production/kubernetes/agent-tempo.yaml, production/tanka/grafana-agent/v1/main.libsonnet
⚠️  BREAKING CHANGE ⚠️ 
Supports multiple tempo instances. This is a breaking change in the same vein as #353. 
Closes #320
=> pkg/tempo: support multiple instances of tempo (BREAKING CHANGE)

production/kubernetes/agent-sigv4.yaml, production/kubernetes/agent.yaml, production/tanka/grafana-agent/config.libsonnet, production/tanka/grafana-agent/v1/internal/kubernetes_instance.libsonnet
Removes TLS config and bearer tokens for scrape configs that don't require them. Related to https://github.com/grafana/jsonnet-libs/issues/442.
None
=> fix: Remove unnecessary tls and bearer tokens

.github/workflows/test.yml, .gitignore, Makefile
* Combines Build and Test into one job
* Only builds amd64 packages for test-packages, which should speed up the job. 
* Sync up build flags used for building/testing to minimize what needs to be recompiled.
=> Speed up CI

pkg/prom/cluster/node_test.go
gRPC service can't be registered after calling Serve on the gRPC server. Since Serve was being called in a separate goroutine, it was a race condition for whether it would fail.
=> fix race condition in pkg/prom/cluster/node_test.go

pkg/tempo/instance.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
Update some comments and log messages.
=> Update some comments

cmd/agent/entrypoint.go, cmd/agent/main.go, cmd/agent/service_windows.go, pkg/tempo/tempo.go, pkg/tempo/tempo_test.go, pkg/util/logger.go, pkg/util/logger_test.go
Ability to reload the logger with a new log level.
Part of #147. 
🤷
=> Allow changing log levels at runtime

CHANGELOG.md, docs/configuration-reference.md, example/docker-compose/agent/config/agent-local.yaml, example/docker-compose/agent/config/agent.yaml, example/docker-compose/agent/instance-configs/avalanche-1.yaml, pkg/config/config.go, pkg/config/config_test.go, pkg/prom/agent.go, pkg/prom/agent_test.go, pkg/prom/instance/global.go, pkg/prom/instance/instance.go, pkg/prom/instance/instance_integration_test.go, pkg/prom/instance/instance_test.go, production/tanka/grafana-agent/v1/README.md, production/tanka/grafana-agent/v1/lib/prometheus.libsonnet
Moves the shared `remote_write` list to the `global` block.
Closes #505.
=> move shared remote_write block to global config

production/tanka/grafana-agent/v1/lib/prometheus.libsonnet
=> jsonnet: fix bug where withRemoteWrite set the wrong field 

CHANGELOG.md, Makefile
Add installer to dist-agent which rolled up to dist
Closes #521
=> Add installer to output

CHANGELOG.md, docs/configuration-reference.md, docs/getting-started.md, production/README.md, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-sigv4.yaml, production/kubernetes/agent-tempo.yaml, production/kubernetes/agent.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/kubernetes/install-loki.sh, production/kubernetes/install-sigv4.sh, production/kubernetes/install-tempo.sh, production/kubernetes/install.sh, production/tanka/grafana-agent/v1/main.libsonnet
Backports v0.13.1 release to the main branch.
=> Backport v0.13.1 release from release-v0.13.1

packaging/windows/install_script.nsis
Setup the Grafana Agent to start automatically instead of manual.
maked the installer and tested it on my VM
- [NA] CHANGELOG updated 
=> Setup the service to start automatically

docs/configuration-reference.md
Fixes syntax for URL
_<none>_
_<none>_
=> Fix syntax for URL

pkg/tempo/automaticloggingprocessor/automaticloggingprocessor.go
Add process tags to span and root logs
None
Did not add anything to the CHANGELOG as no releases have happened since autologging was introduced
=> Include process kv in span and root logs

CHANGELOG.md, cmd/agent/entrypoint.go, docs/configuration-reference.md, docs/migration-guide.md, example/docker-compose/agent/config/agent-scraping-service.yaml, example/docker-compose/agent/config/agent.yaml, pkg/prom/agent_test.go, pkg/prom/http_test.go, pkg/prom/instance/instance.go, pkg/prom/instance/manager.go, pkg/prom/instance/manager_test.go, pkg/prom/instance/noop.go, pkg/tempo/config.go, pkg/tempo/config_test.go, pkg/tempo/contextkeys/keys.go, pkg/tempo/instance.go, pkg/tempo/remotewriteexporter/exporter.go, pkg/tempo/remotewriteexporter/exporter_test.go, pkg/tempo/remotewriteexporter/factory.go, pkg/tempo/tempo.go, pkg/tempo/tempo_test.go
=> Remote write for span metrics

CHANGELOG.md
#597 got merged prior to the release cut, so it's going to be a part of the release.
=> 0.14.0: add bug fix

.github/workflows/force_release.yml
=> add workflow to manually trigger a release against a self-hosted runner

CHANGELOG.md, docs/configuration-reference.md, docs/migration-guide.md, example/docker-compose/agent/config/agent.yaml, pkg/config/config_test.go, pkg/tempo/automaticloggingprocessor/automaticloggingprocessor.go, pkg/tempo/automaticloggingprocessor/automaticloggingprocessor_test.go, pkg/tempo/automaticloggingprocessor/factory.go, pkg/tempo/config.go, pkg/tempo/config_test.go
Adds the option to log to stdout instead of into a Loki instance.
=> Tempo: Add stdout logging option to autologging

CHANGELOG.md, pkg/tempo/config.go, pkg/tempo/config_test.go
Intentionally orders trace processors as described in the issue.
Fixes #604
=> Tempo: Intentional Processor order

example/docker-compose/agent/config/agent-scraping-service.yaml
Config in the tail sampling processor changed a while ago and that example was using the old format
=> Fix config example

.github/workflows/force_release.yml, CHANGELOG.md, docs/configuration-reference.md, docs/getting-started.md, docs/migration-guide.md, production/README.md, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-sigv4.yaml, production/kubernetes/agent-tempo.yaml, production/kubernetes/agent.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/kubernetes/install-loki.sh, production/kubernetes/install-sigv4.sh, production/kubernetes/install-tempo.sh, production/kubernetes/install.sh, production/tanka/grafana-agent/v1/main.libsonnet
- cut changelog
- fix date of 0.14.0 release
- add force_release.yml back to workflows to perform the release
Still doing release testing, but will merge and cut the release in a few hours.
=> Prepare for 0.15.0

docs/configuration-reference.md
Add exemplars to configuration reference
=> Exemplars config reference

CHANGELOG.md, go.mod, go.sum, pkg/operator/selector_eventhandler_test.go
Includes grafana/prometheus#21.
=> Update prometheus dependency to include interner leak fix

docs/overview.md
Discovered a small typo in the documentation 😅
=> Fix small typo

docs/configuration-reference.md
Fix a small typo on how to enable exemplars
=> fix typo in exemplars doc

CHANGELOG.md, cmd/agent-operator/README.md, docs/configuration-reference.md, docs/getting-started.md, docs/operator/README.md, docs/operator/getting-started.md, production/README.md, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-sigv4.yaml, production/kubernetes/agent-tempo.yaml, production/kubernetes/agent.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/kubernetes/install-loki.sh, production/kubernetes/install-sigv4.sh, production/kubernetes/install-tempo.sh, production/kubernetes/install.sh, production/tanka/grafana-agent/v1/main.libsonnet
=> prepare for 0.16.0 release

CHANGELOG.md, docs/configuration-reference.md, docs/getting-started.md, docs/operator/getting-started.md, production/README.md, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-sigv4.yaml, production/kubernetes/agent-tempo.yaml, production/kubernetes/agent.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/kubernetes/install-loki.sh, production/kubernetes/install-sigv4.sh, production/kubernetes/install-tempo.sh, production/kubernetes/install.sh, production/tanka/grafana-agent/v1/main.libsonnet
Prepare for v0.16.1 release.
@mapno I'm going to create a branch just with the bugfix and defer your change to the next non-patch release.
=> Prepare for v0.16.1 release

docs/operation-guide.md
Documents horizontal scaling of Agents, the different approaches that can be taken, and the tradeoffs of each. Also documents scaling via hashmod. 
Closes #695.
=> document horizontal scaling

docs/operator/_index.md, docs/operator/add-custom-scrape-jobs.md, docs/operator/architecture.md, docs/operator/getting-started.md
- Added metadata and renamed some files
- Got rid of the FAQ
- Maintainer file still needs to be moved
- We'll probably want to break up the Getting started topic at some point. Does it need updating like the Agent Getting started does?
=> Docs: Grafana Agent Operator docs

CHANGELOG.md, cmd/agent/entrypoint.go
This PR introduces reload of config using `SIGHUP`  signal. 
Fixes #537.
=> trigger reload configuration using SIGHUP

docs/getting-started/_index.md
1. Fix outdated information
2. Remove references to developer-only k3d and docker-compose examples 
3. Combine installing / running into one section
=> Clean up getting started guide

.github/workflows/scripts.yml, CHANGELOG.md, packaging/deb/control/postinst, packaging/deb/control/prerm, packaging/rpm/control/postinst, packaging/rpm/control/prerm
=> Linux packages: add grafana-agent user to adm and systemd-journal groups

.drone/drone.yml, Makefile
Add Test as a dependency of Release and Containerize 
Add operator
Ensure RELEASE_TAG/IMAGE_TAG set correctly
Closes #770
Closes #768
Closes #762
- [NA] CHANGELOG updated 
=>  Add Test as a Dependency of Release and Containerize, Add Operator

CHANGELOG.md, docs/configuration/integrations/postgres-exporter-config.md, go.mod, go.sum, pkg/integrations/postgres_exporter/postgres_exporter.go
Bumps the version of the postgres exporter to resolve some performance issues for existing users.
=> Update Postgres Exporter to v0.10.0

CHANGELOG.md, docs/configuration-reference.md, docs/migration-guide.md
=> Tempo/traces docs fixes for v0.18.0

docs/configuration/prometheus-config.md
=> Add a comment for informing how to use wal_directory with a PVC

.drone/drone.yml, Makefile
DRONE_TAG is often set to a blank string which causes issues when pushing containers.
=> Ensure drone tag always has a value, default to v0.0.0

CHANGELOG.md, packaging/deb/grafana-agent.service, packaging/rpm/grafana-agent.service
Update RPM & Deb service files to allow for expanding the $HOSTNAME variable in the agent config.
=> Add HOSTNAME env variable to service file

example/docker-compose/grafana/dashboards/agent-operational.json, example/docker-compose/grafana/dashboards/agent-remote-write.json, example/docker-compose/grafana/dashboards/agent.json, production/grafana-agent-mixin/dashboards.libsonnet, production/grafana-agent-mixin/debugging.libsonnet
I took a pass at the mixin to update referenced metrics which have changed overtime. I also moved the collection of samples queries in to the samples row.
- [ na? ] CHANGELOG updated 
- [ na ] Documentation added
- [ na ] Tests updated
=> Update metrics in mixin

CHANGELOG.md, cmd/agentctl/main.go, docs/configuration-reference.md, docs/getting-started.md, docs/operator/getting-started.md, pkg/client/grafanacloud/client.go, pkg/client/grafanacloud/client_test.go, pkg/operator/defaults.go, pkg/prom/cluster/cluster.go, pkg/prom/cluster/config.go, pkg/prom/cluster/config_watcher.go, pkg/prom/cluster/config_watcher_test.go, pkg/prom/cluster/node.go, pkg/prom/instance/configstore/remote.go, pkg/tempo/tempo.go, pkg/util/logger.go, production/README.md, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-sigv4.yaml, production/kubernetes/agent-tempo.yaml, production/kubernetes/agent.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/kubernetes/install-loki.sh, production/kubernetes/install-sigv4.sh, production/kubernetes/install-tempo.sh, production/kubernetes/install.sh, production/tanka/grafana-agent/v1/main.libsonnet
=> Merge v0.18.3 fixes

.drone/drone.yml
Containerizes merges in `dev.{}` branches. This will create a build and push it to Grafana's DockerHub.
Closes https://github.com/grafana/agent/issues/892
=> Containerize merges to development branches

CHANGELOG.md, docs/configuration/integrations/node-exporter-config.md, docs/configuration/integrations/process-exporter-config.md, docs/getting-started/_index.md, docs/operator/getting-started.md, pkg/operator/defaults.go, production/README.md, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-tempo.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
(release PR to main, second PR will cherry pick commits to release branch)
=> Prepare for 0.18.4 release

pkg/metrics/cluster/config_watcher.go
Maybe a little bit easier to follow than having branching paths. Not necessary for v0.18.4, just a nice simplification for next release.
=> Simplify logic a little for calculating next reshard

pkg/tempo/servicegraphprocessor/factory.go, pkg/tempo/servicegraphprocessor/processor.go, pkg/tempo/servicegraphprocessor/processor_test.go, pkg/tempo/servicegraphprocessor/testdata/trace-sample.json
Checks span status and http status code to see if the span failed. If either the client or server span contains an error, the request will be considered as failed.
=> Check span error

README.md, cmd/agent/DEVELOPERS.md, tools/release-note.md
=> Update documentation with better release note and contributions

packaging/deb/grafana-agent.service, packaging/rpm/grafana-agent.service
Use the hosted docs instead of the repo docs.
=> Update docs links in deb/rpm service files

.github/depcheck.yml, CHANGELOG.md, docs/configuration/integrations/elasticsearch-exporter-config.md, docs/configuration/integrations/postgres-exporter-config.md, docs/configuration/integrations/redis-exporter-config.md, go.mod, go.sum, pkg/integrations/elasticsearch_exporter/elasticsearch_exporter.go, pkg/integrations/redis_exporter/redis_exporter.go
This upgrades the following integrations dependencies to the newest version available:
github.com/prometheus/mysqld_exporter: v0.12.0 to v0.13.0 (https://github.com/grafana/agent/issues/601)
github.com/prometheus-community/postgres_exporter: v0.8.0 to v0.10.0 (https://github.com/grafana/agent/issues/730)
github.com/oliver006/redis_exporter: v1.15.0 to v1.27.1 (https://github.com/grafana/agent/issues/934)
github.com/prometheus/memcached_exporter: v0.8.0 to v0.9.0 (https://github.com/grafana/agent/issues/494)
github.com/prometheus/statsd_exporter: v0.21.0 to v0.22.2 (https://github.com/grafana/agent/issues/908)
github.com/justwatchcom/elasticsearch_exporter: v1.1.0 to v1.2.1 (https://github.com/grafana/agent/issues/699)
Which issue(s) this PR fixes …
=> Upgrading Integration Dependencies

pkg/tempo/servicegraphprocessor/processor.go, pkg/tempo/servicegraphprocessor/processor_test.go
Count number of dropped spans and remove untagged metric
=> Count number of dropped spans and remove untagged metric

CHANGELOG.md, pkg/traces/automaticloggingprocessor/factory.go
Validate logs config when using logs_instance with automatic logging processor
Fixes https://github.com/grafana/agent/issues/1056
=> Validate logs config when using logs_instance

docs/upgrade-guide/_index.md
Just a small docs change based on the discussion from #1023
=> Add more detail to migrating to new CRD names in v0.19.0

.github/stale.yml
=> Exempt dev branches issues/PRs from staleness

docs/upgrade-guide/_index.md
=> fix upgrade guide

CHANGELOG.md, go.mod, go.sum
=> Update version of temporary dnsmasq_exporter fork used

CHANGELOG.md, pkg/operator/resources_logs.go, pkg/operator/resources_logs_test.go, pkg/operator/resources_metrics.go, pkg/operator/resources_metrics_test.go
=> Default to using latest agent release version in operator

docs/upgrade-guide/_index.md
Prefer "removed" over "fully deprecated"
Fixes #1000
=> docs: stop using the term "fully deprecated"

docs/configuration/logs-config.md
=> Update Promtail links to link to grafana.com/docs

docs/scraping-service/_index.md
Fixes a broken link in the docs.
=> fix relref link

production/tanka/grafana-agent/v2/internal/helpers/logs.libsonnet
Signed-off-by: Nick Pillitteri <nick.pillitteri@grafana.com>
=> Fix syntax error in Jsonnet logs helper method

pkg/integrations/v2/controller.go, pkg/integrations/v2/controller_metricsintegration_test.go, pkg/integrations/v2/integrations.go, pkg/integrations/v2/metricsutils/metricshandler_integration.go, pkg/integrations/v2/subsystem.go
=> [dev.multiple-integrations] Infer target hostname from SD API host

CHANGELOG.md, docs/configuration/integrations/cadvisor-config.md, example/docker-compose/agent/config/agent-local.yaml, go.mod, go.sum, pkg/integrations/cadvisor/cadvisor.go, pkg/integrations/cadvisor/cadvisor_stub.go, pkg/integrations/cadvisor/common.go, pkg/integrations/install/install.go, pkg/integrations/stub_integration.go
This PR adds an integration for cAdvisor
=> cAdvisor Integration

ADOPTERS.md
Add Canonical to the companies using Grafana Agent in prod
We luv Grafana Agent :-)
=> Add Canonical to the companies using Grafana Agent in prod

CHANGELOG.md, pkg/metrics/agent.go
Signed-off-by: Nick Pillitteri <nick.pillitteri@grafana.com>
=> Only stop the WALCleaner on shutdown when non-nil

production/tanka/grafana-agent/v2/internal/helpers/k8s.libsonnet
This PR fixes an issue that users of config.expand-env face.
See https://github.com/grafana/agent/pull/707 and https://github.com/grafana/agent/issues/691
=> Update grafana-agent config regex replacement

CHANGELOG.md, docs/configuration/traces-config.md, go.mod, pkg/traces/config.go, pkg/traces/config_test.go
WIP
https://github.com/grafana/agent/issues/1135
=> traces: add jaeger exporter

go.mod, go.sum, pkg/traces/servicegraphprocessor/processor_test.go, pkg/traces/servicegraphprocessor/testdata/trace-sample.json, pkg/traces/servicegraphprocessor/testdata/unpaired-trace-sample.json
Removes Tempo dependency which was used only in a test
=> Remove Tempo dependency

cmd/agent/DEVELOPERS.md
This is a simple fix for the relative link pointing to the k3d example in DEVELOPERS.md.
This PR fixes #1241
It's my first PR in the agent repo, so please let me know if there's anything I've missed in the contribution process!
=> Fix link to k3d example in DEVELOPERS.md

docs/upgrade-guide/_index.md
Fix typo from https://github.com/grafana/agent/pull/1228
=> Fix node_exporter upgrade docs

docs/operator/getting-started.md
Fixes an anchor link on operator docs
No linked issues
Nothing to note
=> Fix anchor link on operator docs

example/k3d/scripts/smoke-test.bash, example/k3d/smoke/main.jsonnet, production/tanka/grafana-agent/smoke/main.libsonnet
I had changed this in the smoke jsonnet but didn't update for local smoke tests.
=> new smoke config

docs/configuration/integrations/integrations-next/_index.md, docs/configuration/integrations/integrations-next/eventhandler-config.md, pkg/integrations/v2/eventhandler/eventhandler.go, pkg/integrations/v2/eventhandler/integration.go
=> Add docs and sample manifests

CHANGELOG.md, go.mod, go.sum, pkg/integrations/windows_exporter/windows_exporter_windows.go
Updates to use a windows_exporter version that does not have the issue. We were not setting the config value that is used once. 
Closes #1164
=> Fix mssql issue

pkg/crow/crow.go, tools/crow/Dockerfile, tools/crow/Dockerfile.buildx
Adding password-file flag to crow for use with querying protected cortex endpoints.
=> add password file and basic auth round tripper in crow

docs/user/getting-started/install-agent-on-windows.md
=> Reference page to download windows installer

README.md
=> README: Fix link to agent logo

production/grafana-agent-mixin/alerts.libsonnet
missed a comma in this PR the other day, woops, caught this attempting to validate these. beep boop.
=> fix alerts typo

.drone/drone.yml
Drone updates for smoke test image tags.
=> continuous delivery for smoke images

production/grafana-agent-mixin/alerts.libsonnet
Adjust alerts to reduce noise in smoke tests.
=> reduce smoke alert noise

docs/user/operator/custom-resource-quickstart.md
Clarifies usage of `instanceNamespaceSelector` field
Closes https://github.com/grafana/agent/issues/1400
=> Clarify usage of instanceNamespaceSelector

production/grafana-agent-mixin/alerts.libsonnet, production/grafana-agent-mixin/debugging.libsonnet
* change duration of GrafanaAgentMemHigh and GrafanaAgentCPUHigh alerts to 1h
* refactor CrowFailures alert
* add namespace filter for pod variable in Agent Operational dashboard
=> update smoke alerts

pkg/config/config_test.go
adding the test back for remote_write
=> Adding remote_write test back

.github/workflows/bump-formula-pr.yml, .github/workflows/test.yml
=> Increase swap space on windows for running tests

production/grafana-agent-mixin/alerts.libsonnet
Adds a smoke test alert for container restarts
Closes #1459
=> add container restarts alert

CHANGELOG.md, packaging/deb/control/postinst, packaging/rpm/control/postinst
=> Fix permissions for WAL data directory

docs/user/configuration/_index.md
Missing ">" in shortcode is breaking builds in /website repo
=> Fix broken shortcode

example/k3d/smoke/main.jsonnet, production/tanka/grafana-agent/smoke/crow/main.libsonnet, production/tanka/grafana-agent/v2/README.md, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/main.libsonnet, tools/crow/main.go
=> tools/crow: make sure that default settings are applied to crow

docs/rfcs/0003-new-metrics-subsystem.md, docs/rfcs/xxxx-new-metrics-subsystem.md
Proposes a new metrics subsystem to resolve all of #872, #873, #875, and #888. 
Historically based on the existing [per-target sharding][per-target sharding] proposal, though has some changes to simplify the implementation.  
[per-target sharding]: https://docs.google.com/document/d/1JI804iaut6bKvZprOydes3Gb5Awo_J0sX-3ORlyc5l0
=> [RFC] New Metrics subsystem

example/docker-compose/agent/config/agent.yaml, example/docker-compose/docker-compose.yaml, example/k3d/environment/main.jsonnet
Updates are
- Fix port in docker-compose config
- Update otlp ports to 4317 (from 55680)
- Upgrade Tempo to v1.3.2
=> Update tracing in examples

CHANGELOG.md, docs/user/configuration/traces-config.md, pkg/traces/remotewriteexporter/exporter.go, pkg/traces/remotewriteexporter/exporter_test.go, pkg/traces/remotewriteexporter/factory.go
Protect concurrent writes to the WAL in the remote write exporter. It also contains a refactor of the exporter.
Fixes https://github.com/grafana/agent/issues/1273
=> Fix 'out of order' issues in remotewrite exporter

pkg/integrations/v2/app_o11y_receiver/app_o11y_receiver.go, pkg/integrations/v2/app_o11y_receiver/exporters/logs.go, pkg/integrations/v2/app_o11y_receiver/exporters/logs_test.go, pkg/integrations/v2/app_o11y_receiver/exporters/receiver_metrics.go
Align with rest of agent and rename "loki" to "logs"
=> [dev.frontend-receiver] rename "loki" -> "logs"

CHANGELOG.md, docs/user/configuration/integrations/node-exporter-config.md, docs/user/configuration/integrations/process-exporter-config.md, docs/user/getting-started/_index.md, docs/user/operator/custom-resource-quickstart.md, docs/user/operator/getting-started.md, docs/user/upgrade-guide/_index.md, pkg/operator/defaults.go, production/README.md, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
(cherry picked from commit 4ec400bf3cc81b0df939bf835cb0be16e5a16714)
=> Sync with v0.24.0 

go.mod, go.sum, pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/gossip.go, pkg/cluster/gossip_test.go
This commit introduces a [ckit-based](https://github.com/rfratto/ckit) pkg/cluster package as a top-level subsystem for clustering.
Related to #1496.
Currently, the package is not wired in anywhere, but tests are included for validating correctness. This will be used for #1496 over time.
=> pkg/cluster: introduce clustering package

CHANGELOG.md, cmd/agentctl/main.go, docs/user/configuration/integrations/node-exporter-config.md, docs/user/configuration/integrations/process-exporter-config.md, docs/user/getting-started/_index.md, docs/user/operator/custom-resource-quickstart.md, docs/user/operator/getting-started.md, go.mod, pkg/config/config.go, pkg/logs/logs.go, pkg/metrics/cluster/configapi/types.go, pkg/operator/config/config_test.go, pkg/operator/config/metrics_templates_test.go, pkg/operator/config/templates/component/metrics/remote_write.libsonnet, pkg/operator/defaults.go, pkg/server/config.go, pkg/server/logger_test.go, production/README.md, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Includes the following PRs:
* #1584 
* #1589 
* #1594 
* #1596 
* #1611 
* #1612
=> Prepare for 0.24.1

CHANGELOG.md, pkg/traces/servicegraphprocessor/processor.go
Use the correct attribute name for retrieving gRPC status codes
https://github.com/grafana/agent/issues/1520
=> Use correct attribute for grpc status code

README.md
=> Update README.md to remove Cortex and swap in Mimir

docs/user/configuration/flags.md
=> fix typo in docs

.github/workflows/markdown.links.config.json, CHANGELOG.md, go.mod, go.sum, pkg/metrics/cluster/config_watcher.go
Included PRs:
#1629
#1663 
#1647
=> Cherry pick for 0.24.2

docs/user/configuration/integrations/node-exporter-config.md, docs/user/configuration/integrations/process-exporter-config.md, docs/user/getting-started/_index.md, docs/user/operator/custom-resource-quickstart.md, docs/user/operator/getting-started.md, pkg/operator/defaults.go, production/README.md, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Updating references in scripts and manifests to 0.24.2
=> Final prep for v0.24.2

README.md
PR Description
Fixes broken readme link as per Broken links in docs #1726
Fixes #1726
=> Fixes broken links

cmd/agent/Dockerfile, cmd/agent/Dockerfile.buildx, cmd/agent/agent-local-config.yaml, cmd/agentctl/Dockerfile, cmd/agentctl/Dockerfile.buildx, pkg/integrations/ebpf_exporter/common.go, pkg/integrations/ebpf_exporter/ebpf.go, pkg/integrations/ebpf_exporter/ebpf_stub.go, pkg/integrations/ebpf_exporter/ebpf_test.go, pkg/integrations/install/install.go, pkg/integrations/v2/ebpf/common.go, pkg/integrations/v2/ebpf/integration.go, pkg/integrations/v2/ebpf/integration_stub.go
=> [dev.add-ebpf-integration] Update dev branch with recent changes

example/docker-compose/grafana/dashboards/agent-operational.json
=> make example-dashboards

.github/workflows/publish.yml
* fix test volume path, add tag trigger
* update target folder
* Separate to two Github Actions
* Re-combine the into one Action
* Rename so that Github picks up specific code changes
* Point to upstream grafana-github-actions repo after merge
* Point to upstream grafana-github-actions repo after merge 2
Co-authored-by: Paschalis Tsilias <paschalis.tsilias@grafana.com>
=> sync docs on tags (#1515)

docs/user/cookbook/_index.md, docs/user/cookbook/dynamic-configuration/01_Basics/01_Structure.md, docs/user/cookbook/dynamic-configuration/01_Basics/02_Instances.md, docs/user/cookbook/dynamic-configuration/01_Basics/03_Integrations.md, docs/user/cookbook/dynamic-configuration/01_Basics/04_Logs_and_Traces.md, docs/user/cookbook/dynamic-configuration/02_Templates/01_Looping.md, docs/user/cookbook/dynamic-configuration/02_Templates/02_Datasources.md, docs/user/cookbook/dynamic-configuration/02_Templates/03_Datasource_and_Objects.md, docs/user/cookbook/dynamic-configuration/03_Advanced_Datasources/01_AWS.md, docs/user/cookbook/dynamic-configuration/README.md, docs/user/cookbook/dynamic-configuration/_index.md
Cherry-picks #1751 into release-v0.25. No patch needed, just a docs fix.
=> Cherry-pick #1751

.gitignore, cmd/agentflow/example-config.flow, component/all/all.go, component/discovery/transformer/transformer.go, component/discovery/transformer/transformer_test.go, component/discovery/transformer/types.go, go.mod, go.sum
This is an early draft of the PR that will introduce a component that can mutate/modify/edit/transform scrape targets coming from a variety of service discovery mechanisms.
An early test, with the following configuration
```
discovery "transformer" "one" {
targets = [
{ "__address__" = "localhost:9091", "name" = "one"},
{ "__address__" = "localhost:9092", "name" = "two"},
]
scrape_labels = {
job_name = "my_scrape_job"
interval = "1m"
timeout = "59s"
metrics_path = "/metrics"
scheme = "https"
}
query_params = {"user" = ["tpaschalis"] }
relabel_configs  {
source_labels = ["__address__", "name"]
separator = "/"
target_label = "destination"
action = "replace"
regex = "(.*)"
}
relabel_configs  {
source_labels = ["name"] …
```
=> Add component to transform Service Discovery targets

packaging/grafana-agent.yaml
Not sure what the correct link is, but the current one is broken. PTAL
=> Fix packaging reference link

CHANGELOG.md, pkg/metrics/wal/wal.go
This code change should increase the chances of being able to repair a corrupt WAL.
=> unwrap replayWAL error before attempting repair

CHANGELOG.md, pkg/metrics/wal/wal.go, pkg/operator/config/config_test.go, pkg/operator/config/utils.go
Patch release `v0.25.1` preparation.
* #1793
* #1794
=> v0.25.1 release prep (cherry-picks)

CHANGELOG.md, docs/user/configuration/integrations/node-exporter-config.md, docs/user/configuration/integrations/process-exporter-config.md, docs/user/operator/custom-resource-quickstart.md, docs/user/operator/getting-started.md, docs/user/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
=> v0.25.1 image tags

CHANGELOG.md, docs/user/configuration/integrations/node-exporter-config.md, docs/user/configuration/integrations/process-exporter-config.md, docs/user/operator/custom-resource-quickstart.md, docs/user/operator/getting-started.md, docs/user/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
* update images tags for v0.25.1
=> v0.25.1 image tags (#1801)

.drone/drone.yml
This PR updates the CD mechanism for the Grafana Agent to target the new Tanka environment.
=> CD: Update target Tanka environment for Grafana Agent

docs/sources/configuration/metrics-config.md
=> Fix doc, 2.27 goes to 404

pkg/river/scanner/scanner_test.go
=> river/scanner: add Fuzz test

.drone/drone.yml
=> fix release step

CHANGELOG.md, production/grafanacloud-install.sh
Update grafana cloud install and date
=> Update grafana cloud install

.github/workflows/bump-formula-pr.yml
Cherry Pick RC rules into release branch
=> CI: prevent all -rc* tags from opening formula PRs. (#1884)

.drone/drone.yml, CHANGELOG.md
Change to wait on distribute instead of containerize
=> Trigger branch

pkg/usagestats/reporter_test.go
A data race was reported here: https://github.com/grafana/agent/runs/7321137500?check_suite_focus=true
This can happen if the usagestats happen to tick exactly after the context was canceled.
=> pkg/usagestats: fix rare race condition in usagestats test

.drone/drone.yml, CHANGELOG.md, Makefile, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/custom-resource-quickstart.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet, tools/release-note.md
Update v0.26.0-rc.0 to v0.26.0
=> Remove RC and ready the actual release

CHANGELOG.md, Makefile, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/custom-resource-quickstart.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet, tools/release-note.md
=> merger changelog, references and makefile changes from 26 to main

CHANGELOG.md, Makefile, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/configuration/server-config.md, docs/sources/operator/custom-resource-quickstart.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/config/templates/component/metrics/service_monitor.libsonnet, pkg/operator/defaults.go, pkg/server/tls.go, pkg/server/tls_certstore_windows.go, pkg/server/tls_certstore_windows_test.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Cherry pick 
https://github.com/grafana/agent/commit/0d3f0b929885f976bd38f232d76ea822bf7f4fb0 - windows certificate
https://github.com/grafana/agent/commit/34d1b7151c33bad9a6fd5bd73610266953ac8346 - operator flags
https://github.com/grafana/agent/commit/0844bd744b11158be84241de6b21cb4388a94445 - ebpf build
into v0.26
=> Get patch v0.26.1 ready 

CHANGELOG.md, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/custom-resource-quickstart.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent-operator/main.libsonnet, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Update changelog and v0.26.0  -> v0.26.1 references
=> Update changelog and refs to 0.26.1

CHANGELOG.md, go.mod, go.sum
=> Support Go 1.19

operations/river-jsonnet/main_test.jsonnet, operations/river-jsonnet/manifest.jsonnet
* Support arrays of blocks
* Ensure that literal values are indended correctly
=> river-jsonnet: changes needed for flow configs

CHANGELOG.md, docs/sources/configuration/integrations/integrations-next/_index.md, docs/sources/configuration/integrations/integrations-next/vsphere-config.md, go.mod, go.sum, pkg/integrations/install/install.go, pkg/integrations/v2/vmware_exporter/vmware_exporter.go
This PR introduces a v2 integration for the vmware_exporter (vsphere)
=> vSphere integration

pkg/river/internal/rivertags/rivertags.go, pkg/river/internal/rivertags/rivertags_test.go, pkg/river/internal/value/decode_test.go
Remove the usage of embedded fields
Closes #1998
=> Remove the usage of embedded fields

component/metrics/remotewrite/remote_write.go, component/metrics/remotewrite/types.go
This adds a `wal` block to metrics.remote_write which can be used to configure how the WAL gets cleaned up over time.
Three attributes are exposed within this new block:
1. `truncate_frequency`: How often the WAL gets cleaned up, with new checkpoints being added and stale series being deleted from memory.
2. `min_keepalive_time`: How old samples should be before they're considered from being deleted during the next truncate.
3. `max_keepalive_time`: How old samples can be before they're forced to be deleted during the next truncate.
The remote flush duration is left unexposed for now because there's no way to dynamically change it without shutting down the remote_write.
Closes #2023.
=> metrics.remote_write: expose truncate & min/max keepalive time

component/common/appendable/appendable.go, component/metrics/globalrefmap.go, component/metrics/globalrefmap_test.go, component/metrics/mutate/mutate.go, component/metrics/receiver.go, component/metrics/receiver_test.go, component/metrics/remotewrite/remote_write.go, component/metrics/scrape/scrape_test.go
Fixes the issue in the mutate function where it is assigning what should be an immutable label set. This is a tighter PR with a low amount of changes to fix the mutate issue and help guard against bad uses of labels.
Closes #2030
=> simplified metrics fix

CHANGELOG.md, production/grafanacloud-install.ps1
Adds the platforms query param to the grafanacloud-install.ps1 script.
=> add platform query param in powershell installer script

GOVERNANCE.md
Adding myself to the governance team member list as per onboarding steps.
=> rlankfo governance onboarding

docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/custom-resource-quickstart.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Update docs and deployments for 0.27.0-rc.0
=> Update version numbers for 0.27.0-rc.0

CHANGELOG.md, docs/sources/operator/custom-resource-quickstart.md
Set job label at discovery time
Fixes https://github.com/grafana/agent/issues/1606
=> Move job label from metricrelabeling to relabeling

CHANGELOG.md, pkg/integrations/v2/app_agent_receiver/logs_exporter.go, pkg/integrations/v2/app_agent_receiver/logs_exporter_test.go, pkg/integrations/v2/app_agent_receiver/payload.go, pkg/integrations/v2/app_agent_receiver/payload_test.go, pkg/integrations/v2/app_agent_receiver/receiver_metrics_exporter.go, pkg/integrations/v2/app_agent_receiver/receiver_metrics_test.go, pkg/integrations/v2/app_agent_receiver/testdata/payload.json
* add Event kind
* update changelog
* align logs attributes with otel proposal
* dots are a no go, underscore it is
=> cherry-pick #2075 to release-v0.27

CHANGELOG.md, cmd/agent/Dockerfile, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/custom-resource-quickstart.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Since we've already pushed rc.0, it makes sense to roll the new commits into an rc.1. Then we can bake it in dev and push 0.27 later this week.
=> prepare for v0.27.0-rc.1

docs/flow/concepts/component_controller.md, docs/flow/concepts/configuration_language.md
Give a detailed explanation for how to reference the exports of a component.
=> docs/flow: explain how to reference a component's exports

docs/flow/config-language/expressions/_index.md, docs/flow/config-language/expressions/function_calls.md, docs/flow/config-language/expressions/operators.md, docs/flow/config-language/expressions/referencing_exports.md, docs/flow/config-language/expressions/referencing_outputs.md, docs/flow/config-language/expressions/types_and_values.md
=> river: add documentation for expressions

component/prometheus/scrape/scrape.go
The target groups must match the job name of the scrape_config, otherwise the scrape pool will fail to recognize the targets.
I didn't add tests to check for this so we could fix main quickly, but we should probably have tests in the future to assert this condition.
=> prometheus.scrape: ensure that target groups match configured job name

README.md, docs/sources/_index.md
Documents the new release schedule, where we plan to cut a new minor release every 6 weeks. 
I'm not sure if the language here explains the concept well, so please let me know if there's a way to explain it better (particularly around how if one release is moved, releases following it don't move along with it).
=> Document new release schedule

CHANGELOG.md, Makefile, cmd/agent-operator/Dockerfile, cmd/agent-operator/Dockerfile.buildx, cmd/agent/Dockerfile, cmd/agent/Dockerfile.buildx, cmd/agentctl/Dockerfile, cmd/agentctl/Dockerfile.buildx, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/custom-resource-quickstart.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
The only change is updating the base image used for docker containers.
=> Release 0.27.1

.drone/drone.yml, .github/workflows/scripts.yml, build-image/README.md, cmd/agent-operator/Dockerfile.new, cmd/agent/Dockerfile.new, cmd/agentctl/Dockerfile.new, tools/ci/docker-containers, tools/crow/Dockerfile.new, tools/make/build-container.mk, tools/release, tools/smoke/Dockerfile.new
Updates the Drone config to use the new Makefile and build images.
Jobs moved:
=> Drone: Use new Makefile and build image

docs/flow/reference/components/prometheus.scrape.md
This PR attempts to improve the reference page for the prometheus.scrape component, by detailing some more information about the scraping behavior for users who haven't already stepped in the prometheus ecosystem.
What else should we detail here? Any more information on what marks a scrape as failed or successful? Mentioning that the user can set limits?
=> flow: improve reference page for prometheus.scrape component

docs/sources/configuration/flags.md
This PR improve the transparency of the usage stats reporter detailing the
information collected by the agent when the stats reporter it's enabled.
=> Document all collected data from stats reporter

CODEOWNERS, MAINTAINERS.md
Also add Karen as a CODEOWNER for documentation.
=> Add Karen and Eve as maintainers of documentation

web/ui/src/App.tsx, web/ui/src/features/component/ComponentGraph.tsx, web/ui/src/features/layout/Navbar.tsx, web/ui/src/pages/Graph.tsx
This PR follows up on #2166 and adds a Graph view which can be used to visualize the relationships between running components:
The logic here is the most complicated and probably needs the most attention.
=> web/ui: Add graph view

GOVERNANCE.md
I am leaving Grafana Labs at the end of the month and do not wish to remain on the Agent Governance team. Thanks so much for the opportunity, and it's been an absolute pleasure serving the team and Agent community :)
=> Remove @hjet from governance

docs/flow/reference/components/discovery.relabel.md
This PR adds a small note to the reference page for discovery.relabel about internal labels.
Let me know if I'm missing anything important we should let users know!
=> docs/flow: revamp documentation page for discovery.relabel

component/remote/s3/s3.go, component/remote/s3/types.go, docs/flow/reference/components/remote.s3.md
This is some minor cleanup of the code and docs for remote.s3.
=> Flow remote s3

pkg/river/encoding/attribute.go, pkg/river/encoding/attribute_test.go, pkg/river/encoding/map.go, pkg/river/encoding/map_test.go, pkg/river/internal/value/value.go
Resolve errors with API where it was not handling empty values correctly.
Closes #2186 
Closes #2187
=> Resolve issues #2186 and #2187

web/ui/src/features/component/ComponentGraph.tsx
* Assign synthetic nodes a size of [0, 0] to prevent extra unnecessary padding in the graph.
* Determine the width of the node based on the component name and label indepednently, rather than the combined ID. This is a safe change because the full ID is never rendered, while the name and label are rendered on separate lines.
=> web/ui: reduce total graph size

.github/workflows/scripts.yml, docs/sources/flow/tutorials/assets/generate.sh, docs/sources/flow/tutorials/assets/runt.sh
These are scripts to generate the tutorial script and the tutorial script itself. Split the PR into two parts, this one concerns the scripts and the second will implement those changes in the tutorials itself, along with general cleanup of tutorials and images from the UI. 
This is also linux/osx specific, at some point might do a powershell version for windows.
=> script for generating runt.sh and runt.sh itself

docs/sources/flow/config-language/expressions/function_calls.md
=> docs/flow: fix typo on function_calls.md

docs/sources/flow/config-language/expressions/referencing_exports.md
To show up in the rendered documentation, the link needs to back up one more level.
=> docs/flow: fix link to diagram for referencing_exports.md

docs/sources/flow/_index.md, docs/sources/flow/config-language/expressions/operators.md
Added doc around what a component is
=> add quick explanation about components

CHANGELOG.md, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/custom-resource-quickstart.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
This PR updates all version references from the release candidate to the the upcoming v0.28 release.
=> Update CHANGELOG, version references for v0.28.0 release

CHANGELOG.md, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/custom-resource-quickstart.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Cherry-pick the updated changelog and version references after publishing the `v0.28.0` release.
=> Update version references after v0.28.0 release

docs/rfcs/0005-future-of-agent-operator.md
In the interest of transparency, we'd like to share our plans and goals for the Grafana Agent Operator over the coming months.
=> RFC: Future plans for the Grafana Agent Operator

docs/sources/flow/reference/components/discovery.kubernetes.md, docs/sources/flow/reference/components/discovery.relabel.md, docs/sources/flow/reference/components/local.file.md, docs/sources/flow/reference/components/otelcol.processor.batch.md, docs/sources/flow/reference/components/otelcol.receiver.otlp.md, docs/sources/flow/reference/components/prometheus.relabel.md, docs/sources/flow/reference/components/prometheus.remote_write.md, docs/sources/flow/reference/components/prometheus.scrape.md, docs/sources/flow/reference/components/remote.s3.md
Following a [discussion](https://github.com/grafana/agent/pull/2343#discussion_r992689836) in #2343.
=> docs/sources/flow: unbold yes when an attribute/block is required

docs/sources/shared/flow/reference/components/http-client-config-block.md
=> Removed subblock from http-client-config block

CHANGELOG.md, component/all/all.go, component/otelcol/processor/memorylimiter/memorylimiter.go, component/otelcol/processor/memorylimiter/memorylimiter_test.go, docs/sources/flow/reference/components/otelcol.processor.memory_limiter.md, go.mod, go.sum
This PR introduces a new otelcol.processor.memory_limiter component. It can be used to guard against memory exhaustion situations on a telemetry pipeline
Closes #2287
=> otelcol.procesor.memory_limiter: new component

component/prometheus/relabel/relabel.go
Resolve issue with concurrent writes to the cache map
=> Add mutexes for caching to prevent concurrent writes.

CHANGELOG.md, docs/sources/upgrade-guide/_index.md
=> docs: note binary names changing in v0.31.0

docs/sources/_index.md
This is mainly extracted from the [MinimumRequirements](https://github.com/golang/go/wiki/MinimumRequirements) page on the Go wiki. 
Closes #2394.
=> Document supported operating systems and architectures

CHANGELOG.md, cmd/agent/entrypoint.go, docs/sources/configuration/flags.md, pkg/config/integrations.go, pkg/config/integrations_test.go
This PR enables the reporting of enabled integrations to grafana. This
would help us to identify which integrations are more used than others.
The information sent it's completely anonymous. This is the [full list](https://grafana.com/docs/agent/next/configuration/flags/#report-information-usage) of all
information sent by the reporter. The reporting can always be disabled using 
`--disable-reporting`.
Closes #1830
=> Report usage of enabled integrations

component/prometheus/fanout.go, component/prometheus/fanout_test.go
=> Fix recursive rollback.

docs/sources/configuration/integrations/integrations-next/app-agent-receiver-config.md
The `grafana-javascript-agent` has been renamed to `faro-web-sdk`.  This PR updates the documentation for the `agent_app_receiver` integration.
=> update app receiver docs

docs/sources/flow/reference/components/loki.relabel.md
Now that other loki.* components have been merged, we can amend the documentation with examples or small references to them, so that readers can have a more complete view of how they tie together.
Nothing in particular.
=> Flow: Add doc cross-references to loki.* components

CHANGELOG.md, component/all/all.go, component/discovery/file/file.go, component/discovery/file/file_test.go, component/discovery/file/watch.go, docs/sources/flow/reference/components/discovery.file.md
Add the ability to discover arbitrary files on the filesystem.
Closes #2525
I wonder if we even need FSNotify, the file target in promtail uses it but it also does a sync glob check every 10 seconds. this basically does the same, and having both seems cumbersome.
=> Flow: Add discovery.file component

CHANGELOG.md, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/custom-resource-quickstart.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, docs/sources/upgrade-guide/_index.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Preparation for releasing v0.30.0
=> Update references to v0.30.0

component/otelcol/internal/featuregate/install.go
This PR disables the usage `useOtelForInternalMetrics` when Flow is not running.
This code path is being executed regardless Flow is one causing that some metrics
are not collected for tracing (see https://github.com/grafana/agent/issues/2644)
Fixes https://github.com/grafana/agent/issues/2644
This will be included in the next release patch.
=> Enable useOtelForInternalMetrics only when Flow mode is on

CHANGELOG.md, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/custom-resource-quickstart.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Adding last two bug fixes for patch v0.30.1
=> Prepare for patch v0.30.1

CHANGELOG.md, cmd/agent/Dockerfile, component/otelcol/internal/featuregate/install.go, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/custom-resource-quickstart.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet, tools/make/packaging.mk
This PR bring last v0.30.1 release to main branch.
=> Bring release v0.30.1 to main

CODEOWNERS, MAINTAINERS.md, Makefile, build-image/Dockerfile, cmd/grafana-agent/Dockerfile, docs/sources/configuration/integrations/integrations-next/eventhandler-config.md, docs/sources/flow/tutorials/assets/docker-compose.yaml, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/tanka/grafana-agent/grafana-agent.libsonnet, production/tanka/grafana-agent/v1/internal/agent.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, tools/ci/docker-containers
=> Update references to old binaries in Jsonnet and documentation

.github/workflows/publish-documentation-next.yml, .github/workflows/publish-documentation-versioned.yml
=> Update publishing workflows to use PATs with fine-grained access control

docs/sources/operator/deploy-agent-operator-resources.md
=> Multiple GrafanaAgent resources - different limits

tools/ci/docker-containers-windows
=> don't require DRONE_TAG for docker push

pkg/operator/resources_integrations.go, pkg/operator/resources_logs.go, pkg/operator/resources_metrics.go, pkg/operator/resources_pod_template.go, pkg/operator/resources_pod_template_test.go
=> operator: allow privileged containers when needed for daemonsets

pkg/config/config.go
Adds the hash of the effective config as the instrumented config hash, instead of the initial config.
=> [Agent Managment] Add Config Hash Instrumentation for Effective Config

component/phlare/scrape/scrape_loop_test.go
Verified with `go test -count=100 ./component/phlare`.
cc @cyriltovena
=> component/phlare: fix flake in TestScrapeLoop

.drone/drone.yml, .drone/pipelines/publish.jsonnet
Same as #2840, but for the new release branch
=> Fix drone variable rel

tools/release
Same as #2842 but for the release branch
=> fix zip command in tools/release script

docs/sources/flow/_index.md
Cherry-pick #2854 to the release branch.
=> docs: update landing page for Flow

docs/sources/operator/api.md, tools/gen-crd-docs/template/members.tpl, tools/gen-crd-docs/template/pkg.tpl, tools/gen-crd-docs/template/type.tpl
Cherry picking commit [c7e8f126b85a6046d2dc9a1ee9c9369a615eee5a](https://github.com/grafana/agent/commit/c7e8f126b85a6046d2dc9a1ee9c9369a615eee5a), which was merged via #2733.
=> [Release branch] Refactor template for Operator API docs to use markdown

production/grafana-agent-mixin/alerts.libsonnet
Adds some `warning` and `critical` alerts for agent management-related errors.
=> [Agent Management] Add agent management-related alerts

CHANGELOG.md, component/loki/process/internal/fake/client.go, component/loki/process/internal/metric/counters.go, component/loki/process/internal/metric/counters_test.go, component/loki/process/internal/metric/gauges.go, component/loki/process/internal/metric/gauges_test.go, component/loki/process/internal/metric/histograms.go, component/loki/process/internal/metric/histograms_test.go, component/loki/process/internal/metric/metricvec.go, component/loki/process/internal/stages/drop_test.go, component/loki/process/internal/stages/limit.go, component/loki/process/internal/stages/limit_test.go, component/loki/process/internal/stages/match_test.go, component/loki/process/internal/stages/metric.go, component/loki/process/internal/stages/metric_test.go, component/loki/process/internal/stages/pack.go, component/loki/process/internal/stages/pack_test.go, component/loki/process/internal/stages/pipeline.go, component/loki/process/internal/stages/pipeline_test.go, component/loki/process/internal/stages/replace.go, component/loki/process/internal/stages/stage.go, component/loki/process/internal/stages/template.go, component/loki/process/internal/stages/template_test.go, component/loki/process/internal/stages/tenant.go, component/loki/process/internal/stages/tenant_test.go, docs/sources/flow/reference/components/loki.process.md
This PR brings the `loki.process` component on par with all the processing stages from Promtail's pipelines.
Fixes #2515 
Apologies in advance about the PR size; I've tried to break it down into one commit per stage for easier reviewing.
=> flow: Add remaining stages to loki.process

docs/sources/api/_index.md
Fix #integrations-api anchor in api docs
=> Fix #integrations-api anchor in api docs

cmd/grafana-agent-operator/Dockerfile, cmd/grafana-agent/Dockerfile, cmd/grafana-agentctl/Dockerfile, tools/crow/Dockerfile, tools/smoke/Dockerfile
=> add org.opencontainers.image.source label to docker images

docs/sources/set-up/install-agent-macos.md
Update the documentation to specify the exact location of the Grafana Agent logs when installed via Homebrew
=> Update Log Location for Grafana Agent

CHANGELOG.md, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
I'll update the release branch with all the commits needed for 0.31.1 after this is merged.
=> Prepare for release 0.31.1

CHANGELOG.md, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
There will be a 0.31.2 patch version of the Agent, so this PR is a preparation for it. These changes will later be merged to the release branch, and a new release tag will be created.
=> Update versions and changelog in preparation for v0.31.2

.github/workflows/publish-documentation-next.yml, .github/workflows/publish-documentation-versioned.yml
=> Allow workflow to succeed when there are no changes to publish

docs/sources/set-up/install-agent-macos.md
Clarifying MacOS setup per @ethirolle's feedback in https://github.com/grafana/agent-squad/issues/210.
Fixing this issue: https://github.com/grafana/agent-squad/issues/210
=> Clarify set-up/install-agent-macos

docs/sources/configuration/create-config-file.md
A spelling mistake was spotted in the grafana agent create config file docs
Rectified the spelling mistake in grafana agent create config file
=> Spelling mistake spotted in docs

CHANGELOG.md, component/loki/source/cloudflare/cloudflare.go
(Also make sure that the API key is marked as a secret type)
=> loki.source.cloudflare: fix issue where api_key was used for zone

CHANGELOG.md, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
(cherry picked from commit 732c1d6c44d2994e5eb79049954a8a6c8cb0468d)
=> Prepare for 0.31.3 (release branch)

component/all/all.go, component/component.go, component/module/argument/argument.go, component/module/export/export.go, component/module/string/string.go, component/registry.go, pkg/flow/flow.go, pkg/flow/internal/controller/component.go, pkg/flow/internal/controller/loader.go
Draft PR, very ugly code, will never merge.
=> Unified controller

example/docker-compose/docker-compose.yaml
=> docker-compose: set agent listen address to 0.0.0.0 to expose it to host

CHANGELOG.md, component/common/relabel/relabel.go, component/common/relabel/relabel_test.go, docs/sources/shared/flow/reference/components/rule-block.md
=> Add keepequal and dropequal relabeling config support

CHANGELOG.md, component/loki/process/internal/stages/drop_test.go, component/loki/process/internal/stages/json_test.go, component/loki/process/internal/stages/labels_test.go, component/loki/process/internal/stages/limit_test.go, component/loki/process/internal/stages/logfmt_test.go, component/loki/process/internal/stages/match.go, component/loki/process/internal/stages/match_test.go, component/loki/process/internal/stages/metric.go, component/loki/process/internal/stages/metric_test.go, component/loki/process/internal/stages/output_test.go, component/loki/process/internal/stages/pack_test.go, component/loki/process/internal/stages/pipeline.go, component/loki/process/internal/stages/pipeline_test.go, component/loki/process/internal/stages/regex_test.go, component/loki/process/internal/stages/replace_test.go, component/loki/process/internal/stages/template_test.go, component/loki/process/internal/stages/tenant_test.go, component/loki/process/internal/stages/timestamp_test.go, component/loki/process/process.go, component/loki/process/process_test.go, docs/sources/flow/reference/components/loki.process.md
This PR makes use of the new River feature of 'enum' blocks to improve the configuration of the `loki.process` components.
Fixes #3041 
IIRC It's the first 'big' configuration change we did for River in a while. Do you want to announce this somewhere more prominently?
=> Use enum blocks functionality in loki.process

CHANGELOG.md, component/loki/source/kubernetes/kubernetes.go, component/loki/source/kubernetes/kubernetes_test.go, component/loki/source/podlogs/podlogs_test.go, docs/sources/flow/reference/components/loki.source.kubernetes.md, docs/sources/flow/reference/components/loki.source.podlogs.md
squash loki.source.kubernetes http_client_config
Closes #2995 
Closes #2996
No other places referencing this component's http_client_config were found.
=> squash loki.source.kubernetes http_client_config

CHANGELOG.md, component/otelcol/receiver/zipkin/zipkin.go, component/otelcol/receiver/zipkin/zipkin_test.go, docs/sources/flow/reference/components/otelcol.receiver.zipkin.md
Squashes the http block in zipkin receiver.
Closes #2997
=> Squash http block in zipkin receiver

CHANGELOG.md, component/otelcol/receiver/opencensus/opencensus.go, component/otelcol/receiver/opencensus/opencensus_test.go, docs/sources/flow/reference/components/otelcol.receiver.opencensus.md
Squash "otelcol.receiver.opencensus > grpc". Click [here](https://github.com/grafana/agent/blob/2998-flow-squash-grpc-in-otelcolreceiveropencensus/docs/sources/flow/reference/components/otelcol.receiver.opencensus.md) to see the new documentation.
Closes #2998
=> Squash "otelcol.receiver.opencensus > grpc"

CHANGELOG.md, docs/developer/releasing.md, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Update version string everywhere for v0.32.0-rc.0
=> Update version string everywhere for v0.32.0-rc.0

CHANGELOG.md, docs/developer/releasing.md, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
(cherry picked from commit 055df2f89dc42c53ab5b8a1ab54dea1e1d8c609a)
Update version string everywhere for v0.32.0-rc.0 (#3065)
=> Update version string everywhere for v0.32.0-rc.0 (#3065)

.drone/drone.yml, .drone/pipelines/publish.jsonnet
Fixes an issue from #3077 where buildx context doesn't carry across multiple steps.
=> ci: fix drone job

docs/sources/flow/getting_started.md
(cherry picked from commit 22df59a21f9b7b034d5faf165bf3a473bee283e9)
=> Backport docs fixes to release branch

CHANGELOG.md, component/all/all.go, component/prometheus/exporter/mysql/mysql.go, component/prometheus/exporter/mysql/mysql_test.go, docs/sources/flow/reference/components/prometheus.exporter.mysql.md
Adds `prometheus.exporter.mysql` flow component.
Closes #2305
=> [Flow] Add component for mysqld_exporter

CHANGELOG.md, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
v0.32.0 stable release version update
=> replace RC version with SR version

CHANGELOG.md, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
(cherry picked from commit 2c7556635b71514032e70daa3e5b77ce11add261)
Update version for stable release v0.32.0
=> replace RC version with SR version (#3119)

docs/sources/operator/_index.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/operator-integrations.md
Closes https://github.com/grafana/agent/issues/2178
=> Operator integrations for node_exporter and mysqld_exporter

operations/helm/charts/grafana-agent/CHANGELOG.md
The enhancements entry for the last release was added after my change, rather than before it.
=> helm: Fix changelog

operations/helm/charts/grafana-agent/CHANGELOG.md, operations/helm/charts/grafana-agent/README.md, operations/helm/charts/grafana-agent/templates/controllers/_pod.yaml, operations/helm/charts/grafana-agent/values.yaml
This change add a `priorityClassName` value to the chart. The `priorityClassName` is supported in the Agent Operator, so this PR aims to achieve parity.
Fixed #3135
=> Add priorityClassName for Helm Chart

CODEOWNERS, MAINTAINERS.md
Karen will no longer be doing documentation contributions to the project.
=> Remove Karen from CODEOWNERS, MAINTAINERS.md

.drone/drone.yml, cmd/grafana-agent-operator/Dockerfile, cmd/grafana-agent/Dockerfile, cmd/grafana-agent/Dockerfile.windows, cmd/grafana-agentctl/Dockerfile, cmd/grafana-agentctl/Dockerfile.windows, tools/crow/Dockerfile, tools/make/build-container.mk, tools/smoke/Dockerfile
=> Update build image to v0.22.0

component/phlare/scrape/manager.go, component/phlare/scrape/scrape_loop.go
Ensure we close all scrape loop in parallel to reduce shutdown time.
#3152 
Do we need a changelog for this ?
=> Phlare: Improve Component Shutdown

.drone/drone.yml, .drone/pipelines/check_containers.jsonnet, .drone/pipelines/crosscompile.jsonnet, CHANGELOG.md, tools/ci/docker-containers, tools/make/packaging.mk
=> Add s390x support

docs/sources/set-up/install-agent-on-windows.md
We forgot to update docs when we started to ship agent windows installer zipped.
Fixes #3183
=> Fix broken link for Agent installer on Windows

CHANGELOG.md, component/phlare/scrape/manager.go, component/phlare/scrape/scrape_loop.go, component/phlare/scrape/scrape_loop_test.go, component/phlare/scrape/scrape_test.go, component/phlare/scrape/target.go, pkg/flow/internal/controller/loader.go
This cherry-picks #3142 into the v0.32 release branch
=> Cherry-pick "Improve Phlare target reloading (#3142)" into release v0.32

docs/sources/set-up/install-agent-on-windows.md
Porting this [PR](https://github.com/grafana/agent/pull/3184) to `release` branch.
=> Fix broken link for Agent installer on Windows (#3184)

CHANGELOG.md, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, docs/sources/upgrade-guide/_index.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
=> update version for patch release v0.32.1

CHANGELOG.md, docs/sources/configuration/integrations/node-exporter-config.md, docs/sources/configuration/integrations/process-exporter-config.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/set-up/install-agent-docker.md, docs/sources/upgrade-guide/_index.md, pkg/operator/defaults.go, production/grafanacloud-install.sh, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
=> Update rel branch version v0.32.1

CHANGELOG.md, cmd/grafana-agent-operator/Dockerfile, cmd/grafana-agent/Dockerfile, cmd/grafana-agentctl/Dockerfile, tools/crow/Dockerfile, tools/smoke/Dockerfile
=> Use ubuntu:kinetic for base image of Linux Docker containers

operations/helm/charts/grafana-agent/CHANGELOG.md, operations/helm/charts/grafana-agent/README.md, operations/helm/charts/grafana-agent/templates/controllers/_pod.yaml, operations/helm/charts/grafana-agent/values.yaml
This change adds `affinity` value to the helm chart. Provides the ability to add affinity to pods.
None
=> Add affinity to helm chart

CHANGELOG.md, component/all/all.go, component/prometheus/exporter/postgres/postgres.go, component/prometheus/exporter/postgres/postgres_test.go, docs/sources/flow/reference/components/prometheus.exporter.postgres.md, pkg/integrations/postgres_exporter/postgres_exporter.go
Adds `prometheus.exporter.postgres` component for `postgres_exporter`.
Fixes #2310
=> [Flow] Add Postgres Component

docs/sources/operator/add-custom-scrape-jobs.md
The [issue](https://github.com/grafana/agent/issues/655) referenced in the docs is no longer relevant.
=> docs: remove reference to resolved issue

go.mod, go.sum
I'm running go1.20.1 and it's reporting differences when running `go mod tidy`.
None.
- [-] CHANGELOG updated
- [-] Documentation added
- [-] Tests updated
=> `go mod tidy`

component/module/string/string.go, docs/sources/flow/reference/components/module.string.md, pkg/flow/internal/controller/config.go
Return err if a module component fails to start in module.string.go
Closes #3254
=> Add error if the logging or tracing config block exists in a module

pkg/metrics/cluster/validation.go
Add support for additional service discovery configs:
- linode
- http
n.a.
=> Add SD configs for Linode and simple http.

operations/helm/charts/grafana-agent/CHANGELOG.md, operations/helm/charts/grafana-agent/README.md, operations/helm/charts/grafana-agent/templates/service.yaml, operations/helm/charts/grafana-agent/values.yaml
I need to add annotations for the service 
and I added the ability 
- [v] CHANGELOG updated
- [v] Documentation added
=> add service annotations

.drone/drone.yml, .drone/pipelines/crosscompile.jsonnet, component/loki/source/journal/internal/target/journaltarget.go
PR #3375 introduced an issue in journaltarget that was missed by CI.
=> component/loki: fix journaltarget after #3375

docs/sources/flow/reference/components/prometheus.operator.podmonitors.md
=> Fix typo in reference doc for podmonitors component

docs/developer/contributing.md, go.mod
Introduce new rules to help minimize the time where replace directives are added into the repository. 
cc @gloriasc
=> document new rules for using forks

CHANGELOG.md, component/prometheus/remotewrite/types.go, docs/sources/flow/reference/components/prometheus.remote_write.md
Update Flow defaults to match https://github.com/prometheus/prometheus/pull/12203
=> Flow remote write defaults

component/module/file/file.go, component/module/file/file_test.go, component/module/module.go, component/module/string/string.go
Put shared code into a parent package for module components
=> Module shared library

.drone/drone.yml, .github/workflows/test.yml, CHANGELOG.md, cmd/grafana-agent-operator/Dockerfile, cmd/grafana-agent/Dockerfile, cmd/grafana-agent/Dockerfile.windows, cmd/grafana-agentctl/Dockerfile, cmd/grafana-agentctl/Dockerfile.windows, tools/crow/Dockerfile, tools/make/build-container.mk, tools/smoke/Dockerfile
0.24.0 was cut from #3474, updating the Go dependency to 1.20.3.
=> all: update build image to 0.24.0

.drone/drone.yml, .drone/pipelines/crosscompile.jsonnet, CHANGELOG.md, docs/sources/_index.md, docs/sources/set-up/_index.md, tools/ci/docker-containers, tools/make/packaging.mk
=> all: restore 32-bit ARM builds

docs/sources/flow/concepts/configuration_language.md
=> Correct the description of the "Blocks" example

CHANGELOG.md, docs/sources/configuration/dynamic-config.md, docs/sources/upgrade-guide/_index.md
add notice for removing dynamic configuration
Closes #3499
- [X ] Documentation added
=> Add notice for dynamic configuration

CHANGELOG.md, component/remote/http/http.go, component/remote/http/http_test.go, docs/sources/flow/reference/components/remote.http.md
=> remote.http: Define custom http method and headers

component/component_health.go, pkg/flow/internal/controller/component.go
This fixes a bug introduced here https://github.com/grafana/agent/pull/3545
=> Default back to healthy when a component does not implement component.HealthComponent

CHANGELOG.md, pkg/operator/config/metrics_templates_test.go, pkg/operator/config/templates/component/metrics/pod_monitor.libsonnet, pkg/operator/config/templates/component/metrics/service_monitor.libsonnet
=> operator: Respect FilterRunning field in PodMonitors and ServiceMonitors

pkg/config/agentmanagement_test.go
- Due to performance reasons, the agent management API will return JSON by default instead of YAML (YAML can still be requested via the `Accept` header).
- Since YAML is a subset of JSON, we can still use the YAML parser to parse JSON, so we remain flexible if we decide to switch back to YAML in the future.
- This change updates the tests to reflect the changes in the API and validate all these assumptions.
=> Update agent management tests to validate JSON API responses

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Update version string references to `v0.33.0-rc.0`.
=> Update version references to v0.33.0-rc.0

CHANGELOG.md, docs/sources/flow/reference/components/module.file.md, docs/sources/flow/reference/components/prometheus.operator.podmonitors.md
Cherry-pick https://github.com/grafana/agent/commit/d8ca33ea9f2f0837953f9de5bd1531a79f7b7b11 and https://github.com/grafana/agent/commit/802aff3974d40f3ae6eef92219c2dfbfbd24022e
=> Cherrypick 0.33 docs changes

pkg/operator/config/metrics_templates_test.go, pkg/operator/config/templates/component/metrics/pod_monitor.libsonnet, pkg/operator/config/templates/component/metrics/service_monitor.libsonnet
(cherry picked from commit a893983c882f351b243867668f58046e0f7446b4)
Cherry pick a893983c882f351b243867668f58046e0f7446b4
=> fix filter running logic (#3588)

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Updates `v0.33.0-rc.0` --> `v0.33.0-rc.1` and adds new Header to the `CHANGELOG`.
=> Update v0.33.0 rc.1 refs

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
* Update CHANGELOG with new header
* Bump v0.33.0-rc.0 -> v0.33.0-rc.1
Cherry picks fb0d04d1b6c8280a35cb8d787694a0856a6a0739
=> Update v0.33.0 rc.1 refs (#3594)

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Bumps references to `v0.33.0-rc.1` -> `v0.33.0-rc.2`
=> Update code references for v0.33.0-rc.2

CHANGELOG.md, cmd/internal/flowmode/cmd_run.go, pkg/cluster/cluster.go, pkg/cluster/gossip.go
This PR ensures that clustering metrics are registered when clustering is enabled.
=> flow: add missing metrics to clustering mode

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Cherry-picks f77adb374a9022719f703debbf89d7b5a87e2a80 but removes the `Main (unreleased)` section from the `CHANGELOG`.
=> Update v0.33 release branch with version changes

docs/sources/static/_index.md
Adds a missing `[configured]: {{< relref "./configuration/" >}}` link for this line:
```
Static mode is [configured][] with a YAML file.
```
=> [Docs] Fix relative link in Static Mode Docs

docs/sources/static/configuration/agent-management.md, docs/sources/static/configuration/flags.md, docs/sources/static/configuration/metrics-config.md
Documents the use and protocol of this experimental feature.
=> Document agent management flag

CHANGELOG.md, Makefile, component/loki/source/file/file.go, component/loki/source/file/file_test.go
(cherry picked from commit 498b502950f66e787cd6fd6a7fbeb44e4d2bc499)
=> loki.source.file: fix goroutine leak (#3729)

CHANGELOG.md, docs/sources/flow/upgrade-guide.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/operator/upgrade-guide.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install-agent-docker.md, docs/sources/static/upgrade-guide.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Cherry-picks a8bfb4a6ec2159991697b3131bf82b4bd578e4d2 and updates the CHANGELOG with the correct date + reordering to match what's in `main`.
=> Update refs to v0.33.1 (#3732)

operations/agent-flow-mixin/alerts.libsonnet, operations/agent-flow-mixin/alerts/clustering.libsonnet, operations/agent-flow-mixin/alerts/utils/alert.jsonnet, operations/agent-flow-mixin/grizzly.jsonnet, operations/agent-flow-mixin/mixin.libsonnet
This PR adds some clustering-specific alerts to agent-flow-mixin
Here's how the alerts look in my personal instance after being synced by Grizzly.
=> agent-flow-mixin: add clustering-related alerts

component/module/string/string_test.go
username and password arguments might get evaluated in either order causing the tests to flake. This removes password from the test since it doesn't add all that much and we can explicitly test error messages for username safely.
=> fix up some non deterministic tests so they consistently pass

docs/sources/static/upgrade-guide.md
=> Update upgrade-guide.md to correct version in the header

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/ISSUE_TEMPLATE/proposal.yaml
Add relevant default labels to issues opened using an issue template.
=> misc: add default labels to issue templates

docs/sources/flow/concepts/modules.md
Minor change to fix the example in the module docs.
=> Fix module example

CHANGELOG.md, component/all/all.go, component/prometheus/exporter/mssql/mssql.go, component/prometheus/exporter/mssql/mssql_test.go, docs/sources/flow/reference/components/prometheus.exporter.mssql.md
- Adds a mssql exporter to the list of supported flow integrations.
Fixes #3165
=> flow: Add  Microsoft SQL exporter

go.mod, go.sum
=> misc: update github.com/grafana/ckit to latest

operations/agent-flow-mixin/alerts/clustering.libsonnet
This PR adds some more alerts around clustering.
Fixes #3758 
My PromQL is bad, so let me know if you spot anything amiss. The queries _do_ work with our internal data.
=> agent-flow-mixin: add more alerts around clustering

CHANGELOG.md, cmd/internal/flowmode/cmd_run.go
Fix an issue where the cluster advertise address was overwriting the join addresses.
=> Flow mode: fix cluster advertise address parameter

converter/internal/common/common.go, converter/internal/prometheusconvert/prometheusconvert.go, converter/internal/prometheusconvert/testdata/prometheus_agent.river, converter/internal/prometheusconvert/testdata/prometheus_agent.yaml, pkg/river/token/builder/builder.go, pkg/river/token/builder/builder_test.go
- Implements a new override hook for token encoding
- Leverage new hook for override secret token encoding value
Closes #3901
=> Add new override hook for token encoding and use it for config secret conversion

docs/sources/static/set-up/install-agent-linux.md
* First pass correcting Static install Linux
* Correct some details for openSUSE
* Simplify openSUSE step
* Update heading levels
(cherry picked from commit 4b8807a517071556c7fd520d7ddd792fbcd311f7)
=> Clean up and correct Grafana Agent Static install on Linux (#3931)

docs/sources/static/set-up/install-agent-on-windows.md
General cleanup pass on the Windows installation instructions. No technical content changes - focus on markdown and untangling some of the steps that were hard to follow.
=> General cleanup of the install steps for Static Agent on Windows

docs/sources/static/set-up/install-agent-on-windows.md
* General cleanup of the install steps
---------
Co-authored-by: Robert Fratto <robertfratto@gmail.com>
(cherry picked from commit cbddc1be476d8aa9e5607a3640ce04acafcc5ef0)
=> General cleanup of the install steps for Static Agent on Windows (#3986)

operations/helm/charts/grafana-agent/CHANGELOG.md
Adding the missing changelog entry for #3987
=> helm: add missing CHANGELOG entry

CHANGELOG.md, component/prometheus/operator/configgen/config_gen.go, component/prometheus/operator/configgen/config_gen_podmonitor_test.go, component/prometheus/operator/configgen/config_gen_servicemonitor_test.go
=> flow: fix panic in promethus/operator components when defaults not applied to user supplied relabel configs

docs/sources/flow/config-language/expressions/operators.md
Call out the string operators (just the "+" concatenation operator) by putting them into their own table.
=> Call out string operators

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
=> Update references for v0.34.0-rc.1

CHANGELOG.md, component/module/module.go, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
=> Cherry Pick bugfix into 0.34

component/prometheus/exporter/apache/apache.go
I accidentally added this from some local experiments.
=> remove accidental commit

docs/sources/flow/reference/components/prometheus.exporter.windows.md
Correcting description of dfsr in the Blocks section
=> Correct the description for dfsr in Blocks

CHANGELOG.md, docs/sources/static/configuration/integrations/_index.md, docs/sources/static/configuration/integrations/integrations-next/_index.md, docs/sources/static/configuration/integrations/squid-config.md, go.mod, go.sum, pkg/integrations/install/install.go, pkg/integrations/oracledb_exporter/oracledb_exporter_test.go, pkg/integrations/squid_exporter/squid_exporter.go, pkg/integrations/squid_exporter/squid_exporter_test.go
Adding an integration for the squid_exporter
Metrics exposed on http://hostname:3182
Notes:
The end goal of this integration is to use the exporter [built by boynux](https://github.com/boynux/squid-exporter)
=> Integrations: Add Squid Integration 

docs/sources/static/set-up/install-agent-on-windows.md
A copy paste error added "flow" info to the static install steps. Removing this info in the Windows static install topic.
=> Remove flow reference from Windows static install steps

docs/sources/flow/install/linux.md
Update the Linux install steps for Grafana Agent Flow
* Minor layout changes to align with Static docs where applicable.
* Add in missing SUSE/openSUSE installation steps.
=> Update Agent Flow Linux install topic

docs/sources/flow/reference/components/loki.source.windowsevent.md
Fixing typo in `user_incoming_timestamp`.
Correct spelling is `use_incoming_timestamp` - this is currently what agent flow is expecting.
=> Docs: Update loki.source.windowsevent.md

docs/sources/static/set-up/install-agent-macos.md
This PR makes minor updates and corrections to the macOS static Agent install
=> Minor corrections to macOS Agent Static install

docs/sources/static/set-up/install-agent-macos.md
…108)
* Update macOS steps to fix homebrew and  syntax
* Add missing note
* Fix spelling mistake
* Small changes for clarity
* Convert single step sections to paragraphs
* Fix the bullets and code block syntax
* Apply suggestions from code review
(cherry picked from commit 87dece7bdc9ad2355b3d22e0c0b14cda35304022)
=> Update macOS steps to fix Homebrew info and syntax (#4108)

docs/sources/static/configuration/integrations/integrations-next/app-agent-receiver-config.md
The navigation title is incorrect for app_agent_receiver_config. This PR updates the title metadata to correct the left navigation.
=> Update the nav title for app_agent_receiver_config

component/module/module.go, component/registry.go, pkg/flow/flow.go, pkg/flow/internal/controller/component.go, pkg/flow/internal/controller/loader_test.go, pkg/flow/module.go
ModuleControllers per component
=> Individual module controllers

CHANGELOG.md, component/loki/process/internal/stages/geoip.go, component/loki/process/internal/stages/geoip_test.go, component/loki/process/internal/stages/pipeline.go, component/loki/process/internal/stages/stage.go, docs/sources/flow/reference/components/loki.process.md, go.mod
Port of the [geoip stage](https://grafana.com/docs/loki/latest/clients/promtail/stages/geoip/#geoip) in Promtail.
=> feat: added geoip stage to loki.process

CHANGELOG.md, pkg/integrations/mongodb_exporter/mongodb_exporter.go
- Clarify that that the integration is disabled (not fully removed).
=> Fix wording and CHANGELOG entry

operations/helm/charts/grafana-agent/CHANGELOG.md, operations/helm/charts/grafana-agent/templates/controllers/statefulset.yaml, operations/helm/tests/create-statefulset-autoscaling/grafana-agent/templates/controllers/statefulset.yaml, operations/helm/tests/faro-ingress/grafana-agent/templates/ingress.yaml
=> helm: omit statefulset replicas if autoscaling enabled

CHANGELOG.md, component/all/all.go, component/prometheus/exporter/squid/squid.go, component/prometheus/exporter/squid/squid_test.go, docs/sources/flow/reference/components/prometheus.exporter.squid.md, pkg/integrations/squid_exporter/squid_exporter.go, pkg/integrations/squid_exporter/squid_exporter_test.go
- Adds a squid exporter to the list of supported flow integrations.
First attempt PR
=> flow: Add Squid Exporter

docs/sources/flow/install/linux.md
* First pass at install and uninstall cleanup
* Update the install steps
* Correct optional to match doc style
(cherry picked from commit 15db65933ef34f2bcbc395006e7fafcd3407f7f5)
=> Clean up Install Agent Flow on Linux docs (#4226)

docs/sources/flow/reference/components/otelcol.exporter.otlp.md, docs/sources/flow/reference/components/otelcol.exporter.otlphttp.md
Backport #4192 to release-v0.29.
=> Backport #4192 to release-v0.29

docs/sources/flow/reference/components/otelcol.exporter.otlp.md, docs/sources/flow/reference/components/otelcol.exporter.otlphttp.md
Backport #4192 to release-v0.30.
=> Backport #4192 to release-v0.30

CHANGELOG.md, build-image/Dockerfile, build-image/windows/Dockerfile, component/otelcol/exporter/prometheus/internal/convert/convert.go, component/otelcol/exporter/prometheus/internal/convert/convert_test.go, component/prometheus/operator/common/crdmanager.go, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install-agent-docker.md, packaging/grafana-agent-flow/rpm/gpg-sign.sh, packaging/grafana-agent/rpm/gpg-sign.sh, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
=> Release 0.34.3

docs/sources/flow/setup/install/windows.md
Fixes a typo in the Grafana Agent Flow for Windows installation instructions.
=> Fix typo in Grafana Flow Windows installation instructions.

README.md
Update README installation link from:
https://grafana.com/docs/agent/latest/flow/install/
to:
https://grafana.com/docs/agent/latest/flow/setup/install/
=> Update README installation link

component/pyroscope/appender.go, component/pyroscope/scrape/delta_profiles.go, component/pyroscope/scrape/delta_profiles_test.go, component/pyroscope/write/write.go
This is important to signal to the backend, that the profile is no longer using commulative values.
=> Ensure __delta__ label is exporter in pyroscope.write

docs/sources/_index.md, docs/sources/flow/_index.md, docs/sources/flow/setup/_index.md, docs/sources/flow/setup/configure/_index.md, docs/sources/flow/setup/configure/configure-kubernetes.md, docs/sources/flow/setup/configure/configure-linux.md, docs/sources/flow/setup/configure/configure-macos.md, docs/sources/flow/setup/configure/configure-windows.md, docs/sources/flow/setup/install/_index.md, docs/sources/flow/setup/install/binary.md, docs/sources/flow/setup/install/docker.md, docs/sources/flow/setup/install/kubernetes.md, docs/sources/flow/setup/install/linux.md, docs/sources/flow/setup/install/macos.md, docs/sources/flow/setup/install/windows.md, docs/sources/flow/setup/start-agent.md
* Update install config and start for consistency
* Fix copy paste error
* Rework mode content for flow mode
* Add more context for flow mode
* Additional updates for consistency
* Fix optional markdown
(cherry picked from commit 654e2c54676be05bd834b8a69a5962c453bd182a)
=> Update Grafana Agent install, config, and start topics (#4290)

docs/sources/flow/reference/components/loki.process.md
=> fix attribute name

docs/sources/flow/reference/components/loki.process.md
* fix attribute name
* fixup! fix attribute name
(cherry picked from commit 3211710619892d08adf38a1eb6ad7f5cb03bb06f)
=> fix attribute name (#4323)

build-image/windows/Dockerfile
=> windows build image: use fixed chocolatey version

docs/sources/static/set-up/_index.md
One of the alias redirects was broken in the Agent static docs. This PR fixes the broken redirect.
=> Fix broken alias in static docs

.drone/drone.yml, CHANGELOG.md, cmd/grafana-agent-operator/Dockerfile, cmd/grafana-agent/Dockerfile, cmd/grafana-agent/Dockerfile.windows, cmd/grafana-agentctl/Dockerfile, cmd/grafana-agentctl/Dockerfile.windows, tools/crow/Dockerfile, tools/make/build-container.mk, tools/smoke/Dockerfile
This will officially complete the build system switch to go 1.20.5.
=> Upgrade build-image to 0.28.0

.drone/drone.yml, cmd/grafana-agent-operator/Dockerfile, cmd/grafana-agent/Dockerfile, cmd/grafana-agent/Dockerfile.windows, cmd/grafana-agentctl/Dockerfile, cmd/grafana-agentctl/Dockerfile.windows, tools/crow/Dockerfile, tools/make/build-container.mk, tools/smoke/Dockerfile
This will complete upgrade to go 1.20.6
=> Update to build image 0.29.0

pkg/util/k8s/k8s_test.go
=> Skip one additional test broken by 1.20.6

converter/diag/diagnostic.go, converter/diag/diagnostics.go, converter/diag/severity.go, converter/internal/prometheusconvert/azure.go, converter/internal/prometheusconvert/consul.go, converter/internal/prometheusconvert/digitalocean.go, converter/internal/prometheusconvert/dns.go, converter/internal/prometheusconvert/docker.go, converter/internal/prometheusconvert/ec2.go, converter/internal/prometheusconvert/gce.go, converter/internal/prometheusconvert/kubernetes.go, converter/internal/prometheusconvert/lightsail.go, converter/internal/prometheusconvert/prometheus_blocks.go, converter/internal/prometheusconvert/prometheusconvert.go, converter/internal/prometheusconvert/relabel.go, converter/internal/prometheusconvert/remote_write.go, converter/internal/prometheusconvert/scrape.go, converter/internal/staticconvert/staticconvert_test.go
=> add info diags to prometheus converter

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
=> Update release versioning

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Merge the cherry pick into release-v0.35
=> Update release versioning (#4432)

CHANGELOG.md, docs/sources/flow/reference/stdlib/format.md, docs/sources/flow/reference/stdlib/join.md, docs/sources/flow/reference/stdlib/replace.md, docs/sources/flow/reference/stdlib/split.md, docs/sources/flow/reference/stdlib/to_lower.md, docs/sources/flow/reference/stdlib/to_upper.md, docs/sources/flow/reference/stdlib/trim.md, docs/sources/flow/reference/stdlib/trim_prefix.md, docs/sources/flow/reference/stdlib/trim_space.md, docs/sources/flow/reference/stdlib/trim_suffix.md, pkg/river/internal/stdlib/stdlib.go, pkg/river/vm/vm_stdlib_test.go
Cherry pick the new stdlib funcs
=> Cherry pick stdlib funcs

packaging/grafana-agent-flow/rpm/gpg-sign.sh, packaging/grafana-agent/rpm/gpg-sign.sh
Fix for GPG signing,  verified we changed the user in January. This has been broken since then?
=> GPG signing error

packaging/grafana-agent-flow/rpm/gpg-sign.sh, packaging/grafana-agent/rpm/gpg-sign.sh
Cherry pick changing the signing name
=> Cherry pick GPG signing name

CHANGELOG.md, converter/internal/prometheusconvert/file.go, converter/internal/prometheusconvert/prometheusconvert.go, converter/internal/prometheusconvert/testdata/file.river, converter/internal/prometheusconvert/testdata/file.yaml, converter/internal/prometheusconvert/validate.go
=> Converter prom file sd config

.drone/drone.yml, .drone/pipelines/publish.jsonnet
Update pyroscope-ebpf wave same way as grafana-agent does 
~I am not sure my drone token is valid for this repo, so maybe maintainers need to sign it~
=> chore(ebpf): update dev_canary version in deployment_tools for ebpf

.github/workflows/update-make-docs.yml, CODEOWNERS, docs/docs.mk, docs/make-docs, docs/variables.mk
See individual commits.
I'll need an admin to add @grafana/docs-tooling to the repository if you would like me to be able to promptly review and merge the daily automated update PRs.
@ptodev, this also updates the `make docs` behavior to use the current repository as the source of the content and not use the repository inferred from the project name.
=> Update `make docs` procedure and ensure that it is regularly updated in future.

docs/sources/_index.md
Agent index weight needs to be updated to allow better integration with Cloud docs
=> Update weight for Agent index 

docs/sources/flow/reference/components/loki.process.md
=>  docs: fix typo in geoip_continent_name label

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
=> Update changelog and references to the rc.1

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
=> Cherry pick update from main

operations/helm/charts/grafana-agent/CHANGELOG.md, operations/helm/charts/grafana-agent/README.md, operations/helm/charts/grafana-agent/ci/global-image-pullsecrets-values.yaml, operations/helm/charts/grafana-agent/templates/controllers/_pod.yaml, operations/helm/charts/grafana-agent/values.yaml, operations/helm/tests/global-image-pullsecrets/grafana-agent/templates/controllers/daemonset.yaml
This PR adds the function to set the securityContext at pod level via the pod template.
=> helm: add securityContext at podlevel

CHANGELOG.md, production/grafana-agent-mixin/alerts.libsonnet
Rename the `GrafanaAgentManagement` mixin alert rules to `GrafanaAgentConfig` and update individual alerts to be more accurate.
=> Change GrafanaAgentManagement Mixin Alerts

converter/internal/test_common/testing.go, pkg/integrations/windows_exporter/config_windows.go, pkg/integrations/windows_exporter/config_windows_test.go
=> Re-enable converted config loading when not on Windows

docs/sources/flow/reference/components/otelcol.processor.memory_limiter.md, docs/sources/flow/reference/components/otelcol.processor.tail_sampling.md, docs/sources/flow/reference/components/prometheus.exporter.apache.md, docs/sources/flow/reference/components/prometheus.exporter.consul.md, docs/sources/flow/reference/components/prometheus.exporter.mysql.md, docs/sources/flow/reference/components/prometheus.exporter.process.md
(cherry picked from commit 5a0a4021058226ec72b101104ebe92a59a3dddf9)
=> Remove zero width spaces (#4536)

CHANGELOG.md, component/common/config/types.go, component/common/config/types_test.go
Fix nil reference with tls not being defined with Oauth2.
=> Fix nil reference oauth2

docs/sources/flow/setup/install/docker.md
This PR fixes a broken link in the Agent in Docker deploy topic
=> Fix broken link in Agent Docker deploy topic

docs/sources/_index.md, docs/sources/about.md
Issue https://github.com/grafana/agent/issues/4455 was opened to fix/clarify the language used around picking variants of Grafana Agent. 
This PR renames the `About Grafana Agent` topic to `Introduction to Grafana Agent`. It's a small change and does not fully resolve the concerns raised by the Issue. This change removes some of the question around the intent of the About topic. More work is needed here (will be done in future PRs).
Changes: 
1. Fix Note notation
1. Rename About to Introduction to align with other Grafana doc structure.
=> Rename About and fix links

docs/sources/flow/getting-started/migrating-from-prometheus.md
=> include environment var AGENT_MODE in migration docs

docs/sources/flow/reference/components/pyroscope.ebpf.md, operations/helm/charts/grafana-agent/CHANGELOG.md, operations/helm/charts/grafana-agent/README.md, operations/helm/charts/grafana-agent/templates/controllers/_pod.yaml, operations/helm/charts/grafana-agent/values.yaml
=> fix(helm): add hostPID value

converter/internal/prometheusconvert/azure.go, converter/internal/prometheusconvert/common.go, converter/internal/promtailconvert/internal/build/syslog.go, converter/internal/promtailconvert/promtailconvert.go, converter/internal/promtailconvert/testdata/syslog.river, converter/internal/promtailconvert/testdata/syslog.yaml
Adds converter support for `syslog` promtail config block.
=> Add promtail converter for syslog

component/loki/source/gcplog/gcplog.go, component/loki/source/gcplog/gcplog_test.go, component/loki/source/gcplog/gcptypes/gcptypes.go, component/loki/source/gcplog/internal/gcplogtarget/pull_target.go, component/loki/source/gcplog/internal/gcplogtarget/pull_target_test.go, component/loki/source/gcplog/internal/gcplogtarget/push_target.go, component/loki/source/gcplog/internal/gcplogtarget/push_target_test.go, component/loki/source/gcplog/internal/gcplogtarget/types.go, converter/internal/common/weaveworks_server.go, converter/internal/promtailconvert/internal/build/gcplog.go, converter/internal/promtailconvert/internal/build/push_api.go, converter/internal/promtailconvert/promtailconvert.go, converter/internal/promtailconvert/testdata/gcplog.river, converter/internal/promtailconvert/testdata/gcplog.yaml
This adds GCPLog support for both push and pull
=> Add promtail converters support for GCPLog

CHANGELOG.md
Making sure the CHANGELOG is kept consistent..
=> Add newlines between recent changelog entries

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Bump version references in the main branch for v0.35.2.
=> [main] prepare for release v0.35.2

CHANGELOG.md, cmd/grafana-agentctl/Dockerfile, component/common/config/types.go, component/common/config/types_test.go, component/prometheus/operator/common/crdmanager.go, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install/install-agent-docker.md, packaging/grafana-agent-flow/rpm/gpg-sign.sh, packaging/grafana-agent/rpm/gpg-sign.sh, pkg/metrics/wal/wal.go, pkg/metrics/wal/wal_test.go, pkg/operator/defaults.go, pkg/river/encoding/riverjson/riverjson.go, pkg/river/encoding/riverjson/riverjson_test.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet, tools/make/packaging.mk
Cherry-pick fixes into release-v0.35 and bump version references.
=> [release-v0.35] Prepare for release v0.35.2

.github/workflows/trivy.yml
Runs at 8am and 8pm UTC (arbitrary).
Sans main so we don't have to build.
=> Change trivy job to cron scheduling

.github/workflows/trivy.yml
I think checkout code was needed
Update to :15 after to observe again.
=> Trivy, run checkout step

component/loki/source/windowsevent/component_windows.go, converter/internal/promtailconvert/internal/build/azure_event_hub.go, converter/internal/promtailconvert/internal/build/cloudflare.go, converter/internal/promtailconvert/internal/build/gelf.go, converter/internal/promtailconvert/internal/build/herokudrain.go, converter/internal/promtailconvert/internal/build/kafka.go, converter/internal/promtailconvert/internal/build/scrape_builder.go, converter/internal/promtailconvert/internal/build/windows_events.go, converter/internal/promtailconvert/promtailconvert.go, converter/internal/promtailconvert/testdata/azure_event_hubs.river, converter/internal/promtailconvert/testdata/azure_event_hubs.yaml, converter/internal/promtailconvert/testdata/gelf.river, converter/internal/promtailconvert/testdata/gelf.yaml, converter/internal/promtailconvert/testdata/heroku.river, converter/internal/promtailconvert/testdata/heroku.yaml, converter/internal/promtailconvert/testdata/kafka.river, converter/internal/promtailconvert/testdata/kafka.yaml, converter/internal/promtailconvert/testdata/windowsevents.diags, converter/internal/promtailconvert/testdata/windowsevents.river, converter/internal/promtailconvert/testdata/windowsevents.yaml, converter/internal/promtailconvert/testdata/windowsevents_relabel.river, converter/internal/promtailconvert/testdata/windowsevents_relabel.yaml
Adds support for all the remaining components in promtail converter. 
The only remaining work for promtail is:
* Encoding & DecompressionCfg
* All pipeline stages support
=> promtail config conversions part 3

docs/sources/flow/setup/install/kubernetes.md
Suggest "Next Steps" to point to Kubernetes, which is what this page is about, and not Linux.
=> docs(install/kubernetes): Point to Configure Kubernetes from Install on Kubernetes

docs/sources/flow/setup/install/kubernetes.md
=> [release-v0.35] docs(install/kubernetes): Point to Configure Kubernetes from Install on Kubernetes

docs/sources/flow/setup/install/kubernetes.md
=> [release-v0.33] docs(install/kubernetes): Point to Configure Kubernetes from Install on Kubernetes

component/common/loki/wal/writer_test.go
This PR fixes a Loki WAL Writer flaky test, which was lacking of an eventual assert, since the assertion dependend on a file system flush.
Flaky run: https://drone.grafana.net/grafana/agent/11226/5/2
=> Fix loki WAL writer flaky test

converter/internal/promtailconvert/internal/build/scrape_builder.go, converter/internal/promtailconvert/promtailconvert.go, converter/internal/promtailconvert/testdata/static_pipeline_example.river, converter/internal/promtailconvert/testdata/static_pipeline_example.yaml, converter/internal/promtailconvert/testdata/unsupported.diags, converter/internal/promtailconvert/testdata/unsupported.yaml
Adds handling of encoding and decompression settings for promtail converters. 
* Encoding was added with https://github.com/grafana/agent/issues/3938
* Decompression is not supported, but an issue is opened https://github.com/grafana/agent/issues/4669
=> Promtail converters: encoding and decompression settings

.drone/drone.yml, .drone/pipelines/publish.jsonnet
Grafanabot must have had god rights to directly push to deployment tools, so now based on some other projects, added details to automatically open a repo.
=> Fix GitHub app

docs/sources/flow/reference/components/loki.source.docker.md
I got a question regarding this and I'd prefer this was documented.
=> Document positions file usage in loki.source.docker.md

CHANGELOG.md, converter/internal/prometheusconvert/relabel.go, converter/internal/staticconvert/testdata/integrations.river, converter/internal/staticconvert/testdata/prom_scrape.river
=> fix for converter relabel source_labels

docs/sources/flow/reference/cli/_index.md, docs/sources/flow/reference/cli/convert.md, docs/sources/flow/reference/cli/fmt.md, docs/sources/flow/reference/cli/run.md, docs/sources/flow/reference/cli/tools.md
* Update executable name
* More executable name updates
* Change bullet order and add missing info
* Switch to command name remove binary
Co-authored-by: Robert Fratto
* Update metadata change note to caution
* Swap command order in usage section
* Fix a typo
* General cleanup and formatting
* Remove a gerund
---------
Co-authored-by: Robert Fratto 
(cherry picked from commit 6f885c99ab539a70c33390999f7fe084e2a1e59d)
=> Update the Agent CLI topics to clarify flow mode syntax (#4697)

.drone/drone.yml, .drone/pipelines/publish.jsonnet, .drone/util/secrets.jsonnet, .github/workflows/add-to-project.yml, .github/workflows/depcheck.yml
This removes most of the grafanabot references, there are a few still around docs but that is being worked on separately.
=> Remove most of the grafanabot references.

CHANGELOG.md, cmd/internal/flowmode/cmd_run.go, pkg/cluster/cluster.go
This is a PR to cherry-pick two clustering-specific PRs for release-v0.35
=> Cherry-pick cluster fixes to release-v0.35

CHANGELOG.md, component/prometheus/exporter/mongodb/mongodb.go, component/prometheus/exporter/mongodb/mongodb_test.go, docs/sources/flow/reference/components/prometheus.exporter.mongodb.md, docs/sources/static/configuration/integrations/mongodb_exporter-config.md, pkg/integrations/mongodb_exporter/mongodb_exporter.go
Surfacing tls-basic-auth-config-path config option. 
I am also including direct-connect, discovering-mode config options to give more flexibility to the users, while still abstracting much of the config complexity.
=> MongoDB: tls + other config options

docs/sources/static/set-up/install/install-agent-linux.md
Backport 730887941862d72b098adbd6269bf5565bf2ffb5 from #4755
=> Backport 4755 to release v0.33

converter/internal/promtailconvert/internal/build/loki_write.go, converter/internal/promtailconvert/testdata/unsupported.diags, converter/internal/promtailconvert/validate.go, docs/sources/flow/getting-started/migrating-from-promtail.md, docs/sources/flow/reference/cli/run.md
* Adds promtail migration guide, inspired by prometheus migration guide.
* Rephrases some warnings
=> Promtail migration guide

converter/internal/promtailconvert/internal/build/scrape_builder.go, converter/internal/staticconvert/staticconvert.go, converter/internal/staticconvert/testdata/sanitize.diags, converter/internal/staticconvert/testdata/sanitize.river, converter/internal/staticconvert/testdata/sanitize.yaml
=> sanitize job names for labels

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Cherry pick version number and fix changelog discrepancy.
=> Apply cherry pick

packaging/grafana-agent-flow/rpm/gpg-sign.sh, packaging/grafana-agent/rpm/gpg-sign.sh
Remove command line args that aren't valid
=> Dont need these arguments

docs/sources/flow/reference/components/loki.write.md, docs/sources/flow/reference/components/otelcol.exporter.otlp.md, docs/sources/flow/reference/components/prometheus.remote_write.md
* Add examples showing Grafana Cloud
* Remove some blank lines
* remove strange characters
---------
Co-authored-by: Robert Fratto <robertfratto@gmail.com>
(cherry picked from commit 6dd537434e09c304e56c5e365431a2838a7c38bc)
=> Add examples to flow reference showing Grafana Cloud (#4799)

CHANGELOG.md, cmd/grafana-agent/entrypoint.go, pkg/supportbundle/supportbundle.go
When trying to get the logs targets, a DefaultHTTPClient was being used, which is not able to access in-memory HTTP addresses. This fixes it to use the correct HTTP Client.
Fixes #4803
=> Fix support bundle generation

converter/internal/staticconvert/internal/build/blackbox_exporter.go, converter/internal/staticconvert/internal/build/builder.go, converter/internal/staticconvert/internal/build/cloudwatch_exporter.go, converter/internal/staticconvert/testdata/integrations.diags, converter/internal/staticconvert/testdata/integrations.river, converter/internal/staticconvert/testdata/integrations.yaml, converter/internal/staticconvert/validate.go
=> add static conversion for blackbox and cloudwatch

component/prometheus/operator/configgen/config_gen_podmonitor.go, component/prometheus/operator/configgen/config_gen_podmonitor_test.go, component/prometheus/operator/configgen/config_gen_servicemonitor.go, component/prometheus/operator/configgen/config_gen_servicemonitor_test.go
=> fix bug with integer targetPort in prometheus.operator.*

converter/internal/staticconvert/staticconvert_test.go, converter/internal/staticconvert/testdata/integrations.river, converter/internal/staticconvert/testdata/integrations.yaml, converter/internal/staticconvert/testdata/sanitize.river, converter/internal/staticconvert/testdata/sanitize.yaml, converter/internal/staticconvert/testdata_windows/integrations.diags, converter/internal/staticconvert/testdata_windows/integrations.river, converter/internal/staticconvert/testdata_windows/integrations.yaml
=> separate windows tests for windows components in the static converter

converter/internal/staticconvert/testdata/integrations.river, converter/internal/staticconvert/testdata/integrations.yaml
=> remote non deterministic testing

.github/workflows/publish-documentation-versioned.yml
Let's us manually dispatch the workflow for older branches
=> Add workflow dispatch

docs/sources/flow/concepts/configuration_language.md, docs/sources/flow/config-language/components.md, docs/sources/flow/getting-started/collect-prometheus-metrics.md, docs/sources/flow/reference/components/_index.md, docs/sources/static/configuration/integrations/integrations-next/_index.md, docs/sources/static/configuration/integrations/integrations-next/app-agent-receiver-config.md, docs/sources/static/configuration/integrations/integrations-next/blackbox-config.md, docs/sources/static/configuration/integrations/integrations-next/eventhandler-config.md, docs/sources/static/configuration/integrations/integrations-next/snmp-config.md, docs/sources/static/configuration/integrations/integrations-next/vsphere-config.md
This PR updates/remove duplicated titles in the Agent documentation. See: https://github.com/grafana/website/issues/14851
=> Update and remove duplicated titles

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/release-notes.md, docs/sources/static/set-up/install/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Prepare for v0.36.0-rc.0 release as per release docs.
=> Prepare main for v0.36.0-rc.0 release

CHANGELOG.md
Cherr-pick what we've merged to main as it's relevant for this release
https://github.com/grafana/agent/pull/4944
=> Split changelog into features and enhancements (#4944)

.drone/drone.yml, .github/workflows/test.yml, CHANGELOG.md, cmd/grafana-agent-operator/Dockerfile, cmd/grafana-agent/Dockerfile, cmd/grafana-agent/Dockerfile.windows, cmd/grafana-agentctl/Dockerfile, cmd/grafana-agentctl/Dockerfile.windows, component/loki/source/syslog/internal/syslogtarget/syslogtarget_test.go, converter/internal/staticconvert/testdata/integrations.river, go.mod, go.sum, pkg/server/tls_test.go, tools/crow/Dockerfile, tools/make/build-container.mk, tools/smoke/Dockerfile
=> Update builds to use Go 1.21

docs/sources/flow/reference/components/prometheus.exporter.consul.md, docs/sources/operator/_index.md, docs/sources/static/_index.md, docs/sources/static/release-notes.md, docs/sources/static/set-up/install/_index.md, docs/sources/static/set-up/install/install-agent-kubernetes.md, docs/sources/static/set-up/quick-starts.md
This PR fixes several 403s, 404s, and other outdated or otherwise broken links identified by a Hugo build error report.
=> Fix broken links

docs/sources/flow/reference/components/prometheus.exporter.consul.md, docs/sources/operator/_index.md, docs/sources/static/_index.md, docs/sources/static/release-notes.md, docs/sources/static/set-up/install/_index.md, docs/sources/static/set-up/install/install-agent-kubernetes.md, docs/sources/static/set-up/quick-starts.md
(cherry picked from commit dba4970355703fa0b61be878c614176c2a8ea9fd)
Backporting https://github.com/grafana/agent/pull/4978
=> Fix broken links (#4978)

docs/sources/flow/reference/components/prometheus.exporter.elasticsearch.md
(cherry picked from commit d73bbd9b6d6c0ac899914fc62e846a4e0e360305)
Backport https://github.com/grafana/agent/pull/4966 to v0.35
=> Fix elasticsearch flow component usage example (#4966)

docs/sources/flow/getting-started/configure-agent-clustering.md, docs/sources/flow/getting-started/distribute-prometheus-scrape-load.md, docs/sources/operator/_index.md, docs/sources/operator/deploy-agent-operator-resources.md
* Move link inside of admonition section
* Include beta links and add period
---------
(cherry picked from commit 1632c12e802f637afc836260daff0e93dc9d7bd3)
Backport https://github.com/grafana/agent/pull/4952 to v0.35
=> [Docs] Fix and add a few links (#4952)

docs/sources/flow/reference/components/loki.write.md
This looks like it was a copy/paste error.
=> correct docs for max_streams

README.md
This fixes a broken link in README.md to correctly point to Pyroscope.
=> Fix broken link to Pyroscope

README.md, docs/make-docs, docs/rfcs/0006-clustering.md, docs/sources/_index.md, docs/sources/about.md, docs/sources/flow/reference/components/pyroscope.write.md
Update phlare references pre pyroscope 1.0
=> Update phlare references

CHANGELOG.md
Fix a conflict which accidentally made its way on main.
=> Fix changelog conflict

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
=> Prepare main for v0.36.0

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Prepare release branch for v0.36.0 (cherry pick of #5003) to release branch.
=> Prepare release branch for v0.36.0 (cherry pick of #5003)

docs/sources/_index.md
This PR updates the main _index.md file so it lands in the right place in the Cloud doc tree.
=> Update index weight

docs/make-docs, docs/sources/_index.md, docs/sources/about.md, docs/sources/flow/reference/components/pyroscope.write.md
(cherry picked from commit 48a62dcdbf221c57c79c472d13cae6d192a943d0)
Backporting https://github.com/grafana/agent/pull/4987 to Agent v0.35 docs
=> Update phlare references (#4987)

docs/sources/static/configuration/scraping-service.md
…5050)
* Remove mode and adjust sentences
* Minor puntuation and grammar cleanup
(cherry picked from commit 33b7b61ed2421f3168cd9349a499201409e54284)
=> [release-v0.34] Remove reference to `mode` in the Agent scraping service document.

go.mod, go.sum, pkg/server/server.go, service/http/http.go
=> Update to latest pyroscope-go/godeltaprof module

CHANGELOG.md, example/docker-compose/mimir/config/mimir.yaml
Correct indentation for Mimir's `multitenancy_enabled` option.
Fixes #5073 
- ~~[ ] Tests updated~~
- ~~[ ] Config converters updated~~
=> fix(cfg): correct indentation for Mimir's `multitenancy_enabled` option

CHANGELOG.md, component/all/all.go, component/discovery/triton/triton.go, component/discovery/triton/triton_test.go, converter/internal/prometheusconvert/prometheusconvert.go, converter/internal/prometheusconvert/testdata/triton.river, converter/internal/prometheusconvert/testdata/triton.yaml, converter/internal/prometheusconvert/triton.go, converter/internal/prometheusconvert/validate.go, converter/internal/promtailconvert/testdata/triton.river, converter/internal/promtailconvert/testdata/triton.yaml, converter/internal/promtailconvert/testdata/unsupported.diags, docs/sources/flow/reference/components/discovery.triton.md
=> add support for discovery.triton flow component and converter

CHANGELOG.md, pkg/operator/defaults.go
Fixes #3282 among others perhaps
=> Operator: update default reloader version

docs/sources/flow/reference/components/pyroscope.ebpf.md
=> fix(pyroscope): include popular k8s labels in pyroscope.ebpf k8s example docs

docs/sources/flow/reference/components/loki.process.md
Just updated the stage.drop block example to use the `drop_counter_reason` argument instead of the (old?) `drop_reason` argument.
=> docs: fix stage.drop block example of loki.process component

CHANGELOG.md, converter/internal/common/common.go, converter/internal/prometheusconvert/prometheusconvert.go, converter/internal/prometheusconvert/remote_write.go, converter/internal/prometheusconvert/testdata/scrape.river, converter/internal/prometheusconvert/testdata/scrape.yaml, converter/internal/staticconvert/internal/build/blackbox_exporter.go, converter/internal/staticconvert/internal/build/snmp_exporter.go, converter/internal/staticconvert/staticconvert_test.go
See changelog for details
Fixes #5077
=> Converter fix identifiers

.drone/drone.yml, .golangci.yml, cmd/grafana-agent-operator/Dockerfile, cmd/grafana-agent/Dockerfile, cmd/grafana-agent/Dockerfile.windows, cmd/grafana-agentctl/Dockerfile, cmd/grafana-agentctl/Dockerfile.windows, tools/crow/Dockerfile, tools/make/build-container.mk, tools/smoke/Dockerfile
Follow up on #5108.
Closes #4163.
=> Bump usage of build image to v0.30.1

CHANGELOG.md, component/all/all.go, component/discovery/kuma/kuma.go, component/discovery/kuma/kuma_test.go, converter/internal/prometheusconvert/kuma.go, converter/internal/prometheusconvert/prometheusconvert.go, converter/internal/prometheusconvert/testdata/kuma.river, converter/internal/prometheusconvert/testdata/kuma.yaml, converter/internal/prometheusconvert/validate.go, docs/sources/flow/reference/components/discovery.kuma.md
=> Add discovery.kuma component and converter

docs/developer/release/8-update-helm-charts.md, operations/helm/charts/grafana-agent/CHANGELOG.md, operations/helm/charts/grafana-agent/Chart.yaml, operations/helm/charts/grafana-agent/README.md, operations/helm/tests/clustering/grafana-agent/templates/controllers/statefulset.yaml, operations/helm/tests/controller-volumes-extra/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/create-daemonset-hostnetwork/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/create-daemonset/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/create-deployment-autoscaling/grafana-agent/templates/controllers/deployment.yaml, operations/helm/tests/create-deployment/grafana-agent/templates/controllers/deployment.yaml, operations/helm/tests/create-statefulset-autoscaling/grafana-agent/templates/controllers/statefulset.yaml, operations/helm/tests/create-statefulset/grafana-agent/templates/controllers/statefulset.yaml, operations/helm/tests/custom-config/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/default-values/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/envFrom/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/existing-config/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/extra-env/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/extra-ports/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/faro-ingress/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/global-image-pullsecrets/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/global-image-registry/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/initcontainers/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/local-image-pullsecrets/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/local-image-registry/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/nodeselectors-and-tolerations/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/static-mode/grafana-agent/templates/controllers/daemonset.yaml
also included installing yamllint in the release docs for the make command
=> bump agent helm version v0.36.1

CHANGELOG.md, converter/internal/prometheusconvert/scrape.go, converter/internal/prometheusconvert/testdata/unsupported.diags, converter/internal/prometheusconvert/testdata/unsupported.yaml
Signed-off-by: erikbaranowski <39704712+erikbaranowski@users.noreply.github.com>
(cherry picked from commit 16bda28480748df713acf13851030d2d09485e4f)
Fixes #5077
=> Add a couple more unsupported fields to the prometheus converter

.drone/drone.yml, CHANGELOG.md, cmd/grafana-agent-operator/Dockerfile, cmd/grafana-agent/Dockerfile, cmd/grafana-agent/Dockerfile.windows, cmd/grafana-agentctl/Dockerfile, cmd/grafana-agentctl/Dockerfile.windows, tools/crow/Dockerfile, tools/make/build-container.mk, tools/smoke/Dockerfile
=> build: bump build image usage to 0.30.2

converter/internal/staticconvert/staticconvert.go, converter/internal/staticconvert/testdata/unsupported.diags, converter/internal/staticconvert/testdata/unsupported.yaml, converter/internal/staticconvert/validate.go
=> validate unsupported disabled integrations in the static converter

docs/sources/flow/setup/install/macos.md
This doc should be referring to 'grafana-agent-flow' service, however this one code snippet is referring to the service name for Grafana Agent in static mode.
=> Update Brew service name reference for flow

docs/sources/flow/setup/install/macos.md
Backport 0cf05ba6dca59140b784661a4ae53b5d879fef73 from #5140
=> [release-v0.34] Update Brew service name reference for flow

docs/sources/flow/setup/start-agent.md
This PR fixes a link that is causing a 404 error in the builds.
=> Update path to fix 404 error

docs/sources/flow/setup/install/_index.md
removed Armv7 and Armv6 from supported architecture. see slack thread for more details.
https://raintank-corp.slack.com/archives/C011RGTMUSY/p1680887617024879
(cherry picked from commit 5cb9e6b6afe53eb0171fe0f99500b5da99093d4e)
=> Update _index.md (#5142)

docs/sources/static/set-up/install/_index.md
removed Armv7 and Armv6 from supported architecture. see slack thread for more details.
https://raintank-corp.slack.com/archives/C011RGTMUSY/p1680887617024879
(cherry picked from commit f3eee34b425ecd2d33c3e8da35c8c71c9322b1e3)
=> Update _index.md (#5141)

docs/sources/flow/reference/components/prometheus.exporter.blackbox.md, docs/sources/flow/reference/components/prometheus.exporter.cloudwatch.md, docs/sources/flow/reference/components/prometheus.exporter.snmp.md
* Remove name from block arguments and add a sentence that a label is required
* Fix blocks header levels and move 'period and length' section
* Add suggested change
* Revert "Fix blocks header levels and move 'period and length' section"
This reverts commit 93a593aad79e1a88eac4e6d5e3e63107866156c2.
---------
(cherry picked from commit 31999c8224d3d6cbf848fa441e5862a03abd5837)
=> [Docs] prometheus.exporter.[blackbox, snmp] misc. fixes (#5187)

docs/sources/flow/reference/components/prometheus.exporter.cloudwatch.md
* Update prometheus.exporter.cloudwatch docs
* Move period and length section and remove backticks from header
---------
(cherry picked from commit 5db01d94c93c820e75e7c716aba1083aa228dcde)
=> Update prometheus.exporter.cloudwatch docs (#5195)

docs/sources/static/set-up/install/install-agent-on-windows.md
This PR fixes a double character typo in the Agent static Windows install topic
=> Fix bad link syntax in Agent static mode Windows install

converter/internal/staticconvert/testdata/prom_scrape.river, converter/internal/staticconvert/testdata/prom_scrape.yaml, converter/internal/staticconvert/testdata_windows/integrations.river, converter/internal/staticconvert/testdata_windows/integrations.yaml
=> fix flaky static converter test

CHANGELOG.md, docs/sources/flow/reference/components/discovery.http.md
Fixes #5232 
- [ x ] Documentation added
=> Expand documentation to demonstrate label options

CHANGELOG.md, component/all/all.go, component/prometheus/exporter/agent/agent.go, docs/sources/flow/reference/components/prometheus.exporter.agent.md
Add a Flow component, equivalent to agent's integration in static mode
Close #5021 
- ~~[ ] Tests updated~~
- ~~[ ] Config converters updated~~
=> feat(exporter): add Flow component for agent Integration

docs/sources/flow/reference/components/prometheus.exporter.snmp.md, docs/sources/static/configuration/integrations/snmp-config.md
This PR adds a note to the SNMP documentation detailing which version of the Prometheus SNMP exporter is used.
=> Update SNMP topics to add note about the version of Prometheus snmp_exporter

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Adding v0.36.2 to the changelog and updating version references throughout the repo.
=> Update version for patch release v0.36.2

operations/helm/charts/grafana-agent/CHANGELOG.md, operations/helm/charts/grafana-agent/Chart.yaml, operations/helm/charts/grafana-agent/README.md, operations/helm/tests/clustering/grafana-agent/templates/controllers/statefulset.yaml, operations/helm/tests/controller-volumes-extra/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/create-daemonset-hostnetwork/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/create-daemonset/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/create-deployment-autoscaling/grafana-agent/templates/controllers/deployment.yaml, operations/helm/tests/create-deployment/grafana-agent/templates/controllers/deployment.yaml, operations/helm/tests/create-statefulset-autoscaling/grafana-agent/templates/controllers/statefulset.yaml, operations/helm/tests/create-statefulset/grafana-agent/templates/controllers/statefulset.yaml, operations/helm/tests/custom-config/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/default-values/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/enable-servicemonitor/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/envFrom/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/existing-config/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/extra-env/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/extra-ports/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/faro-ingress/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/global-image-pullsecrets/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/global-image-registry/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/initcontainers/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/local-image-pullsecrets/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/local-image-registry/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/nodeselectors-and-tolerations/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/static-mode/grafana-agent/templates/controllers/daemonset.yaml
Update Grafana Agent version to v0.36.2 and release Agent Helm chart v0.25.0
=> Release Agent Helm chart v0.25.0

converter/internal/staticconvert/staticconvert.go, converter/internal/staticconvert/testdata/prom_scrape.yaml, pkg/config/config.go
=> evaluate env vars in static converter instead of crashing

pkg/integrations/cadvisor/cadvisor.go
Adds `plugins` and `raw.Options` for the new `manager.New()`.
(The tests will likely fail because it's not using the real fork, I added a `replace github.com/google/cadvisor => /path/to/cadvisorfork` to my `go.mod`)
=> Update cadvisor inputs

docs/sources/_index.md, docs/sources/flow/reference/components/prometheus.exporter.agent.md, docs/sources/flow/reference/components/remote.kubernetes.configmap.md, docs/sources/flow/reference/components/remote.kubernetes.secret.md
This PR fixes some bad links found in a Hugo build report.
=> Fix some bad links in Agent documentation

docs/sources/flow/reference/components/remote.vault.md
Just a small doc formatting change.
=> Stop code-formatting the title

component/prometheus/exporter/cadvisor/cadvisor_test.go, docs/sources/flow/reference/components/prometheus.exporter.cadvisor.md
Adds basic tests and documentation for the cAdvisor flow component.
=> cAdvisor component tests and docs

docs/sources/static/configuration/scraping-service.md
=> Fix typo in scraping-service topic

CHANGELOG.md, converter/internal/promtailconvert/internal/build/loki_write.go, converter/internal/promtailconvert/testdata/unsupported.diags, converter/internal/promtailconvert/testdata/unsupported.yaml, converter/internal/promtailconvert/validate.go, go.mod, go.sum
Upgrades `loki` to `go get github.com/grafana/loki@k169`. This is to include a fix https://github.com/grafana/loki/pull/10631.
=> Fix static mode file tailing race condition

CHANGELOG.md, component/loki/source/kubernetes/kubetail/tailer.go
Fixes #5322 
Certainly should be looked at from the upstream library's perspective
=> Set MinBackoff for Tailer config to one

go.mod, go.sum
https://github.com/grafana/pyroscope/pull/2473
=> fix(ebpf): add pprof time

CHANGELOG.md, operations/agent-flow-mixin/dashboards/controller.libsonnet, pkg/flow/internal/controller/loader.go, pkg/flow/internal/controller/metrics.go, pkg/flow/internal/controller/node_component.go, pkg/flow/internal/dag/walk.go
This PR pulls out some metric from https://github.com/grafana/agent/pull/5280 in order to make that PR smaller and also collect some metrics before and after it is merged.
=> [flow] Measure dependency evaluation wait time

docs/sources/operator/helm-getting-started.md
This PR fixes a broken link in the Agent Operator docs.
=> Fix broken link in Agent Operator docs

docs/sources/flow/getting-started/migrating-from-prometheus.md, docs/sources/flow/getting-started/migrating-from-promtail.md
=> clarify migration usage guide limitation for metamonitoring metric names

docs/sources/flow/reference/components/discovery.kubernetes.md
=> discovery.kubernetes docs: add example for node filtering

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Step 3 of the process to publish the release candidate
https://github.com/grafana/agent/blob/main/docs/developer/release/3-update-version-in-code.md
=> all: update version string everywhere for v0.37.0-rc.0

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Step 3 of the process to publish the release candidate
https://github.com/grafana/agent/blob/main/docs/developer/release/3-update-version-in-code.md
=> all: update version string everywhere for v0.37.0-rc.1

docs/sources/flow/getting-started/collect-prometheus-metrics.md
=> Fixing of a copy-paste error

CHANGELOG.md, component/loki/process/stages/decolorize.go, component/loki/process/stages/decolorize_test.go, component/loki/process/stages/extensions.go, component/loki/process/stages/pipeline.go, component/loki/process/stages/stage.go, converter/internal/promtailconvert/internal/build/stages.go, converter/internal/promtailconvert/testdata/pipeline_stages_part2.river, converter/internal/promtailconvert/testdata/pipeline_stages_part2.yaml, converter/internal/promtailconvert/testdata/pipeline_stages_unsupported.diags, converter/internal/promtailconvert/testdata/pipeline_stages_unsupported.yaml, docs/sources/flow/reference/components/loki.process.md
Part of https://github.com/grafana/agent/issues/4836
This fell through the cracks for feature parity.
=> loki.process: add decolorise stage support

component/loki/source/kubernetes_events/event_controller.go, component/prometheus/operator/common/crdmanager.go, pkg/operator/operator.go
(cherry picked from commit 37c40cc530c101d993f063d1825f384738531bcd)
=> operator: initialise default namespaces map config (#5424)

CHANGELOG.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/getting-started.md, docs/sources/static/configuration/integrations/node-exporter-config.md, docs/sources/static/configuration/integrations/process-exporter-config.md, docs/sources/static/set-up/install/install-agent-docker.md, pkg/operator/defaults.go, production/kubernetes/agent-bare.yaml, production/kubernetes/agent-loki.yaml, production/kubernetes/agent-traces.yaml, production/kubernetes/build/lib/version.libsonnet, production/kubernetes/build/templates/operator/main.jsonnet, production/kubernetes/install-bare.sh, production/operator/templates/agent-operator.yaml, production/tanka/grafana-agent/v1/main.libsonnet, production/tanka/grafana-agent/v2/internal/base.libsonnet, production/tanka/grafana-agent/v2/internal/syncer.libsonnet
Step 2 for publishing a patch release
https://github.com/grafana/agent/tree/main/docs/developer/release#patch-release-publish-latest-version
=> all: update version string everywhere for v0.37.1

docs/sources/_index.md, docs/sources/_index.md.t
This PR fixes a failing cross reference link from a note.
Restoring the original relref results in a broken link when this topic is mounted into the Grafana Cloud docs.  Converting the link to a fully qualified link ensures the link will work in Agent docs and in Cloud docs. Refer to: https://grafana.com/docs/writers-toolkit/write/references/#choose-the-correct-link
=> Fix a cross reference link in a note in the Agent root topic

operations/helm/charts/grafana-agent/CHANGELOG.md, operations/helm/charts/grafana-agent/templates/rbac.yaml, operations/helm/tests/clustering/grafana-agent/templates/rbac.yaml, operations/helm/tests/controller-volumes-extra/grafana-agent/templates/rbac.yaml, operations/helm/tests/create-daemonset-hostnetwork/grafana-agent/templates/rbac.yaml, operations/helm/tests/create-daemonset/grafana-agent/templates/rbac.yaml, operations/helm/tests/create-deployment-autoscaling/grafana-agent/templates/rbac.yaml, operations/helm/tests/create-deployment/grafana-agent/templates/rbac.yaml, operations/helm/tests/create-statefulset-autoscaling/grafana-agent/templates/rbac.yaml, operations/helm/tests/create-statefulset/grafana-agent/templates/rbac.yaml, operations/helm/tests/custom-config/grafana-agent/templates/rbac.yaml, operations/helm/tests/default-values/grafana-agent/templates/rbac.yaml, operations/helm/tests/enable-servicemonitor/grafana-agent/templates/rbac.yaml, operations/helm/tests/envFrom/grafana-agent/templates/rbac.yaml, operations/helm/tests/existing-config/grafana-agent/templates/rbac.yaml, operations/helm/tests/extra-env/grafana-agent/templates/rbac.yaml, operations/helm/tests/extra-ports/grafana-agent/templates/rbac.yaml, operations/helm/tests/faro-ingress/grafana-agent/templates/rbac.yaml, operations/helm/tests/global-image-pullsecrets/grafana-agent/templates/rbac.yaml, operations/helm/tests/global-image-registry/grafana-agent/templates/rbac.yaml, operations/helm/tests/initcontainers/grafana-agent/templates/rbac.yaml, operations/helm/tests/local-image-pullsecrets/grafana-agent/templates/rbac.yaml, operations/helm/tests/local-image-registry/grafana-agent/templates/rbac.yaml, operations/helm/tests/nodeselectors-and-tolerations/grafana-agent/templates/rbac.yaml, operations/helm/tests/static-mode/grafana-agent/templates/rbac.yaml
=> helm: add secrets and configmaps to rbac

docs/sources/_index.md
Missed an underscore in the link.
Refer to: 
* https://github.com/grafana/agent/pull/5495
* https://github.com/grafana/agent/pull/5478
=> Add a missing underscore in a link URL in a note admonition

docs/sources/flow/setup/install/linux.md
`sudo ... > ...` doesn't work, use the same `tee` trick as the deb instructions.
=> 📝 Fix RHEL install instructions to work.

docs/sources/_index.md
This PR fixes a broken link in a note admonition.
Refer to: 
* https://github.com/grafana/agent/pull/5494
* https://github.com/grafana/agent/pull/5478
=> Fix broken link in Note

docs/sources/static/configuration/integrations/windows-exporter-config.md
This PR adds the missing documentation for `scheduled_task` to https://grafana.com/docs/agent/latest/static/configuration/integrations/windows-exporter-config/
Fixes #4341 
I made a guess at what was required based on the documentation for Flow and what I read in https://github.com/grafana/agent/blob/3d92001037b3a9915b1760a15683f3023a876b17/pkg/integrations/windows_exporter/config.go
=> Add docs for scheduled_task to Static documentation

CHANGELOG.md, converter/internal/staticconvert/internal/build/agent_exporter.go, converter/internal/staticconvert/internal/build/builder.go, converter/internal/staticconvert/testdata/integrations.river, converter/internal/staticconvert/testdata/integrations.yaml, converter/internal/staticconvert/testdata/sanitize.diags, converter/internal/staticconvert/testdata/sanitize.river, converter/internal/staticconvert/testdata/unsupported.diags, converter/internal/staticconvert/testdata/unsupported.yaml, converter/internal/staticconvert/validate.go
=> wire up the agent integration for the static converter

docs/sources/flow/getting-started/migrating-from-prometheus.md, docs/sources/flow/getting-started/migrating-from-promtail.md, docs/sources/flow/getting-started/migrating-from-static.md
This PR updates the migration topics to use the `code` shortcode to show the CLI command for both Static and Flow binaries.
=> Update migration topic to use codeblock for static and flow commands

component/loki/source/cloudflare/cloudflare.go, component/loki/source/cloudflare/internal/cloudflaretarget/client.go, component/loki/source/cloudflare/internal/cloudflaretarget/fields.go, component/loki/source/cloudflare/internal/cloudflaretarget/fields_test.go, component/loki/source/cloudflare/internal/cloudflaretarget/metrics.go, component/loki/source/cloudflare/internal/cloudflaretarget/target.go, component/loki/source/cloudflare/internal/cloudflaretarget/target_test.go, component/loki/source/cloudflare/internal/cloudflaretarget/util_test.go, docs/sources/flow/reference/components/loki.source.cloudflare.md, go.mod, go.sum
This PR ports the latest changes from the equivalent Promtail package since its iniital creation.
The very last change was already ported over on our wide
Fixes #4842 
The new changes we've had to mirror are only about adding new field, and switching to using a grafana fork of the cloudflare's API.
=> loki.source.cloudflare: port latest Promtail changes

CHANGELOG.md, docs/sources/flow/config-language/expressions/types_and_values.md, go.mod, go.sum
=> update to River v0.2.0 for raw strings

docs/sources/flow/reference/components/prometheus.exporter.blackbox.md
Instead of using `:`, it should be `=`
=> Update the correct syntax for extra label

docs/sources/flow/reference/components/otelcol.connector.spanmetrics.md
(cherry picked from commit c5143e749bf60d7a3917bb12e0f0c9baa5d327e8)
=> Fix typos (#5583)

docs/sources/flow/reference/components/prometheus.exporter.cadvisor.md
Fix example config
Fixes #5620
=> Fix prometheus.exporter.cadvisor.md

internal/slogadapter/gokit.go
=> Nit: simplify loop in go kit

CHANGELOG.md, docs/sources/flow/config-language/expressions/operators.md, go.mod, go.sum
=> bump river to v0.3.0

operations/helm/charts/grafana-agent/CHANGELOG.md, operations/helm/charts/grafana-agent/README.md, operations/helm/charts/grafana-agent/templates/containers/_agent.yaml, operations/helm/charts/grafana-agent/values.yaml, operations/helm/tests/clustering/grafana-agent/templates/controllers/statefulset.yaml, operations/helm/tests/controller-volumes-extra/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/create-daemonset-hostnetwork/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/create-daemonset/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/create-deployment-autoscaling/grafana-agent/templates/controllers/deployment.yaml, operations/helm/tests/create-deployment/grafana-agent/templates/controllers/deployment.yaml, operations/helm/tests/create-statefulset-autoscaling/grafana-agent/templates/controllers/statefulset.yaml, operations/helm/tests/create-statefulset/grafana-agent/templates/controllers/statefulset.yaml, operations/helm/tests/custom-config/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/default-values/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/enable-servicemonitor/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/envFrom/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/existing-config/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/extra-env/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/extra-ports/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/faro-ingress/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/global-image-pullsecrets/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/global-image-registry/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/initcontainers/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/local-image-pullsecrets/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/local-image-registry/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/nodeselectors-and-tolerations/grafana-agent/templates/controllers/daemonset.yaml
Hello!
I think the title says it all. This is a pretty straightforward PR I think :)
=> feat(helm): expose the ui-path-prefix flag

component/loki/source/api/internal/lokipush/push_api_server.go
Nothing new since the component was added (https://github.com/grafana/agent/pull/3648): https://github.com/grafana/loki/commits/main/clients/pkg/promtail/targets/lokipush
The only change would be the one coming from the last commit but we would need to update the loki version to match it.
Fixes #4839
=> Promtail sync loki source api

docs/sources/data-collection.md, docs/sources/flow/reference/cli/run.md, docs/sources/flow/setup/install/_index.md, docs/sources/static/set-up/install/_index.md
* Clarify data collection
* Clarify data collection done onlly in Static mode
* Update links and add missing data collection
* Fix broken link
(cherry picked from commit e08bcbbe7e23ee9297e60d24589494c8ae66ab15)
Backport e08bcbb from #5656
=> [release-v0.35] Clarify data collection in Grafana Agent (#5656)

CHANGELOG.md, docs/sources/flow/setup/install/windows.md, packaging/grafana-agent-flow/windows/install_script.nsis
Add /CONFIG and /DISABLEREPORTING flag to NSIS installer
Fixes #4005
=> NSIS: Add /CONFIG and /DISABLEREPORTING flag

docs/sources/flow/reference/components/prometheus.scrape.md
=> prometheus.scrape: clarify docs on job label

CHANGELOG.md, component/common/loki/wal/watcher_metrics.go, component/otelcol/exporter/prometheus/internal/convert/convert.go, component/otelcol/exporter/prometheus/internal/convert/convert_test.go, component/otelcol/exporter/prometheus/prometheus.go, component/otelcol/exporter/prometheus/prometheus_test.go, docs/sources/flow/reference/components/otelcol.exporter.prometheus.md
https://github.com/grafana/agent/tree/main/docs/developer/release#patch-release-publish-latest-version
Step 1 of the patch release process
=> Cherry picks v0.37.4

docs/sources/flow/reference/components/prometheus.exporter.agent.md
Fixes the example on the docs `prometheus.exporter.agent`
=> docs: fix example in  prometheus.exporter.agent

CHANGELOG.md, pkg/integrations/v2/app_agent_receiver/handler.go
Follow up on PR #5835:
* Add missing CHANGELOG entry
* Mirror fix to static mode
=> misc: follow up on #5835

CHANGELOG.md, component/otelcol/internal/fanoutconsumer/logs.go
=> fix(otelcol/fanoutconsumer): nil check during fanout consumer creation

CHANGELOG.md
I put the changelog for 5869 in the wrong place , it is now in 38.1 where it belongs.
=> Move changelog entry to correct place.

docs/sources/flow/reference/components/otelcol.processor.filter.md
Fix broken OTTL context links in otelcol.processor.filter topic
=> Fix broken OTTL context links in otelcol.processor.filter topic

component/loki/source/windowsevent/bookmark.go, docs/docs_updated_test.go
Fixes windows test failures introduced by #5784 and #5791
=> Fix windows tests 2

docs/sources/flow/reference/components/otelcol.receiver.vcenter.md
Fix missing codefence in otelcol.receiver.vcenter
=> Fix missing codefence in otelcol.receiver.vcenter

operations/helm/charts/grafana-agent/CHANGELOG.md, operations/helm/charts/grafana-agent/templates/rbac.yaml, operations/helm/tests/clustering/grafana-agent/templates/rbac.yaml, operations/helm/tests/controller-volumes-extra/grafana-agent/templates/rbac.yaml, operations/helm/tests/create-daemonset-hostnetwork/grafana-agent/templates/rbac.yaml, operations/helm/tests/create-daemonset/grafana-agent/templates/rbac.yaml, operations/helm/tests/create-deployment-autoscaling/grafana-agent/templates/rbac.yaml, operations/helm/tests/create-deployment/grafana-agent/templates/rbac.yaml, operations/helm/tests/create-statefulset-autoscaling/grafana-agent/templates/rbac.yaml, operations/helm/tests/create-statefulset/grafana-agent/templates/rbac.yaml, operations/helm/tests/custom-config/grafana-agent/templates/rbac.yaml, operations/helm/tests/default-values/grafana-agent/templates/rbac.yaml, operations/helm/tests/enable-servicemonitor/grafana-agent/templates/rbac.yaml, operations/helm/tests/envFrom/grafana-agent/templates/rbac.yaml, operations/helm/tests/existing-config/grafana-agent/templates/rbac.yaml, operations/helm/tests/extra-env/grafana-agent/templates/rbac.yaml, operations/helm/tests/extra-ports/grafana-agent/templates/rbac.yaml, operations/helm/tests/faro-ingress/grafana-agent/templates/rbac.yaml, operations/helm/tests/global-image-pullsecrets/grafana-agent/templates/rbac.yaml, operations/helm/tests/global-image-registry/grafana-agent/templates/rbac.yaml, operations/helm/tests/initcontainers/grafana-agent/templates/rbac.yaml, operations/helm/tests/local-image-pullsecrets/grafana-agent/templates/rbac.yaml, operations/helm/tests/local-image-registry/grafana-agent/templates/rbac.yaml, operations/helm/tests/nodeselectors-and-tolerations/grafana-agent/templates/rbac.yaml, operations/helm/tests/static-mode/grafana-agent/templates/rbac.yaml
See the rbac requirements for this processor: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/README.md#role-based-access-control
=> update helm chart rbac to support k8sattribute processor

converter/internal/staticconvert/internal/build/app_agent_receiver.go, converter/internal/staticconvert/internal/build/builder.go, converter/internal/staticconvert/internal/build/vmware_exporter.go, converter/internal/staticconvert/testdata-v2/integrations_v2.river, converter/internal/staticconvert/testdata-v2/integrations_v2.yaml, converter/internal/staticconvert/testdata-v2/unsupported.diags, converter/internal/staticconvert/testdata-v2/unsupported.river, converter/internal/staticconvert/testdata-v2/unsupported.yaml, converter/internal/staticconvert/validate.go
Wire up app_agent_receiver and vsphere. Mark eventhandler as unsupported for now
=> wire up remaining integrations v2 for the static to flow converter

CHANGELOG.md, component/prometheus/relabel/relabel.go, component/prometheus/relabel/relabel_test.go, converter/internal/prometheusconvert/component/relabel.go, docs/sources/flow/reference/components/prometheus.relabel.md
Allow configuring the max_relabel_cache, there are many cases where 100k is far to low.
=> add max_cache_size

CHANGELOG.md, converter/internal/prometheusconvert/component/http.go, converter/internal/prometheusconvert/component/service_discovery.go, converter/internal/prometheusconvert/testdata/http.river, converter/internal/prometheusconvert/testdata/http.yaml
=> Add support for http_sd_config within a scrape_config for the prometheus converter

docs/sources/flow/monitoring/agent-resource-usage.md
Add resource usage guidelines based on our experiences.
Fixes #5950
Note: the traces usage is too low to provide any reasonable guidelines. We will need to come back to this.
=> Add resource usage guidelines docs

operations/helm/charts/grafana-agent/CHANGELOG.md, operations/helm/charts/grafana-agent/Chart.yaml, operations/helm/charts/grafana-agent/README.md
=> create new helm release 0.30.0

CHANGELOG.md
This was resolved in https://github.com/grafana/agent/pull/5866 but I did not add a changelog at the time.
=> This adds a changelog for a fix not mentioned with process and windows exporter

component/common/loki/wal/watcher_test.go, converter/internal/staticconvert/testdata-v2_windows/integrations_v2.river
=> Fix windows tests 3

docs/sources/flow/tasks/migrate/from-operator.md, docs/sources/flow/tasks/migrate/from-prometheus.md, docs/sources/flow/tasks/migrate/from-promtail.md, docs/sources/flow/tasks/migrate/from-static.md
When moving these pages I have incorrectly defined the aliases. This was likely because this was my first time doing this and I didn't know that `make docs` requires a restart in order to remove the old routes. 
```
➜  agent git:(thampiotr/fix-aliases-in-docs) curl http://localhost:3003/docs/agent/latest/flow/getting-started/migrating-from-prometheus/
<!doctype html><html><head><script>const destination="http://localhost:3003/docs/agent/latest/flow/tasks/migrate/from-prometheus/";console.log(window.location.search),document.head.innerHTML=`<meta http-equiv="refresh" content="0; url=${destination}${window.location.search}"/>`</script><title>http://localhost:3003/docs/agent/latest/flow/tasks/migrate/from-prometheus/</title><link rel=canonical …
```
=> Fix incorrect aliases for config migration docs

component/otelcol/connector/spanmetrics/spanmetrics_test.go, component/otelcol/processor/processortest/processortest.go, docs/sources/flow/reference/components/otelcol.connector.spanmetrics.md
This has been a source of confusion for several customers.
=> Clarify usage of spanmetrics connector with a prometheus remote write

operations/helm/charts/grafana-agent/CHANGELOG.md, operations/helm/charts/grafana-agent/Chart.yaml, operations/helm/charts/grafana-agent/README.md, operations/helm/tests/additional-serviceaccount-label/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/clustering/grafana-agent/templates/controllers/statefulset.yaml, operations/helm/tests/controller-volumes-extra/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/create-daemonset-hostnetwork/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/create-daemonset/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/create-deployment-autoscaling/grafana-agent/templates/controllers/deployment.yaml, operations/helm/tests/create-deployment/grafana-agent/templates/controllers/deployment.yaml, operations/helm/tests/create-statefulset-autoscaling/grafana-agent/templates/controllers/statefulset.yaml, operations/helm/tests/create-statefulset/grafana-agent/templates/controllers/statefulset.yaml, operations/helm/tests/custom-config/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/default-values/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/enable-servicemonitor/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/envFrom/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/existing-config/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/extra-env/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/extra-ports/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/faro-ingress/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/global-image-pullsecrets/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/global-image-registry/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/initcontainers/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/local-image-pullsecrets/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/local-image-registry/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/nodeselectors-and-tolerations/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/sidecars/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/static-mode/grafana-agent/templates/controllers/daemonset.yaml
Update agent version to v0.39.0 from Helm charts
=> helm: update agent version to v0.39.0

docs/developer/writing-docs.md
Add a link to reference docs guide.
=> Add a link between docs guidelines

docs/sources/flow/reference/compatibility/_index.md
=> Docs: fix double note docs formatting

docs/sources/flow/reference/components/loki.source.docker.md
Replaces `loki.source.file` in `loki.source.docker` docs.
=> [Docs] Minifix: loki.source.file -> loki.source.docker

CHANGELOG.md
Previously my PR #5927 (thanks @mattdurham for your efforts!) got merged but the CHANGELOG entry was a bit outdated and place in already released version. This PR fixes that.
N/A
N/A
=> chore(doc): correct placement for `hainenber`'s recent merged changelog entry

docs/sources/flow/reference/components/loki.source.file.md
Fixes typo in `loki.source.file`
=> [Docs] Minifix: typo in loki.source.file

docs/sources/flow/setup/install/binary.md
https://raintank-corp.slack.com/archives/C5PG2JK8W/p1705319868959469
=> Fix broken link syntax

docs/sources/flow/reference/components/prometheus.exporter.blackbox.md
=> doc(prom/exp/blackbox): correct key-val separator for River map

docs/sources/flow/reference/components/prometheus.exporter.blackbox.md
Backport 4b0408e9420650409327059a7e056ea3c6b9ce7a from #6147
=> [release-v0.37] doc(prom/exp/blackbox): correct key-val separator for River map

docs/sources/flow/reference/components/otelcol.exporter.otlp.md
Our documentation listed https and failed to add the port.
Fixes #6166
=> fix typo in doc

docs/sources/flow/tutorials/flow-by-example/_index.md, docs/sources/flow/tutorials/flow-by-example/first-components-and-stdlib/index.md, docs/sources/flow/tutorials/flow-by-example/get-started.md
Backport 77aac507124cdf2d5aef2bbfb5d7ec7024a33daf from #5888
=> [release v0.39] Add first chapter of flow-by-example to docs #5888

operations/helm/charts/grafana-agent/CHANGELOG.md, operations/helm/charts/grafana-agent/Chart.yaml, operations/helm/charts/grafana-agent/README.md, operations/helm/tests/additional-serviceaccount-label/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/clustering/grafana-agent/templates/controllers/statefulset.yaml, operations/helm/tests/controller-volumes-extra/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/create-daemonset-hostnetwork/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/create-daemonset/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/create-deployment-autoscaling/grafana-agent/templates/controllers/deployment.yaml, operations/helm/tests/create-deployment/grafana-agent/templates/controllers/deployment.yaml, operations/helm/tests/create-statefulset-autoscaling/grafana-agent/templates/controllers/statefulset.yaml, operations/helm/tests/create-statefulset/grafana-agent/templates/controllers/statefulset.yaml, operations/helm/tests/custom-config/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/default-values/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/enable-servicemonitor/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/envFrom/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/existing-config/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/extra-env/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/extra-ports/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/faro-ingress/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/global-image-pullsecrets/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/global-image-registry/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/initcontainers/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/local-image-pullsecrets/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/local-image-registry/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/nodeselectors-and-tolerations/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/pod_annotations/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/sidecars/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/static-mode/grafana-agent/templates/controllers/daemonset.yaml, operations/helm/tests/topologyspreadconstraints/grafana-agent/templates/controllers/deployment.yaml
helm: update agent version to v0.39.1
=> helm: update agent version to v0.39.1

go.mod, go.sum
=> chore(profiling): bump godeltaprof to 0.1.7 to fix compilation on gotip

CHANGELOG.md, go.mod, go.sum
Update `jfr-parser` dependency to include line numbers in pprofs
=> pyroscope.java: include line numbers in pprof

docs/sources/flow/_index.md
This PR adds the variables back to headings (changed in https://github.com/grafana/agent/pull/6242 ). The correct syntax for shortcodes in headings is documented here: https://grafana.com/docs/writers-toolkit/write/shortcodes/#param
=> Use correct syntax for var names in headings

docs/sources/flow/_index.md
Backport d017470abd9364c10fb3ba70ae36e61c39378a60 from https://github.com/grafana/agent/pull/6244
=> (cherry picked from commit d017470abd9364c10fb3ba70ae36e61c39378a60)

docs/sources/flow/tutorials/flow-by-example/logs-and-relabeling-basics/index.md
Backport 7a6b74a54fb68e5ecb076b27f38c8abe119ea9c7 from https://github.com/grafana/agent/pull/6172
=> Backport 6172 to release v0.39

go.mod, go.sum
update jfr-parser/pprof dependency to include little fix for java 21 
https://github.com/grafana/jfr-parser/pull/28
=> pyroscope.java: bump jfr-parser/pprof dependency

docs/sources/operator/getting-started.md
Backport bc91e84a7c4a7fcd9dffb04a6650a04284691968 from https://github.com/grafana/agent/pull/6241
=> Backport 6241 to release v0.37

component/pyroscope/ebpf/args.go, component/pyroscope/ebpf/ebpf_linux.go
remove `targets_only` and `default` targets. They are undocumented and should not be there.
=> fix(pyroscope.ebpf): remove undocumented fields(default, targets_only)

cmd/grafana-agent-operator/DEVELOPERS.md, docs/sources/operator/deploy-agent-operator-resources.md, docs/sources/operator/helm-getting-started.md, docs/sources/static/set-up/install/_index.md
This PR updates some URLs pointing at the CRDs
https://github.com/grafana/agent/issues/6077
=> Update CRD link URLs

docs/sources/flow/reference/components/pyroscope.ebpf.md
pyroscope.ebpf component is now capable of profiling not only containers but also processes
Update docs to reflect that.
=> docs(pyroscope.ebpf): rewrite container id sections, include PID label

docs/sources/static/_index.md
This is a small PR to remove the "most mature" part of the description of Agent Static.  More changes will come as the relationship between Static and Flow becomes better defined.
=> Remove most mature part of description

docs/sources/static/api/_index.md
Backport 18b394ce5e183c4b973107b4c04ad922e846264e from #6293
=> Docs/add note about docker api (#6293)

docs/sources/static/api/_index.md
Backport 18b394ce5e183c4b973107b4c04ad922e846264e from #6293
=> [release-v0.39] Docs/add note about docker api (#6293)

docs/sources/static/api/_index.md
Backport 18b394ce5e183c4b973107b4c04ad922e846264e from #6293
=> [release-v0.37] Backport 6293 to release v0.37

docs/sources/flow/get-started/install/ansible.md
This PR cleans up some of the page formatting and grammar in the new Ansible topic.
=> Tidy up formatting, syntax and tweak grammar in the Ansible topic

docs/sources/flow/reference/components/prometheus.exporter.mssql.md, docs/sources/static/configuration/integrations/mssql-config.md
Backport 86e6378145461d79a554d08327b64e0fca57629f from #6325
=> [release-v0.39] Updates MSSQL Integrations docs with extra auth details #6325

operations/agent-flow-mixin/alerts/opentelemetry.libsonnet
For now I'm just adding alerts for spans. In the near future we could also add alerts for metrics and logs.
=> Add OpenTelemetry alerts

CHANGELOG.md, docs/sources/_index.md, docs/sources/_index.md.t
(cherry picked from commit cce3c302dae8b4bb703bc36ff38d26979dd70a1a)
=> remove windows 2012 support (#6086)

.gitattributes, pkg/flow/import_test.go
- use path.join to create a path instead of building it manually
- add eol rule for txtar files in .gitattributes to fix the parsing on windows
=> Fix import tests windows

pkg/flow/import_test.go, pkg/flow/internal/controller/node_config.go, pkg/flow/internal/controller/node_config_import.go, pkg/flow/internal/importsource/import_file.go, pkg/flow/internal/importsource/import_http.go, pkg/flow/internal/importsource/import_source.go, pkg/flow/module_eval_test.go, pkg/flow/source.go, pkg/flow/testdata/import_http/import_http_1.txtar
Add the import source http.
Docs come in another PR: https://github.com/grafana/agent/pull/6368
The implementation uses the remote.http component.
=> New modules import http

pkg/flow/internal/controller/component_node_manager.go, pkg/flow/internal/controller/custom_component_registry.go
The race was found in drone ci pipeline: https://drone.grafana.net/grafana/agent/16673/4/2
=> Fix data race in custom component registry

converter/internal/otelcolconvert/converter_zipkinreceiver.go, converter/internal/otelcolconvert/testdata/zipkin.river, converter/internal/otelcolconvert/testdata/zipkin.yaml
=> otelcolconvert: support converting zipkinreceiver

converter/internal/otelcolconvert/converter_opencensusreceiver.go, converter/internal/otelcolconvert/testdata/opencensus.river, converter/internal/otelcolconvert/testdata/opencensus.yaml
=> otelcolconvert: support converting opencensusreceiver

converter/internal/otelcolconvert/converter_otlphttpexporter.go, converter/internal/otelcolconvert/testdata/otlphttp.river, converter/internal/otelcolconvert/testdata/otlphttp.yaml
=> otelcolconvert: support converting otlphttpexporter

CHANGELOG.md, pkg/flow/flow_services.go, pkg/flow/internal/controller/loader.go
=> Fix an issue where services were included in the graph and updated in a child flow controller

converter/internal/otelcolconvert/converter_probabilisticsamplerprocessor.go, converter/internal/otelcolconvert/testdata/probabilistic_sampler.river, converter/internal/otelcolconvert/testdata/probabilistic_sampler.yaml
=> otelcolconvert: support converting probabilistic_sampler processor

converter/internal/otelcolconvert/converter_loadbalancingexporter.go, converter/internal/otelcolconvert/testdata/loadbalancing.river, converter/internal/otelcolconvert/testdata/loadbalancing.yaml
=> otelcolconvert: support converting loadbalancingexporter

converter/internal/otelcolconvert/converter_memorylimiterprocessor.go, converter/internal/otelcolconvert/testdata/memorylimiter.river, converter/internal/otelcolconvert/testdata/memorylimiter.yaml
=> otelcolconvert: support converting memory_limiter processor

converter/internal/otelcolconvert/converter_batchprocessor.go, converter/internal/otelcolconvert/testdata/batch.river, converter/internal/otelcolconvert/testdata/batch.yaml
=> otelcolconvert: support converting batch processor

component/otelcol/connector/host_info/host_info.go, component/otelcol/processor/resourcedetection/resourcedetection.go, component/pyroscope/java/java.go, component/pyroscope/java/java_stub.go, pkg/flow/internal/testcomponents/experimental.go, pkg/flow/testdata/import_error/import_error_3.txtar, pkg/flow/testdata/import_error/import_error_4.txtar, pkg/flow/testdata/import_file/import_file_14.txtar, pkg/flow/testdata/import_file/import_file_15.txtar
Addresses the feedback here: https://github.com/grafana/agent/pull/6523#pullrequestreview-1904650863
=> Fix incorrect stability labels and add test

CHANGELOG.md, packaging/grafana-agent-flow/windows/install_script.nsis, packaging/grafana-agent/windows/install_script.nsis
This solves a minor problem where the key being deleted needed to be the 64 bit registry.
=> Fix reg delete

docs/developer/contributing.md
You need a specific cgo compiler for windows development that we had not documented
Fixes #6411
=> add doc on setting up windows

docs/sources/flow/reference/components/loki.rules.kubernetes.md, docs/sources/flow/reference/config-blocks/tracing.md, docs/sources/flow/tutorials/flow-by-example/get-started.md
This PR cleans up some broken links and bad markdown syntax
=> Fix some broken links and bad markdown syntax

docs/sources/flow/reference/config-blocks/tracing.md, docs/sources/flow/tutorials/flow-by-example/get-started.md
Backport 72b08cae804624f444b1c7529aaa4148672b4db8 from https://github.com/grafana/agent/pull/6596
=> Fix some broken links and bad markdown syntax (#6596)

cmd/grafana-agent-operator/Dockerfile, cmd/grafana-agent/Dockerfile, cmd/grafana-agentctl/Dockerfile
Switch to ECR-hosted Ubuntu for the Agent's base image. It's more frequently updated and hence new vulnerabilities are patched as well
Fixes #6610
=> chore(build): upgrade base image to frequently updated ECR-hosted Ubuntu

ADOPTERS.md
=> Add CLOUDETEER to ADOPTERS

internal/converter/internal/otelcolconvert/converter_attributesprocessor.go, internal/converter/internal/otelcolconvert/testdata/attributes.river, internal/converter/internal/otelcolconvert/testdata/attributes.yaml
=> implement otel to flow converter for attributes processor

internal/service/remotecfg/remotecfg_test.go
This PR is to fix a race condition in the tests of the remotecfg package that renders our build pipeline flaky.
I'll be pushing along a series of commits to verify that the Drone and Github action runners are in a better state as well.
Apologies in advance for not picking this up earlier and the lost amount of dev time.
=> remotecfg: fix race condition in test

internal/converter/internal/otelcolconvert/converter_jaegerremotesamplingextension.go, internal/converter/internal/otelcolconvert/testdata/jaegerremotesampling.river, internal/converter/internal/otelcolconvert/testdata/jaegerremotesampling.yaml
Closes #6421
cc @rfratto I saw you'd self-assigned the previous issue so I hope I'm not duplicating any work, but I wanted to get the rest of the static mode converters down.
=> otelcolconvert: support converting jaegerremotesampling extension

internal/flow/import_git_test.go, internal/flow/import_test.go
=> Make git test linux only.

CHANGELOG.md, docs/sources/flow/reference/components/otelcol.connector.spanmetrics.md, docs/sources/flow/reference/components/otelcol.exporter.otlphttp.md, docs/sources/shared/flow/reference/components/extract-field-block.md, internal/component/otelcol/exporter/otlphttp/otlphttp.go, internal/static/traces/config.go, internal/static/traces/config_test.go
This partially resolves some comments from the otel upgrade. This specifically does not handle the otel kafka conversion, but that will be coming.
I did not update the changelog since functionally nothing changed.
=> Finish otel upgrade

CHANGELOG.md, docs/sources/flow/reference/cli/convert.md, docs/sources/flow/reference/cli/run.md, docs/sources/flow/tasks/migrate/from-operator.md, docs/sources/flow/tasks/migrate/from-otelcol.md, internal/converter/converter.go
Closes #6697 
Closes #6698 
Closes #6419
=> wire in the otel converter and create a migration guide

internal/converter/internal/staticconvert/internal/build/builder_traces.go, internal/converter/internal/staticconvert/testdata/traces.river, internal/converter/internal/staticconvert/testdata/traces.yaml
This PR wires up additional testing and fixes 1 bug with how we were removing receivers/processors from the static config with multiple pipelines. I commented out the 3 major config sections that still need implementation.
=> wire up static traces converter test for all major scenarios and squash a bug along the way

internal/converter/internal/otelcolconvert/otelcolconvert.go, internal/converter/internal/staticconvert/internal/build/builder_traces.go, internal/converter/internal/staticconvert/internal/build/converter_discoveryprocessor.go, internal/converter/internal/staticconvert/internal/build/converter_prometheusexporter.go, internal/converter/internal/staticconvert/internal/build/converter_remotewriteexporter.go, internal/converter/internal/staticconvert/internal/build/self_exporter.go, internal/converter/internal/staticconvert/testdata/traces.river, internal/converter/internal/staticconvert/testdata/traces.yaml, internal/converter/internal/staticconvert/testdata/unsupported.diags, internal/converter/internal/staticconvert/testdata/unsupported.yaml
=> converting spanmetrics from static traces to flow

CHANGELOG.md, docs/sources/flow/tasks/migrate/from-static.md, internal/converter/internal/staticconvert/internal/build/builder_traces.go, internal/converter/internal/staticconvert/testdata/traces.yaml, internal/converter/internal/staticconvert/testdata/unsupported.diags, internal/converter/internal/staticconvert/testdata/unsupported.yaml
Closes #6694
Closes #6696
Closes #6591 
Closes #3659
=> Added support for static configuration conversion of the traces subsytem

docs/sources/_index.md, docs/sources/_index.md.t, docs/sources/flow/_index.md, docs/sources/operator/_index.md, docs/sources/static/_index.md
Backport 99b2c127cd71a32276b59f225e68776099adb5b3 from #6843
=> [release-v0.39] Add deprecation banner to main index files in Agent #6844

docs/sources/_index.md, docs/sources/_index.md.t, docs/sources/flow/_index.md, docs/sources/operator/_index.md, docs/sources/static/_index.md
* Add deprecation banner to main index files in Agent
* Remove extra shared file
(cherry picked from commit 99b2c127cd71a32276b59f225e68776099adb5b3)
Backport 99b2c127cd71a32276b59f225e68776099adb5b3 from #6843
=> [release-v0.38] Add deprecation banner to main index files in Agent #6844

docs/sources/_index.md, docs/sources/_index.md.t, docs/sources/flow/_index.md, docs/sources/operator/_index.md, docs/sources/static/_index.md
=> Update share link to use next

docs/sources/_index.md, docs/sources/_index.md.t, docs/sources/flow/_index.md, docs/sources/operator/_index.md, docs/sources/static/_index.md
Remove deprecation Caution in Agent docs. Replaced by banner added in https://github.com/grafana/website/pull/19362
=> Remove Agent deprecation caution

docs/sources/_index.md, docs/sources/_index.md.t, docs/sources/operator/_index.md, docs/sources/static/_index.md
(cherry picked from commit 0a9bdad0d0ea028f480b0ffb5caaa43a2c876de2)
Backport https://github.com/grafana/agent/commit/0a9bdad0d0ea028f480b0ffb5caaa43a2c876de2 from https://github.com/grafana/agent/pull/6861
=> [release-v0.37] Remove Agent deprecation caution

docs/sources/_index.md, docs/sources/_index.md.t, docs/sources/flow/_index.md, docs/sources/operator/_index.md, docs/sources/static/_index.md
Backport https://github.com/grafana/agent/commit/0a9bdad0d0ea028f480b0ffb5caaa43a2c876de2 from https://github.com/grafana/agent/pull/6861
=> [release-v0.39] Remove Agent deprecation caution

CHANGELOG.md, docs/sources/flow/reference/components/otelcol.receiver.kafka.md, internal/component/otelcol/receiver/kafka/kafka.go, internal/component/otelcol/receiver/kafka/kafka_test.go, internal/component/otelcol/receiver/receiver.go, internal/component/otelcol/receiver/receiver_test.go, internal/converter/internal/otelcolconvert/testdata/kafka.river
backport https://github.com/grafana/alloy/pull/687
=> backport spawn otel receivers on need

docs/sources/flow/tasks/configure/configure-kubernetes.md
Add mode and fix YAML indentation
Fixes #issue_id  https://github.com/grafana/support-escalations/issues/10761
=> Add mode and fix YAML indentation

docs/sources/flow/release-notes.md
Add breaking change to release notes.
=> Add doc for release notes.

go.mod, go.sum, internal/component/loki/source/docker/docker_test.go, internal/component/loki/source/docker/internal/dockertarget/target.go
This will resolve a few CVEs flagged up by the scanner
=> Update Docker and runc

go.mod, go.sum, internal/component/loki/source/docker/docker_test.go, internal/component/loki/source/docker/internal/dockertarget/target.go
=> [release-v0.43] Cherry pick docker update

CHANGELOG.md, packaging/grafana-agent-flow/windows/install_script.nsis
backport of https://github.com/grafana/alloy/pull/1765
=> fix registry windows path

.drone/drone.yml, CHANGELOG.md, cmd/grafana-agent-operator/Dockerfile, cmd/grafana-agent/Dockerfile, cmd/grafana-agent/Dockerfile.windows, cmd/grafana-agentctl/Dockerfile, cmd/grafana-agentctl/Dockerfile.windows, docs/Makefile, go.mod, internal/cmd/integration-tests/configs/kafka/Dockerfile, internal/cmd/integration-tests/configs/otel-metrics-gen/Dockerfile, internal/cmd/integration-tests/configs/prom-gen/Dockerfile, tools/make/build-container.mk
This updates to use 1.22.9 go to resolve misc CVEs.
=> Use 1.22.9 in the build

docs/sources/flow/reference/cli/convert.md, docs/sources/flow/reference/components/discovery.kubelet.md, docs/sources/flow/reference/components/loki.echo.md, docs/sources/flow/reference/components/mimir.rules.kubernetes.md, docs/sources/flow/reference/components/module.file.md, docs/sources/flow/reference/components/module.git.md, docs/sources/flow/reference/components/module.http.md, docs/sources/flow/reference/components/module.string.md, docs/sources/flow/reference/components/otelcol.exporter.loadbalancing.md, docs/sources/flow/reference/components/otelcol.processor.resourcedetection.md, docs/sources/flow/reference/components/otelcol.processor.tail_sampling.md, docs/sources/flow/reference/components/otelcol.receiver.loki.md, docs/sources/flow/reference/components/otelcol.receiver.prometheus.md, docs/sources/flow/reference/components/prometheus.exporter.postgres.md, docs/sources/flow/reference/components/prometheus.exporter.windows.md, docs/sources/flow/reference/components/prometheus.operator.podmonitors.md, docs/sources/flow/reference/components/prometheus.operator.probes.md, docs/sources/flow/reference/components/prometheus.operator.servicemonitors.md, docs/sources/flow/reference/components/pyroscope.ebpf.md, docs/sources/flow/reference/components/pyroscope.scrape.md, docs/sources/flow/reference/components/pyroscope.write.md, docs/sources/flow/reference/config-blocks/import.file.md, docs/sources/flow/tasks/configure-agent-clustering.md
It's confusing to have a deprecated piece of software with a "beta" label.
for https://github.com/grafana/website/issues/24067 
upstream of https://github.com/grafana/website/pull/24098
=> docs - remove beta label

docs/sources/_index.md, docs/sources/_index.md.t
This PR updates the supported platforms info to match Alloy info
=> Update supported platforms

.github/workflows/autolock.yml, .github/workflows/backport.yml, .github/workflows/bump-formula-pr.yml, .github/workflows/check-linux-build-image.yml, .github/workflows/check-versioned-files.yml, .github/workflows/check-windows-build-image.yml, .github/workflows/check_docs.yml, .github/workflows/depcheck.yml, .github/workflows/helm-release.yml, .github/workflows/helm-test.yml, .github/workflows/integration-tests.yml, .github/workflows/needs-attention.yml, .github/workflows/publish-documentation-next.yml, .github/workflows/publish-technical-documentation-release.yml, .github/workflows/scripts.yml, .github/workflows/snyk.yml, .github/workflows/test.yml, .github/workflows/trivy.yml, .github/workflows/update-make-docs.yml
Fix findings reported by https://github.com/woodruffw/zizmor
=> fix github actions

build-image/Dockerfile, internal/component/loki/source/gelf/gelf.go, internal/component/loki/source/syslog/syslog_test.go
Also address some flaky unit tests
=> ci: fix node version installation
