grafana/agent

operations/helm/charts/grafana-agent/README.md
operations/helm/charts/grafana-agent/README.md.gotmpl

Fixes `Test Helm Chart / regenerate-docs`.

helm: fix README to sync with template

---

operations/helm/charts/grafana-agent/CHANGELOG.md

0.8.1 released all the pending features. 
It likely should've been 0.9.0 in that case, but since it's already released, we'll leave it as-is.

helm chart: fix CHANGELOG

---

.drone/drone.yml
.drone/pipelines/crosscompile.jsonnet
CHANGELOG.md
tools/make/packaging.mk

Now that we're using Go 1.20.2, we can build the UI back.

Bring back the Flow UI for ARMv6 builds

---

operations/helm/charts/grafana-agent/CHANGELOG.md
operations/helm/charts/grafana-agent/README.md
operations/helm/charts/grafana-agent/templates/controllers/_pod.yaml
operations/helm/charts/grafana-agent/values.yaml

This change adds `podLabels` value to the helm chart. Provides the ability to add extra labels to pods.
None

add pod labels to the helm chart

---

pkg/integrations/mssql/sql_exporter.go
pkg/integrations/oracledb_exporter/oracledb_exporter.go
pkg/integrations/oracledb_exporter/oracledb_exporter_test.go
pkg/integrations/snowflake_exporter/snowflake_exporter.go

Some integrations were using plain strings instead of `Secret` type for
secret fields. This PR fixes it.

Use missing Secret field in integrations

---

pkg/river/encoding/map.go
pkg/river/encoding/map_test.go
pkg/river/internal/value/value.go
pkg/river/internal/value/value_test.go

This fixes an issue where any reference to a zero value in a Go map would be treated as if the key didn't exist. This was due to a misunderstanding of the Go documentation that said "the zero Value" will be returned if the key does not exist in the map. This documentation referred to an invalid `reflect.Value` instead of the zero value of the map's value type.
This allows to simplify the logic when performing a map lookup to determine if the key was found or not, and permits expressions which reference a map key set to the zero value of the value type.
Opening in draft because it still needs some unit tests.

river: allow referencing zero values in Go maps

---

pkg/river/river.go
pkg/river/vm/vm.go
pkg/river/vm/vm_block_test.go
tools/agentlint/internal/rivertags/rivertags.go

This allows decoding blocks into maps instead of structs. The map type can be any map[string]T, which is useful of the map values must always be a consistent type. If map values can be anything, use map[string]any for decoding.
Additionally, if decoding into an interface{}, it will default to map[string]any when decoding.
When decoding into a map, nested blocks aren't allowed and will be rejected.
Closes #2903, and unlocks module loader components to accept arguments to propagate to the module as a block rather than an object.
This is not added to the changelog because this is not a user-facing change.

river/vm: support decoding blocks into map[string]T

---

docs/sources/flow/tutorials/collecting-prometheus-metrics.md

When a relref target is not explicitly set as relative to the current page with a preceding `./` or `../`, Hugo attempts to resolve the relref target by seeing if it could refer any page in the site.
For local builds, this relref results in the relative permalink /docs/agent/latest/flow/concepts/configuration_language/#Attributes because of the docs/sources/flow/concepts/configuration_language.md file. This works locally because there is only one file with this name. However, in the website, multiple files have this name because of the multiple published versions of Agent documentation. When the resolution is ambiguous, Hugo prefers to avoid linking to any of the pages and instead makes the permalink point to the current page.
This should be backported to all the way back to `v0.28` to …

Fix ambiguous link

---

docs/sources/flow/tutorials/collecting-prometheus-metrics.md

When a relref target is not explicitly set as relative to the current page with a preceding `./` or `../`, Hugo attempts to resolve the relref target by seeing if it could refer any page in the site.
For local builds, this relref results in the relative permalink /docs/agent/latest/flow/concepts/configuration_language/#Attributes because of the docs/sources/flow/concepts/configuration_language.md file. This works locally because there is only one file with this name. However, in the website, multiple files have this name because of the multiple published versions of Agent documentation. When the resolution is ambiguous, Hugo prefers to avoid linking to any of the pages and instead makes the permalink point to the current page.
(cherry …

Fix ambiguous link (#3233)

---

CHANGELOG.md
pkg/flow/tracing/internal/jaegerremote/sampler_remote.go

This fixes an issue where the remote sampler could not be parsed if it used strings for the strategy type instead of numbers. The resolution is to switch to the protobuf JSON encoding, which properly parses this type as a string.
Not being able to parse the remote sampler rules meant that sampling rate fell back to the default (10%).
This change is equivalent to
open-telemetry/opentelemetry-go-contrib#3183. We are still unable to move to the upstream type while
open-telemetry/opentelemetry-go-contrib#2981 remains unresolved.

flow/tracing: fix issue where remote sampler could not be parsed

---

CHANGELOG.md
cmd/grafana-agent/flow_run.go
component/all/all.go
component/module/string/string.go
docs/sources/flow/reference/components/module.string.md
pkg/flow/flow.go
pkg/flow/flow_test.go

This commit adds a `module.string` component, which loads a flow module from a string and runs it in a nested controller.
The `module.string` component accept arguments to pass to the controller, and exposes the controller's exports back out to peer components.
TODO:
Closes #3114

module.string: new component

---

docs/sources/flow/concepts/configuration_language.md
docs/sources/flow/concepts/modules.md
docs/sources/flow/reference/components/module.string.md
docs/sources/flow/reference/config-blocks/argument.md
docs/sources/flow/reference/config-blocks/export.md
docs/sources/flow/reference/config-blocks/logging.md
docs/sources/flow/reference/config-blocks/tracing.md

This PR adds concept-level documentation for Flow modules, and configuration block reference pages for `argument` and `export`.
I'm a little worried that this isn't being explained very well; let me know if there's anything I can do here to help make things clearer.
Closes #3105.

Introduce documentation to explain modules

---

CHANGELOG.md
pkg/river/encoding/encoding.go

Components with no arguments returned a `null` for the arguments block, but the UI contract expects that arguments is always an array.
cc @rgeyer

web/api: fix Flow UI for components with no arguments

---

.drone/drone.yml
.drone/pipelines/crosscompile.jsonnet
CHANGELOG.md
Makefile
docs/sources/_index.md
docs/sources/set-up/_index.md
tools/ci/docker-containers
tools/make/packaging.mk

32-bit ARM builds are broken again (see CI for #3259). This commit temporarily removes support for 32-bit ARM builds so we can keep iterating while we wait for a new Go patch (golang/go#58425) and bring them back.
Ideally 32-bit ARM builds are restored prior to releasing v0.33.0.

Temporarily remove 32-bit ARM builds

---

.github/workflows/backport.yml
docs/sources/flow/tutorials/collecting-prometheus-metrics.md
docs/sources/flow/tutorials/filtering-metrics.md

Follow up from #3233 where I left some behind.
Again needs to be backported all the way back to v0.28 but we can maybe use the workflow in #3262 for that.

Avoid ambiguous relref lookups by forcing relative resolution

---

docs/sources/flow/tutorials/collecting-prometheus-metrics.md
docs/sources/flow/tutorials/filtering-metrics.md

* Add backport workflow
The workflow automatically backports PRs to branches labeled with `backport <BRANCH>` on closure or labeling of PRs.
Requires GH_BOT_ACCESS_TOKEN to work and in the future this will need to be replaced by a GitHub App based workflow. Timeline TBC.
* Avoid ambiguous relref lookups by forcing relative resolution
---------
(cherry picked from commit a0c0072cffce891665737d0e8063ab7880505bed)

[release-v0.28] Avoid ambiguous relref lookups by forcing relative resolution

---

docs/sources/flow/config-language/expressions/types_and_values.md

The escape sequence for strings was being incorrectly documented as `\\` instead of `\`.

Fix typo in Flow string escape sequence

---

tools/make/packaging.mk

Hello
The rpm package contains some build id link unwanted.
```
curl -sL https://github.com/grafana/agent/releases/download/v0.32.0/grafana-agent-0.32.0-1.amd64.rpm -o dist/grafana-agent-0.32.0-1.amd64.rpm
rpm -qlp dist/grafana-agent-0.32.0-1.amd64.rpm
/etc/grafana-agent.yaml
/etc/sysconfig/grafana-agent
/usr/bin/grafana-agent
/usr/bin/grafana-agentctl
/usr/lib/.build-id
/usr/lib/.build-id/02
/usr/lib/.build-id/02/37ab358b2b1a12883706afb2ca49b156595171
/usr/lib/.build-id/fd
/usr/lib/.build-id/fd/a80dec8593b78ecd34d51fc9601e0fa0d3c581
/usr/lib/systemd/system/grafana-agent.service
```
I suggest to add the fpm command attribute to ignore this with `--rpm-rpmbuild-define "_build_id_links none"`, but I'm clearly not sure about the implementation.

fix: rpm package should not contain build id links

---

production/grafanacloud-install.ps1

Prior to changes here, the Expand-Archive command was extracting the agent installer into a path with the same name and then not executing it from the path in the subsequent command, causing the script to fail.  These changes get the current path and use that in the -DestinationPath parameter, effectively extracting the ZIP into the same directory the ps1 script runs in which is also where the zip is downloaded to. This fixes the installation failing.

fix script zip expand issues

---

CHANGELOG.md
component/loki/source/file/file.go

`loki.source.file` had a deadlock while updating the component and shutting down old tailers. The terminating tailers try to flush their final log lines, but log lines aren't being processed because the Run goroutine is waiting forever to grab a mutex that the Update goroutine already holds.
This is most visible in environments where the Update goroutine is called frequently, since that's the most likely scenario where tailers will have data to flush.

loki.source.file: fix deadlock

---

CHANGELOG.md
component/loki/process/process.go

This fixes a deadlock when loki.process has no stages defined, since previously it needed at least one stage to create the input pipelines.

loki.process: fix deadlock on components with no stages

---

component/prometheus/exporter/redis/redis.go
docs/sources/flow/reference/components/prometheus.exporter.redis.md

`redis_addr` should be listed in the "usage" section because it is a mandatory attribute.

Add redis address to usage docs

---

CHANGELOG.md
pkg/operator/reconciler_metrics.go

Related to #1649. If you have too many PodMonitors for example, your final agent config can be too big to fit in a secret.
Following comments in https://github.com/prometheus-operator/prometheus-operator/issues/2234, I learned the config reloader container we are already deploying already natively supports gzip compression transparently. So all we need to do to take advantage of that is compress our secret data.
I chose a fairly safe limit at 100kb under which we will not compress, mainly to keep things easier to debug for most installs.
I am currently generating a test install to 100% verify this works.

operator: conditionally compress config secrets

---

CHANGELOG.md
pkg/river/parser/parser.go
pkg/river/vm/vm_test.go

Fixes the issue mentioned in #3222.  The ParseExpression() function on the main branch does not currently raise an error if trailing parts of the expressions were not evaluated.
Fixes #3222
Apparently in River it's possible to define a float value without specifying the 0 before the dot. For example, `.8` is equivalent to `0.8`.

Fix issue with evaluating expressions

---

CHANGELOG.md
cmd/grafana-agent/main.go
cmd/grafana-agent/service_windows.go
pkg/config/agentmanagement_test.go
pkg/config/config.go
pkg/config/config_test.go
pkg/server/config.go
pkg/server/logger_test.go
pkg/server/server_test.go
tools/crow/main.go

- A recent [PR](https://github.com/grafana/agent/pull/3030) converted the default server config into a pointer. As a side effect, it also caused the DefaultConfig to be mutated when used for unmarshaling, following a pattern we use consistently across the code base.
- In order to prevent unwanted side effects (as seen in a different [PR](https://github.com/grafana/agent/pull/2959), where tests affect each other when run sequentially), we now generate a new copy of the DefaultConfig every time via a function call.
I have tested this in the mentioned broken branch and all tests pass.
I did not add tests since we changed from a variable to a function call returning a struct, which enforces a new copy every time.
I have not fixed this everywhere, follow up PRs my follow top ensure …

Ensure DefaultConfig is immutable

---

docs/developer/contributing.md
docs/sources/flow/monitoring/component_metrics.md
docs/sources/flow/monitoring/controller_metrics.md
docs/sources/flow/monitoring/debugging.md
docs/sources/flow/reference/cli/_index.md
docs/sources/flow/reference/cli/run.md
docs/sources/flow/tutorials/collecting-prometheus-metrics.md

Backport 9ed71e2e80aef883d3ece778bc4411f8c86f29d6 from #3315

[release-v0.31] docs: fix existing references to old binary names #3317

---

docs/sources/flow/config-language/expressions/types_and_values.md
docs/sources/flow/config-language/syntax.md
docs/sources/flow/reference/cli/fmt.md

Clarify documentation around object construction and the `fmt` command based on feedback in provided in #3304.

docs: clarify objects, fmt based on feedback in #3304

---

docs/sources/flow/getting-started/collect-prometheus-metrics.md

Add a _Collect Prometheus metrics_ topic in the Grafana Agent Flow documentation. This topic is intended to be used for all common tasks around Prometheus metric collection.
For this initial commit, the only task is for configuring a prometheus.remote_write component. More tasks will be added in follow-up PRs to keep the review size as small as possible.
I've started with the task for configuring metrics delivery _first_ to allow each task section to be functional in isolation. Without being instructed to configure metrics delivery, there would be no point in collecting metrics. I plan to open a second PR for a metrics collection task ASAP after this is merged to reduce confusion for readers that stumble on it while there's only one task. 
Like #3314, this follows the recommendation for …

docs: add Collect Prometheus metrics topic for Flow

---

docs/sources/flow/getting-started/collect-prometheus-metrics.md

I got advice from the documentation team that nesting the bullet points for substituting  values in the code blocks is the right move.

docs: nest bullet points in the instructions for code blocks

---

docs/sources/flow/getting-started/collect-opentelemetry-data.md

Add a _Collect OpenTelemetry data_ topic in the Grafana Agent Flow documentation. This topic is intended to be used for all common tasks around OpenTelemetry data collection and processing.
For this initial commit, the only task is for configuring an exporter (otelcol.exporter.otlp). More tasks will be added in follow-up PRs to keep the review size as small as possible.
This PR is the counterpart to #3320.

docs: add Collect OpenTelemetry data topic for Flow

---

docs/sources/flow/getting-started/collect-prometheus-metrics.md

Add a _Collect metrics from Kubernetes Pods_ task to the _Collect Prometheus Metrics_ topic.
This is a follow-up PR on #3332.
Note that I always refer to Pods with capitalization here, since that's how the Kubernetes docs seem to exclusively refer to them.

docs: add Collect metrics from Kubernetes Pods task

---

README.md

Grafana Agent has changed a lot over the last three years, starting as a lightweight Prometheus agent, and gradually adding new capabilities over time. Throughout all these changes, the README for the project has mainly remained the same.
Today, the way we talk about Grafana Agent has changed, especially with the introduction of Grafana Agent Flow. For a while now, Grafana Agent has been a vendor-neutral, powerful, and flexible observability collector.
This commit adapts the README to reflect the current state of the project. As we believe Grafana Agent Flow is the future, the README focuses solely on Grafana Agent Flow.
Here's to another three years! 🥂
To see the new README in rendered form before this is merged, go here: https://github.com/rfratto/agent/blob/revamp-readme/README.md

misc: revamp project README

---

component/otelcol/auth/auth.go
component/otelcol/auth/auth_test.go
component/otelcol/auth/basic/basic.go
component/otelcol/auth/bearer/bearer.go
component/otelcol/auth/headers/headers.go
component/otelcol/auth/oauth2/oauth2.go
component/otelcol/auth/sigv4/sigv4.go
component/otelcol/exporter/exporter.go
component/otelcol/exporter/exporter_test.go
component/otelcol/exporter/jaeger/jaeger.go
component/otelcol/exporter/otlp/otlp.go
component/otelcol/exporter/otlphttp/otlphttp.go
component/otelcol/extension/extension.go
component/otelcol/extension/extension_test.go
component/otelcol/extension/jaeger_remote_sampling/jaeger_remote_sampling.go
component/otelcol/processor/batch/batch.go
component/otelcol/processor/memorylimiter/memorylimiter.go
component/otelcol/processor/processor.go
component/otelcol/processor/processor_test.go
component/otelcol/processor/tail_sampling/tail_sampling.go
component/otelcol/receiver/jaeger/jaeger.go
component/otelcol/receiver/kafka/kafka.go
component/otelcol/receiver/opencensus/opencensus.go
component/otelcol/receiver/opencensus/opencensus_test.go
component/otelcol/receiver/otlp/otlp.go
component/otelcol/receiver/receiver.go
component/otelcol/receiver/receiver_test.go
component/otelcol/receiver/zipkin/zipkin.go
component/otelcol/receiver/zipkin/zipkin_test.go

If the Convert() method returns an error, this allows us to handle errors in UnmarshalRiver without doing a type assertion. It also makes sense to return an error if a conversion could not be done. This change was discussed in a [comment](https://github.com/grafana/agent/pull/3200#discussion_r1143298235) in a prior PR.
It is such a minor change, that I think there is no need for a changelog entry?

Convert() method for otel auth extensions to return an error

---

component/module/string/string.go
web/ui/src/features/component/ComponentView.tsx

This commit fixes a bug where API endpoints for nested controllers did not propagate correctly. The controller handler assumed that the full HTTP path was being used rather than the truncated path given to component handlers.
This also fixes an issue in the UI where the URL for deeply nested modules was calculated incorrectly.
Fixes #3294

module.string: fix issue with nested controller API

---

docs/sources/flow/getting-started/collect-prometheus-metrics.md

This commit adds a _Collect metrics from Kubernetes Services_ task into the _Collect Prometheus metrics_ topic.
This is a nearly exact copy of #3336, but tailored towards Services instead of Pods.

docs: add Collect metrics from Kubernetes Services task for Flow

---

CHANGELOG.md
component/loki/source/docker/docker.go

This PR fixes the loki.source.docker deadlock by adding a separate mutex for updating the LogsReceiver fanout and allowing containers to flush their log lines before being shut down.
Fixes #3391

Fix deadlock in loki.source.docker with a separate mutex

---

CHANGELOG.md
go.mod
go.sum

Fixes #3400 
There were no config updates. This just contains a bugfix for connecting to a TLS-enabled Redis Cluster.

Updates redis_exporter to v1.49.0

---

CHANGELOG.md
pkg/config/agent_management_remote_config_test.go
pkg/config/agentmanagement.go
pkg/config/agentmanagement_remote_config.go
pkg/config/agentmanagement_test.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/integrations.go
pkg/config/integrations_test.go
pkg/integrations/manager.go

Adds support for integrations in agent management snippets.
- Removes global state for integrations configuration (`DefaultManagerConfig` was a global variable that was modified every time an integrations config was unmarshaled; this could lead to all kinds of bugs and unexpected side effects, and becomes particularly relevant for agent management, where configurations are constantly changed and reloaded). The same applies to `DefaultVersionedIntegrations`.
- Modifies `setVersion` to avoid overriding existing integrations config. This is needed due to the way integrations config is loaded: it is stored as a raw config and only unmarshaled at a later stage once the integrations version from the flagset has been parsed. Integration snippets for agent management are pinned to specific …

[Agent Management] Add support for integration snippets

---

CHANGELOG.md
pkg/config/agentmanagement.go
pkg/config/agentmanagement_test.go
pkg/config/config_test.go

- Replaces the `agent_management.api_url` config field with `agent_management.host`. This allows
pinning the agent to a specific API version without the need for
configuration changes, which removes the need for maintaining
multiple protocol versions in newer versions of the Agent.
- In addition, it now supports both `http` and `https` protocols
explicitly via `agent_management.protocol`. Previously, `http` was
used for both, with the final protocol used being inferred from the url.
This led to confusion on which protocol was actually being used.

[Agent Management] Replace `api_url` with `host`

---

operations/helm/charts/grafana-agent/CHANGELOG.md
operations/helm/charts/grafana-agent/README.md
operations/helm/charts/grafana-agent/ci/create-daemonset-hostnetwork-values.yaml
operations/helm/charts/grafana-agent/templates/controllers/_pod.yaml
operations/helm/charts/grafana-agent/values.yaml
operations/helm/tests/controller-volumes-extra/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/create-daemonset-hostnetwork/grafana-agent/templates/configmap.yaml
operations/helm/tests/create-daemonset-hostnetwork/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/create-daemonset-hostnetwork/grafana-agent/templates/rbac.yaml
operations/helm/tests/create-daemonset-hostnetwork/grafana-agent/templates/service.yaml
operations/helm/tests/create-daemonset-hostnetwork/grafana-agent/templates/serviceaccount.yaml
operations/helm/tests/create-daemonset/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/create-deployment-autoscaling/grafana-agent/templates/controllers/deployment.yaml
operations/helm/tests/create-deployment/grafana-agent/templates/controllers/deployment.yaml
operations/helm/tests/create-statefulset/grafana-agent/templates/controllers/statefulset.yaml
operations/helm/tests/custom-config/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/default-values/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/envFrom/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/existing-config/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/extra-env/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/extra-ports/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/faro-ingress/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/tolerations/grafana-agent/templates/controllers/daemonset.yaml

Allows configuring `dnsPolicy` especially important when enabling `hostNetwork: true` although not strictly necessary unless you have to resolve a DNS in the same cluster we are running the grafana agent pod
Related to this PR #728
N/A

[helm] Allow configuring dnsPolicy

---

pkg/flow/internal/controller/component_references.go
pkg/flow/internal/controller/config_logging.go
pkg/flow/internal/controller/config_tracing.go
pkg/flow/internal/controller/loader.go
pkg/flow/internal/controller/loader_test.go
pkg/flow/logging/sink.go
pkg/river/ast/ast.go

Fixes #3334
This can be done without the opts caching that was added to sink.go but it seems nicer to not mess with the logger if nothing changed. I also considered if this should be done here or have the caller to Update track the state but I think this is much simpler and improves all consumers of the sink functionality.

Add default logging and tracing nodes back into the dag when not provided in the river config

---

build-image/Dockerfile
build-image/windows/Dockerfile

Disables a warning by git to add /src or /drone/src as a safe directory. This was added as a security measure on systems, but it doesn't make sense in build containers which always use the root user.

Disable git user warning on build container

---

go.mod
go.sum

Removes a require directive on `github.com/gomodule/redigo v2.0.0+incompatible` as `redis_exporter` currently depends on the latest version of `redigo`, `v1.8.9`.
`go mod why -m github.com/gomodule/redigo` showed:
```
github.com/grafana/agent/pkg/integrations/redis_exporter
github.com/oliver006/redis_exporter/exporter
github.com/gomodule/redigo/redis
```
So I assumed since nothing except ultimately `redis_exporter` depends on `redigo`, it would be safe to remove the `v2.0.0+incompatible` & `replace` and run `go get github.com/oliver006/redis_exporter`.

Remove +incompatible require for redigo

---

pkg/config/agentmanagement_remote_config.go
pkg/config/config.go
pkg/logs/config.go
pkg/logs/config_test.go
pkg/logs/logs_test.go

- This change fixes a bug with agent management where log defaults would not be applied, resulting in missing validations and failure to initialize the positions file for log snippets.
- In order to avoid calling `ApplyDefaults` in multiple places, it has been moved to the `Validate` function, where defaults for metrics and integrations are also applied.
- Additionally, the name of snippet metrics and logs instance configs has been changed to just "snippets". This is done to prevent filenames (i.e. positions) with spaces and for consistency.
- Note: Logs config might be nil if no log configs have been defined, hence the extra check.

Apply all config defaults in a centralized place

---

docs/developer/writing-exporter-flow-components.md

Add tutorial of best practices and tips how to write Flow components for Prometheus
exporters. This will help us to get adoption of more exporters in Flow. 
Ideally we should merge #3145 before this get merged (as it references it).
Fixes #3228

Add tutorial how to create Prometheus exporter Flow components

---

CHANGELOG.md
component/prometheus/remotewrite/remote_write.go

prometheus.remote_write was originally creating a folder called `wal/COMPONENT_ID` relative to the data path given to the component.
Because the data path given to the component is already unique, AND because the Prometheus storage code creates a WAL directory, this means that the WAL was being stored at
`DATA_PATH/COMPONENT_ID/wal/COMPONENT_ID/wal`. This issue compounds itself when using modules, as each module adds an additional unnecessary directory to the path.
This commit changes the WAL to be stored at
`DATA_PATH/COMPONENT_ID/wal`.

prometheus.remote_write: fix issue where unnecessary directory was used

---

docs/sources/flow/reference/components/loki.source.gelf.md
docs/sources/flow/reference/components/loki.source.journal.md
docs/sources/flow/reference/components/loki.source.kafka.md
docs/sources/flow/reference/components/loki.source.syslog.md

1. Removes the incorrect `relabel_rules` block section, as `relabel_rules` is a capsule and not a block.
2. Shortens the arguments table length and moves descriptions to outside of the table, following the recent recommendations for writing component docs.
3. Adds using relabeling to the example.
I've mirrored some of these changes to other `loki.source.` components which also seemed unclear.  
Closes #3460

docs: changes to loki.source.journal

---

CHANGELOG.md
go.mod
go.sum

This PR updates `github.com/grafana/loki` dependency. 
The reason why we want to add it is to include this change:
`17e05d28e4bf4f3a3c382180e4ba0fdb141af26f Promtail: Add a new target for the Azure Event Hub (#8787)`
It allows us to add support for Azure Event Hub in the future, which will be implemented in a separate PR.
Not available
Output for diff between loki branches`git log --pretty=oneline origin/k142..origin/k144`:
```
e2c4454a2d7deeec9996eb4c8a6303e44f4a996f Fix dns-port in network-policy (#8733)
9f41182da2f69fe7164a6e93915e34cd4162f54b Fix the link in the Azure Event Hubs doc (#8904)
c4d016fd53de7c4af0a4a6d60d191859d244417d Add projected volume type to psp (#8747)
1fcefe8efaccc4175506d2a64f7d4dbe55a5e608 index-gateway: fix failure in initializing index gateway when …
```

Update Loki dependency to the k144 branch

---

.drone/drone.yml
.drone/pipelines/crosscompile.jsonnet
CHANGELOG.md
docs/sources/_index.md
docs/sources/set-up/_index.md
tools/ci/docker-containers
tools/make/packaging.mk

This PR reverts #3476, as we're once again running into compiler issues with 32-bit ARM builds. If a compiler patch is released where 32-bit ARM builds become stable again, we will consider bringing back support, but for now, we need to remove support so we can continue iterating.

Remove 32-bit ARM support (revert #3476)

---

packaging/grafana-agent-flow/deb/grafana-agent-flow.service
packaging/grafana-agent-flow/rpm/grafana-agent-flow.service

The user created by the package is `grafana-agent-flow`, not `grafana-agent`.

packaging: fix user used to run grafana-agent-flow service

---

.github/workflows/bump-formula-pr.yml

The grafana/grafana/grafana-agent Formula was [deprecated][] on 2023-01-08, but the automation to bump it after a Grafana Agent release was left in.
With the introduction of the grafana-agent-flow Formula, we can repurpose the automation to bump that Formula instead.
[deprecated]: https://github.com/grafana/homebrew-grafana/blob/master/grafana-agent.rb

ci: repurpose bump-formula-pr action to bump grafana-agent-flow Formula

---

.drone/drone.yml
.drone/pipelines/build_images.jsonnet
.drone/pipelines/check_containers.jsonnet
.drone/pipelines/publish.jsonnet
.drone/pipelines/test.jsonnet
.drone/pipelines/test_packages.jsonnet

Remove the usage of Docker from the test path so CI tests run faster.

drone: remove usage of Docker from test path

---

.gitattributes
Makefile
docs/developer/contributing.md
go.sum

Minor clean up performed while following the contributing guide. 
Mostly related to the fact that we now use Go 1.19.
N/A - trivial fixes and improvements such as this one do not require an issue.

Contributing guide (and related) clean up

---

component/component_health.go
component/component_health_test.go
component/module/file/file.go
pkg/flow/internal/controller/component.go

This introduces a new function called `component.LeastHealth` which returns the least healthy Health from a list. 
This is useful when there are multiple Health values for a given component, such as with `module.file` containing the health of the managed `local.file` component and its module controller. 
Using this function in `module.file` fixes an issue where the health of `local.file` was never reported, which can be observed by using `module.file` and deleting the file on disk after the agent first loads successfully.

Introduce `component.LeastHealthy` utility function and fix bug in module.file

---

CHANGELOG.md
component/prometheus/exporter/blackbox/blackbox.go
component/prometheus/exporter/blackbox/blackbox_test.go
docs/sources/flow/reference/components/prometheus.exporter.blackbox.md

Add the possibility to pass the blackbox exporter config as string.
Ref: https://grafana.slack.com/archives/C01050C3D8F/p1681416858928169

[flow] prometheus.exporter.blackbox: Support embedded config

---

component/loki/source/file/file_test.go
component/module/file/file.go
component/module/file/file_test.go
pkg/util/eventually.go

Fixes a few flaky tests:
- `component/loki/source/file/file_test.go` had a race condition on clean up & component creating a file
- `component/module/file/file_test.go` had an issue where health message was not deterministic, leading to test flakiness.
- `Test_serviceManager/can_run_service_binary` fails to dial a local service, potentially not enough time to start up? increased the backoff time.

Fixing flaky tests

---

CHANGELOG.md
go.mod
go.sum

- Fixes a bug that would cause the exporter to get stuck in an infinite loop when the github API returns an error.
- See https://github.com/grafana/github-exporter/pull/1
- Switches to grafana's fork instead of rgeyer's one.
Fixes #3144
Closes #3417

Update github exporter

---

cmd/internal/flowmode/cmd_run.go
component/component.go
component/discovery/discovery.go
component/loki/process/process_test.go
component/loki/source/file/file_test.go
component/module/file/file_test.go
component/module/module.go
component/module/string/string_test.go
component/phlare/scrape/scrape_loop_test.go
component/phlare/scrape/scrape_test.go
component/prometheus/scrape/scrape.go
component/registry.go
go.mod
go.sum
pkg/cluster/cluster.go
pkg/cluster/gossip.go
pkg/flow/flow.go
pkg/flow/flow_test.go
pkg/flow/internal/controller/component.go
pkg/flow/internal/controller/loader.go
pkg/flow/internal/controller/loader_test.go

This is a PR to showcase a first use of clustering in the Agent.
For easier review, I suggest going commit-by-commit.
I'd like to throw out the idea that we may even split this up into multiple PRs if we at least agree in the way that we make the controller cluster-aware if we don't agree on the way we implement component behavior.
More specifically, this PR:
* Introduces a couple of new command-line arguments that enable clustered mode and specifying which peers to connect to.
* Introduces a `Clusterer` struct which is a thin layer over rfratto/ckit
* Propagates the Clusterer to be used by components through their Arguments
* Allows components to register and unregister themselves to have their Update method called 
* Uses the above to have the `prometheus.scrape` component wrap its …

Make the Flow controller cluster-aware and use it to distribute targets between prometheus.scrape components

---

docs/sources/flow/reference/cli/fmt.md

The title page was not consistent with the `run` command.

docs: fix page title for cli/fmt.md

---

CHANGELOG.md
cmd/internal/flowmode/cmd_run.go
docs/sources/flow/reference/cli/run.md
docs/sources/flow/reference/components/prometheus.scrape.md

This PR adds some documentation around clustering, the new cli args that can enable it as well as the single component that can opt-in to using it (prometheus.scrape).
Nothing in particular.

flow: Add docs around clustering

---

CHANGELOG.md
pkg/config/agentmanagement.go
pkg/config/agentmanagement_test.go
pkg/config/config_test.go

- Moves remote_config_cache_location config field under remote_configuration section.
- Since we have a remote_config section, all fields specifically related to it should go there.
- Although this is a breaking change and last minute before the next rc, I think it is worth doing since we can bundle it together with other breaking changes to the config.

[Agent Management] Move `agent_management.remote_config_cache_location`

---

CHANGELOG.md

We mistyped `prometheus` instead of `otelcol` for `exporter.logging` in the CHANGELOG.

Fix entry in CHANGELOG

---

operations/helm/charts/grafana-agent/CHANGELOG.md
operations/helm/charts/grafana-agent/Chart.yaml
operations/helm/charts/grafana-agent/README.md

Update Helm chart to 0.11.0 to include latest changes since it's been a while since the last release.
Closes #3576.

helm: cut 0.11.0

---

CHANGELOG.md
component/loki/source/docker/docker.go
component/loki/source/docker/docker_test.go

Building a client relied on the zero value of previous options, which would always result in an error.
Closes #3609.

loki.source.docker: fix issue where building a client always fails

---

cmd/internal/flowmode/cmd_run.go
pkg/cluster/cluster.go

The previous implementation had an oversight where the default port was only set from the `--cluster.advertise-address` flag, _if_ it was provided.
That meant that when using a DNS name as `--cluster.join-addresses`, it was expected that it the other nodes would be reacheable on port 80.
This PR adds a new CLI flag that appends a default port to the advertise and join addresses, if not one is explicitly defined.
Also, as we expect nodes to have their port numbers _mostly_ aligned to prevent networking issues, we continue using the advertise address to set the default port, if it is provided on it.
No issue filed
Nothing to note. Tested this using our helm charts, but I should invest in getting some testing in the near future.

flow: Parse default clustering port from --server.http.listen-addr

---

CHANGELOG.md
cmd/internal/flowmode/cmd_run.go
component/prometheus/scrape/scrape.go
component/prometheus/scrape/scrape_test.go
component/registry.go
docs/sources/flow/concepts/component_controller.md
docs/sources/flow/reference/cli/run.md
docs/sources/flow/reference/components/prometheus.exporter.apache.md
docs/sources/flow/reference/components/prometheus.exporter.blackbox.md
docs/sources/flow/reference/components/prometheus.exporter.consul.md
docs/sources/flow/reference/components/prometheus.exporter.github.md
docs/sources/flow/reference/components/prometheus.exporter.memcached.md
docs/sources/flow/reference/components/prometheus.exporter.mysql.md
docs/sources/flow/reference/components/prometheus.exporter.postgres.md
docs/sources/flow/reference/components/prometheus.exporter.process.md
docs/sources/flow/reference/components/prometheus.exporter.redis.md
docs/sources/flow/reference/components/prometheus.exporter.snmp.md
docs/sources/flow/reference/components/prometheus.exporter.statsd.md
docs/sources/flow/reference/components/prometheus.exporter.unix.md
docs/sources/flow/reference/components/prometheus.exporter.windows.md
docs/sources/flow/reference/components/prometheus.scrape.md
pkg/flow/flow.go
pkg/flow/internal/controller/component.go

This PR integrates github.com/rfratto/ckit/memconn into Flow, which was already in use in the integrations-next subsystem in static mode. 
memconn allows establishing fully in-memory HTTP connections to avoid the network stack. This is primarily useful in the presence of mTLS, where otherwise Flow would need to know how to connect to itself as a client with the proper TLS certificates.  
As of this PR, in-memory HTTP connections are only used for prometheus.exporter.* components and prometheus.scrape, where prometheus.exporter.* components export an in-memory address, and prometheus.scrape can use a custom dialer to connect to that address. 
I am not really happy with the API as-is, but @mattdurham is actively working on refactoring the controller/module API which would be able to …

Support in-memory HTTP connections for scraping

---

CHANGELOG.md

Adds back the `Main (unreleased)` header that was mistakenly removed.

Fix CHANGELOG Header

---

tools/release-note.md

The links to documentation will change with the v0.33 release, so this commit updates the release note to use the proper links.
This also takes the opportunity to offload all of the instructions to the documentation rather than duplicating instructions between the documentation and the release notes.

misc: update release note to link to new documentation

---

CHANGELOG.md
docs/sources/flow/reference/stdlib/coalesce.md
pkg/river/internal/stdlib/stdlib.go
pkg/river/vm/vm_stdlib_test.go

Adding an coalesce function as described in https://github.com/grafana/agent/pull/3540#issuecomment-1511352098
Fixes #3389
Replaces #3540 
I currently, it's not tested, if updates from components like `local.file` or `remote.http` are passed. 
For example 
```
local.file "blackbox_exporter_config" {
filename  = "/etc/grafana-agent/blackbox_exporter.yaml"
}
prometheus.exporter.blackbox "this" {
config = coalesce(local.file.blackbox_exporter_config.content, "{ modules: { http_2xx: { prober: http, timeout: 5s } } }")
target "TARGET_NAME" {
address = "TARGET_ADDRESS" 
}
}
```
If `local.file.blackbox_exporter_config.content` switches from empty string to content, the `coalesce` function needs to aware of this. Not sure, if river functions supporting this.

Added coalesce function

---

CHANGELOG.md
cmd/grafana-agent-operator/Dockerfile
cmd/grafana-agent/Dockerfile
cmd/grafana-agentctl/Dockerfile
docs/sources/flow/upgrade-guide.md
docs/sources/operator/upgrade-guide.md
docs/sources/static/upgrade-guide.md

Back in v0.31 when we renamed the binaries to include the `grafana-` prefix, we added symbolic links to the Dockerfiles so that we wouldn't immediately break the workflows of people using a custom entrypoint.
Our [upgrade guide](https://grafana.com/docs/agent/latest/upgrade-guide/#v0310) mentioned removing those in v0.33 which we never did.
Fixes #2877
Should this have _another_ changelog entry?

Remove symbolic links to old binary names

---

CHANGELOG.md
pkg/river/internal/value/decode.go
pkg/river/internal/value/decode_test.go

Previously, capsules were always decoded to the `any` type using their fully deferenced values.
Fixes #3565.

river: retain pointer to capsule when decoding to any

---

pkg/cluster/cluster.go

This PR makes use of the address only when finding join addresses via a DNS lookup.
I found two clusters with different behavior; in one the lookup returned a port, in the other it didn't and made the cluster unable to bootstrap.
I think this ties better with the recommendation that all nodes use the same port; we should double down on that message instead of allowing wiggle room.

clustering: Use only the address on DNS lookups

---

pkg/cluster/cluster.go

We should call ApplyDefaults _after_ setting JoinPeers.

clustering: Apply defaults after defining join peers

---

pkg/river/internal/value/decode.go
pkg/river/internal/value/decode_test.go
pkg/river/internal/value/value_object_test.go
pkg/river/vm/vm_block_test.go
pkg/river/vm/vm_stdlib_test.go

Previously, all non-floating point numbers decoded into an int, and all floating-point numbers decoded into a float64. This did not match the documentation, which stated that all River numbers should decode into a float64.
No changelog entry is added because this is only a developer-facing change.
Closes #3629.

river: match documentation when decoding numbers into any

---

docs/sources/flow/install/kubernetes.md

Following the discussion on slack, the project recommends against using doing new rollouts on config change, which would be the default behavior when using kustomize to generate the ConfigMap if one is not careful.
This PR adds a section to the installation docs mentioning this recommendation, along with a snippet of a kustomization with the appropriate config to disable the behaviour.

docs: Add kustomize considerations on flow mode install for kubernetes

---

docs/sources/static/configuration/agent-management.md

Iterates on Agent Management documentation.
I think this additional note adds mostly noisy and is not generally relevant to users.

Remove implementation detail from agent management doc

---

CHANGELOG.md
docs/sources/static/api/_index.md
docs/sources/static/configuration/flags.md
pkg/supportbundle/supportbundle.go

(cherry picked from commit 689587f700e8b6101ee8ca9691f2fc6797970d12)

supportbundle: add debug information about log targets (#3625)

---

docs/sources/flow/config-language/expressions/types_and_values.md

The backspace escape sequence has not been listed in the docs even though it has been supported.

List backspace escape sequence in the documentation

---

CHANGELOG.md
component/loki/source/gcplog/gcplog.go
component/loki/source/heroku/heroku.go
component/loki/source/heroku/internal/herokutarget/herokutarget.go
component/loki/source/heroku/internal/herokutarget/metrics.go
pkg/util/unchecked_collector.go

Every time an HTTP server for `loki.source.heroku` is created, it creates a new weaveworks/common server, and registers the same set of metrics to the provided collector.
By default, these are checked metrics, which causes the agent-wide `/metrics` endpoint to stop working with an error:
An error has occurred while serving metrics:
4 error(s) occurred:
* collected metric "loki_source_heroku_drain_target_tcp_connections_limit" { label:<name:"component_id" value:"loki.source.heroku.repro" > label:<name:"protocol" value:"http" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "loki_source_heroku_drain_target_tcp_connections_limit" { label:<name:"component_id" value:"loki.source.heroku.repro" > label:<name:"protocol" value:"grpc" > gauge:<value:0 …

loki.source.heroku: use an unchecked collector for server metrics

---

build-image/Dockerfile

yamllint is used now in `make generate-helm-tests`
Fixes #3722.

build-image: add yamllint

---

CHANGELOG.md
Makefile
component/loki/source/file/file.go
component/loki/source/file/file_test.go

Previously, one loki.EntryHandler was created per target, but only the most recent loki.EntryHandler was tracked in memory. This caused all the other loki.EntryHandlers to permanently leak whenever the component was reloaded.
PR #3036 attempted to initially address the leak, but we missed that handlers were being created in a loop in the case of loki.source.file.
Closes #3728.
cc @spartan0x117 I'd like to include this in the v0.33.1 patch release if we could.

loki.source.file: fix goroutine leak

---

operations/helm/charts/grafana-agent/CHANGELOG.md
operations/helm/charts/grafana-agent/Chart.yaml
operations/helm/charts/grafana-agent/README.md
operations/helm/tests/controller-volumes-extra/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/create-daemonset-hostnetwork/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/create-daemonset/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/create-deployment-autoscaling/grafana-agent/templates/controllers/deployment.yaml
operations/helm/tests/create-deployment/grafana-agent/templates/controllers/deployment.yaml
operations/helm/tests/create-statefulset/grafana-agent/templates/controllers/statefulset.yaml
operations/helm/tests/custom-config/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/default-values/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/envFrom/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/existing-config/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/extra-env/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/extra-ports/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/faro-ingress/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/static-mode/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/tolerations/grafana-agent/templates/controllers/daemonset.yaml

Bumps helm chart version to `0.13.0` and updates the agent version to `v0.33.1`.

[Helm] Update Agent version to v0.33.1

---

CHANGELOG.md
component/component_health.go
pkg/flow/internal/controller/component.go

This commit offers an alternative approach to #3558, where the overall health of a component only considers the component implementation of health if that component implements the component.HealthComponent interface.
It also has the benefit of reducing the overall public API surface. 
This reverts commit b2f8992ce0c8a7e9de53c871e64774c2ae8f8d8e. The previous commit introduced a bug where the "default health" message was always returned for healthy components, overriding the message informing the user when the last time the component evaluated was.

flow: only use component health when component implements component.HealthComponent

---

docs/sources/flow/reference/components/module.git.md

`git` was missing from the usage section.

Fix usage in module.git documentation

---

CHANGELOG.md
component/phlare/scrape/scrape.go
component/phlare/scrape/scrape_test.go
docs/sources/flow/reference/components/phlare.scrape.md

This commit adds clustering support to `phlare.scrape`, allowing profile collection to be distributed amongst agents participating in a cluster.
Let me know if there's anything I missed to allow clustering to work with phlare.scrape.

phlare.scrape: support clustering

---

operations/agent-flow-mixin/dashboards/cluster-node.libsonnet
operations/agent-flow-mixin/dashboards/cluster-overview.libsonnet
operations/agent-flow-mixin/dashboards/utils/panel.jsonnet
operations/agent-flow-mixin/grizzly.jsonnet

There was some feedback that _I thought_ I'd incorporated into #3744, but I'd committed them to the wrong branch, so apologies for missing them the first time out.
In this PR we've
a) Added actually helpful descriptions for panels that need one, and removed descriptions for self-explanatory panels
b) Made long queries into multi-line strings for better readability
c) Made the axis centered and fixed the legend for the Stream Bandwidth and Transport Bandwidth channels
d) Added a dirty hack so that relative dashboard links still work whenever Grafana splices part of the URL with the dashboards UID.
Here's how the two affected panels look with their axis centered and their legend fixed. The difference between rx/tx is now more pronounced.

agent-flow-mixin: amended descriptions and fixes around clustering dashboards

---

CHANGELOG.md
docs/sources/flow/reference/components/prometheus.exporter.unix.md
docs/sources/static/configuration/integrations/node-exporter-config.md
pkg/integrations/node_exporter/config.go

The current logic in the node_exporter integration, that was also inherited by the prometheus.exporter.unix component was that a) the `device_exclude` field had a default value and b) the `device_exclude` and `device_include` fields were mutually exclusive.
This meant that the first field was always being set implicitly, and if the second was defined then node_exporter could not start.
That means that the following two config files failed to start the Agent and there was no way to make use of `device_include`.
```yaml
integrations:
node_exporter:
enabled: true
scrape_integration: true
set_collectors:
- "diskstats"
diskstats_device_include: "/dev/vd.*"
```
```river
prometheus.exporter.unix {
disk {
device_include = "foo"
}
}
```
This PR changes the logic of the two fields to allow the …

node_exporter: fix usage of diskstat flags

---

CHANGELOG.md
docs/sources/flow/reference/components/prometheus.exporter.postgres.md

Relates to https://github.com/grafana/agent/pull/3176
This PR updates the Flow documentation for the `prometheus.exporter.postgres` component to reference the correct `custom_queries_config_path` argument.

[Flow] Update configuration documentation for the Postgres Component

---

CHANGELOG.md
docs/sources/flow/reference/components/prometheus.remote_write.md
pkg/metrics/wal/series.go
pkg/metrics/wal/wal.go
pkg/metrics/wal/wal_test.go

This commit synchronizes the WAL code with the upstream tsdb/agent code in Prometheus. I synced the code  against the latest main commit at the time of starting the commit; prometheus/prometheus@7c2de14b0bd74303c2ca6f932b71d4585a29ca75.  
For now, I opted to synchronize the code instead of importing upstream literally for two reasons:
1. Importing upstream literally will require more effort and be a breaking change, as the metrics and metric names used by upstream are different than the names we had selected. 
2. For now, we may want to continue to experiment with changes to WAL storage downstream, such as for clustering and cleaning up memory faster. 
This change should have little-to-no noticeable impact on end users, with one exception being that each series should use slightly less …

Sync WAL code with upstream

---

operations/agent-flow-mixin/dashboards/cluster-overview.libsonnet
operations/agent-flow-mixin/grizzly.jsonnet
operations/agent-flow-mixin/grizzly/alerts.jsonnet
operations/agent-flow-mixin/grizzly/dashboards.jsonnet

This adds a convergence state timeline to the overview dashboard, allowing users to see a history of when the cluster was converged or not converged, along with the time it took to transition between the states.
Additionally, Grizzly functionality has been split into multiple files in a folder. This allows the primary grizzly.jsonnet entry file to be used for syncing everything, while allowing developers to opt in to only developing a specific set of resources (like dashboards but not alerts).

agent-flow-mixin: Add convergence state timeline

---

docs/sources/flow/install/docker.md
docs/sources/flow/install/linux.md
docs/sources/flow/install/macos.md
docs/sources/flow/install/windows.md
docs/sources/flow/monitoring/debugging.md

The default listen address for non-containerized installations is `localhost`, which prevents other machines on the network from being able to see the UI.
This default behavior may not be obvious to people, so this commit documents that behavior more clearly and instructs people on how to change the listen address.

docs: document how to expose the UI to other machines on the network

---

operations/agent-flow-mixin/alerts.libsonnet
operations/agent-flow-mixin/alerts/clustering.libsonnet
operations/agent-flow-mixin/alerts/utils/alert.jsonnet
operations/agent-flow-mixin/dashboards/utils/panel.jsonnet
operations/agent-flow-mixin/grizzly/alerts.jsonnet

When using `mixtool` to render alerting rules, I noticed that it required a different approach than dashboards; instead of being rendered in a different file each, they all get listed under a groups key. Meanwhile grizzly still requires them to be present as a separate item each.
This change allows alerts to be usable _both_ when using grizzly and in the context of a rendered mixin.
The alerts can now be applied via grizzly _and_ work when rendering the mixin using `mixtool generate alerts`.
```
grr apply grizzly.jsonnet --log-level=debug
INFO[0000] Applying 7 resources
DEBU[0000] Getting the remote value for `DashboardFolder.grafana-agent-flow`
DEBU[0000] `DashboardFolder.grafana-agent-flow` was found, updating it...
DashboardFolder.grafana-agent-flow updated
DEBU[0000] …
```

agent-flow-mixin: fix alerts format

---

operations/agent-flow-mixin/alerts.libsonnet

This PR updates the agent-flow-mixin definition in alerts to merge the Prometheus rule groups instead of replacing them.
Nothing to note.

agent-flow-mixin: merge rule groups instead

---

CHANGELOG.md
component/prometheus/exporter/windows/config.go
component/prometheus/exporter/windows/config_default_windows_test.go
component/prometheus/exporter/windows/windows_test.go
docs/sources/flow/reference/components/prometheus.exporter.windows.md
go.mod
go.sum
pkg/integrations/windows_exporter/config.go
pkg/integrations/windows_exporter/config_windows.go
pkg/integrations/windows_exporter/windows_exporter_windows.go

This PR removes the outdated internal grafana/windows_exporter fork.
This PR is still in draft, since various upstream PR needs to be solved first. This PR based on personal forks of windows_exporter which are planned to be merged upstreamed. After that, the PR is ready to review.
I'm creating the PR right now to indicate that some is working on the windows_exporter.
It introduce a breaking change from https://github.com/prometheus-community/windows_exporter/pull/1170 (not sure how to handle this). If Grafana Agent follows SemVer, the breaking change is fine.
Test on a windows 10 system with following config:
```
prometheus.exporter.windows "exporter1" {
// Subset of overall collectors  
enabled_collectors = "cpu,cs,logical_disk"
}
prometheus.exporter.windows "exporter2" {
// Different …
```

Switch to upstream windows_exporter

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/ISSUE_TEMPLATE/proposal.yaml

Add issue templates for:
* Bug reports, to allow users to report specific problems.
* Feature requests, to allow users to request that new functionality be added.
* Proposals, to allow users to propose a specific implementation for a problem they would like to solve.
Feature requests are just off-the-cuff suggestions, while proposals are expected to go more in depth about the background and the proposed solution(s).

misc: add issue templates

---

CHANGELOG.md
component/phlare/scrape/scrape_loop.go

phlare.scrape `fetch profile failed` logs are creating a bunch of noise. Change them to `debug` level.

Update log level for a phlare.scrape log

---

pkg/operator/clientutil/clientutil.go
pkg/operator/reconciler_integrations.go
pkg/operator/reconciler_logs.go
pkg/operator/reconciler_metrics.go

There are some cases where kubernetes will not allow you to update a StatefulSet if certain fields have changed. In that case, we will delete and recreate it as a fallback.
This adds a little logging to help diagnose that.

operator: add logging if we fail to update a controller

---

CHANGELOG.md
go.mod
go.sum

Update our dependency of Prometheus to a fork which includes a cherry pick of prometheus/prometheus#12349 in the v2.42.0 release.
Fixes #3826.

misc: cherry-pick prometheus/prometheus#12349

---

CHANGELOG.md
component/loki/source/kubernetes/kubetail/tailer.go

We've gotten some reports of the agent crashing when using loki.source.kubernetes.
Here's a stack trace of this happening:
<details>
```
grafana-agent ts=2023-05-11T15:57:01.398384003Z level=info trace_id=559f5d0626cd43cb04fc351bc95144b3 msg="starting complete graph evaluation"
grafana-agent ts=2023-05-11T15:57:01.398661803Z level=info msg="now listening for http traffic" addr=0.0.0.0:80
grafana-agent ts=2023-05-11T15:57:01.398753303Z level=info msg="running usage stats reporter"
grafana-agent ts=2023-05-11T15:57:01.398922603Z component=discovery.kubernetes.services level=info msg="Using pod service account via in-cluster config"
grafana-agent ts=2023-05-11T15:57:01.399386203Z level=info trace_id=559f5d0626cd43cb04fc351bc95144b3 msg="finished node evaluation" …
```

Make sure labels are cloned from loki.source.kubernetes

---

operations/river-jsonnet/README.md
operations/river-jsonnet/builder.jsonnet
operations/river-jsonnet/main_test.jsonnet
operations/river-jsonnet/manifest.jsonnet

Support adding an index argument to river.block to ensure that blocks get marshaled in a specific order.

river-jsonnet: support block indexes

---

docs/sources/flow/upgrade-guide.md
docs/sources/operator/upgrade-guide.md
docs/sources/static/upgrade-guide.md

This removes patch versions from the upgrade guide, since upgrade guide applies to minor versions as a whole and not individual patch releases.
The only instance where the patch release mattered was for a security release in the past; this has been explicitly listed with the patch version.
(cherry picked from commit db7f9f28ff625e4ea82c464f97af4dec17cc9c4f)

[release-v0.33] Backport #3864 to release v0.33

---

CHANGELOG.md
component/common/loki/client/client.go
component/common/loki/client/config.go
component/common/loki/client/config_test.go
component/loki/write/types.go
docs/sources/flow/reference/components/loki.write.md

This PR adds configuration to support custom headers for the `loki.write` endpoint block. This is needed in certain situations such as sending to Loki sitting behind Cloudflare Access network.
This PR is essentially a copy of: https://github.com/grafana/loki/pull/7472 retrofit to work with Agent.
Fixes #3879

feat(loki): add custom headers to loki.remote_write

---

CHANGELOG.md
tools/make/packaging.mk

This PR fixes some occurrences where the s390x artifacts were built using the PowerPC GOARCH value, rendering them unusable.
Related to #3891
I'm not sure whether this should be backported to the previous release. I don't think we can rebuild the already-published artifacts, but we can advise people on how to build their own.
WDYT?

tools: fix cases where s390x artifacts were built using the wrong GOARCH

---

packaging/grafana-agent-flow/deb/grafana-agent-flow.service
packaging/grafana-agent-flow/rpm/grafana-agent-flow.service
packaging/grafana-agent/deb/grafana-agent.service
packaging/grafana-agent/rpm/grafana-agent.service

The current systemd unit file specifies `/usr/bin/kill` for the `kill` command. The command isn't always placed in that location. It's best to call the command using `/usr/bin/env kill` to always receive the path to the actual location of the command.
N/A

Do not use hard-coded `kill` command path

---

CHANGELOG.md
component/common/net/config.go
component/common/net/config_test.go
component/common/net/server.go
component/common/net/server_test.go
component/loki/source/api/api_test.go
docs/sources/shared/flow/reference/components/loki-server-grpc.md
pkg/traces/traces_test.go

This PR fixes the `common/net` server configuration, which was overriding the defaults inherited from weaveworks. Before, the calls of `http.Into()` or `grpc.Into()` were overriding the defaults that were already present on the weaverworks config object. 
For tackling that, the defaults of the configs we expose were copied over, so that they are used during unmarshalling.

Fix `common/net` server defaults working incorrectly

---

CHANGELOG.md
cmd/internal/flowmode/cmd_run.go
docs/sources/flow/reference/cli/run.md

This PR introduce a CLI flag to conditionally enable the go profiling endpoints. Leaving the default enable to preserve backwards compatibility.

flow: Add toggle to enable /debug/pprof endpoint

---

docs/sources/flow/install/macos.md

Previously, an instance of the grafana/grafana-agent-flow Homebrew formula installed on macOS would generate logs in the same location as the static mode grafana-agent formula.
The documentation here was incorrect, saying that the stderr file would write to a Flow-specific file.
grafana/homebrew-grafana#52 fixes the formula to log files in the proper, Flow-specific, place, and this PR updates the documentation to use the correct file names (assuming grafana/homebrew-grafana#52 is merged).
Related to #3871.

docs: fix macOS log locations for Flow

---

docs/sources/static/configuration/agent-management.md
docs/sources/static/configuration/integrations/node-exporter-config.md

Change the places in docs where we still specify 15s instead of 60s.
Closes #3411

change scrape intervals in docs to 60s

---

CHANGELOG.md
component/loki/source/journal/journal.go
component/loki/source/journal/types.go
docs/sources/flow/reference/components/loki.source.journal.md

Allow adding custom labels to journal scrapers. Keeps the default behaviors of defaulting to adding a `job: <name>` label, but can be overridden if `job` label passed in explicitly. 
https://github.com/grafana/agent/issues/3182#event-9273947588
Fixes #3182

allow passing in labels from config

---

CHANGELOG.md
component/discovery/discovery.go

Prometheus deduplicates targets after removing the `__meta_` labels.
If these labels are used to define the targets distribution, targets
that must be deduplicated could end in different nodes, resulting in
duplicated metrics.

cluster: Fix targets deduplication

---

cmd/internal/flowmode/cmd_run.go
pkg/cluster/cluster.go

We would like to delay the clusterer implementation's startup (which includes connecting to the configured list of peers) until after the Flow HTTP server is up.
In that case, when Start() is experiencing delays, or it deadlocks, we will still be able to grab pprof profiles to figure out what's wrong. This can also allow the clusterer implementation to _always_ have at least one valid peer to connect to; itself.
Nothing in particular.

clustering: delay startup until after the HTTP server is up

---

CHANGELOG.md
pkg/cluster/gossip.go

Use a 512-token ring to achieve better distribution. Because a 512-token ring only needs 12MB for 1,000 nodes (compared to 6MB for 1,000 nodes in a 256-token ring), its overhead is marginal enough to be worth it for the improved distribution.
However, this change means that any existing cluster being upgraded to the new version will suffer from incorrect or missing hashing assignments until all nodes are using 512 tokens.
This is the type of change we shouldn't make often; I think it's only feasible now because clustering is still experimental. Future changes would likely need to be opt-in via a flag.

clusterer: use a 512-token ring

---

docs/sources/flow/reference/components/loki.source.journal.md

This PR fixes the incorrect example for loki.source.journal.
Until we decide how to handle relabeling rules for Loki components, the loki.relabel component must still have its `forward_to` argument be set.
Fixes #3656.
Nothing to note.

docs: fix example for loki.source.journal component

---

CODEOWNERS
MAINTAINERS.md

Update the list of CODEOWNERS to make sure every PR notifies some group of people, even if that group of people should redirect it to others. 
The list of MAINTAINERS.md is then updated to refer back to the GOVERNANCE.md and CODEOWNERS files.

update CODEOWNERS, MAINTAINERS.md

---

operations/agent-flow-mixin/alerts/clustering.libsonnet
operations/agent-flow-mixin/dashboards/cluster-node.libsonnet
operations/agent-flow-mixin/dashboards/cluster-overview.libsonnet

This PR adds the proper template variables on the queries for the Cluster Overview and Cluster Node dashboards. It also relaxes the alert for NodeConflict time to fire from 5 to 10 minutes.
Fixes #3940
Nothing to add :)

agent-flow-mixin: add template variables to queries; relax NodeConflict alert

---

CHANGELOG.md
pkg/operator/clientutil/clientutil.go
pkg/operator/resources_metrics.go
pkg/operator/resources_metrics_test.go
pkg/operator/resources_pod_template.go
pkg/operator/resources_pod_template_test.go

StatefulSet labels cannot be changed after creation (depending on your kubernetes version).
We were putting the agent version in as a label on agent pods, AND on the StatefulSets themselves. That meant that anytime a version upgrade happens, the statefulset needed to be dropped and recreated, causing all pods to restart at once.
This change removes the version label from the stateful set. This means all pods will restart after this upgrade one last time, but future upgrades should be smoother.
I also decreased the termination grace period on the recreate code path, so that the pods shut down faster, and hopefully downtime will be less when this happens.

cmd/operator: Fix bug where StatefulSets get fully recreated on version upgrades

---

docs/sources/flow/reference/components/discovery.kubernetes.md

Add `__meta_kubernetes_pod_container_id` to the docs of `discovery.kubernetes`
Has been added to Prometheus in January 2023, so was probably just an oversight.
- ~[ ] CHANGELOG updated~
- ~[ ] Tests updated~!

Add `__meta_kubernetes_pod_container_id` to the docs

---

operations/helm/charts/grafana-agent/CHANGELOG.md
operations/helm/charts/grafana-agent/templates/controllers/_pod.yaml
operations/helm/tests/controller-volumes-extra/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/create-daemonset-hostnetwork/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/create-daemonset/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/create-deployment-autoscaling/grafana-agent/templates/controllers/deployment.yaml
operations/helm/tests/create-deployment/grafana-agent/templates/controllers/deployment.yaml
operations/helm/tests/create-statefulset-autoscaling/grafana-agent/templates/controllers/statefulset.yaml
operations/helm/tests/create-statefulset/grafana-agent/templates/controllers/statefulset.yaml
operations/helm/tests/custom-config/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/default-values/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/envFrom/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/existing-config/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/extra-env/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/extra-ports/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/faro-ingress/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/static-mode/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/tolerations/grafana-agent/templates/controllers/daemonset.yaml

As per the [Kubernetes docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#podspec-v1-core), in PodSpec the `serviceAccount` field is a deprecated alias for `serviceAccountName`, which should be used in its place.
This change should be a no-op to people using the Helm chart.
```
serviceAccount (string) | Deprecated - ServiceAccount is a depreciated alias for ServiceAccountName. Deprecated: Use serviceAccountName instead.
```
No issue filed
Do we want to notify users that this is a no-op change so that they're not worried if they see a diff in their rendered manifests?

helm: rename pod template's serviceAccount to serviceAccountName

---

web/ui/src/features/component/ComponentList.module.css
web/ui/src/features/component/ComponentList.tsx

Fixes #3870 
Quick glance at the changes
https://github.com/grafana/agent/assets/112968312/6522466d-31f7-4113-aaa7-bd60528ee418
Changes in the video:
1. Vertically aligned the View button
2. Fixed the padding of first and second column of table
Checks in the other page:
1. Double checked with the detail page to see the changes does not affect the table in there
2. Double checked to see if the component work properly with flex while window shrink

fix table padding

---

CHANGELOG.md
component/loki/source/journal/journal.go

This PR fixes the permissions which are used to create the positions directory for loki.source.journal to match all the other `loki.source.*` components. It also moves the directory creation to before the definition of the file.
Eg. here's how it works for loki.source.docker
https://github.com/grafana/agent/blob/4b8807a517071556c7fd520d7ddd792fbcd311f7/component/loki/source/docker/docker.go#L77-L85
Fixes #3972
Nothing in particular. Maybe this should also be part of the shared abstraction for logging components.

loki.source.journald: sync positions directory permissions

---

go.mod
go.sum

These were referenced in various (dubious) CVEs. There is no way the vulns specified were exploitable through agent, but updates are fun anyway.

update github.com/sirupsen/logrus and github.com/docker/distribution

---

component/common/net/config.go
component/common/net/config_test.go
component/common/net/server.go
component/loki/source/api/api.go
component/loki/source/gcplog/internal/gcplogtarget/types.go
component/loki/source/heroku/heroku.go
component/prometheus/receive_http/receive_http.go

Most flow components that use `fnet.TargetServer` expose the `fnet.ServerConfig` squashed in their river config. The unmarshalling of `ServerConfig` was applying defaults by implementing `UnmsarshalRiver`. Since the block is squashed, this doesn't work as expected.
This PR applies the same pattern as https://github.com/grafana/agent/blob/f5ed4ce08fff02fd030d7a0d35663d19888eaef4/component/prometheus/scrape/scrape.go#L100 which is, when a block is squashed, to apply the defaults from the unsmarshall river in the outermost struct.
Also, this PR adapts the `ServerConfig` testing suite to test the unmarshalling with the block being squashed.

Fix ServerConfig defaults due to block squashing

---

docs/developer/writing-exporter-flow-components.md

- The function `NewMultiTarget` was recently extended to allow further customization of scrape targets and renamed to `NewWithTargetBuilder`.
- See https://github.com/grafana/agent/pull/3873

Update documentation for writing a prometheus exporter component

---

docs/sources/static/set-up/install-agent-macos.md

Setting config yaml filename back to `config.yml`. It was noted in usability testing that the default config filename for OSX uses `.yml` for the file extension. This change is a quick fix to change the documented filename back to match the install.
Original change was in https://github.com/grafana/agent/pull/3507
Future editing/changes will look at using placeholder naming instead of explicit filenames.

Reverting config yml filename

---

docs/sources/shared/flow/reference/components/rule-block.md

The uppercase and lowercase relabel actions are available in the Agent, but are not listed in the documentation.

Updating rule block documentation to add uppercase/lowercase

---

production/grafana-agent-mixin/alerts.libsonnet

- Agent management does a failover to a disk-cached copy of the last valid configuration on failure to fetch a remote config. In certain scenarios, the local copy might not exist (on first run of the agent, or when the local copy has been deleted).
- When that happens, the agent will fallback to an empty config while trying to reconnect. This needs to be alerted on because during this time, the agent won't do any work, and may indicate issues with the initial configuration.

[Agent Management] Add alerts for fallback to empty config

---

CHANGELOG.md
cmd/grafana-agent-operator/Dockerfile
cmd/grafana-agent/Dockerfile
cmd/grafana-agentctl/Dockerfile
tools/crow/Dockerfile
tools/smoke/Dockerfile

Updating to ubuntu:lunar includes updating the systemd dependency to 252, which is required to read journald on newer host systems.
Fixes #4004.

misc: update base image of Docker containers to ubuntu:lunar

---

CODEOWNERS

Ownership of CHANGELOG.md should be effectively shared; owners of code for which a PR is being opened should be share responsibility for properly modifying the CHANGELOG in that PR.
This avoids an issue where @grafana/grafana-agent-core-maintainers were tagged on any PR that modified the CHANGELOG, even if that PR wasn't relevant to that team.

misc: remove CODEOWNERS from CHANGELOG.md

---

CHANGELOG.md
web/ui/src/features/component/ComponentList.tsx

grafana/agent#3101 accidentally removed the logic which calculated the proper URL of a component which took parent modules into account.
Fixes #3999.

web/ui: fix issue where nested modules did not properly display

---

CHANGELOG.md
component/module/module.go

The dialerfunc is not being passed to the child modules, this caused exporters to fail since they were exporting agent.internal but serving on normal http.
- [X ] CHANGELOG updated

Fix issue where the in-memory dialer was not being passed to modules.

---

CHANGELOG.md

My PR https://github.com/grafana/agent/pull/3995 was in-flight when we cut the release and the release note landed in a wrong place.

Move misplaced release note

---

docs/sources/flow/reference/components/prometheus.exporter.windows.md

I think there was a mixup in the documentation for the windows exporter. `enabled_list` was documented in the way that `enabled_collectors` should have been documented, and vice versa. 
I raised this PR just to fix the docs, but I think we should make another PR to also convert the `enabled_list` to a `list(string)`

[Flow] Fix attribute docs for the Prometheus Windows Exporter

---

CHANGELOG.md
component/prometheus/exporter/dnsmasq/dnsmasq.go
component/prometheus/exporter/dnsmasq/dnsmasq_test.go

Changes to use `NewWithTargetBuilder` to set the `"instance"` key for metrics, matching what is currently set in https://github.com/grafana/agent/blob/main/pkg/integrations/dnsmasq_exporter/dnsmasq_exporter.go#L35.

dnsmasq - Add customizeTarget which matches InstanceKey

---

docs/sources/flow/reference/components/prometheus.exporter.windows.md

* Fix docs for enabled_collectors
* Fix typo
* Fix default value for enabled_list
---------
(cherry picked from commit 68f8dca896b8790e6f3dbd36bc045e2ce1f0d4f6)

[Flow] Fix attribute docs for the Prometheus Windows Exporter (#4053)

---

pkg/river/encoding/riverjson/riverjson_test.go
pkg/river/encoding/riverjson/types.go

This change ensures that required fields in the API are always returned; the only truly optional field is the label on blocks.
This resolves an issue from #4069 where a module with no exports omitted the `body` field, crashing the UI.
This was tested with the following module:
```txtar 
-- root.river --
prometheus.remote_write "default" { }
module.file "a" {
filename = "child_a.river"
}
-- child_a.river -- 
prometheus.remote_write "default_a" { }
module.file "b" {
filename = "child_b.river"
}
-- child_b.river --
prometheus.remote_write "default_b" { }
```
No CHANGELOG entry was added because this issue is only present in main and hasn't been released yet.

river/encoding/riverjson: ensure required fields are always marshaled

---

CHANGELOG.md
component/prometheus/exporter/statsd/config.go
component/prometheus/exporter/statsd/statsd_test.go
docs/sources/flow/reference/components/prometheus.exporter.statsd.md
docs/sources/static/configuration/integrations/statsd-exporter-config.md
pkg/integrations/statsd_exporter/statsd_exporter.go

`statsd_exporter` natively supports setting the relay endpoint. However, the current implementation of statsd integration doesn't allow configuring the endpoint.
The proposed PR extends statsd integration to configure relay endpoint.
The default value for `RelayPacketLength` was taken from the original implementation. Please refer to the code reference [here](https://github.com/prometheus/statsd_exporter/blob/c3752cf30f14d53838a3104c1fd1b20f3cc354eb/main.go#L262).

Extend statsd integration to configure relay endpoint

---

CHANGELOG.md
component/remote/http/http.go

This updates `remote.http` to return an error if polling after Update fails. Returning an error following Update is important to make sure that background failures don't cause issues to propagate across components:
If a component expects remote.http to have a non-empty body, remote.http should be unhealthy on first evaluation to prevent downstream components from evaluating.
In addition to failing early, failed requests are now logged to assist with user debugging.
Fixes #4084.

remote.http: fail early and add logs for failed requests

---

CHANGELOG.md
component/loki/source/azure_event_hubs/azure_event_hubs.go

Fixed an issue I had when using workload identity in AKS to authenticate to Azure Event Hubs. It was fixed by adding the path `/.default` to the scope.

fix(azure_event_hubs): default scope

---

docs/sources/static/set-up/install-agent-macos.md

A review of macOS installation steps showed that the install information for Agent static install was incorrect in some areas and other important information was completely missing.
1. The default prefix for Homebrew is based on CPU type (Intel vs Apple Silicon). Added a note about this.
2. The information about where grafana-agent is installed by default is now based on the CPU type.
3. Removed `mkdir $(brew --prefix)/etc/grafana-agent/` because this directory is created by the installer.
4. The sections are now split by task with new headings for each task.
5. Clarified the information around where the `config.yml` file is located - this was confusing people.
6. The log information is updated to match the Flow style.

Update macOS steps to fix Homebrew information and correct syntax

---

docs/sources/flow/reference/components/prometheus.receive_http.md
docs/sources/static/api/_index.md
docs/sources/static/configuration/flags.md
docs/sources/static/configuration/integrations/integrations-next/_index.md
docs/sources/static/configuration/integrations/integrations-next/snmp-config.md
docs/sources/static/configuration/integrations/snmp-config.md
docs/sources/static/configuration/traces-config.md

Some of the links in the documentation have been broken. This change will point those links to the latest version of Prometheus.
There's only one minor issue with this change - ideally we should point to the version of Prometheus which the Agent is using. However, I suppose Prometheus is relatively stable and this is not a big concern.
Closes #4051.

Use latest version of Prometheus in URLs to Prometheus docs

---

pkg/river/internal/value/decode.go
pkg/river/internal/value/decode_test.go
pkg/river/internal/value/value_object_test.go
pkg/river/river.go
pkg/river/vm/constant.go
pkg/river/vm/vm_benchmarks_test.go
pkg/river/vm/vm_block_test.go
pkg/river/vm/vm_stdlib_test.go

Currently, if River unmarshals a number into an `interface{}` it will always turn it into a float64.  This is similar to json unmarshaling which always unmarshals numbers to floats. 
However, it is a problem in some cases, when we need to be yaml-compatible. For example, in #3822 we have an `interface{}` value in our River struct which could be an int, float or a string. Depending on which type is used, OpenTelemetry will create an attribute (label) in the signal with this same type. Since River always unmarshals numbers into a float when the variable is of type `interface{}`, all Otel attributes of a numerical type will be floats and none will be integers. 
This change makes River more in line with yaml, whose behaviour could be summarised as:
1. Try parsing the string into an integer
2. …

River: Unmarshal integers from interface{} into int64, uint64 or float64

---

CODEOWNERS

`prometheus.operator.*` components were missing from CODEOWNERS.

CODEOWNERS: add /component/prometheus/operator/

---

CHANGELOG.md
docs/sources/static/configuration/integrations/cloudwatch-exporter-config.md
go.mod
go.sum
pkg/integrations/cloudwatch_exporter/cloudwatch_exporter.go
pkg/integrations/cloudwatch_exporter/config.go

This PR bumps the cloudwatch exporter dependency to the latest releast ([v0.51.0](https://github.com/nerdswords/yet-another-cloudwatch-exporter/releases/tag/v0.51.0)), which includes multiplex fixes and new features. Some api changes occurred since the previous version, so this PR updates them.
Also, some changes are made from our experience running the exporter:
- Error handling added, don't know why it was missing
- Add support for enabling exporter debug logging (useful for debugging)
- Enable max dimension associator feature flag, which uses the new tags to metrics associator, fixing a couple of bugs [info](https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/master/docs/feature_flags.md#new-associator-algorithm)
This PR is the previous step to migrating this component …

Bump and improve Cloudwatch exporter

---

CHANGELOG.md
go.mod
go.sum
pkg/integrations/mongodb_exporter/mongodb_exporter.go

- We need to remove mongodb exporter until licensing issues with one of its dependencies have been resolved.
- Keeps the configuration and boilerplate code, making the actual exporter a no-op that always returns an error.
- Hopefully we will be able to bring it back before the next release.
Fixes #4158

Remove mongodb exporter for the time being

---

.drone/drone.yml
.drone/pipelines/test.jsonnet

The Windows tests historically have bad performance, causing the turnaround time for a PR to be anywhere up to 10-15 minutes, even though all other jobs finish in 3 minutes or less.
This commit takes Windows tests out of the PR testing path to reduce total turnaround time for a PR.
Windows tests will now be run on main commits, and maintainers will need to be on the lookout for test failures so they can follow up if a bad PR gets merged that breaks Windows.

drone: only run Windows tests on merge

---

converter/converter.go

Normally builder.File already pretty-prints the file, but custom tokens aren't pretty-printed. This makes sure that the resulting file is in the standard format.

converter: pretty-print the output

---

component/loki/process/internal/stages/geoip.go
docs/sources/flow/reference/components/loki.process.md

Extracting data as labels, how it was done in the port from promtail, makes it more difficult to use with other stages. In addition, extracted values had to be converted to a string. The only extracted non-string values are currently only `latitude` and `longitude`, however, with the #4141 proposal then it would be possible to add complex types.

loki.process: extract data to shared map in geoip stage

---

CHANGELOG.md
component/prometheus/relabel/relabel.go

In [this change](https://github.com/grafana/agent/commit/edcc83858ad92f3b96c44fa77142db352dd431de#diff-5f10a07e4c853517c2aad2506e6686e92430e34aaa059f7338c7fcd89df2e0bfL198), the use of `:=` creates a new `relabelled` variable in scope only of the `else` block. This means that even though we call `addToCache`, we will return `nil` from `relabel` method.
It likely means that relabel is not done correctly when we have a first cache miss.
It's not clear if this can lead to issues with caching yet (e.g. memory leak), further testing is required.

Fix relabel bug

---

component/prometheus/relabel/relabel.go

Checking for a labelset to be nil is not always correct; an dropped metric from relabel will return a non-nil, but still empty labelset.

prometheus.relabel: do a more resilient empty label check

---

CHANGELOG.md
component/prometheus/relabel/relabel.go
component/prometheus/relabel/relabel_test.go
go.mod
go.sum

Instead of using an unbounded `map` for relabel caches instead use an LRU of 100_000 items. Currently its not configurable but likely to become so once we sort out good defaults and performance.

Switch to using capped LRU cache instead of raw map.

---

CHANGELOG.md
component/prometheus/interceptor.go
component/prometheus/relabel/relabel.go

This PR renames the histogram hook to be aligned with the other ones and ties it in to the prometheus.relabel component.

prometheus.relabel: allow relabeling of prometheus native histograms

---

component/discovery/azure/azure.go
component/discovery/consul/consul.go
component/discovery/digitalocean/digitalocean.go
component/discovery/dns/dns.go
component/discovery/docker/docker.go
component/discovery/gce/gce.go
component/discovery/kubernetes/kubernetes.go
component/loki/source/api/api.go
component/loki/source/api/api_test.go
component/loki/source/gelf/gelf.go
component/loki/source/journal/journal.go
component/loki/source/journal/journal_stub.go
component/mimir/rules/kubernetes/rules.go
component/otelcol/receiver/loki/loki.go
component/otelcol/receiver/prometheus/prometheus.go
component/prometheus/receive_http/receive_http.go
component/prometheus/receive_http/receive_http_test.go
component/prometheus/remotewrite/remote_write.go
component/pyroscope/write/write.go
component/pyroscope/write/write_test.go
component/remote/s3/s3.go

This PR shouldn't have any user-facing changes. It goes through the code for various components and a) standardizes the struct and builder names, b) makes sure the components builders return a struct as per Go's "Accept interfaces, return structs" idiom.

all: make component builders return the concrete structs

---

operations/helm/charts/grafana-agent/CHANGELOG.md
operations/helm/charts/grafana-agent/README.md
operations/helm/charts/grafana-agent/README.md.gotmpl
operations/helm/charts/grafana-agent/ci/create-deployment-autoscaling-values.yaml
operations/helm/charts/grafana-agent/ci/create-statefulset-autoscaling-values.yaml
operations/helm/charts/grafana-agent/templates/hpa.yaml
operations/helm/tests/create-deployment-autoscaling/grafana-agent/templates/controllers/deployment.yaml
operations/helm/tests/create-statefulset-autoscaling/grafana-agent/templates/controllers/statefulset.yaml

This PR amends the Helm chart to fail when trying to use autoscaling without having the resources key set for both the agent and configReloader containers.
I'm on the fence whether the added complexity is worth it from a Helm-conventions perspective, let me know what you think. If these were not set, the HPA would be created, but will have no effect.
* This will require amending if/when we allow the HPA to act on custom metrics instead of CPU/Memory utilization
* This started out with the generic verification that the `resources.request` field just exists; the last commit adds specific validations for when the user has chosen cpu/memory-utilization based autoscaling. Let me know if you think it's too much and I can revert back to the previous solution. 
* We have to check …

helm: make resources required for autoscaling

---

CHANGELOG.md
component/otelcol/exporter/prometheus/internal/convert/convert.go
component/otelcol/exporter/prometheus/internal/convert/convert_test.go

This PR attempts to fix the problem with non-cumulative histograms exported to Prometheus, from the otel metrics collector. The code change follows the approach taken by the opentelemetry-prometheus-exporter as shown here:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusexporter/collector.go#LL224C76-L224C76
Given a number of histogram buckets, we first sort the buckets by the bucket bounds value, then we calculate the cumulative value for each bucket, instead of using the exact bucket count provided by OTel. 
Fixes #4193
I'd appreciate any feedback on where to add tests for this issue.

otelcol.exporter.prometheus: Make histogram counts cumulative for Prometheus

---

CHANGELOG.md
component/otelcol/exporter/otlphttp/otlphttp.go

Fix bug where `otelcol.exporter.otlphttp` ignores configuration for TracesEndpoint/ MetricsEndpoint/ LogsEndpoint
Fixes [#4206](https://github.com/grafana/agent/issues/4210)

Fix bug where otelcol.exporter.otlphttp ignores configuration for TracesEndpoint/ MetricsEndpoint/ LogsEndpoint

---

docs/sources/flow/reference/cli/fmt.md

Fixes the binary name for the command to format river files.

[Docs] Replace 'agent fmt' with 'grafana-agent fmt'

---

go.mod
go.sum
pkg/integrations/blackbox_exporter/blackbox_exporter.go
pkg/integrations/v2/blackbox_exporter/blackbox.go

This PR includes the last changes of blackbox exporter, which has this [PR](https://github.com/prometheus/blackbox_exporter/pull/1060). Those changes are to prevent that some of the metrics of blackbox exporter where automatically added to global metrics registry even if the blackbox integration was not enabled.
Fixes #2627

Disable blackbox metrics when integration is not enabled

---

CHANGELOG.md
tools/release

@julienduchesne found that the `tools/release` script wasn't updated to call the new gpg-sign.sh paths after the Grafana Agent Flow package was introduced.
Related to #4268.

Fix release signing

---

CHANGELOG.md
packaging/grafana-agent-flow/rpm/gpg-sign.sh
packaging/grafana-agent/rpm/gpg-sign.sh

Sets gpg digest signing algo to sha256 to allow rpm installation on FIPS enabled OS'es
Fixes #4267

Use sha256 for rpm signing to allow installation on fips-enabed systems

---

go.mod
go.sum

This PR updates the version of our grafana/ckit dependency to enable the API endpoint that the clustering UI page needs to use.

Update grafana/ckit version

---

CHANGELOG.md
cmd/internal/flowmode/cmd_run.go
pkg/flow/module.go
web/api/api.go
web/ui/src/Router.tsx
web/ui/src/features/clustering/PeerList.module.css
web/ui/src/features/clustering/PeerList.tsx
web/ui/src/features/clustering/Table.module.css
web/ui/src/features/clustering/Table.tsx
web/ui/src/features/clustering/types.ts
web/ui/src/features/layout/Navbar.tsx
web/ui/src/hooks/peerInfo.tsx
web/ui/src/pages/Clustering.tsx

This PR adds a first version of a Flow UI page that contains information around Agent Clustering.
* It introduces a new /api/v0/web/peers endpoint that is wired to call the Peers() method of the Flow controller's clusterer.
* It copies the Typescript/React `ComponentList` code and adds the hooks and types to populate with the API response
* It adds a new page under /clustering and adds it to the NavBar
One thing that I'd like to do here is to be able to expand the width of the "Node Name" column but so far I've had no luck 🤦 
Another thing that is potentially interesting is to show/hide the page from the NavBar and conditionally render it only when clustering is _enabled_ and we haven't fallen back to the localNode implementation. Do you think it's worth it?
Fixes #3483 
* It's my first …

clustering: add basic UI page for peer info

---

CHANGELOG.md
pkg/river/vm/op_binary.go
pkg/river/vm/op_binary_test.go

This change unwraps an OptionalSecret (when IsSecret is false) to a string for the purposes of binary operations. This allows OptionalSecret to be compared to strings and concatenated with strings, including with other OptionalSecret values.
This is a hack to fix the observable behavior, but the nature of the fix means that other issues may still occur in the future if there are ever more capsule types which support conversion to a non-capsule type. A longer-term fix is needed once we identify what type of conversions binary operations should do.
Fixes #4036.

river/vm: unwrap nonsesitive OptionalSecret before performing binary ops

---

converter/internal/prometheusconvert/testdata/azure.river
converter/internal/prometheusconvert/testdata/consul.river
converter/internal/prometheusconvert/testdata/digitalocean.river
converter/internal/prometheusconvert/testdata/discovery.river
converter/internal/prometheusconvert/testdata/discovery_relabel.river
converter/internal/prometheusconvert/testdata/dns.river
converter/internal/prometheusconvert/testdata/docker.river
converter/internal/prometheusconvert/testdata/ec2.river
converter/internal/prometheusconvert/testdata/gce.river
converter/internal/prometheusconvert/testdata/kubernetes.river
converter/internal/prometheusconvert/testdata/lightsail.river
converter/internal/prometheusconvert/testdata/metric_relabel.river
converter/internal/prometheusconvert/testdata/scrape.river
converter/internal/prometheusconvert/testdata/unsupported.river
pkg/river/token/builder/builder.go

The logic to check to see if an optional field matches its default takes precedence over the old logic.
This fixes an unreleased issue where converting fields like send_exemplars would never be emitted, because `true` was the default (so it was omitted) and `false` is a zero value (so it was omitted).
The changelog is not updated since this issue is only observable in main.

river/token/builder: don't always skip zero valued optional fields

---

CHANGELOG.md
example/docker-compose/grafana/dashboards/agent-operational.json
production/grafana-agent-mixin/debugging.libsonnet

When using dashboard mixin, on the "Agent Operational" dashboard, the `all` option for `pod` template expects that pods have `grafana-agent-.*` prefix. This is not always the case for every user. At the same time filtering pods in some way is useful, so this PR changes the regex to `.*agent.*`. 
Also gave some panels more descriptive names as I found some of them quite cryptic.

Fix static mode operational dash for agent-logs namespace

---

component/loki/source/windowsevent/component_test.go

My previous PR https://github.com/grafana/agent/pull/4303 caused one windows test to fail to build, but we don't run windows tests as a merge gate, so I missed this.
This should fix the compilation error.

Fix broken test on Windows

---

CHANGELOG.md
cmd/internal/flowmode/cmd_run.go
docs/sources/flow/reference/cli/run.md
pkg/cluster/cluster.go

This PR allows users to configure the node name used for clustering with a command line flag. Since the empty node name defaults to the node's HOSTNAME, it made it difficult to test clustering on a single machine.
The list of clustering-based options has continued growing. This is the last new option I'm adding without some kind of structure to it. Once/if https://github.com/grafana/agent/issues/4253 is up, then we'll probably need to refactor the way we configure clustering either way.

clustering: allow setting the node's name with a CLI flag

---

docs/sources/static/configuration/agent-management.md
pkg/config/agentmanagement.go
pkg/config/agentmanagement_test.go
pkg/config/remote_config.go
pkg/config/testdata/example_password.txt

In order to add HTTP headers to the request, `FetchRemoteConfig` had to be changed to make raw HTTP requests, rather than using the code in the `remote_config` package. The behavior (in terms of metrics exposed and `Retry-After`) should be the same.
Other than that the primary change is here (and in the `RemoteConfiguration` struct to add the new fields):
```go
// Set headers for label management, if enabled
if r.InitialConfig.RemoteConfiguration.LabelManagementEnabled && r.InitialConfig.RemoteConfiguration.AgentID != "" {
req.Header.Add("X-LabelManagementEnabled", "1")
req.Header.Add("X-AgentID", r.InitialConfig.RemoteConfiguration.AgentID)
}
```
which adds the headers necessary for label management when (a) it is enabled in the config and (b) an `agent_id` was set.

[Agent Management] Add Label Management

---

component/component_provider.go
pkg/flow/flow.go
pkg/flow/flow_components.go
pkg/flow/internal/controller/component.go
pkg/flow/internal/controller/loader_test.go
pkg/flow/internal/controller/module.go
pkg/flow/module.go
pkg/flow/module_test.go

This allows clients to query for running modules. 
This introduces an internal API for module controllers for lower-level information, leaving the API exposed to components unchanged.
This is required as part of enabling the component.Provider API to be able to navigate through modules and have a global view of all running components.

component: include running module IDs in Info

---

CHANGELOG.md
component/loki/process/internal/stages/timestamp.go

time/tzdata needs to be imported to ensure all timezones are embedded into the binary. pkg/logs already imported this for the grafana-agent binary, but the grafana-agent-flow binary did not have it in its import path.
Related to #4337.

grafana-agent-flow: ensure time/tzdata is imported

---

pkg/flow/internal/controller/component_test.go

Sanitize the filepaths used in test assertions to always use `/` characters.
This fixes an issue introduced by tests added in #4310, where the new tests failed on Windows since the returned paths used the default Windows path separator `\` instead.

flow: sanitize tests when testing file paths

---

operations/helm/charts/grafana-agent/CHANGELOG.md
operations/helm/charts/grafana-agent/README.md
operations/helm/charts/grafana-agent/templates/containers/_watch.yaml
operations/helm/charts/grafana-agent/values.yaml

Users can now set the IDs of the configReloader container in addition to the grafana-agent.
I would like to run the configReloader container with non-root IDs in my cluster. Unfortunately I currently have no way to set these via the values. With my pullrequest it should be possible to set the IDs for the container optionally.

feat(configReloader): set securitycontext

---

component/prometheus/exporter/blackbox/blackbox.go
component/prometheus/exporter/snmp/snmp.go
docs/sources/flow/reference/components/prometheus.exporter.blackbox.md
docs/sources/flow/reference/components/prometheus.exporter.snmp.md

This PR changes inline `config` fields of blackbox and snmp exporter to be type `Secret`.
Fixes #4302

Use `rivertypes.OptionalSecret` for SNMP and Blackbox components inline config

---

operations/helm/charts/grafana-agent/CHANGELOG.md
operations/helm/charts/grafana-agent/README.md
operations/helm/charts/grafana-agent/ci/clustering-values.yaml
operations/helm/charts/grafana-agent/templates/cluster_service.yaml
operations/helm/charts/grafana-agent/templates/containers/_agent.yaml
operations/helm/charts/grafana-agent/templates/controllers/statefulset.yaml
operations/helm/charts/grafana-agent/values.yaml
operations/helm/tests/clustering/grafana-agent/templates/cluster_service.yaml
operations/helm/tests/clustering/grafana-agent/templates/configmap.yaml
operations/helm/tests/clustering/grafana-agent/templates/controllers/deployment.yaml
operations/helm/tests/clustering/grafana-agent/templates/controllers/statefulset.yaml
operations/helm/tests/clustering/grafana-agent/templates/rbac.yaml
operations/helm/tests/clustering/grafana-agent/templates/service.yaml
operations/helm/tests/clustering/grafana-agent/templates/serviceaccount.yaml

This adds a new value, `agent.clustering.enabled`, to automatically configure clustering with the appropriate service and flags. 
This makes it easier to deploy clustering by having a dedicated service for clustering, compared to the current approach of disabling the existing service, and then switching it to a headless service. 
Because clustering only discovers peers once on startup, and because StatefulSet is the only controller which can roll out one pod at a time, controller.type=statefulset is required to use clustering. A long-term solution would be to periodically rediscover peers, which would allow other controller types to be used correctly.

helm: add native support for clustering with agent.clustering.enabled value

---

docs/sources/flow/reference/components/module.http.md

The example of usage of `module.http` refers wrongly to `polling_interval`.
Changing to `poll_frequency`.

Fix argument name in `module.http` example

---

cmd/internal/flowmode/cmd_run.go
pkg/cluster/cluster.go
pkg/cluster/gossip.go

This PR ensures that cluster nodes shutting down transition to the StateTerminating before leaving the memberlist, so that they're no longer considered owners for write hash operations.
We introduce a new context here, because when in order to call Stop() on the deferred function, it would mean that the context from `interruptContext` would already be cancelled.

cluster: transition to StateTerminating before leaving the cluster

---

CHANGELOG.md
cmd/grafana-agentctl/main.go
cmd/internal/flowmode/cmd_tools.go
cmd/internal/flowmode/flowmode.go
component/prometheus/remotewrite/cli.go
docs/sources/flow/reference/cli/tools.md
pkg/agentctl/waltools/cardinality.go
pkg/agentctl/waltools/cardinality_test.go
pkg/agentctl/waltools/samples.go
pkg/agentctl/waltools/wal_iterator.go
pkg/agentctl/waltools/walstats.go
pkg/agentctl/waltools/walstats_test.go

This commit adds a new subcommand to Flow, `tools`, which contains a bunch of per-component command line utilities. Each component has its own subcommand within `tools`.
The first of these commands is for prometheus.remote_write, where the old tooling from agentctl has been ported as:
* `grafana-agent tools prometheus.remote_write sample-stats`
* `grafana-agent tools prometheus.remote_write target-stats`
* `grafana-agent tools prometheus.remote_write wal-stats`
The command names are quite long, but I appreciate how they're namespaced per-component to avoid long-term confusion as we gradually add more of these. 
Closes grafana/agent#2708.

cmd/grafana-agent-flow: add agentctl tools

---

docs/sources/_index.md

The link to Flow mode in the landing page of the docs is currently broken:

docs: fix link to Flow mode in admonition banner

---

tools/release-note.md

The link to the Flow installation docs in the release notes is broken. I also fixed the static mode link to point to the actual installation page.

Fix broken link in release notes

---

CHANGELOG.md
component/all/all.go
component/local/file_match/file.go
component/local/file_match/file_test.go
component/local/file_match/watch.go
docs/sources/flow/reference/components/local.file_match.md
docs/sources/flow/reference/components/loki.echo.md
docs/sources/flow/reference/components/loki.source.file.md
docs/sources/flow/upgrade-guide.md

This commit renames discovery.file to local.file_match so that:
* The purpose of the component is more clear (i.e., to find files on the local filesystem which match a given pattern).
* To remove a point of confusion where `discovery.file` was thought to be Prometheus' file SD.
* To allow a component for Prometheus' file SD to be named discovery.file, which otherwise would've collided with the now-named local.file_match.
A redirect from the old documentation page is explicitly not configured because we anticipate creating a new page called discovery.file, which will have a warning about the rename.
Related to #3607.

breaking change: rename discovery.file to local.file_match

---

CHANGELOG.md
component/all/all.go
component/otelcol/config_grpc.go
component/otelcol/config_tls.go
component/otelcol/exporter/loadbalancing/loadbalancing.go
component/otelcol/exporter/loadbalancing/loadbalancing_test.go
docs/sources/flow/reference/components/otelcol.exporter.loadbalancing.md
go.sum

This PR is mostly done, with the exception of the items listed in the "notes to the Reviewer" section. 
For now the main thing I'd appreciate feedback on is the `endpoint` attribute in the client block. Could we make it mandatory for all components except this, without copying the whole struct? And would you prefer copying the struct to making it an optional argument, as is done in this PR?
Having it as an optional argument is more in line with the Collector, but I fear that it goes too much agains the Agent way of doing things. It's a "three steps back and one step forward" type situation :)
#4068
There are a few controversial things that I'm not sure about:
* The `endpoint` attribute in the gRPC client block used to be mandatory and I changed it to optional. I couldn't think of a clean …

Add a otelcol.exporter.loadbalancing component

---

component/remote/vault/vault_test.go
pkg/operator/build_hierarchy_test.go
pkg/operator/hierarchy/hierarchy_test.go
pkg/operator/kubelet_test.go
pkg/operator/operator_test.go

There is a bug in testcontainers (via docker client) that breaks those things in go 1.20.6.
Skipping for now. Watch https://github.com/testcontainers/testcontainers-go/issues/1359 for updates.

Skip some tests broken by go 1.20.6 Host changes

---

docs/sources/operator/deploy-agent-operator-resources.md

Oauth2 is mentioned as supported in Operator `remotewrite`. This is incorrect and needs to be removed from the documentation. Oauth2 is supported in static and flow mode `remote_write`, but not in operator.
Reference https://github.com/grafana/agent/pull/2654 that added the information

Remove oauth2 agent config from example in Operator docs

---

CHANGELOG.md
component/otelcol/auth/bearer/bearer.go
component/otelcol/auth/headers/headers.go
component/otelcol/auth/headers/headers_test.go
component/otelcol/processor/batch/batch.go
component/otelcol/processor/batch/batch_test.go
component/otelcol/processor/tail_sampling/tail_sampling.go
component/otelcol/processor/tail_sampling/tail_sampling_test.go
component/otelcol/processor/tail_sampling/types.go
component/otelcol/receiver/jaeger/jaeger.go
component/otelcol/receiver/kafka/kafka.go
docs/sources/flow/reference/components/otelcol.auth.basic.md
docs/sources/flow/reference/components/otelcol.auth.bearer.md
docs/sources/flow/reference/components/otelcol.auth.headers.md
docs/sources/flow/reference/components/otelcol.exporter.jaeger.md
docs/sources/flow/reference/components/otelcol.processor.batch.md
docs/sources/flow/reference/components/otelcol.processor.tail_sampling.md
docs/sources/flow/reference/components/otelcol.receiver.kafka.md
docs/sources/flow/upgrade-guide.md
docs/sources/static/upgrade-guide.md
go.mod
go.sum
pkg/traces/instance.go
pkg/traces/internal/traceutils/otel_meter_settings.go

#3858 updated to version 0.80 of Otel Collector, but some work was still yet to be done. This PR completes the Otel upgrade by doing the following:
* Updates our components to use the latest features of Collector's components
* Disables Otel Collector "process" metrics
* Uses version `v1.0.0-rcv0013` of pdata and featuregate modules instead of the ones from the fork.
This PR completes the upgrade to version 0.80 of the Collector. No more work is expected to be needed.

Cleanup after the Otel upgrade

---

docs/sources/flow/reference/components/loki.relabel.md
docs/sources/shared/flow/reference/components/rule-block-logs.md

`loki.relabel` cannot share he same rule block documentation fragment as `prometheus.relabel`. Create a new rule block for logs and replace link to the old rule block with new.
Fixes #4329

Update loki.relabel to logs instead of metrics

---

operations/agent-flow-mixin/alerts/clustering.libsonnet

Single-node clusters have no external peers to communicate with, so their lamport times won't increase.

agent-flow-mixin: do not fire ClusterLamportClockStuck for single-node clusters

---

CHANGELOG.md
docs/sources/flow/upgrade-guide.md

I added this deprecation recently, but didn't know it needs to be under a "deprecation" section and listed in the upgrade guide.
The exporter is due to be deleted from the Collector in July 2023, so I think v0.38.0 is ok as a target version for removal.

Clarify otelcol.exporter.jaeger deprecation

---

CHANGELOG.md
component/module/http/http.go
component/remote/http/http.go

Previously, the health of the component was only set on background polls, which caused the health of the component to be listed as "Unknown" until a background poll occured.
In cases where the polling interval is extremely infrequent, the component appeared to be permanently in state "Unknown."
Closes #4451.

remote.http: set health after poll on Update

---

go.mod
go.sum

There were two places which performed bpf syscalls: rlimit package and btf package.
The btf problem was fixed in v11 library, so just update it.
The rlimit package executes bpf calls on purpose, so we copy the cilium/ebpf/rlimit package and do the init lazy later, see the pyroscope PR for more details
https://github.com/grafana/phlare/pull/859
Agent executes bpf syscalls during package init
https://raintank-corp.slack.com/archives/CSN5HV0CQ/p1689263967983789

fix(ebpf): no syscalls during package init

---

CHANGELOG.md
component/pyroscope/scrape/scrape.go
docs/sources/flow/reference/components/pyroscope.scrape.md
go.mod
go.sum
pkg/server/server.go

This PR introduces `godeltaprof_memory`, `godeltaprof_mutex`, `godeltaprof_block` from [godeltaprof](https://github.com/grafana/godeltaprof)  package.
Currently we have two options to compute delta profiles: in pyroscope server, and in agent before sending to the pyroscope server. 
This PR adds another option to compute the delta on the scraped service itself.
Usually it  consumes less cpu and produce smaller profile size.
In og pyroscope it was named `delta_heap`,  `delta_block`, `delta_mutex`, here I named it `godeltaprof_{...}` to be not confused with `delta` parameter of other profiling types. Maybe we could come up with a better name before we merge it.
Unfortunately

feat(pyroscope.scrape): add godeltaprof profiling types

---

CHANGELOG.md
production/tanka/grafana-agent/scraping-svc/syncer.libsonnet
production/tanka/grafana-agent/v2/internal/syncer.libsonnet

The `v1beta1` CronJob API has been removed in Kubernetes 1.25 and its
stable replacement in `v1` exists since Kubernetes 1.21, which is not
supported for a fairly long time anymore.
Signed-off-by: Milan Plzik <milan.plzik@grafana.com>

Update Grafana Agent to use v1 CronJob API.

---

CHANGELOG.md
component/prometheus/exporter/unix/config.go
docs/sources/flow/reference/components/prometheus.exporter.unix.md
docs/sources/static/configuration/integrations/node-exporter-config.md
pkg/integrations/node_exporter/config.go

Node exporter has added udev data to it's diskstats collector. It's possible to set up this path in node_exporter but right now we can't do the same in the grafana agent, so this PR just makes that available. Also, it appears that when node_exporter can't access the path it fails to create disk metrics. This has already been fixed in [prometheus operator](https://github.com/prometheus-operator/kube-prometheus/pull/1913) and in the [helm chart](https://github.com/prometheus-community/helm-charts/pull/2941).
It seems like it fixes https://github.com/grafana/agent/issues/4207
Fixes  #4517 
As far as I understand, no tests need to updated for this change. Please correct me if I'm wong.

[integrations] Add udev data path arg to node_exporter

---

operations/agent-flow-mixin/dashboards/utils/panel.jsonnet

In newer versions of Grafana, heatmap panels default to calculating the buckets based on the query. However, the heatmaps we're using in the dashboard have precalculated buckets.
This adds a `calculate: false` option so that the heatmaps display as expected.
Before:
After:

agent-flow-mixin: fix display of heatmaps

---

docs/sources/flow/reference/components/discovery.kubernetes.md

We've received a question regarding the selectors/role attribute - why wouldn't it always match the top-level role attribute. 
Turns out there is a use case for this as documented in prometheus docs - porting this explanation to our docs with this PR.
Also fixes some typos and a broken link.

Clarification and fixing typos in discovery.kubernetes.md

---

docs/sources/flow/reference/components/otelcol.processor.memory_limiter.md
docs/sources/flow/reference/components/otelcol.processor.tail_sampling.md
docs/sources/flow/reference/components/prometheus.exporter.apache.md
docs/sources/flow/reference/components/prometheus.exporter.consul.md
docs/sources/flow/reference/components/prometheus.exporter.mysql.md
docs/sources/flow/reference/components/prometheus.exporter.process.md

Zero width spaces in titles is a legacy workaround that's no longer needed. There are still a few titles in the Agent ref docs that contain zero width spaces. This PR removes them

Remove zero width spaces from reference titles

---

CHANGELOG.md
component/prometheus/operator/common/crdmanager.go
pkg/river/encoding/riverjson/riverjson.go
pkg/river/encoding/riverjson/riverjson_test.go

This commit fixes two issues:
* If the component failed to build and was unhealthy, a nil pointer panic would be generated when requesting debug info.
* An empty slice of discovered CRDs failed to be encoded as JSON in a way expected by the UI.
Fixes #4512.

prometheus.operator.*: fix UI issues

---

CHANGELOG.md
cmd/grafana-agentctl/Dockerfile
tools/make/packaging.mk

Add journald support into agentctl so `grafana-agentctl test-logs` functions properly when using a config which reads log entries from the systemd journal.
Fixes #4520.

agentctl: add journald support

---

operations/agent-flow-mixin/dashboards/utils/panel.jsonnet

The migration from `heatmap-new` to `heatmap` (in Grafana 10) seems to force the heatmap to calculate the heatmap buckets regardless of the setting of `calculate`. Changing the type to `heatmap` addresses this issue.
Related to #4527, which didn't fully fix the issue when migrating the dashboard to Grafana 10.

agent-flow-mixin: change heatmap type from `heatmap-new` to `heatmap`

---

operations/helm/charts/grafana-agent/CHANGELOG.md

The CHANGELOG for the Helm chart was missing an entry saying that the Grafana Agent version has been updated.
cc @mattdurham

helm: add missing CHANGELOG entry

---

pkg/flow/internal/controller/loader.go

Previously, a log line when graph node evaluation completes was only generated when a graph node was evaluated as part of a full walk (meaning when the config file was reloaded).
This change ensures that node evaluation always generates a log line, including for partial walks (meaning when a component updates its exports, causing downstream dependencies to reevaluate).

flow: always log when node evaluation completes

---

component/pyroscope/scrape/delta_profiles.go
component/pyroscope/scrape/delta_profiles_test.go
component/pyroscope/scrape/internal/fastdelta/fd_test.go
go.mod
go.sum

This improves allocations of the delta profiles appender.
Mostly it doesn't use `ioutil.ReadAll` but instead grows and reuses a buffer. I've also moved the buffer to a pool to avoid having those scale with the amount of targets.
Result on a very small profile.
```
❯ benchstat before.txt after.txt
name             old time/op    new time/op    delta
ComputeDelta-16    31.1µs ± 5%    31.1µs ± 3%     ~     (p=0.842 n=9+10)
name             old alloc/op   new alloc/op   delta
ComputeDelta-16      743B ± 0%      169B ± 8%  -77.22%  (p=0.000 n=10+10)
name             old allocs/op  new allocs/op  delta
ComputeDelta-16      3.00 ± 0%      1.00 ± 0%  -66.67%  (p=0.000 n=10+10)
```

Improve allocations of the delta profiles appender

---

component/all/all.go
component/otelcol/processor/attributes/attributes_test.go
component/otelcol/processor/processortest/processortest.go
component/otelcol/processor/span/span.go
component/otelcol/processor/span/span_test.go
docs/sources/flow/reference/components/otelcol.processor.attributes.md
docs/sources/flow/reference/components/otelcol.processor.span.md
docs/sources/shared/flow/reference/components/match-properties-block.md
docs/sources/shared/flow/reference/components/otelcol-filter-attribute-block.md
docs/sources/shared/flow/reference/components/otelcol-filter-library-block.md
docs/sources/shared/flow/reference/components/otelcol-filter-log-severity-block.md
docs/sources/shared/flow/reference/components/otelcol-filter-regexp-block.md
docs/sources/shared/flow/reference/components/otelcol-filter-resource-block.md
docs/sources/shared/flow/reference/components/output-block-traces.md
go.mod
go.sum

This is based on the upstream [span](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/spanprocessor) processor.
Fixes #2612

Add an otelcol.processor.span component

---

component/otelcol/exporter/jaeger/jaeger.go
component/otelcol/exporter/loadbalancing/loadbalancing.go
component/otelcol/exporter/loadbalancing/loadbalancing_test.go
component/otelcol/exporter/otlp/otlp.go
component/otelcol/extension/jaeger_remote_sampling/jaeger_remote_sampling.go
component/otelcol/extension/jaeger_remote_sampling/jaeger_remote_sampling_test.go
docs/sources/flow/reference/components/otelcol.exporter.jaeger.md
docs/sources/flow/reference/components/otelcol.exporter.loadbalancing.md
docs/sources/flow/reference/components/otelcol.exporter.otlp.md
docs/sources/flow/reference/components/otelcol.extension.jaeger_remote_sampling.md
docs/sources/shared/flow/reference/components/otelcol-grpc-balancer-name.md

`balancer_name` has a default value which is not listed in the tables in our docs.
This was noticed by @mattdurham in [another PR](https://github.com/grafana/agent/pull/4148#discussion_r1237634250).

Flow Otelcol: Document default values for gRPC client balancer_name

---

docs/sources/flow/upgrade-guide.md
docs/sources/static/upgrade-guide.md

I'd [updated](https://github.com/grafana/agent/pull/4359/files#diff-8f08accdca0d98a1c64aa36075f87267ebe91f6db19ca8074554e58667f73d2f) the upgrade guide with a new "Main (unreleased)" section similar to the one in the changelog, but apparently there was already a 0.35 section underneath which I hadn't noticed. This will PR will add the deprecation information in the right section.

Fix upgrade guide

---

CHANGELOG.md
pkg/integrations/v2/app_agent_receiver/payload.go
pkg/traces/automaticloggingprocessor/automaticloggingprocessor.go
pkg/traces/servicegraphprocessor/processor.go

This is a bug which was introduced in the Otel upgrade in #3858. I must have gotten confused about the [deprecation](https://github.com/open-telemetry/opentelemetry-collector/pull/6530) of the HexString function. Apologies for this - the bug could have been easily prevented if I'd taken more care reading the functions and the deprecation PR.
Fixes #4552
There are two other places which use such code, but I think they are not impacted from an external user point of view:
* The `SpanToKeyVal` function in `pkg/integrations/v2/app_agent_receiver/payload.go` appears to be unused.
* In the service graph processor as long as a unique ID is generated (which I think is the case), then the code should work, even if the ID is not the same hex ID.
I will mention the service graph in the changelog …

Fix incorrect display of trace IDs in the automatic_logging processor

---

CHANGELOG.md
cmd/internal/flowmode/cmd_run.go
docs/sources/flow/reference/cli/run.md
pkg/cluster/cluster.go

This PR adds a new `cluster.discover-peers` command-line flag, to enable discovering clustering peers using the [go-discover](https://github.com/hashicorp/go-discover) library based on a list of key-value tuples, depending on the used "provider" and the settings it allows for.
We support all the default providers, plus the extra `k8s` provider.
Fixes #3484

clustering: wire in go-discover for discovering peers

---

CHANGELOG.md
component/all/all.go
component/discovery/uyuni/uyuni.go
component/discovery/uyuni/uyuni_test.go
docs/sources/flow/reference/components/discovery.uyuni.md

Adds the `discovery.uyuni` component for discovering scrape targets from a Uyuni Server.
Fixes #2283

[Flow] Add discovery.uyuni component

---

docs/sources/flow/setup/install/binary.md
docs/sources/flow/setup/install/macos.md

This PR corrects the filename in the Agent standalone binary install topic.
* Change `grafana-agent-flow` to `grafana-agent` in step 3 of the download procedure.

Correct file name in the Agent standalone install and macOS install

---

CHANGELOG.md

This PR removes the bugfix which goes into v0.35.1 from the "main" section and adds it to the "v0.35.1" section.

Add v0.35.1 to changelog

---

operations/helm/charts/grafana-agent/CHANGELOG.md

#4592 didn't update the Helm chart's changelog.

helm: update changelog for 0.18.0 release

---

CODEOWNERS

Have @grafana/grafana-agent-profiling-maintainers be the maintainers of component/pyroscope.

CODEOWNERS: change codeownership of component/pyroscope

---

CHANGELOG.md
docs/sources/flow/reference/config-blocks/logging.md
pkg/flow/logging/logger.go
pkg/flow/logging/options.go

This is a rehash of #3566 to add a new `write_to` argument to the special logging configuration block, to tee the Agent's own logs to one or more loki.* components' exported receivers.
Fixes #2700
I'll look into whether I can add some test for this.

flow: Add 'write_to' argument to logging block

---

CHANGELOG.md
pkg/metrics/wal/wal.go
pkg/metrics/wal/wal_test.go

If a new series is introduced in a storage.Appender instance, that series should be written to the WAL once the storage.Appender is closed, even on Rollback.
Previously, new series would only be written to the WAL when calling Commit. However, because the series is stored in memory regardless, subsequent calls to Commit may write samples to the WAL which reference a series ID which that was never written.
Port of prometheus/prometheus#12592

pkg/metrics/wal: always write series records to WAL, even on rollback

---

CHANGELOG.md
packaging/grafana-agent-flow/rpm/gpg-sign.sh
packaging/grafana-agent/rpm/gpg-sign.sh

This is wholly a copy of https://github.com/grafana/agent/pull/4611/files so we can get it into a patch asap.

Fix issue with fips on behalf of @andrewimeson

---

operations/agent-flow-mixin/dashboards/prometheus.remote_write.libsonnet

To be compatible with kube-prometheus, filenames must be valid for ConfigMaps, containing only alphanumerics, hyphens (`-`), and periods (`.`).
This means that the underscore character used by the component name is not valid for the filename.
Fixes #4633.

agent-flow-mixin: change filename to be compatible with ConfigMaps

---

CHANGELOG.md
cmd/grafana-agent/Dockerfile
cmd/grafana-agent/Dockerfile.windows
tools/make/packaging.mk

This uses the code by @bboreham to lower overall memory consumption for Prometheus-based metric pipelines.
This change impacts both static and Flow mode.

build: build with stringlabels to reduce memory footprint of metrics

---

CHANGELOG.md
cmd/grafana-agentctl/main.go

Hello, I would like to add some validation steps in `grafana-agentctl config-check` cmd, like this:
```
$ grafana-agentctl config-check bad-config-values.yaml 
invalid metrics config: error validating instance test: scrape interval greater than wal_truncate_frequency for scrape config with job name "agent-3"
```
I'm using the `grafana-agentctl` cmd to check the config file validity before applying changes and restart the agent, so I would expect it fail at this step.

enhancement(agentctl): better validation of config file

---

cmd/grafana-agent/Dockerfile.windows

Don't use double quotes for the GO_TAGS environment variable, since double quotes are already being used for the bash command.
Follow up on #4641 which broke the images.

docker: fix Windows images

---

CHANGELOG.md
cmd/internal/flowmode/cmd_run.go
pkg/cluster/cluster.go

This commit enables delaying the transition of the GossipNode to Participant state to after the graph has been completely evaluated at least once. This guards against missing scrapes when other peers think we're ready to participate to distributing load, but we're still loading all our components.
Fixes #4639.
A more straighforward solution would be to move the [Start call](https://github.com/grafana/agent/pull/4647/files#diff-a5071380b513bfb7750c3b1d67b1f7b9e34fcd4e86d24c0ac19df8b9dddc6900R267) in  `cmd/internal/flowmode/cmd_run.go` to after the block performing the initial reload. 
On one hand, this would be simpler/synchronous but on the other hand would add another unnecessary waiting time to bootstrap a new cluster, especially if it's a large one. Since we don't have #4464 in place …

clustering: wait for graph evaluation before changing to Participant state

---

CHANGELOG.md
Makefile
cmd/grafana-agent-operator/Dockerfile
cmd/grafana-agent/Dockerfile
cmd/grafana-agentctl/Dockerfile
tools/make/packaging.mk

Go 1.19 adds Windows support for the native Go network stack, but doesn't include support for resolving DNS short names.
Other projects, including Prometheus, have updated their build process to exclude the netgo build tags when producing Windows binaries to work around this behavior.
Fixes grafana/agent#4665

build: do not produce Windows binaries with netgo build tags

---

CHANGELOG.md
component/loki/source/file/file.go
component/loki/source/file/file_test.go
docs/sources/flow/reference/components/loki.source.file.md

loki.source.file: allow defining the encoding of read files

---

CHANGELOG.md
cmd/internal/flowmode/cmd_run.go

The signal is natively implemented in Linux and macOS.
On Windows, _CTRL_SHUTDOWN_EVENT which is used on Windows Kubernetes to signal graceful termination is [mapped](https://github.com/golang/go/blob/5f2e24efb3c7e021308d15a26d93e5a7aa3c05f0/src/runtime/os_windows.go#L1105-L1112) to SIGTERM internally so it should work in the same way.
Fixes #4684
The SIGKILL signal is used as a backup when the graceful termination period is over. Do we think we should have some extra handling around this?
Also, I find it weird this hasn't caused any other problems recently. Is it possible I'm missing any context or that this was done on purpose?

flow: fix graceful termination on kubernetes

---

component/registry.go
pkg/flow/flow.go
pkg/flow/flow_services_test.go
pkg/flow/internal/controller/loader.go
pkg/flow/internal/controller/node_component.go
pkg/flow/internal/testcomponents/service_consumer.go
pkg/flow/internal/testservices/hook.go

> **NOTE**: I recommend reviewing this PR commit-by-commit.
This change allows components to declare a dependency on a service and access data for services for which a dependency has been declared. This follows up on #4664, which initially introduced the concept of services into the Flow controller.
Related to #4253.
A follow up PR will be opened to complete the services implementation: allow components in modules to have access to services.

component: allow components to consume data for services 

---

pkg/integrations/v2/app_agent_receiver/app_agent_receiver.go
pkg/integrations/v2/app_agent_receiver/handler.go
pkg/integrations/v2/app_agent_receiver/handler_test.go
pkg/integrations/v2/app_agent_receiver/logs_exporter.go
pkg/integrations/v2/app_agent_receiver/receiver_metrics_exporter.go
pkg/integrations/v2/app_agent_receiver/traces_exporter.go

This will enable external integration of the AppAgent with custom-built exporters
While integrating the AppAgent into an existing Go codebase, I was blocked by the fact that the interface used to implement exporters was not exported. I feel like this is a safe change and that potentially breaking change handling is the responsibility of the integrator and not the project.
N/A
I was discussing this in [Slack](https://grafana.slack.com/archives/C01050C3D8F/p1690969732012899) and felt like it was an acceptable contribution 😄

Export AppAgentReceiverExporter interface

---

pkg/flow/flow_services.go
pkg/flow/flow_services_test.go
pkg/flow/module_registry.go
service/service.go

GetServiceConsumers will be used by services to quickly retrieve a list of components and services which depend on a service for service-related operations.
For example, the clustering service will use GetServiceConsumers to know which components to notify of a cluster update.
GetServiceConsumers needs to return dependant components throughout all modules, otherwise the clustering service will be unable to notify all appropriate components when the clustering state changes.

flow: fix bug where GetServiceConsumers didn't search through loaded modules

---

CHANGELOG.md
component/loki/source/file/compression_format.go
component/loki/source/file/decompresser.go
component/loki/source/file/decompresser_test.go
component/loki/source/file/file.go
converter/internal/promtailconvert/internal/build/scrape_builder.go
converter/internal/promtailconvert/testdata/static_pipeline_example.river
converter/internal/promtailconvert/testdata/static_pipeline_example.yaml
converter/internal/promtailconvert/testdata/unsupported.diags
converter/internal/promtailconvert/testdata/unsupported.yaml
docs/sources/flow/reference/components/loki.source.file.md
docs/sources/flow/upgrade-guide.md

This adds a decompression support in `loki.source.file` that matches the current behaviour of `promtail`.
It is a breaking change, since it was also a breaking change in `promtail`.
Fixes #4669 
The PR that made equivalent change in promtail is this: https://github.com/grafana/loki/pull/8994
Tested this locally using `gzip`:
```
➜  /tmp echo hello_zip > foo.txt
➜  /tmp gzip foo.txt
```
Used the following River config
```
local.file_match "logs" {
path_targets = [
{__path__ = "/tmp/*.gz"},
]
}
loki.source.file "tmpfiles" {
targets    = local.file_match.logs.targets
forward_to = [loki.echo.print.receiver]
decompression {
enabled       = true
initial_delay = "10s"
format        = "gz"
}
}
loki.echo "print" {}
```
Observed these logs:
```
ts=2023-08-03T12:40:36.611169Z level=info …
```

Porting decompression support from promtail to loki.source.file

---

CHANGELOG.md
component/common/loki/wal/writer.go

Small PR that adds a new metric that tacks the last reclaimed segment on the logs WAL.

Add last reclaimed segment metric to logs WAL

---

.drone/drone.yml
.drone/pipelines/publish.jsonnet
.drone/util/secrets.jsonnet

Use updater which has override rights instead of agent github app.

Use updater app instead of github agent app for merging into dev 

---

docs/sources/static/set-up/install/install-agent-linux.md

Some copy paste errors have slipped into the static docs while the content was being aligned between flow and static. This PR fixes the copy paste errors.

Remove copy paste error - static install on Linux uses flow in some places

---

CHANGELOG.md
component/loki/source/cloudflare/cloudflare.go
component/loki/source/cloudflare/internal/cloudflaretarget/fields.go
component/loki/source/cloudflare/internal/cloudflaretarget/fields_test.go
component/loki/source/cloudflare/internal/cloudflaretarget/target.go
docs/sources/flow/reference/components/loki.source.cloudflare.md

Add the property `custom_fields` and the type "custom" to the property `fields_type` to allow the user to define its own field for the loki.source.cloudflare. 
In the case where the `fields_type` is set to "all", then the `custom_fields` is expected to be empty or not set.
In the case where the `fields_type` is set to something else than "all" or "custom", the `custom_fields` will be merged with the one provided by the `fields_type` and the duplicates (if any) will be removed.
Fixes #4760

Add configurable fields loki source cloudflare

---

CHANGELOG.md
pkg/metrics/wal/wal.go
pkg/metrics/wal/wal_test.go

This PR fixes a sneaky bug that makes WAL loading more brittle in cases of corruption.
I saw this initially when the Agent was crashlooping on building the component with a message like:
```
Failed to build component: building component: read records: %!w(<nil>)
```
The underlying issue is that we're returning a new `errors.(*errorString)` but we're never wrapping the original `r.Err()` of type `*wlog.CorruptionErr`.
When the return value of loadWAL bubbles up to wal.NewStorage, it never has the chance of being detected as the correct error type to avoid failure to build the storage.
https://github.com/grafana/agent/blob/dc3cdde444ad605c68a0728edcb0a926e04ba50c/pkg/metrics/wal/wal.go#L179-L185
I also noticed that the agent would crashloop in case a segment was missing. If …

wal: fix detection of corruption errors

---

pkg/metrics/wal/wal_test.go

In the last PR, we didn't handle closing of the WAL, which lead to failing tests on Windows.

fix flaky wal_test.go for windows

---

docs/sources/flow/release-notes.md
docs/sources/operator/release-notes.md
docs/sources/static/release-notes.md

This PR updates the current Upgrade guide metadata and introductory text to Release notes.  
The current content is not upgrade information (answering the question "how do I get from release x to release y?", it is just a list of deprecations and breaking changes.
This frees up the "upgrade guide" for actual upgrade and migration step which are currently missing outside of some information buried in the Getting started section.
This also aligns with the overall Grafana doc architecture

Update Upgrade Guide metadata and text and convert to Release notes

---

CHANGELOG.md
packaging/grafana-agent-flow/rpm/gpg-sign.sh
packaging/grafana-agent/rpm/gpg-sign.sh
tools/make/packaging.mk

Tested both flow and nonflow rpms on both fips and non fips versions of Fedora
Fixes #4419
- [NA] Config converters updated

Sign rpms with sha256

---

component/component.go
component/prometheus/operator/common/component.go
component/prometheus/scrape/scrape.go
component/pyroscope/scrape/scrape.go
pkg/flow/internal/controller/loader.go
pkg/flow/internal/controller/node_component.go

Previously, components would opt in to clustering notifications through a call to ClusterUpdatesRegistration. Then, if that method returned true, they would be re-evaluated.
In preparation for the move to services, the clustering service would not be able to function the same way, as services are not permitted to trigger a re-evaluation of a component.
The new interface is a NotifyClusterChange method, which allows components to opt-in to whether they want to ignore that signal or not.
This is not reflected in the CHANGELOG as it is a no-op for users.

flow: change clustering interface to be a call to NotifyClusterChange

---

CHANGELOG.md
docs/sources/flow/reference/components/loki.source.file.md

Fixes #3954
Clarify that `loki.source.file` doesn't handle discovery, and link to the example in the docs that shows usage with the correct component.

clarify loki source file doesn't handle discovery

---

CHANGELOG.md
component/otelcol/exporter/prometheus/prometheus.go
docs/sources/flow/reference/components/otelcol.exporter.prometheus.md

The collector doesn't implement this yet and the metrics are not very useful.
See: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24248

otel/prometheus_exporter: disable otel_scope_info by default

---

CHANGELOG.md
component/prometheus/operator/configgen/config_gen_podmonitor.go
component/prometheus/operator/configgen/config_gen_podmonitor_test.go
component/prometheus/operator/configgen/config_gen_servicemonitor.go
component/prometheus/operator/configgen/config_gen_servicemonitor_test.go

If you didn't define a port at all in your CRD, this would panic. That is not good.

prometheus.operator.*: fix panic when port not defined in CRD

---

CHANGELOG.md
cmd/internal/flowmode/cmd_run.go
docs/sources/flow/reference/cli/run.md
go.mod
go.sum
pkg/cluster/cluster.go
pkg/cluster/gossip.go
pkg/cluster/gossip_test.go

This PR enables clustering to periodically refresh its list of peers found through one of `--cluster.join-addresses` or `--cluster.discover-peers` and attempt to re-join them using memberlist's Start.
This re-discovery is run by default every 60s, and is configurable via `--cluster.rejoin-interval`.
This allows for a more robust clustering implementation, where a temporary split brain at startup is not fatal, requiring _another_ node to coordinate the cluster.
To do this, the PR
* Decouples `JoinPeers` from its previous triple role (storing hardcoded addresses, used to populate the return of `go-discover` output and being passed to Start. Now JoinPeers is only
* Honors GossipConfig's behavior of not changing during runtime
* Extracts the logic of peer discovery into a new GetPeers method …

clustering: enable refreshing the list of peers on an interval

---

.github/workflows/bump-formula-pr.yml

This changes the action which creates a Homebrew formula PR to only run under the following conditions:
* A new release is published on GitHub
* The new release was set to be the latest release
Whether the release was previously a draft does not impact this action.
This was driven by feedback from the Homebrew maintainers, where they won't merge an update to a Homebrew formula unless the release was actually published. If they see the PR before Grafana Agent maintainers publish the release, then it's put in a backlog and merged later than we would normally want. The suggestion was that our automation should only open the PR once the release is actually published.
This was tested in a private repo with the following action:
```yaml
name: New release available
on:
release:
types: [released] …
```

ci: only create Homebrew formula PRs when a release is published

---

go.mod
go.sum

Update pyroscope/ebpf dependency
Includes fixes improving memory consumption:
https://github.com/grafana/pyroscope/pull/2248
https://github.com/grafana/pyroscope/pull/2255
https://github.com/grafana/pyroscope/pull/2246
https://github.com/grafana/pyroscope/pull/2245

chore(pyroscope-ebpf):  improve memory consumption

---

component/prometheus/operator/common/component.go
component/prometheus/operator/types.go
component/prometheus/operator/types_test.go

We previously had to discriminate between "argument" updates and "clustering" updates. Now that the notification mechanism for clustering is changed, this gets a bit simpler.
I don't think this needs a changelog.

prometheus.operator.*, simplify cluster update logic.

---

docs/sources/flow/reference/components/prometheus.exporter.apache.md
docs/sources/flow/reference/components/prometheus.exporter.blackbox.md
docs/sources/flow/reference/components/prometheus.exporter.cloudwatch.md
docs/sources/flow/reference/components/prometheus.exporter.consul.md
docs/sources/flow/reference/components/prometheus.exporter.dnsmasq.md
docs/sources/flow/reference/components/prometheus.exporter.elasticsearch.md
docs/sources/flow/reference/components/prometheus.exporter.gcp.md
docs/sources/flow/reference/components/prometheus.exporter.github.md
docs/sources/flow/reference/components/prometheus.exporter.kafka.md
docs/sources/flow/reference/components/prometheus.exporter.memcached.md
docs/sources/flow/reference/components/prometheus.exporter.mongodb.md
docs/sources/flow/reference/components/prometheus.exporter.mssql.md
docs/sources/flow/reference/components/prometheus.exporter.mysql.md
docs/sources/flow/reference/components/prometheus.exporter.oracledb.md
docs/sources/flow/reference/components/prometheus.exporter.postgres.md
docs/sources/flow/reference/components/prometheus.exporter.process.md
docs/sources/flow/reference/components/prometheus.exporter.redis.md
docs/sources/flow/reference/components/prometheus.exporter.snmp.md
docs/sources/flow/reference/components/prometheus.exporter.snowflake.md
docs/sources/flow/reference/components/prometheus.exporter.squid.md
docs/sources/flow/reference/components/prometheus.exporter.statsd.md
docs/sources/flow/reference/components/prometheus.exporter.unix.md
docs/sources/flow/reference/components/prometheus.exporter.windows.md
docs/sources/shared/flow/reference/components/exporters-components-exports.md

A community member reported an issue with the following documentation snippet on exporters 
```
For example, the `targets` can either be passed to a `prometheus.relabel`
component to rewrite the metric's label set, or to a `prometheus.scrape`
component that collects the exposed metrics.
```
Targets should be passed to `discovery.relabel`  to rewrite the targets' label sets; any metric-level relabeling should be done _after_ prometheus.scrape.
Since this change was present in a lot of places, I also extracted it to a shared snippet in `docs/sources/shared/flow/reference/components/exporters-components-exports.md`.
The drawback is that the description of the targets field no longer explicitly mentions _which_ exporter it is, but is a more generic phrase. This could be fixed by …

docs: extract exporter Exports section to a shared snippet

---

docs/sources/flow/reference/components/prometheus.exporter.cloudwatch.md

After updating the cloudwatch exporter dependency, we have to also update its docs, otherwise `make docs` doesn't work.
```
$ cd $AGENT_REPO
$ cd /pkg/integrations/cloudwatch_exporter/docs
$ go run doc.go generate 
$ go run doc.go check $AGENT_REPO docs/sources/flow/reference/components/prometheus.exporter.cloudwatch.md
```

Update cloudwatch exporter docs

---

CHANGELOG.md
component/loki/source/docker/docker.go
component/loki/source/docker/internal/dockertarget/target.go
component/loki/source/docker/runner.go

This PR refactors the usage of labels on the `loki.source.docker` containers to reduce CPU usage by ~84% and memory usage by ~91% (`main` vs `fix`)
Fixes #4777
I've verified this by using our pyroscope components and checking the profiles on Grafana Cloud with a config like the following
```
pyroscope.scrape "local" {
targets    = [
{"__address__" = "localhost:12346", "service_name"="main"},
{"__address__" = "localhost:12347", "service_name"="fix"},
]
forward_to = [pyroscope.write.grafanacloud.receiver]
profiling_config {
profile.process_cpu {
enabled = true
}
}
}
pyroscope.write "grafanacloud" {
endpoint {
url = "<url>"
basic_auth {
username = "<user>"
password = "<pass>"
}
}
external_labels = {
"env" = "tpaschalis-comparison",
}
}
```

loki.source.docker: reduce labels-related resource usage

---

docs/sources/static/configuration/integrations/cloudwatch-exporter-config.md

In the last PR, I forgot to update the corresponding docs for static mode, leading to `make docs` still being broken.

docs: update static mode cloudwatch exporter docs

---

component/prometheus/operator/common/component.go

fix panic when prometheus.operator.* is not initialized for cluster updates

---

CHANGELOG.md
component/prometheus/remotewrite/types.go
converter/internal/prometheusconvert/testdata/azure.river
converter/internal/prometheusconvert/testdata/consul.river
converter/internal/prometheusconvert/testdata/digitalocean.river
converter/internal/prometheusconvert/testdata/discovery.river
converter/internal/prometheusconvert/testdata/discovery_relabel.river
converter/internal/prometheusconvert/testdata/dns.river
converter/internal/prometheusconvert/testdata/docker.river
converter/internal/prometheusconvert/testdata/ec2.river
converter/internal/prometheusconvert/testdata/file.river
converter/internal/prometheusconvert/testdata/gce.river
converter/internal/prometheusconvert/testdata/kubernetes.river
converter/internal/prometheusconvert/testdata/lightsail.river
converter/internal/prometheusconvert/testdata/metric_relabel.river
converter/internal/prometheusconvert/testdata/scrape.river
converter/internal/prometheusconvert/testdata/unsupported.river
converter/internal/staticconvert/testdata/integrations.river
converter/internal/staticconvert/testdata/prom_remote_write.river
converter/internal/staticconvert/testdata/prom_remote_write.yaml
converter/internal/staticconvert/testdata/prom_scrape.river
converter/internal/staticconvert/testdata/promtail_prom.river
converter/internal/staticconvert/testdata/sanitize.river
converter/internal/staticconvert/testdata/unsupported.river
docs/sources/flow/reference/components/prometheus.remote_write.md
docs/sources/flow/release-notes.md

Set retry_on_http_429 to true by default in the queue config block of prometheus.remote_write.
Fixes #4441

Set retry_on_http_429 to true by default prometheus.remote_write queue

---

.github/workflows/publish-documentation-next.yml
.github/workflows/publish-documentation-versioned.yml

The PR CI was already fixed in https://github.com/grafana/agent/pull/4814 but I neglected to update the CD pipelines.
Reviewers should be able to see that the publish build steps match the ones in PR CI again: https://github.com/grafana/agent/blob/main/.github/workflows/check_docs.yml#L9-L15

Fix the CI step blocking the CD pipeline to publish technical documentation

---

CHANGELOG.md
component/loki/write/types.go
converter/internal/promtailconvert/internal/build/loki_write.go
converter/internal/promtailconvert/testdata/loki_write.river
converter/internal/promtailconvert/testdata/loki_write.yaml
converter/internal/promtailconvert/testdata/unsupported.diags
docs/sources/flow/reference/components/loki.write.md

Add support for retry on http429 to loki write for static and flow mode. It was decided in the issue to go with the property RetryOnHTTP429 like in prometheus remote write rather than going for the DropRateLimitedBatches used in promtail.
Fixes #4335

Add support for retry on http429 to loki write

---

.github/workflows/check_docs.yml
docs/sources/flow/release-notes.md
docs/sources/static/_index.md
docs/sources/static/api/_index.md
docs/sources/static/configuration/_index.md
docs/sources/static/configuration/create-config-file.md
docs/sources/static/configuration/flags.md
docs/sources/static/configuration/metrics-config.md
docs/sources/static/configuration/scraping-service.md
docs/sources/static/configuration/traces-config.md
docs/sources/static/operation-guide/_index.md
docs/sources/static/release-notes.md
docs/sources/static/set-up/install/install-agent-binary.md
docs/sources/static/set-up/install/install-agent-docker.md
docs/sources/static/set-up/install/install-agent-linux.md
docs/sources/static/set-up/install/install-agent-macos.md
docs/sources/static/set-up/install/install-agent-on-windows.md
docs/sources/static/set-up/start-agent.md

* First pass at updating references
* Remove note admonition
* Adjust ref syntax
* Trying different syntax
* Restory syntax to documented style
* Ensure that Hugo knows the documentation is versioned
Allows interpoloation of the `<GRAFANA VERSION>` variable used in the `docs/reference` shortcode.
* Use more appropriate version variable
* Update cross references in setup
* Update install cross references
* Update cross refs in api and operations
* First pass at updating conf refs
* Fix remaining cross refs
* Convert to relative links for cloud
* Fix URL sytnax
---------
Co-authored-by: Jack Baldry <jack.baldry@grafana.com>
(cherry …

Update cross reference syntax in Agent static mode documentation (#4814)

---

docs/sources/operator/_index.md

This PR adds a note to the Agent Operator description stating taht Operator cannot collect traces
Fixes [#6066](https://github.com/grafana/support-escalations/issues/6066)

Add note about traces and fix note syntax

---

component/prometheus/remotewrite/remote_write.go

This comment was copied from `instance.go` where there's `getRemoteWriteTimestamp` function. We don't have in this file, so this PR updates the comment.

Fix comment in remote_write.go

---

CHANGELOG.md
component/all/all.go
component/otelcol/connector/connector.go
component/otelcol/connector/spanmetrics/spanmetrics.go
component/otelcol/connector/spanmetrics/spanmetrics_test.go
component/otelcol/connector/spanmetrics/types.go
docs/sources/flow/reference/components/otelcol.connector.spanmetrics.md
docs/sources/shared/flow/reference/components/output-block-metrics.md
go.mod
go.sum

This component adds an `otelcol.connector.spanmetrics` flow component, based on the Collector's, [spanmetrics connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.80.0/connector/spanmetricsconnector).
Fixes #2295
This PR is the first time we port a "connector" component:
* Only a `TracesToMetrics` connector is supported at the moment. I don't want to over-engineer the code before we have consensus on how to handle connectors in the Agent.
* If a component is configured to send non-traces data to `otelcol.connector.spanmetrics` there won't be an error message on startup. E.g. `logs = [otelcol.connector.spanmetrics.default.input]` won't generate an error message. I am not sure if there would be an error message later on, when logs/metrics are actually …

Add an otelcol.connector.spanmetrics component

---

docs/sources/flow/reference/components/otelcol.connector.spanmetrics.md

Apparently the component is labeled as "alpha" on the [OpenTelemetry docs](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/spanmetricsconnector), so it should be labeled as such in the Agent docs too.

Label spanmetrics connector as alpha

---

docs/sources/flow/reference/components/otelcol.processor.span.md

The span processor's stability is [labeled](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.80.0/processor/spanprocessor) as "alpha". Our docs should match that.

Update the otelcol.processor.span stability to alpha

---

cmd/internal/flowmode/cluster_builder.go
service/cluster/cluster.go

* Prevents a failure to start the agent with default config when the machine doesn't have eth0 or en0 interfaces.
* Does not register clustering metrics when clustering is not enabled
* Does not start the rejoining peers goroutine if clustering is not enabled, as it spams logs and uses resources
* Fixes the peers not printing in one log message
Before:
```
$ AGENT_MODE=flow ./grafana-agent-windows-amd64.exe run config.river
ts=2023-08-25T09:06:44.8303801Z level=info boringcryptoenabled=false
Error: determining advertise address: 2 errors occurred:
* interface "eth0": route ip+net: no such network interface
* interface "en0": route ip+net: no such network interface
```
After this change - tested different combinations of flags on Windows:
```
$ AGENT_MODE=flow …
```

Clustering: Fall back to localhost if default interfaces not found

---

CHANGELOG.md
docs/sources/operator/deploy-agent-operator-resources.md
docs/sources/operator/getting-started.md
docs/sources/static/configuration/integrations/node-exporter-config.md
docs/sources/static/configuration/integrations/process-exporter-config.md
docs/sources/static/set-up/install/install-agent-docker.md
pkg/operator/defaults.go
production/kubernetes/agent-bare.yaml
production/kubernetes/agent-loki.yaml
production/kubernetes/agent-traces.yaml
production/kubernetes/build/lib/version.libsonnet
production/kubernetes/build/templates/operator/main.jsonnet
production/kubernetes/install-bare.sh
production/operator/templates/agent-operator.yaml
production/tanka/grafana-agent/v1/main.libsonnet
production/tanka/grafana-agent/v2/internal/base.libsonnet
production/tanka/grafana-agent/v2/internal/syncer.libsonnet

Hopefully got this right this time:
* Targets `release-v0.36` branch
* Cherry pick the https://github.com/grafana/agent/pull/4937 
* Remove the `Main (unreleased)` section

Prepare release-v0.36 branch for v0.36.0-rc.0 release

---

build-image/Dockerfile
build-image/windows/Dockerfile

Upgrade the build-image to Go 1.21.

build-image: upgrade to Go 1.21

---

.drone/drone.yml
.drone/pipelines/publish.jsonnet

After verifying that the custom image works and allows releases to be published using a GitHub token, I'm bringing the change back to `main` to be available for future releases.

drone: include gcr registry credentials (#4962)

---

CHANGELOG.md
docs/sources/operator/deploy-agent-operator-resources.md
docs/sources/operator/getting-started.md
docs/sources/static/configuration/integrations/node-exporter-config.md
docs/sources/static/configuration/integrations/process-exporter-config.md
docs/sources/static/set-up/install/install-agent-docker.md
pkg/operator/defaults.go
production/kubernetes/agent-bare.yaml
production/kubernetes/agent-loki.yaml
production/kubernetes/agent-traces.yaml
production/kubernetes/build/lib/version.libsonnet
production/kubernetes/build/templates/operator/main.jsonnet
production/kubernetes/install-bare.sh
production/operator/templates/agent-operator.yaml
production/tanka/grafana-agent/v1/main.libsonnet
production/tanka/grafana-agent/v2/internal/base.libsonnet
production/tanka/grafana-agent/v2/internal/syncer.libsonnet

Update version references for v0.36.0-rc.3
We're skipping over rc.2 as the tag was used to verify that the drone pipeline changes were working properly prior to updating code references.

Update version string everywhere for v0.36.0-rc.3

---

operations/agent-flow-mixin/alerts/clustering.libsonnet

We've noticed the `ClusterLamportClockDrift` to be exceptionally sensitive with bigger cluster sizes; this makes sense given gossip's random nature, it's not hard for nodes to temporarily be more than 4 messages apart.
I propose that we gently scale the arbitrary threshold value that we chose to correlate with cluster size; this would still 
```
1 node    = 4 * 0   = 0
2 nodes   = 4 * 1.4 = 6
4 nodes   = 4 * 2   = 8
8 nodes   = 4 * 2.8 = 11.3
25 nodes  = 4 * 5   = 20
100 nodes = 4 * 10  = 40  
```
I've looked at some internal metrics and it looks like the scaled metric better correlates with instances where we _did_ have issues with the network communication of cluster nodes.

clustering: configure threshold for ClusterLamportClockDrift alert

---

docs/sources/flow/reference/components/prometheus.exporter.elasticsearch.md

`address` field for Elasticsearch component needs to have `http` as prefix, otherwise
doesn't work. This PR fixes the usage  example in the docs of the flow component.

Fix elasticsearch flow component usage example

---

docs/developer/release/README.md

The task of adding a link to grafana agent docs to OTEL docs (example: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26104/files) should be performed only when we release a stable version:
* RCs are not yet recommended to use in prod, so no need to update
* Patch releases don't add new OTEL components, so no need

Update otelcol release instructions in README.md

---

.github/workflows/stale.yml

This PR re-enables stale bot but without closing issues or PR marked
as stale. This would help us to identify if we have to follow up on issues or
PR and help contributors to follow up on opened issues or PR.

Re-enable stale bot (without closing issues or PRs)

---

converter/internal/common/common.go
converter/internal/promtailconvert/internal/build/scrape_builder.go
converter/internal/staticconvert/internal/build/blackbox_exporter.go
converter/internal/staticconvert/internal/build/snmp_exporter.go
converter/internal/staticconvert/staticconvert.go
go.mod
go.sum
pkg/flow/module.go

add more complete river identifier validation and sanitization

---

CHANGELOG.md

The change was added under v0.36 but the code itself was not part of v0.36.
This PR moves it to the right part in changelog.md

Fix changelog: enhancement added under the wrong version

---

CHANGELOG.md
pkg/integrations/v2/app_agent_receiver/logs_exporter_test.go
pkg/integrations/v2/app_agent_receiver/payload.go
pkg/integrations/v2/app_agent_receiver/payload_test.go
pkg/integrations/v2/app_agent_receiver/testdata/payload.json

In the Faro Web-SDK we added an option to provide additional contextual attributes to the measurements payload.
To enable this we need to update the agent as well.
Just for reference here are the PRs which make the needed changes to the Faro Receiver and the Faro Web-SDK.
* [PR Receiver](https://github.com/grafana/app-o11y-kwl-endpoint/pull/262)
* [PR Docs](https://github.com/grafana/website/pull/15059)

chore: add contextual attributes to faro measurement

---

CHANGELOG.md
packaging/grafana-agent-flow/windows/install_script.nsis
packaging/grafana-agent/windows/install_script.nsis

The current name is very long and its not best practice to put an entire description in the displayname. 
(For more info here: https://learn.microsoft.com/en-us/windows/win32/msi/uninstall-registry-key)
This is mainly annoying in automatic deployments as it causes people to have to list the full description in there.
- [ x ] CHANGELOG.md updated

Remove description from the Windows Program Display Name

---

docs/sources/flow/reference/components/discovery.docker.md
docs/sources/flow/reference/components/discovery.kubernetes.md
docs/sources/flow/reference/components/discovery.relabel.md
docs/sources/flow/reference/components/loki.relabel.md
docs/sources/flow/reference/components/loki.source.journal.md
docs/sources/flow/reference/components/loki.source.kubernetes.md
docs/sources/flow/reference/components/loki.source.podlogs.md
docs/sources/flow/reference/components/loki.source.syslog.md
docs/sources/flow/reference/components/loki.write.md
docs/sources/flow/reference/components/mimir.rules.kubernetes.md
docs/sources/flow/reference/components/otelcol.exporter.jaeger.md
docs/sources/flow/reference/components/otelcol.exporter.otlp.md
docs/sources/flow/reference/components/otelcol.exporter.otlphttp.md
docs/sources/flow/reference/components/otelcol.processor.batch.md
docs/sources/flow/reference/components/otelcol.processor.memory_limiter.md
docs/sources/flow/reference/components/otelcol.receiver.jaeger.md
docs/sources/flow/reference/components/otelcol.receiver.kafka.md
docs/sources/flow/reference/components/otelcol.receiver.loki.md
docs/sources/flow/reference/components/otelcol.receiver.opencensus.md
docs/sources/flow/reference/components/otelcol.receiver.otlp.md
docs/sources/flow/reference/components/otelcol.receiver.prometheus.md
docs/sources/flow/reference/components/otelcol.receiver.zipkin.md
docs/sources/flow/reference/components/phlare.scrape.md
docs/sources/flow/reference/components/phlare.write.md
docs/sources/flow/reference/components/prometheus.relabel.md
docs/sources/flow/reference/components/prometheus.remote_write.md
docs/sources/flow/reference/components/prometheus.scrape.md
docs/sources/flow/reference/components/remote.http.md

Previously, an empty version was inferred from the relative permalink for the page. Although the behavior was similar to the other version inference done in shortcodes like `docs/reference`, it did not allow specifying an empty version needed to include content from unversioned documentation.
For consistency with other shortcodes like `docs/reference`, the `docs/shared` shortcode version lookup has been replaced with the following behavior:
1. If `version=""`, use an empty version.
1. If `version="<SOMETHING VERSION>`, use version inference as described in https://grafana.com/docs/writers-toolkit/write/shortcodes/#docsreference-shortcode:~:text=The%20path%20to,becomes%20GRAFANA%20CLOUD..
1. If `version="ANYTHING ELSE"`, use that literal value.

[release-v0.31] Update `docs/shared` shortcode usage to use keyword argument interface

---

docs/sources/flow/reference/components/discovery.kubernetes.md
docs/sources/flow/reference/components/discovery.relabel.md
docs/sources/flow/reference/components/otelcol.exporter.otlp.md
docs/sources/flow/reference/components/otelcol.exporter.otlphttp.md
docs/sources/flow/reference/components/otelcol.processor.batch.md
docs/sources/flow/reference/components/otelcol.processor.memory_limiter.md
docs/sources/flow/reference/components/otelcol.receiver.jaeger.md
docs/sources/flow/reference/components/otelcol.receiver.otlp.md
docs/sources/flow/reference/components/otelcol.receiver.prometheus.md
docs/sources/flow/reference/components/prometheus.relabel.md
docs/sources/flow/reference/components/prometheus.remote_write.md
docs/sources/flow/reference/components/prometheus.scrape.md

Previously, an empty version was inferred from the relative permalink for the page. Although the behavior was similar to the other version inference done in shortcodes like `docs/reference`, it did not allow specifying an empty version needed to include content from unversioned documentation.
For consistency with other shortcodes like `docs/reference`, the `docs/shared` shortcode version lookup has been replaced with the following behavior:
1. If `version=""`, use an empty version.
1. If `version="<SOMETHING VERSION>`, use version inference as described in https://grafana.com/docs/writers-toolkit/write/shortcodes/#docsreference-shortcode:~:text=The%20path%20to,becomes%20GRAFANA%20CLOUD..
1. If `version="ANYTHING ELSE"`, use that literal value.

[release-v0.29] Update `docs/shared` shortcode usage to use keyword argument interface

---

docs/sources/flow/reference/components/discovery.docker.md
docs/sources/flow/reference/components/discovery.kubernetes.md
docs/sources/flow/reference/components/discovery.relabel.md
docs/sources/flow/reference/components/loki.relabel.md
docs/sources/flow/reference/components/loki.write.md
docs/sources/flow/reference/components/otelcol.exporter.otlp.md
docs/sources/flow/reference/components/otelcol.exporter.otlphttp.md
docs/sources/flow/reference/components/otelcol.processor.batch.md
docs/sources/flow/reference/components/otelcol.processor.memory_limiter.md
docs/sources/flow/reference/components/otelcol.receiver.jaeger.md
docs/sources/flow/reference/components/otelcol.receiver.otlp.md
docs/sources/flow/reference/components/otelcol.receiver.prometheus.md
docs/sources/flow/reference/components/prometheus.relabel.md
docs/sources/flow/reference/components/prometheus.remote_write.md
docs/sources/flow/reference/components/prometheus.scrape.md
docs/sources/flow/reference/components/remote.http.md

Previously, an empty version was inferred from the relative permalink for the page. Although the behavior was similar to the other version inference done in shortcodes like `docs/reference`, it did not allow specifying an empty version needed to include content from unversioned documentation.
For consistency with other shortcodes like `docs/reference`, the `docs/shared` shortcode version lookup has been replaced with the following behavior:
1. If `version=""`, use an empty version.
1. If `version="<SOMETHING VERSION>`, use version inference as described in https://grafana.com/docs/writers-toolkit/write/shortcodes/#docsreference-shortcode:~:text=The%20path%20to,becomes%20GRAFANA%20CLOUD..
1. If `version="ANYTHING ELSE"`, use that literal value.

[release-v0.30] Update `docs/shared` shortcode usage to use keyword argument interface

---

docs/sources/static/configuration/scraping-service.md

Remove reference to `mode` in the Agent scraping service document.
Minor update/corrections to punctuation and word use also included in this PR.
Fixes https://github.com/grafana/agent/issues/3827

Remove reference to `mode` in the Agent scraping service document.

---

operations/helm/charts/grafana-agent/CHANGELOG.md
operations/helm/charts/grafana-agent/README.md
operations/helm/charts/grafana-agent/templates/controllers/statefulset.yaml
operations/helm/charts/grafana-agent/values.yaml

Since we've merged support for periodically rejoining the list of peers, this enables clustering to work with deployments, daemonsets as well as statefulsets with maxUnavailablePods > 1.
We've already identified this can be noisy in large environments, but this will be mitigated with #4464 or similar.
As a drive-by, we fix the changelog of a previous release.
Fixes #4995.

helm: enable clustering support for deployments and daemonsets

---

.github/workflows/bump-formula-pr.yml

`rez0n/actions-github-release@main` only works on Linux runners, while the bump formula action works on either macOS or Linux runners.

Fix bump-formula-pr to run on linux runners

---

CHANGELOG.md
component/module/module.go

add tracking and comparison of latest healthy content before loading a module

---

CHANGELOG.md
component/remote/http/http.go
component/remote/http/http_test.go

Fixes #4042
Allow user to override default `User-Agent` header for `http.remote` component.

fix(http): allow override default user-agent header for http.remote

---

CHANGELOG.md
pkg/metrics/wal/wal.go

This change causes deleted series to be deleted earlier based on the last segment involved in the checkpoint rather than the first segment involved in the checkpoint.
This will then cause the next truncate to be more aggressive with dropped series, which should help free memory associated with deleted series in remote_write sooner.
Mirrors prometheus/prometheus#12297 from @bboreham.

pkg/metrics/wal: remove deleted series from WAL sooner

---

CHANGELOG.md
component/loki/process/process.go
component/loki/process/process_test.go

This PR fixes a deadlock candidate in `loki.process` when Update was concurrently called with a log line being fanned out.
We've already fixed similar problems in other components, as #5061 mentions we should go through all of the loki components to look for similar issues.
No issue filed
Let me know if you know of a better way to detect partial deadlocks here.

loki.process: fix deadlock in case of frequent Updates

---

CHANGELOG.md
pkg/config/config_test.go
pkg/config/integrations.go

Also add unit tests to prevent regression.
Prevent panic when validating integration-included cfg file by performing nil check
Fixes #5047 
- ~~[ ] Documentation added~~
- ~~[ ] Config converters updated~~

fix(agentctl): prevent panic when validating integration-included cfg file

---

docs/sources/flow/reference/components/otelcol.connector.spanlogs.md
docs/sources/flow/reference/components/otelcol.connector.spanmetrics.md
docs/sources/flow/reference/components/prometheus.exporter.apache.md
docs/sources/flow/reference/components/prometheus.exporter.blackbox.md
docs/sources/flow/reference/components/prometheus.exporter.cloudwatch.md
docs/sources/flow/reference/components/prometheus.exporter.consul.md
docs/sources/flow/reference/components/prometheus.exporter.dnsmasq.md
docs/sources/flow/reference/components/prometheus.exporter.elasticsearch.md
docs/sources/flow/reference/components/prometheus.exporter.gcp.md
docs/sources/flow/reference/components/prometheus.exporter.github.md
docs/sources/flow/reference/components/prometheus.exporter.kafka.md
docs/sources/flow/reference/components/prometheus.exporter.memcached.md
docs/sources/flow/reference/components/prometheus.exporter.mongodb.md
docs/sources/flow/reference/components/prometheus.exporter.mssql.md
docs/sources/flow/reference/components/prometheus.exporter.mysql.md
docs/sources/flow/reference/components/prometheus.exporter.oracledb.md
docs/sources/flow/reference/components/prometheus.exporter.postgres.md
docs/sources/flow/reference/components/prometheus.exporter.process.md
docs/sources/flow/reference/components/prometheus.exporter.redis.md
docs/sources/flow/reference/components/prometheus.exporter.snmp.md
docs/sources/flow/reference/components/prometheus.exporter.snowflake.md
docs/sources/flow/reference/components/prometheus.exporter.squid.md
docs/sources/flow/reference/components/prometheus.exporter.statsd.md
docs/sources/flow/reference/components/prometheus.exporter.unix.md
docs/sources/flow/reference/components/prometheus.exporter.windows.md

In most cases the include was a typo and some were missing the special `<AGENT VERSION>` parameter.
All in all, this should fix 124 build errors in the site after backporting.

Fix broken `docs/shared` usage

---

docs/sources/flow/reference/components/prometheus.exporter.apache.md
docs/sources/flow/reference/components/prometheus.exporter.blackbox.md
docs/sources/flow/reference/components/prometheus.exporter.consul.md
docs/sources/flow/reference/components/prometheus.exporter.github.md
docs/sources/flow/reference/components/prometheus.exporter.memcached.md
docs/sources/flow/reference/components/prometheus.exporter.mysql.md
docs/sources/flow/reference/components/prometheus.exporter.postgres.md
docs/sources/flow/reference/components/prometheus.exporter.process.md
docs/sources/flow/reference/components/prometheus.exporter.redis.md
docs/sources/flow/reference/components/prometheus.exporter.snmp.md
docs/sources/flow/reference/components/prometheus.exporter.statsd.md
docs/sources/flow/reference/components/prometheus.exporter.unix.md
docs/sources/flow/reference/components/prometheus.exporter.windows.md

I honestly don't know how I missed them with the initial search and replace.
- Fix typos in `exporter-component-exports.md` shared include.
- Include version argument using `<AGENT VERSION>` variable syntax that is substituted during the website build for the version inferred from the including page.

[release-v0.33] Update `docs/shared` shortcode usage to use keyword argument interface and fix typos

---

docs/sources/flow/reference/components/prometheus.exporter.apache.md
docs/sources/flow/reference/components/prometheus.exporter.blackbox.md
docs/sources/flow/reference/components/prometheus.exporter.cloudwatch.md
docs/sources/flow/reference/components/prometheus.exporter.consul.md
docs/sources/flow/reference/components/prometheus.exporter.dnsmasq.md
docs/sources/flow/reference/components/prometheus.exporter.elasticsearch.md
docs/sources/flow/reference/components/prometheus.exporter.github.md
docs/sources/flow/reference/components/prometheus.exporter.kafka.md
docs/sources/flow/reference/components/prometheus.exporter.memcached.md
docs/sources/flow/reference/components/prometheus.exporter.mongodb.md
docs/sources/flow/reference/components/prometheus.exporter.mssql.md
docs/sources/flow/reference/components/prometheus.exporter.mysql.md
docs/sources/flow/reference/components/prometheus.exporter.oracledb.md
docs/sources/flow/reference/components/prometheus.exporter.postgres.md
docs/sources/flow/reference/components/prometheus.exporter.process.md
docs/sources/flow/reference/components/prometheus.exporter.redis.md
docs/sources/flow/reference/components/prometheus.exporter.snmp.md
docs/sources/flow/reference/components/prometheus.exporter.snowflake.md
docs/sources/flow/reference/components/prometheus.exporter.squid.md
docs/sources/flow/reference/components/prometheus.exporter.statsd.md
docs/sources/flow/reference/components/prometheus.exporter.unix.md
docs/sources/flow/reference/components/prometheus.exporter.windows.md

I honestly don't know how I missed them with the initial search and replace.
- Fix typos in `exporter-component-exports.md` shared include.
- Include version argument using `<AGENT VERSION>` variable syntax that is substituted during the website build for the version inferred from the including page.

[release-v0.35] Update `docs/shared` shortcode usage to use keyword argument interface and fix typos

---

docs/sources/flow/reference/components/otelcol.connector.spanmetrics.md
docs/sources/flow/reference/components/prometheus.exporter.apache.md
docs/sources/flow/reference/components/prometheus.exporter.blackbox.md
docs/sources/flow/reference/components/prometheus.exporter.cloudwatch.md
docs/sources/flow/reference/components/prometheus.exporter.consul.md
docs/sources/flow/reference/components/prometheus.exporter.dnsmasq.md
docs/sources/flow/reference/components/prometheus.exporter.elasticsearch.md
docs/sources/flow/reference/components/prometheus.exporter.gcp.md
docs/sources/flow/reference/components/prometheus.exporter.github.md
docs/sources/flow/reference/components/prometheus.exporter.kafka.md
docs/sources/flow/reference/components/prometheus.exporter.memcached.md
docs/sources/flow/reference/components/prometheus.exporter.mongodb.md
docs/sources/flow/reference/components/prometheus.exporter.mssql.md
docs/sources/flow/reference/components/prometheus.exporter.mysql.md
docs/sources/flow/reference/components/prometheus.exporter.oracledb.md
docs/sources/flow/reference/components/prometheus.exporter.postgres.md
docs/sources/flow/reference/components/prometheus.exporter.process.md
docs/sources/flow/reference/components/prometheus.exporter.redis.md
docs/sources/flow/reference/components/prometheus.exporter.snmp.md
docs/sources/flow/reference/components/prometheus.exporter.snowflake.md
docs/sources/flow/reference/components/prometheus.exporter.squid.md
docs/sources/flow/reference/components/prometheus.exporter.statsd.md
docs/sources/flow/reference/components/prometheus.exporter.unix.md
docs/sources/flow/reference/components/prometheus.exporter.windows.md

I honestly don't know how I missed them with the initial search and replace.
- Fix typos in `exporter-component-exports.md` shared include.
- Include version argument using `<AGENT VERSION>` variable syntax that is substituted during the website build for the version inferred from the including page.

[release-v0.36] Update `docs/shared` shortcode usage to use keyword argument interface and fix typos

---

docs/sources/flow/reference/components/prometheus.exporter.apache.md
docs/sources/flow/reference/components/prometheus.exporter.blackbox.md
docs/sources/flow/reference/components/prometheus.exporter.consul.md
docs/sources/flow/reference/components/prometheus.exporter.dnsmasq.md
docs/sources/flow/reference/components/prometheus.exporter.github.md
docs/sources/flow/reference/components/prometheus.exporter.memcached.md
docs/sources/flow/reference/components/prometheus.exporter.mssql.md
docs/sources/flow/reference/components/prometheus.exporter.mysql.md
docs/sources/flow/reference/components/prometheus.exporter.oracledb.md
docs/sources/flow/reference/components/prometheus.exporter.postgres.md
docs/sources/flow/reference/components/prometheus.exporter.process.md
docs/sources/flow/reference/components/prometheus.exporter.redis.md
docs/sources/flow/reference/components/prometheus.exporter.snmp.md
docs/sources/flow/reference/components/prometheus.exporter.snowflake.md
docs/sources/flow/reference/components/prometheus.exporter.statsd.md
docs/sources/flow/reference/components/prometheus.exporter.unix.md
docs/sources/flow/reference/components/prometheus.exporter.windows.md

I honestly don't know how I missed them with the initial search and replace.
- Fix typos in `exporter-component-exports.md` shared include.
- Include version argument using `<AGENT VERSION>` variable syntax that is substituted during the website build for the version inferred from the including page.

[release-v0.34] Update `docs/shared` shortcode usage to use keyword argument interface and fix typos

---

component/loki/process/process_test.go

This fixes the flaky `TestDeadlockWithFrequentUpdates` test we introduced recently.
Turns out, while the deadlock happens _very_ quickly (so lastSend.Load was always ~900ms behind on my machine), the CI runners can be much slower in sending logs.

loki.process: make test condition less sensitive

---

CHANGELOG.md
pkg/integrations/v2/eventhandler/eventhandler.go

This removes the info-level log line indicating that an event is logged. When agent logs are being collected, this makes the event appear as if it was double-collected, as the event appears both in the logs sent directly to Loki and in the agent logs.

integrations/eventhandler: remove double-logging of events

---

build-image/Dockerfile

Bump golangci-lint to latest version which includes Go 1.21 support. This unblocks #5107.

build-image: bump golangci-lint to latest version

---

CHANGELOG.md
component/loki/source/internal/kafkatarget/kafkatarget.go
component/loki/source/internal/kafkatarget/kafkatarget_test.go
docs/sources/flow/reference/components/loki.source.kafka.md

Expose message's offset in `loki.source.kafka` as internal label in the format of `__meta_kafka_message_offset`
Fixes #5079

feat(comp/loki): expose msg's offset as internal label

---

build-image/Dockerfile
build-image/windows/Dockerfile

Bump build-image to use Go 1.21.1.

build-image: bump to go 1.21.1

---

CHANGELOG.md
component/all/all.go
component/otelcol/connector/servicegraph/servicegraph.go
component/otelcol/connector/servicegraph/servicegraph_test.go
docs/sources/flow/reference/components/otelcol.connector.servicegraph.md
docs/sources/flow/reference/components/otelcol.connector.spanlogs.md
go.mod
go.sum

The new `otelcol.connector.servicegraph` component is based on the [servicegraphconnector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.80.0/connector/servicegraphconnector), which on the other hand is based on [servicegraphprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.80.0/processor/servicegraphprocessor).
Fixes #2300
Fixes #2213
There is one config parameter for the servicegraph connector which we cannot yet support in flow - `virtual_node_peer_attributes`. It is behind a `processor.servicegraph.virtualNode` feature gate in the Collector. In the Agent we don't yet support enabling Otel feature gates. I will try to submit a PR to the Collector to either remove that feature gate or enable it by default, and the next time …

Add a otelcol.connector.servicegraph component

---

operations/helm/charts/grafana-agent/CHANGELOG.md
operations/helm/charts/grafana-agent/Chart.yaml
operations/helm/charts/grafana-agent/README.md
operations/helm/charts/grafana-agent/templates/controllers/statefulset.yaml
operations/helm/charts/grafana-agent/values.yaml
operations/helm/tests/clustering/grafana-agent/templates/controllers/statefulset.yaml
operations/helm/tests/create-statefulset-autoscaling/grafana-agent/templates/controllers/statefulset.yaml
operations/helm/tests/create-statefulset/grafana-agent/templates/controllers/statefulset.yaml

Now that Flow mode cluster nodes will rejoin the cluster in the background, we can speed up the default rollout by changing StatefulSets to deploy in Parallel.

operations/helm: change StatefulSets to deploy in Parallel

---

docs/developer/writing-flow-component-documentation.md
docs/sources/flow/reference/components/discovery.consulagent.md
docs/sources/flow/reference/components/otelcol.connector.servicegraph.md

The shared link syntax was missing the `version="<AGENT VERSION>"` part. This PR adds it to the topic.
Parent PR is: https://github.com/grafana/agent/pull/5008

Add missing shared link syntax

---

CHANGELOG.md
component/prometheus/scrape/scrape.go
component/prometheus/scrape/scrape_test.go

Extend the validation check by comparing the value of scrape timeout with scrape interval to detect an eventual misconfiguration before trying to scrape.
The check is similar to the one in [Prometheus](https://github.com/prometheus/prometheus/blob/24d7e5bd49dd26a45c2123a897c6cac5ac7c47f0/config/config.go#L549-L569)
Fixes #3696

Improve river config validation in prometheus.scrape 

---

docs/Makefile

`make docs` started to fail as `check-cloudwatch-integration` used a 1.19 Go build container. Now that our builds use Go 1.21, and the go.mod includes a patch version, the build container must be updated to Go 1.21 to work again.

docs: fix check-cloudwatch-integration for the Go 1.21.X go.mod file

---

CHANGELOG.md
component/prometheus/exporter/blackbox/blackbox.go
component/prometheus/exporter/blackbox/blackbox_test.go
docs/sources/flow/reference/components/prometheus.exporter.blackbox.md

Adds a `labels` object to `prometheus.exporter.blackbox`'s `target` block. This allows setting labels individually per target.

Add extra_labels object to BlackboxTarget block

---

CHANGELOG.md
component/otelcol/processor/discovery/discovery.go
docs/sources/flow/reference/components/otelcol.processor.discovery.md
docs/sources/flow/reference/components/otelcol.processor.span.md
pkg/traces/promsdprocessor/consumer/consumer.go
pkg/traces/promsdprocessor/prom_sd_processor.go

Fixes a bug where `otelcol.processor.discovery` would modify one of its config attributes. This seems to have an effect on the component which is passing this attribute to `otelcol.processor.discovery`, because the attribute contains a map and is not deep copied.
Static mode is not affected because it deep copies the targets.
Fixes #5164

otelcol.processor.discovery should not modify its targets attribute

---

docs/sources/flow/reference/components/loki.source.kafka.md

This PR updates the example in https://grafana.com/docs/agent/latest/flow/reference/components/loki.source.kafka/ and adds in a missing `forward_to` argument, fixes another `forward_to` destination, and puts the blocks into a more logical/readable order.
Fixes #5044

Correct the example syntax in the loki.source.kafka reference topic

---

CHANGELOG.md
component/otelcol/config_retry.go
component/otelcol/exporter/loadbalancing/loadbalancing.go
component/otelcol/exporter/loadbalancing/loadbalancing_test.go

The v0.80 upgrade introduced two new settings to the common retry mechanism shared between components. One of these new settings, `multiplier`, specifies the rate at which a backoff is applied.
We did not convert this new field after upgrading, leading the multiplier to be set to the Go default (zero). After the first retry, the backoff period would be multiplied by zero for each subsequent retry, causing retries to happen in a hot loop.
A follow up PR should expose these new settings to the user rather than hard coding them at the new upstream defaults. I've split the additions of the new fields and fixing the defaults across two separate PRs in case we want to release this in a patch.

otelcol: fix retry mechanism

---

docs/sources/static/set-up/install/install-agent-linux.md

This PR removes a sudo command that slipped into the Linux install instructions for RHEL/Fedora

Remove sudo command from RHEL Fedora install instructions

---

docs/sources/flow/reference/stdlib/split.md

Fixes split function documentation.
NA
Fixes documentation for split function order examples.

Wrong order for the split functions example

---

docs/sources/flow/reference/components/otelcol.connector.spanmetrics.md
docs/sources/flow/reference/components/otelcol.processor.span.md

#4934 and #4936 named the component stability of `otelcol.processor.span` and `otelcol.connector.spanmetrics` as "alpha". This is an Otel Collector term, and should be replaced by the [Agent's](https://grafana.com/docs/agent/latest/stability/) "experimental" label.
The Agent has a policy of not downgrading stability. I think this change doesn't count as downgrading, because it's reasonable to expect that something labeled "alpha" is not stable.

Rename component stability from "alpha" to "experimental".

---

docs/sources/flow/reference/components/prometheus.exporter.blackbox.md
docs/sources/flow/reference/components/prometheus.exporter.cloudwatch.md
docs/sources/flow/reference/components/prometheus.exporter.snmp.md

(Hopefully) alleviates some confusion in the docs for `prometheus.exporter.blackbox` and `prometheus.exporter.snmp` derive the `name` attribute from the _label_ of the block and is not a required _argument_ to the block.
Related to https://github.com/grafana/agent/issues/5163

[Docs] prometheus.exporter.[blackbox, snmp] misc. fixes

---

docs/sources/flow/reference/components/prometheus.exporter.blackbox.md
docs/sources/flow/reference/components/prometheus.exporter.cloudwatch.md
docs/sources/flow/reference/components/prometheus.exporter.snmp.md

* Remove name from block arguments and add a sentence that a label is required
* Fix blocks header levels and move 'period and length' section
* Add suggested change
* Revert "Fix blocks header levels and move 'period and length' section"
This reverts commit 93a593aad79e1a88eac4e6d5e3e63107866156c2.
---------
(cherry picked from commit 31999c8224d3d6cbf848fa441e5862a03abd5837)

[Docs] prometheus.exporter.[blackbox, snmp] misc. fixes (#5187)

---

docs/sources/flow/reference/components/otelcol.processor.attributes.md

There has been some confusion regarding the attributes processor. It contains an `exclude` block, and people sometimes get confused that this means the data will be excluded in downstream components. This is not the case.
I mention the tail sampling processor as a processor which can do this. However, it only works for traces. It would have been nice to also point to similar processors for logs and metrics, but I don't think we have such components in Flow at the moment. I think the otel components for dropping metrics and logs are [metricstransform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor) and [probabilisticsampler processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/process …

Clarify that attribute processor does not drop signals

---

CHANGELOG.md
Makefile
component/all/all.go
component/otelcol/processor/probabilistic_sampler/probabilistic_sampler.go
component/otelcol/processor/probabilistic_sampler/probabilistic_sampler_test.go
docs/sources/flow/reference/components/otelcol.processor.probabilistic_sampler.md
go.mod
go.sum

implements a flow component otelcol.processor.probabilistic_sampler that wraps over the upstream OpenTelemetry Collector Contrib probabilistic_sampler processor.
https://github.com/grafana/agent/issues/3596

Add probabilistic sampler processor

---

CHANGELOG.md
component/prometheus/exporter/cloudwatch/config.go
component/prometheus/exporter/cloudwatch/config_test.go
converter/internal/staticconvert/internal/build/cloudwatch_exporter.go
converter/internal/staticconvert/testdata/integrations.river
converter/internal/staticconvert/testdata/integrations.yaml
docs/sources/flow/reference/components/prometheus.exporter.cloudwatch.md
docs/sources/static/configuration/integrations/cloudwatch-exporter-config.md
pkg/integrations/cloudwatch_exporter/config.go
pkg/integrations/cloudwatch_exporter/config_test.go

Adds `nil_to_zero` config flag so `YACE` can be configured instead of hard-coding `true`.
Fixes #5075

add `nil_to_zero` YACE config

---

CHANGELOG.md
pkg/config/remote_config.go

In addition to `429 TooManyRequests`, remote servers may return `503 ServiceUnavailable` with a `Retry-After` header. This allows overloaded servers to apply back-pressure for a quick recovery.

Agent Management: Honor 503 ServiceUnavailable Retry-After header

---

CHANGELOG.md
component/loki/process/stages/extensions.go
component/loki/process/stages/extensions_test.go
component/loki/process/stages/stage.go
converter/internal/promtailconvert/internal/build/stages.go
converter/internal/promtailconvert/testdata/pipeline_stages_cri_empty.river
converter/internal/promtailconvert/testdata/pipeline_stages_cri_empty.yaml
converter/internal/promtailconvert/testdata/pipeline_stages_part2.river
converter/internal/promtailconvert/testdata/pipeline_stages_part2.yaml
docs/sources/flow/reference/components/loki.process.md

There is a [new feature](https://github.com/grafana/loki/pull/9508) in promtail - this PR is adding it to `loki.process`.
Fixes #4883
* I updated the promtail config converter test file, but I'm not sure if that's all I need to do for the converters?
* I updated the docs to say "number" instead of "int", to make it more consistent with the River [Types and values](https://grafana.com/docs/agent/latest/flow/config-language/expressions/types_and_values/) documentation.

Sync cri stage in loki.process with promtail.

---

internal/slogadapter/gokit.go
internal/slogadapter/gokit_test.go

The custom log.Logger implementation wrapping around a slog.Handler must check to see if a level is enabled before logging log lines.

slogadapter: check for log level being enabled

---

CHANGELOG.md
cmd/internal/flowmode/cmd_run.go
service/otel/otel.go

Otel metrics were supposed to be integrated into Flow mode in #5045, but it was recently discovered that they were still not working. I think this is because I did some last minute refactoring, and must have forgotten to do a local test of the Agent to make sure the metrics are still visible. I suspect that I initially had the feature gate registration in `New` and moved it to `Run` later on.
This PR does the feature gate registration in the `New` function, because doing it in the `Run` function would be too late - the otel components would already have checked the feature gate by then.

Set the otel feature gates in Flow mode earlier

---

CHANGELOG.md
component/prometheus/scrape/scrape.go

In https://github.com/grafana/agent/pull/5263/files I have used `len` on a wrong structure, resulting in the targets gauge being always 1.

Fix bug in metric reporting

---

pkg/integrations/cadvisor/cadvisor.go

The current iteration of the cadvisor integration is not compatible with the way we're building `prometheus.exporter.*` components today.
The current code gets the HTTP handler for the metrics endpoint once at the start (after the exporter is created), and then calls to run the exporter itself.
https://github.com/grafana/agent/blob/363b169217812dec56dc1f2e9f27998fc7e07644/component/prometheus/exporter/exporter.go#L73-L80
The cadvisor integration behaves somewhat differently and updates its collectors within its custom `Run` method
https://github.com/grafana/agent/blob/363b169217812dec56dc1f2e9f27998fc7e07644/pkg/integrations/cadvisor/cadvisor.go#L148-L150
This means at the point where the component would fetch the handler, no collectors are registered and no metrics are available.
This PR …

pkg/integrations/cadvisor: minimize runner responsibilities

---

.github/dependabot.yml

JS dependencies in agent's UI are not kept up-to-date and can cause issue like #4957. We should have a way to automate version upgrade for the agent's UI dependencies.

feat(build): auto-generate PRs to bump agent's web UI dependencies

---

CHANGELOG.md
component/prometheus/scrape/scrape.go
docs/sources/flow/reference/components/prometheus.scrape.md

This PR adds a couple of new Arguments to the `prometheus.scrape` component to toggle scraping of Prometheus' native histograms over gRPC and conditionally allowing classic histograms being scraped in parallel.
Fixes #5136 
Nothing for now.

prometheus.scrape: add options for enabling native histograms scraping

---

component/prometheus/receive_http/receive_http_test.go
go.mod
go.sum

You can see the diff with the branch (and pinned commit SHA) on the following link. Once the next Prometheus release is out with the two fixes, we can stop using the Prometheus replace directive altogether since we also removed our Cortex dependency.
https://github.com/prometheus/prometheus/compare/v2.45.0...grafana:prometheus:v0.45.0-retry-improvements?expand=1

go.mod: cherry-pick improvements to Prometheus' retry behaviour

---

CHANGELOG.md
pkg/flow/internal/controller/node_config_argument.go
pkg/flow/module_test.go

fix(pkg/flow): cmt stmt in arg block is now parseable

---

component/pyroscope/ebpf/args.go
component/pyroscope/ebpf/ebpf_linux.go
docs/sources/flow/reference/components/pyroscope.ebpf.md
go.mod
go.sum

Introduce an argument to configure c++ symbol demangling. 
Available options are: none, simplified, templates, full. None is default.
https://github.com/grafana/pyroscope/pull/2479
https://github.com/grafana/support-escalations/issues/7691

pyroscope.ebpf: add an demangling options

---

docs/sources/_index.md
docs/sources/about.md
docs/sources/operator/release-notes.md
docs/sources/static/configuration/create-config-file.md
docs/sources/static/configuration/flags.md
docs/sources/static/release-notes.md
docs/sources/static/set-up/install/install-agent-binary.md

Primarily arising from Flow content not being mounted in Grafana Cloud.
Some were typos or incorrect relative paths.
Links for this PR and the [backport](https://github.com/grafana/agent/pull/5353) tested in https://github.com/grafana/website/pull/15708.

Fix some build errors related to mounted content

---

docs/sources/_index.md
docs/sources/about.md
docs/sources/operator/release-notes.md
docs/sources/static/configuration/create-config-file.md
docs/sources/static/configuration/flags.md
docs/sources/static/release-notes.md
docs/sources/static/set-up/install/install-agent-binary.md

Primarily arising from Flow content not being mounted in Grafana Cloud.
Some were typos or incorrect relative paths.
(cherry picked from commit 824dc6a925c700e6007d3e31effc4b9b5c5610b7)

[release-v0.36] Fix some build errors related to mounted content

---

docs/sources/flow/getting-started/migrating-from-static.md

Change Promtail Reference to Static Mode since the Doc does not reference Promtail.
Replaces `Promtail` with `Static mode` in one of the Section Headers.
Section content refers to Static Mode

Change Promtail Reference to Static Mode in migrating-from-static.md

---

CHANGELOG.md
component/all/all.go
component/otelcol/processor/transform/transform.go
component/otelcol/processor/transform/transform_test.go
docs/developer/writing-flow-component-documentation.md
docs/sources/flow/reference/components/otelcol.processor.transform.md
go.mod
go.sum

This PR ports the [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.85.0/processor/transformprocessor#contexts) to Flow.
Fixes #2910
When writing flow docs, usually we avoid linking to the documentation of the underlying Otel component so that we don't confuse users with yaml configs which don't apply for the Agent. In this case I had to link to the Otel docs quite a lot. I tried to only link to places where it made sense, and to sections where there isn't any yaml config which could confuse a reader.

Add a otelcol.processor.transform component

---

pkg/flow/flow_updates_test.go

Fixes flaky test on Windows and potentially other slower machines (which can pause for 7+ ms).
In current component updates tests that were added in https://github.com/grafana/agent/pull/5280 we have a `count` components which count `0, 1, ..., 10` every `10ms` and a `summation` component that adds up all the numbers it receives from `count` through other components that simulate a total lag of e.g. `3ms`. 
The test waits for the last update - `10` - to arrive to the `summation` component and then performs a bunch of assertions. This is the hard guarantee we need to provide - that the latest update always arrives. 
However, current and previous (before https://github.com/grafana/agent/pull/5280) implementations of Flow allow for intermediate updates to be skipped, if there is already an …

Relax flow updates test assertions

---

converter/internal/staticconvert/testdata_windows/integrations.river

After https://github.com/grafana/river/commit/75f893ffa7df5b9460710bf50b187db8886178b1 was merged, we no longer output some of the default field values. We seem to have had a concurrent change which led to semantic merge conflict where the default values were not removed from tests.

Fix windows test

---

CHANGELOG.md
component/common/loki/wal/wal.go
component/prometheus/receive_http/receive_http.go
go.mod
go.sum
pkg/agentctl/waltools/walstats_test.go
pkg/metrics/http.go
pkg/metrics/wal/wal.go

This updates our Prometheus dependency to v2.46.0 with the retry behavior improvement cherry-picked
https://github.com/prometheus/prometheus/compare/v0.46.0...grafana:prometheus:v0.46.0-retry-improvements?expand=1
https://github.com/grafana/loki/compare/k169...07cbef92268aecc0f20d1791a6df390c2df5c072

go.mod: update Prometheus to v2.46.0 with retry behavior cherry-picks

---

CHANGELOG.md
component/prometheus/remotewrite/types.go
component/prometheus/remotewrite/types_test.go
converter/internal/prometheusconvert/remote_write.go
converter/internal/prometheusconvert/testdata/scrape.river
converter/internal/prometheusconvert/testdata/scrape.yaml
converter/internal/prometheusconvert/testdata/unsupported.diags
converter/internal/prometheusconvert/testdata/unsupported.yaml
converter/internal/staticconvert/testdata/prom_remote_write.river
converter/internal/staticconvert/testdata/prom_remote_write.yaml
docs/sources/flow/reference/components/prometheus.remote_write.md
docs/sources/shared/flow/reference/components/azuread-block.md
docs/sources/shared/flow/reference/components/managed_identity-block.md
docs/sources/shared/flow/reference/components/sigv4-block.md

Adding SigV4 and AzureAD authentication support for `prometheus.remote_write`.
Fixes #5346
Unlike other authentication methods, this one is not used in discovery processes since it's just specific to remote write.

SigV4 and AzureAD authentication support for `prometheus.remote_write`

---

component/module/file/file.go
component/module/git/git.go
component/module/http/http.go
component/module/string/string.go
pkg/flow/module_caching_test.go

This is necessary so that modules can successfully load otelcol components which depend on the otel service. Those are almost all otelcol receivers and exporters.
I am not updating the changelog because we haven't released a version of the Agent with this bug.
I wish I could add tests to the CI for this, but I cannot see any test files which exist already for modules.
I tested this change with this river file:
```
tracing {
sampling_fraction = 1
write_to          = [module.git.traces_otel_input.exports.input]
}
module.git "traces_otel_input" {
repository = "https://github.com/grafana/agent-modules.git"
revision   = "add_aaron_benton_code_owner"
path       = "example/traces/otel_input/module.river"
arguments {
username = ""
password = ""
url      = ""
}
}
```

Add otel service as a dependency to module loaders.

---

CHANGELOG.md
component/otelcol/auth/oauth2/oauth2.go
docs/sources/flow/reference/components/otelcol.auth.oauth2.md

Changing the type of the `client_secret` argument of the `otelcol.auth.oauth2` component from `string` to `secret`. It should not have been a `string` in the first place... this is an oversight from the time when the component was created.

`otelcol.auth.oauth2`: Change the type of the `client_secret` argument

---

pkg/flow/flow.go
pkg/flow/flow_updates_test.go
pkg/flow/internal/controller/loader.go

This prevents a hot retry loop in the unlikely event of worker queue getting full. The symptom of hot retry loop would be a lot of log lines saying `failed to submit node for evaluation - the agent is likely overloaded and cannot keep up with evaluating components` - as it could be observed when running a test dedicated to reproducing this situation - `TestController_Updates_WithQueueFull`. 
* `Flow` passes updated components to `loader`'s `EvaluateDependencies`, which submits the component's direct dependencies for evaluation to the worker pool.
* In unlikely event that the pool is full, e.g. we have a component that runs into a deadlock, we would currently log an error and return the parent component back to `Flow` for a retry. But `Flow` would attempt retry right away, leading to a hot …

Prevent hot loop retry on full worker queue

---

converter/internal/test_common/testing.go

This PR is to help with clarity for when a test fail to show the full name of the source config for the test.

include source config suffix in converter test names

---

component/discovery/consulagent/promtail_consulagent_test.go

The test would be sometimes flaky due to race detection:
```
➜  agent git:(main) go test -race -count 1000 github.com/grafana/agent/component/discovery/consulagent -run TestAllServices
==================
WARNING: DATA RACE
Write at 0x00c000164a30 by goroutine 19386:
runtime.recvDirect()
/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/chan.go:348 +0x7c
github.com/grafana/agent/component/discovery/consulagent.TestAllServices.func1()
/Users/piotr/workspace/agent/component/discovery/consulagent/promtail_consulagent_test.go:372 +0x58
Previous read at 0x00c000164a30 by goroutine 19395:
runtime.chansend1()
/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/chan.go:146 +0x2c
github.com/grafana/agent/component/discovery/consulagent.(*consulService).watch() …
```

Fix sometimes flaky test

---

docs/sources/flow/reference/components/loki.write.md

Added required path to the Loki endpoint for Grafana Cloud Logs.

Update loki.write.md -  Add Grafana Cloud Logs endpoint path

---

pkg/integrations/node_exporter/config.go

We forgot to initialize `RaplConfig` when we create a new `NodeCollectorConfig` to enable node_exporter integration.
This causes some issues.
Fixes #5388

Fix config for Rapl in node exporter config

---

component/common/loki/wal/timer_test.go

In CI, especially on slower machines or in presence of noisy neighbours, the execution of tests may be paused by GC or resource exhaustion for longer period of time, sometimes even multiple seconds. When our tests rely on some code executing within certain deadline, we can end up with flaky tests. 
One way to fix it is to add more slack to the test, allowing it to pause for longer time. Another is to retry test on failure where it makes sense. In this PR I picked the first option as a simpler one that should increase the tolerance for pauses from 20ms to 200ms.

Fix flaky test by increasing tolerance to process pauses

---

CHANGELOG.md
component/loki/process/metric/counters.go
component/loki/process/metric/counters_test.go
component/loki/process/metric/gauges.go
component/loki/process/metric/gauges_test.go
component/loki/process/metric/histograms.go
component/loki/process/metric/histograms_test.go
component/loki/process/metric/metricvec.go
component/loki/process/process_test.go

Part of https://github.com/grafana/agent/issues/4836

Sync loki.process: metric.coutners

---

CHANGELOG.md
docs/sources/operator/deploy-agent-operator-resources.md
docs/sources/operator/getting-started.md
docs/sources/static/configuration/integrations/node-exporter-config.md
docs/sources/static/configuration/integrations/process-exporter-config.md
docs/sources/static/set-up/install/install-agent-docker.md
pkg/operator/defaults.go
production/kubernetes/agent-bare.yaml
production/kubernetes/agent-loki.yaml
production/kubernetes/agent-traces.yaml
production/kubernetes/build/lib/version.libsonnet
production/kubernetes/build/templates/operator/main.jsonnet
production/kubernetes/install-bare.sh
production/operator/templates/agent-operator.yaml
production/tanka/grafana-agent/v1/main.libsonnet
production/tanka/grafana-agent/v2/internal/base.libsonnet
production/tanka/grafana-agent/v2/internal/syncer.libsonnet

Step 2 in publishing the next stable minor release v0.37.0
https://github.com/grafana/agent/tree/main/docs/developer/release#stable-release-publish

all: update version string everywhere for v0.37.0

---

CHANGELOG.md
component/common/loki/wal/wal.go

This PR enables compression the `loki.write` WAL. Both snappy and zstd are supported by the reader/writer side, and the reader side checks the compression of each record read (so no compat issues). Snappy was picked because since this it will be used in a WAL, rather than a wire-protocol, we strive more for cpu efficiency (snappy is cpu lighter) rather higher compression rate (which zstd does better, but at a higher CPU cost).
Enabling compression in WAL allowed us in our agents deployment to have a compression rate of ~2.

Enable compression in logs WAL

---

component/loki/source/kubernetes_events/event_controller.go
component/prometheus/operator/common/crdmanager.go
pkg/operator/operator.go

Initialise a map to prevent panic

Fix: Initialise default namespaces map config

---

operations/helm/charts/grafana-agent/CHANGELOG.md
operations/helm/charts/grafana-agent/README.md
operations/helm/charts/grafana-agent/ci/initcontainers-values.yaml
operations/helm/charts/grafana-agent/templates/controllers/_pod.yaml
operations/helm/charts/grafana-agent/values.yaml

Other pod-level settings are determined by the `controller` group of settings, so initContainers should be inside of controller (`controller.initContainers`) rather than a top-level field.

helm: move initContainers to inside controller for consistency with pod settings

---

CHANGELOG.md
component/loki/process/stages/pipeline.go
component/loki/process/stages/sampling.go
component/loki/process/stages/sampling_test.go
component/loki/process/stages/stage.go
converter/internal/promtailconvert/internal/build/stages.go
converter/internal/promtailconvert/testdata/pipeline_stages_part2.river
converter/internal/promtailconvert/testdata/pipeline_stages_part2.yaml
converter/internal/promtailconvert/testdata/pipeline_stages_unsupported.diags
converter/internal/promtailconvert/testdata/pipeline_stages_unsupported.yaml
docs/sources/flow/reference/components/loki.process.md

Part of https://github.com/grafana/agent/issues/4836
This fell through the cracks for feature parity.

Add loki.process stage.sampling

---

component/otelcol/processor/discovery/discovery_test.go
docs/sources/flow/reference/components/otelcol.processor.discovery.md

As #5306 shows, there has been some confusion regarding `otelcol.processor.discovery`, discovery components, and OpenTelemetry semantic conventions. I hope that this new addition to the docs will clear the confusion for future users.
Fixes #5306

Clarify usage of otelcol.processor.discovery

---

CHANGELOG.md
pkg/flow/tracing/wrap_tracer.go

feat(tracing): inject component ID as instrumentation scope attribute

---

docs/sources/_index.md

This PR fixes a failing cross reference link from a note.
Restoring the original relref results in a broken link when this topic is mounted into the Grafana Cloud docs. Converting the link to a fully qualified link ensures the link will work in Agent docs and in Cloud docs. Refer to: https://grafana.com/docs/writers-toolkit/write/references/#choose-the-correct-link
Followup PR to https://github.com/grafana/agent/pull/5464

Fix a cross reference link in a note in the Agent root topic (v0.37)

---

cmd/grafana-agent/Dockerfile

This resolves a number of (afaik unexploitable) cves.
Mantic does not have definitions yet, but there are updated libc6 packages. This runs `apt-get upgrade -y` in the dockerfile.

upgrade packages in dockerfile

---

docs/developer/updating-otel.md

Putting in writing the lessons learned from #3858. Hopefully this helps us to do upgrades more often and with less effort.

Add docs for updating Otel dependencies

---

cmd/grafana-agent-operator/Dockerfile
cmd/grafana-agentctl/Dockerfile

#5463 updated the `grafana-agent` dockerfile, but not the other two docker files. This PR also updates the other two files for consistency, and also to make sure they are not flagged for CVEs.

"apt-get upgrade" in agentctl and operator docker images

---

CHANGELOG.md
cmd/internal/flowmode/cluster_builder_test.go
cmd/internal/flowmode/cmd_run.go

We recently almost had this bite us when porting the cadvisor integration to a new component. 
`strings.Split` returns the input string itself if the separator is not found; this meant that for an empty flag, `strings.Split("", ",")` returned a 1-element slice with the empty string, and _not_ an empty slice.
Fixes #5449 
Nothing to note.

clustering: fix handling of empty join-addresses flag

---

build-image/Dockerfile
build-image/windows/Dockerfile

Makes build-image use Go 1.21.3.

build-image: bump to go 1.21.3

---

CHANGELOG.md
component/loki/process/stages/structured_metadata.go
component/loki/process/stages/structured_metadata_test.go

This PR upstreams the promtail changes from https://github.com/grafana/loki/pull/10752 into the Grafana Agent.
This is rather expected behavior, so no need to update the docs.

Port loki/#10752 to Agent

---

.drone/drone.yml
CHANGELOG.md
cmd/grafana-agent-operator/Dockerfile
cmd/grafana-agent/Dockerfile
cmd/grafana-agent/Dockerfile.windows
cmd/grafana-agentctl/Dockerfile
cmd/grafana-agentctl/Dockerfile.windows
tools/crow/Dockerfile
tools/make/build-container.mk
tools/smoke/Dockerfile

This bumps the build-image to the newly pushed v0.30.3 tag which makes use of Go 1.21.3

build: bump build image usage to 0.30.3

---

.drone/drone.yml
cmd/grafana-agent-operator/Dockerfile
cmd/grafana-agent/Dockerfile
cmd/grafana-agent/Dockerfile.windows
cmd/grafana-agentctl/Dockerfile
cmd/grafana-agentctl/Dockerfile.windows
cmd/internal/flowmode/cluster_builder_test.go
cmd/internal/flowmode/cmd_run.go
component/prometheus/exporter/blackbox/blackbox.go
component/prometheus/exporter/blackbox/blackbox_test.go
converter/internal/staticconvert/internal/build/blackbox_exporter.go
converter/internal/staticconvert/testdata/integrations.river
go.mod
go.sum
pkg/integrations/blackbox_exporter/blackbox_exporter.go
tools/crow/Dockerfile
tools/make/build-container.mk
tools/smoke/Dockerfile

This PR cherry-picks multiple commits to prepare for a v0.37.2 patch release:
* Bumps our Prometheus dependency to v2.47.2 along with our retry improvements to fix two bugs with native histograms
* Bumps Go to v1.21.3 to resolve the recent HTTP/2 CVE
* Updates our Ubuntu packages to the latest
* Fixes a bug in clustering's handle of the `--cluster.join-addresses` CLI flag.
* Fixes an issue with the converter and the blackbox exporter

Cherry picks for v0.37.2

---

CHANGELOG.md
pkg/metrics/wal/wal.go
pkg/metrics/wal/wal_test.go

This copies the behavior of https://github.com/prometheus/prometheus/pull/12897 into our own tsdb. 
- [NA] Config converters updated

Allow out of order samples to be written to the WAL.

---

pkg/metrics/wal/wal.go
pkg/metrics/wal/wal_test.go

Cherry-pick #5487 from main that allows OOO samples to be written to the WAL.

Allow out of order samples to be written to the WAL (#5487)

---

docs/sources/flow/reference/components/remote.vault.md

I'm surprised that "HashiCorp" is not mentioned in the docs for `remote.vault`. "Vault" is a term which is so overused in the security space, that probably even the component should have been called `remote.hashicorp_vault`.

Docs: Clarify which Vault "remote.vault" connects to

---

go.mod
go.sum

`google.golang.org/grpc@v1.58.0` --> `@v1.58.3` to remove flag for [CVE-2023-44487](https://www.cve.org/CVERecord?id=CVE-2023-44487).

Update google.golang.org/grpc@v1.58.0 -> 1.58.3

---

CHANGELOG.md
docs/sources/static/configuration/traces-config.md
pkg/traces/config.go
pkg/traces/config_test.go

Adding new config options to spanmetrics processor in static mode:
- `aggregation_temporality`: configures whether to reset the metrics after flushing.
- `metrics_flush_interval`: configures how often to flush generated metrics.
Fixes #4614
This change is ok from a feature parity point of view because both of these config options are present in [otelcol.connector.spanmetrics](https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.connector.spanmetrics/).

Add new options to spanmetrics processor in static mode:

---

docs/sources/static/configuration/agent-management.md

- Remove references to v2 in the API (this does not have much meaning to users).
- Specify that `agent_id` is required when label management is enabled.

Agent Management: Small doc tweaks

---

docs/sources/flow/reference/components/prometheus.exporter.unix.md

Ref: #5361
Missing label for prometheus.exporter.unix
See #5361

docs: Add label to prometheus.exporter.unix

---

docs/sources/flow/concepts/configuration_language.md
docs/sources/flow/config-language/components.md
docs/sources/flow/reference/components/module.file.md
docs/sources/flow/reference/components/module.http.md
docs/sources/flow/reference/components/module.string.md
docs/sources/flow/reference/components/otelcol.exporter.logging.md
docs/sources/flow/tutorials/assets/flow_configs/example.river
docs/sources/flow/tutorials/chaining.md

PR #5361 removed the concept of "singleton components" (components which must not have a user-specified label), and thus made prometheus.exporter.unix require a label.
However, documentation referring to the old form of this component was not updated to include a label.
Related to #5542.

docs: fix old instances of prometheus.exporter.unix not needing a label

---

docs/sources/flow/getting-started/configure-agent-clustering.md

Clustering has not required a StatefulSet since v0.36.

docs: remove mention of using statefulset for clustering

---

CHANGELOG.md
component/pyroscope/scrape/scrape.go
component/pyroscope/scrape/scrape_loop.go
component/pyroscope/scrape/scrape_loop_test.go
component/pyroscope/scrape/target.go
component/pyroscope/scrape/target_test.go

This improves the sync method of Pyroscope scrapes based on some investigation.
The change is basically caching values of labels, url and hash of targets to avoid regenerating them when we sync and scrape profiles.
To ensure we're improving something I've added a benchmark.
Result:
```
benchstat before.txt after.txt
name     old time/op    new time/op    delta
Sync-16     796µs ±13%     167µs ± 3%  -79.06%  (p=0.008 n=5+5)
name     old alloc/op   new alloc/op   delta
Sync-16     609kB ± 0%     162kB ± 0%  -73.35%  (p=0.008 n=5+5)
name     old allocs/op  new allocs/op  delta
Sync-16     8.26k ± 0%     1.55k ± 0%  -81.29%  (p=0.008 n=5+5)
```
I'm sure there's more we can do.

Improves Pyroscope's scrape sync

---

docs/sources/about.md

Flow mode has feature parity with static mode and operator in v0.37. This removes references implying it doesn't.

docs: remove implication that flow mode doesn't have feature parity from about page

---

production/grafana-agent-mixin/alerts.libsonnet

The `AgentRemoteConfigBadAPIRequests` was using the wrong operator to evaluate the pattern.

Fix alert for Agent Management in mixin

---

internal/slogadapter/gokit.go
pkg/flow/logging/level/level.go
pkg/flow/logging/logger.go
pkg/flow/logging/logger_test.go

It's recommended too review the first two commits of this PR separately:
* [First one](https://github.com/grafana/agent/pull/5452/commits/c9d638b3917ecac138afe53c60339100842a00ce) adds benchmarks and includes the results in a comment
* [Second one](https://github.com/grafana/agent/pull/5452/commits/3ed08cfd5598a7d3f336f7af529083d314b5db62) adds a few optimisations for the logging and includes the new benchmark results in a comment.
Summary of optimisations:
* Look for the log level first in log adapter to avoid costly allocations if the record will not be logged
* Implement our own `level` package that can replace gokit's `level.Debug(logger)...` - our `level` package is level-aware and will be checking whether given level is enabled in the underlying logger (if it can, opportunistically. …

Improve loggers performance

---

component/common/relabel/relabel.go
component/common/relabel/relabel_test.go

This PR updates the validation rules for all `*.relabel` blocks to be aligned with the validations in [upstream Prometheus](https://github.com/prometheus/prometheus/blob/a807dd16160f0816d5f03bfed72a5321372b0de4/model/relabel/relabel.go#L102-L153)'s UnmarshalYAML method.
Fixes #4837 
I don't think there's something else to sync for loki.relabel since it's not _really_ using much of Promtail code

common/relabel: update validation rules from Prometheus

---

CHANGELOG.md
build-image/Dockerfile

NodeSource has clarified that they [no longer support installing NodeJS via installation script `setup_XX.x`](https://github.com/nodesource/distributions#new-update-%EF%B8%8F). This MR is to remediate above issue.

feat(ci): switch to NodeSource's supported installation

---

CHANGELOG.md
component/loki/source/docker/docker.go
component/loki/source/docker/internal/dockertarget/metrics.go
component/loki/source/docker/internal/dockertarget/target.go
component/loki/source/docker/internal/dockertarget/target_test.go
component/loki/source/docker/runner.go
docs/sources/flow/reference/components/loki.source.docker.md

This PR updates `loki.source.docker` to port the latest changes from the equivalent Promtail package.
The only change hee was commit https://github.com/grafana/loki/commit/a9268338c3561d299696c09f9544d32bf2c4006f, all previous commits were already present since Oct/Nov 2022 (our base back when we initially were porting over the Loki components).
Fixes #4843 
This also adds some new behavior, so I'm documenting the new fields.

loki.source.doker: port latest Promtail changes

---

CHANGELOG.md
component/prometheus/operator/common/crdmanager.go
component/prometheus/operator/configgen/config_gen_podmonitor.go
component/prometheus/operator/configgen/config_gen_podmonitor_test.go
component/prometheus/operator/configgen/config_gen_probe.go
component/prometheus/operator/configgen/config_gen_servicemonitor.go
component/prometheus/operator/configgen/config_gen_servicemonitor_test.go
component/prometheus/operator/types.go

Fixes #5324 
Calls the `Validate` function on the generated scrape config after generating, to make sure the Scrape Manager will be happy with it before we try.
timeout > interval is just one of the things it catches.

prometheus.exporter.*: validate scrape configs while generating

---

pkg/metrics/wal/wal.go
pkg/metrics/wal/wal_test.go

During my second or third week at Grafana, I wrote #1316 to avoid sending duplicate exemplars and putting extra load on remote write systems Now, almost two years after, it's fun having to revisit this code and reminiscing all the steps we've made to be here today. :) Just wanted to say thanks to everyone who helped on this journey. <3
Anyway, Native Histogram can have more than one exemplar on the same datapoint; if they don't have an explicit timestamp they inherit the scrape's timestamp, and this triggers the out-of-order warning on the remote write side.
Since OOO exemplars are not in the 'normal' code path, having remote writes reject them with a 4xx code makes the agent think that _all_ datapoints in that request were discarded (as there's no way for the protocol to relay partial …

pkg/metrics/wal: drop out-of-order exemplars

---

CHANGELOG.md
component/otelcol/exporter/prometheus/internal/convert/convert.go
component/otelcol/exporter/prometheus/internal/convert/convert_test.go
component/otelcol/exporter/prometheus/prometheus.go
component/otelcol/exporter/prometheus/prometheus_test.go
docs/sources/flow/reference/components/otelcol.exporter.prometheus.md

Added option add_metrics_suffixes. If set to false, type and unit suffixes will not be added to metrics. Default: true.
This option is needed for compatibility with https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter
https://github.com/grafana/agent/issues/5567

otelcol.exporter.prometheus add_metrics_suffixes option

---

CHANGELOG.md
go.mod
go.sum

This PR bumps the github-exporter to the last version (1.0.6). This is includes a fix for
a regression introduced after using the new repository of the exporter.
Fixes #5579

Bump github-exporter to 1.0.6

---

operations/helm/charts/grafana-agent/CHANGELOG.md
operations/helm/charts/grafana-agent/Chart.yaml
operations/helm/charts/grafana-agent/README.md
operations/helm/tests/clustering/grafana-agent/templates/controllers/statefulset.yaml
operations/helm/tests/controller-volumes-extra/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/create-daemonset-hostnetwork/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/create-daemonset/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/create-deployment-autoscaling/grafana-agent/templates/controllers/deployment.yaml
operations/helm/tests/create-deployment/grafana-agent/templates/controllers/deployment.yaml
operations/helm/tests/create-statefulset-autoscaling/grafana-agent/templates/controllers/statefulset.yaml
operations/helm/tests/create-statefulset/grafana-agent/templates/controllers/statefulset.yaml
operations/helm/tests/custom-config/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/default-values/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/enable-servicemonitor/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/envFrom/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/existing-config/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/extra-env/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/extra-ports/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/faro-ingress/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/global-image-pullsecrets/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/global-image-registry/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/initcontainers/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/local-image-pullsecrets/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/local-image-registry/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/nodeselectors-and-tolerations/grafana-agent/templates/controllers/daemonset.yaml
operations/helm/tests/static-mode/grafana-agent/templates/controllers/daemonset.yaml

This is the sixth step in the process of publishing the new v0.37.3 patch release
https://github.com/grafana/agent/tree/main/docs/developer/release#patch-release-publish-latest-version

helm: update agent version to v0.37.3

---

docs/sources/flow/concepts/clustering.md
docs/sources/flow/concepts/component_controller.md
docs/sources/flow/concepts/configuration_language.md
docs/sources/flow/concepts/modules.md
docs/sources/flow/monitoring/component_metrics.md
docs/sources/flow/monitoring/controller_metrics.md
docs/sources/flow/monitoring/debugging.md

Replace relrefs with docrefs in Agent concepts and Agent monitoring topics

---

component/loki/source/azure_event_hubs/internal/parser/parser.go
component/loki/source/internal/kafkatarget/authentication.go
component/loki/source/internal/kafkatarget/consumer.go
component/loki/source/internal/kafkatarget/consumer_test.go
component/loki/source/internal/kafkatarget/formatter.go
component/loki/source/internal/kafkatarget/kafkatarget.go
component/loki/source/internal/kafkatarget/kafkatarget_test.go
component/loki/source/internal/kafkatarget/target_syncer.go
component/loki/source/internal/kafkatarget/topics.go
component/loki/source/internal/kafkatarget/topics_test.go

No change found in : 
- https://github.com/grafana/loki/commits/main/clients/pkg/promtail/targets/kafka
- https://github.com/grafana/loki/commits/main/clients/pkg/promtail/targets/azureeventhubs
Since the last update that brought the azure_event_hubs component to Flow: https://github.com/grafana/agent/pull/3412
Fixes #4841 
Fixes #4849

Promtail sync loki.source.kafka and loki.source.azure_event_hubs

---

.drone/drone.yml

Looking at recent builds on main I noticed that the windows unit tests were trying to run the integration tests (https://drone.grafana.net/grafana/agent/14196/2/2).
Integration tests are not meant to run in drone for now but in github actions. This PR should fix the problem.

Remove integration-tests from windows unit tests in drone

---

CHANGELOG.md
component/discovery/discovery.go
component/loki/source/kubernetes/kubernetes.go
component/loki/source/kubernetes/kubetail/tail_utils.go
component/loki/source/kubernetes/kubetail/tail_utils_test.go
component/loki/source/kubernetes/kubetail/tailer.go
component/loki/source/podlogs/podlogs.go
component/loki/source/podlogs/reconciler.go
component/prometheus/interceptor.go
component/prometheus/operator/types.go
component/prometheus/scrape/scrape.go
component/pyroscope/scrape/scrape.go
converter/internal/prometheusconvert/component/scrape.go
docs/sources/flow/reference/components/loki.source.kubernetes.md
docs/sources/flow/reference/components/loki.source.podlogs.md
service/cluster/cluster.go

> **NOTE**: This PR is a combination of four smaller PRs, made in collaboration with @slim-bean. It'll be easier to review this PR commit-by-commit. 
This commit fixes a panic in prometheus.Interceptor where an interceptor which doesn't forward samples to another appendable panics when appending data.
Authored by @slim-bean 
Versions of Kubernetes that do not contain kubernetes/kubernetes#115702 will fail to detect rolled log files, causing the API to stop sending logs to the agent for processing.
To work around this, this commit introduces a rolling average calculator to determine the average delta between log entries per target. If 3x the normal delta time has elapsed since the last entry, the tailer is restarted.
False positives here are acceptable, but false negatives mean that log …

Flow: Improve Kubernetes log collection 

---

docs/sources/data-collection.md
docs/sources/flow/reference/cli/run.md
docs/sources/flow/setup/install/_index.md
docs/sources/static/set-up/install/_index.md

This PR moves Data Collection info to a more central location and links from install topics back to data collection.

Clarify data collection in Grafana Agent

---

CHANGELOG.md
component/loki/source/windowsevent/arguments.go
component/loki/source/windowsevent/component_test.go
component/loki/source/windowsevent/component_windows.go
converter/internal/promtailconvert/internal/build/windows_events.go
converter/internal/promtailconvert/testdata/windowsevents.river
converter/internal/promtailconvert/testdata/windowsevents_relabel.river
docs/sources/flow/reference/components/loki.source.windowsevent.md

Syncs the `loki.source.windowsevent` flow component with a [change](https://github.com/grafana/loki/pull/7462) done in promtail a few months ago. Interestingly, this config entry exists in the Agent codebase but was always set to false. I don't know why that is the case. Probably it was an oversight.
Fixes #4851

Add an "exclude_event_message" argument to loki.source.windowsevent

---

CHANGELOG.md
component/faro/receiver/internal/payload/payload.go
component/faro/receiver/internal/payload/payload_test.go
component/faro/receiver/testdata/payload.json
pkg/integrations/v2/app_agent_receiver/payload.go
pkg/integrations/v2/app_agent_receiver/payload_test.go
pkg/integrations/v2/app_agent_receiver/testdata/payload.json

This includes the measurement `type` field for Faro payloads in the flow component or the legacy integration.
Fixes https://github.com/grafana/agent/issues/5667

faro: include measurement type

---

docs/sources/flow/reference/components/otelcol.processor.k8sattributes.md

This was recently discussed [on the community slack](https://grafana.slack.com/archives/C01050C3D8F/p1697614064021499). I also raised [an issue](https://github.com/grafana/agent/issues/5631) for a feature which would make this easier.

otelcol.processor.k8sattributes: Add example with labels of Prometheus metrics

---

component/otelcol/processor/attributes/attributes_test.go
component/otelcol/processor/transform/transform_test.go
docs/sources/flow/reference/components/otelcol.processor.attributes.md
docs/sources/flow/reference/components/otelcol.processor.transform.md

Usability improvement - we can now use raw strings in River configs, so I'm updating the otelcol docs. It'll make an especially big difference to `otelcol.processor.transform`.

Use raw strings for regexes in otelcol docs

---

CHANGELOG.md
component/all/all.go
component/otelcol/processor/filter/filter.go
component/otelcol/processor/filter/filter_test.go
component/otelcol/processor/filter/types.go
docs/sources/flow/reference/components/otelcol.processor.filter.md
go.mod
go.sum

feat(comp/otelcol): component to filter OTEL telemetry

---

docs/sources/data-collection.md

This PR fixes a bad link to Flow topics. In the initial configuration the link was pointing at flow topics as if they were mounted in Cloud docs. Instead the link has to point out to the OSS docs (until the Flow topics are mounted into the Cloud doc tree again).

Fix bad links for Cloud to Flow

---

component/discovery/hetzner/hetzner.go

The type `hetzner.Role` and constants `HetznerRoleRobot` and `HetznerRoleHcloud` where not exported.
After upgrading Prometheus to last version, those are now exported, therefore we can cleanup the current
code to use the types from Prometheus.

Use types from discovery Hetzner when converting configs

---

component/common/loki/client/internal/marker_encoding.go
component/common/loki/client/internal/marker_encoding_test.go
component/common/loki/client/internal/marker_file_handler.go
go.mod
go.sum

This PR into https://github.com/grafana/agent/pull/5590 proposes a marker file format for `loki.write`. Also, it introduces a lib that allows us to write marker's atomically both in UNIX and Windows OSes.

Logs WAL marker encoding and atomic swap

---

converter/internal/staticconvert/internal/build/agent_exporter.go
converter/internal/staticconvert/internal/build/builder.go
converter/internal/staticconvert/staticconvert.go
converter/internal/staticconvert/testdata-v2/integrations_v2.river
converter/internal/staticconvert/testdata-v2/integrations_v2.yaml
converter/internal/staticconvert/testdata-v2/missing_metrics_config.diags
converter/internal/staticconvert/testdata-v2/missing_metrics_config.yaml
converter/internal/staticconvert/validate.go

This PR wires up the first integration for static converter integrations-next. It implements all the underlying shared code necessary to wire up additional integrations.

initial wiring agent integration for integration-next

---

docs/sources/flow/reference/components/pyroscope.scrape.md

See this conversation https://raintank-corp.slack.com/archives/C03NCLB4GG7/p1698431277146729 for more context
cc @korniltsev

docs(pyroscope): fixes wrong memory profiling path

---

pkg/config/agent_management_remote_config_test.go
pkg/config/agentmanagement_remote_config.go

Adds support for optional response from the API (`agent_metadata: {external_labels: {...}}`). External labels supplied by the API in this way will only add to (not override) any existing external labels.

[Agent Management] Support External Labels from API

---

README.md
docs/sources/_index.md
docs/sources/_index.md.t

As part of improving our work process, we are no longer using milestones for tracking when items get released.

misc: remove references to milestones

---

.github/workflows/helm-release.yml
.github/workflows/helm-test.yml

The current release being used, 2.4.0, doesn't work anymore.

ci: bump helm/chart-testing-action to latest release

---

component/common/loki/client/batch.go
component/common/loki/client/internal/marker_encoding.go
component/common/loki/client/internal/marker_encoding_test.go
component/common/loki/client/internal/marker_file_handler.go
component/common/loki/client/internal/marker_file_handler_test.go
component/common/loki/client/internal/marker_handler.go
component/common/loki/client/internal/marker_handler_test.go
component/common/loki/client/internal/metrics.go
component/common/loki/client/manager.go
component/common/loki/client/queue_client.go
component/common/loki/client/queue_client_test.go
component/common/loki/wal/watcher.go
component/common/loki/wal/watcher_metrics.go
component/common/loki/wal/watcher_test.go
go.mod
go.sum

This PR branches of https://github.com/grafana/agent/pull/5434, and applies the work done in https://github.com/ptodev/prometheus/pull/1 to improve two things:
1. WAL replay is implemented for `loki.write`, so upon an agent restart, it will replay "not sent" data saved in the WAL segments that are alive
2. Implement a "markers" mechanism that keeps track of which was the last consumed segment, consumed being read and delivered to the RW destination. This mechanisms works by creating a feedback loop between the side that reads from the WAL, and the side that sends batches.

Implement WAL replay and markers for `loki.write`

---

CHANGELOG.md
component/loki/source/kafka/kafka.go
component/loki/source/kafka/kafka_test.go
converter/internal/promtailconvert/internal/build/kafka.go
docs/sources/flow/reference/components/loki.source.kafka.md

The `Password` field in `kafka.go` was set to string, which caused it to be exposed. This PR fixes it by changing its type to `flagext.Secret`, which ensures that the value is not exposed directly without explicit calling to its `String()` method
- Fixes #4636

Fix the type of Password field in kafka config

---

converter/internal/staticconvert/internal/build/agent_exporter.go
converter/internal/staticconvert/internal/build/apache_exporter.go
converter/internal/staticconvert/internal/build/azure_exporter.go
converter/internal/staticconvert/internal/build/builder.go
converter/internal/staticconvert/testdata-v2/integrations_v2.river
converter/internal/staticconvert/testdata-v2/integrations_v2.yaml
converter/internal/staticconvert/validate.go
pkg/integrations/v2/metricsutils/versionshim.go

There are 2 categories of new exporter types that were wired in so I'm looking for feedback before copying the pattern to the rest.
1. apache exporter is the first case where multiple instances are allowed. I made some changes in the first commit on this PR to allow this to work smoothly
2. azure exporter is the first case that relies on a v1 integrations shim. I made changes to set this up for this exporter and future ones. See the 2nd commit for this implementation

wire up more integrations v1 exporters to integrations v2

---

CHANGELOG.md
pkg/integrations/mssql/collector_config.yaml

Adds a few new memory related metrics to the mssql integration
It doesn't 100% fix this [issue](https://github.com/grafana/support-escalations/issues/7841), but it's a kick off point before we change up the memory panels in the mixin.

Adds new memory related metrics for mssql integration

---

CHANGELOG.md
web/ui/src/features/component/ComponentList.tsx
web/ui/src/features/component/Table.module.css
web/ui/src/features/component/Table.tsx
web/ui/src/features/component/TableHead.tsx
web/ui/src/features/component/types.ts
web/ui/src/hooks/componentInfo.tsx
web/ui/src/pages/ComponentDetailPage.tsx
web/ui/src/pages/Graph.tsx
web/ui/src/pages/PageComponentList.tsx

Implements #5616 
Please check if the screen recording is as expected or something more formal needs to be done, i.e. tests
https://github.com/grafana/agent/assets/41283691/b037e1e4-efa2-47ad-b6f2-89012f3a6652

Sortable header for component list in web UI

---

CHANGELOG.md
component/common/loki/wal/watcher_metrics.go

The original issue in #5414 is easily reproducible by changing the configuration of a `loki.write` component and hitting the reload endpoint, as the NewWatcherMetrics will attempt to re-register the same set of metrics.
Fixes #5414
Another possible fix would be to create these metrics at the top-level, when creating a New component and propagate a pointer to the metrics struct down to here. Both solutions could work, but for now, this is what we've mainly been doing in loki.* components when forklifting Promtail code, so an argument can be made to leave this as-is for now to not trip off people when trying to bring new Promtail code in.

loki/wal: fix panic for duplicate registered metrics

---

docs/sources/flow/reference/components/remote.kubernetes.secret.md

The prometheus.remote_write > basic_auth > username is a string type and the agent will non start if the username is provided directly as a secret out of remote.kubernetes.secret as done in the example. nonsensitive() needs to be added to it for the config to be valid.

Fixing example in remote.kubernetes.secret.md to include nonsensitive()

---

component/common/loki/client/client.go
component/common/loki/client/manager.go
component/common/loki/client/metrics.go
component/common/loki/client/queue_client.go
component/common/loki/client/queue_client_test.go
component/common/loki/wal/watcher_metrics.go
component/common/loki/wal/writer.go
pkg/util/metrics.go

This PR adds two new metrics to the WAL enabled `loki.write`:
- last written timestamp
- last read timestamp
This will allow us to track the delay between the WAL writing and reading side, in actual time from the entries flowing through the WAL.

Added last read/wrote timestamp metrics to loki.write

---

component/prometheus/exporter/blackbox/blackbox.go
component/prometheus/exporter/blackbox/blackbox_test.go
docs/sources/flow/reference/components/prometheus.exporter.blackbox.md
docs/sources/static/configuration/integrations/blackbox-config.md
pkg/integrations/blackbox_exporter/blackbox_exporter.go

- Documentation for blackbox exporter contained some broken config examples. This PR fixes
them and clarifies some areas.
- Added validation for either specifying config file or blackbox module config content.
Fixes #5007

Clarify blackbox exporter documentation

---

operations/helm/charts/grafana-agent/CHANGELOG.md

This fixes the changelog header to match the most recent [published version](https://artifacthub.io/packages/helm/grafana/grafana-agent).

helm: Fix the CHANGELOG header for v0.27.2

---

pkg/flow/logging/level/level.go
pkg/flow/logging/logger_test.go

The recent _unreleased_ change to the logging library had a bug where in some cases the log lines would be reported as INFO, regardless of the level set.
This PR fixes this issue and adds tests.

Fix logging issue

---

CHANGELOG.md
cmd/grafana-agentctl/main.go

Set exit code 1 (instead of 0) on grafana-agentctl non-runnable command.

fix(agentctl): set exit code 1 on non-runnable command

---

CHANGELOG.md
pkg/flow/flow_updates_test.go
pkg/flow/internal/worker/worker_pool.go
pkg/flow/internal/worker/worker_pool_test.go
pkg/flow/module_test.go

The current worker pool distributes tasks among goroutines using hash of the task's key. In presence of a very slow task, e.g. due to a bug, we can have one goroutine that will be effectively stuck. All other tasks that are unfortunate to hash to the same goroutine will also be affected.
We could prevent this if we were to not rely on hash, but instead assign tasks randomly to any goroutine. The problem with this approach, however, is that a slow task may come in again and again and soon we will have every goroutine in the pool trying to execute the very slow task. So, in order to prevent this, we must only allow one task with given key to be executing at any given time. 
In this PR changes the worker pool implementation:
* We _maintain_ the existing behaviour of only one task with given …

Make worker pool more resilient to slow tasks

---

CHANGELOG.md
pkg/metrics/wal/wal.go

Port of https://github.com/prometheus/prometheus/pull/13113
N/A

Fix wrong order of exemplars vs samples

---

pkg/flow/internal/worker/worker_pool.go
pkg/flow/internal/worker/worker_pool_test.go

As discussed in [this thread](https://github.com/grafana/agent/pull/5751#discussion_r1389791081), the worker_pool queue could use linked list instead of slice. I was curious about performance and wrote a quick benchmark, which shows that as long as there are less than 100 elements in the queue, the slice implementation is faster. Given our use case, it's unlikely we'll have 100+ elements and the queue size is capped at 1024, where the performance of a slice is still going to be good-enough (~1 microsecond).

Benchmark for the queue

---

CODEOWNERS

Previously, CODEOWNERS were introduced to split PRs across the following groups:
* @grafana/grafana-agent-core-maintainers
* @grafana/grafana-agent-signals-maintainers
* @grafana/grafana-agent-operator-maintainers
* @grafana/grafana-agent-infrastructure-maintainers
However, membership of these groups is broad, with a lot of overlap. Furthermore, high PR volume meant that members of these groups had a high amount of notification noise, which makes it difficult to track what work an individual is actually responsible for.
This commit removes these four groups from CODEOWNERS, and shifts PR tracking to GitHub project boards. This reduces the notification noise of group members, and group members to more selectively choose what PRs they want to get involved in.

CODEOWNERS: remove core set of maintainers from CODEOWNERS

---

.github/workflows/test.yml

Use the new Apple silicon macOS runner when running macOS tests.
While these new runners are twice as expensive as the normal macOS runners, it is expected to be cost-neutral thanks to the speed increase.
For more information, see GitHub's announcement about the new runners: https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

ci: use Apple silicon macOS runners

---

CHANGELOG.md
component/otelcol/exporter/loadbalancing/loadbalancing.go
component/otelcol/exporter/loadbalancing/loadbalancing_test.go
docs/sources/flow/reference/components/otelcol.exporter.loadbalancing.md
docs/sources/static/configuration/traces-config.md
pkg/traces/config.go
pkg/traces/config_test.go

This feature was [added](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22776/files) to Collector version [v0.82.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.82.0), but it looks like we didn't update the components on our end to use it.

Added Kubernetes service resolver to loadbalancing exporters.

---

CHANGELOG.md

When #5678 was merged, its changelog entry went into the section for v0.37.4 instead of `main`, apologies....

Move k8s resolver change to the changelog's main branch section

---

CHANGELOG.md
packaging/grafana-agent-flow/grafana-agent-flow.river

Add needed label in default `grafana-agent-flow.river` default configuration used in downstream packages.
Fixes #5802

packaging: fix grafana-agent-flow.river (#5802)

---

CHANGELOG.md
component/module/git/git.go
component/module/git/internal/vcs/git.go

Allow `module.git` loader to use cached contents when failed to fetch during startup/update. This should be transient as the next poll interval, if fetch failure got resolved, the Git content will be up-to-date.
Fixes #5708
Do let me know if something more format is needed, like a unit test or so.

feat(module/git): allow module.git use cached content when failed to fetch

---

component/faro/receiver/handler.go

Faro introduced a header identifying the session id to collectors. This header needs to be whitelisted by the agent receiver to support people self-hosting.
Fixes: https://github.com/grafana/faro-web-sdk/issues/386

Allow x-faro-session-id header for faro receiver

---

component/pyroscope/scrape/scrape_loop.go

pyroscope.scrape: change error log level to not swallow errors

---

CHANGELOG.md
example/docker-compose/docker-compose.yaml

- Use the official HashiCorp Consul image
from https://hub.docker.com/_/consul:
> Upcoming in Consul 1.16, we will stop publishing official Dockerhub images and publish only our Verified Publisher images. Users of Docker images should pull from [hashicorp/consul](https://hub.docker.com/r/hashicorp/consul) instead of [consul](https://hub.docker.com/_/consul). Verified Publisher images can be found at https://hub.docker.com/r/hashicorp/consul.

fix: use official hashicorp consul image

---

docs/sources/operator/helm-getting-started.md

Links not displaying correctly, due to concatenation of two markdown elements.
Backticks should be used inside the link text, to properly be displayed as inline code style, while still preserving the link element.
This PR fixes these two entries.

Fixed the url links

---

CHANGELOG.md
go.mod
go.sum

This PR updates pyroscope ebpf depdendency to include this PR https://github.com/grafana/pyroscope/pull/2703 which brings support for python profiling on arm64 glibc platforms and arm64 musl libc platforms

fix(pyroscope.ebpf): add python arm64 support

---

CHANGELOG.md
component/otelcol/exporter/prometheus/internal/convert/convert.go
component/otelcol/exporter/prometheus/internal/convert/convert_test.go
component/otelcol/exporter/prometheus/prometheus.go
component/otelcol/exporter/prometheus/prometheus_test.go
docs/sources/flow/reference/components/otelcol.exporter.prometheus.md

Support conversion of OTEL's resource attributes to Prometheus-compatible datapoint attributes. Strongly inspired by [OTEL's contributor implementation](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/a80edda1860b50fde9a2e7d6d9df9152cc49e87c/pkg/resourcetotelemetry/resource_to_telemetry.go#L20)
Closes #5631

feat(otelcol/exp/prom): add support for resource_to_telemetry_conversion

---

CHANGELOG.md
component/prometheus/operator/common/crdmanager.go
component/prometheus/operator/common/crdmanager_test.go
component/prometheus/operator/common/interfaces.go

Fixes #5679 
Fixes #5839
Switch from doing a prefix match on job names to just storing which jobs are associated with a given crd.
We make less assumptions this way.
Thank you to @Paul424 for #5844, which did the main discovery, and is the core of this PR.

prometheus.operator.* - Fix issue with missing targets when one monitor's name is a prefix of another

---

docs/sources/flow/reference/components/prometheus.exporter.windows.md
go.mod
go.sum

This updates windows_exporter to a version that handles the process config correctly and no longer lets a nil slip through.
Fixes #5855
Ran with the default configuration for all  the available collectors except for the ones mentioned in the admonition since those caused panics when calling underlying windows layer.
Did not update the changelog since it falls under my previous change of fixing defaults.

Add fix for process and include details on crash behavior.

---

docs/sources/flow/reference/config-blocks/http.md

The flow `http` module docs referenced the `client_auth` configuration incorrectly. Referencing the code directly you'll see the [configuration](https://github.com/rfratto/agent/blob/0bd12997ae23e5f09ca76fa0dfcf4a8e6c99b25e/service/http/tls.go#L22) is actually `client_auth_type`
Trying to start the server with `client_auth` in the `tls` block results in the following error:
```
decoding River: /var/lib/grafana-agent/config/agent.river:12:5: unrecognized attribute name "client_auth"
```

fix: Documentation references of client_auth in flow http client.

---

CHANGELOG.md
docs/sources/data-collection.md
internal/useragent/useragent.go
internal/useragent/useragent_test.go
pkg/usagestats/stats.go

With 0.38.0 we added a deploy mode to the user agent, and added ways to set it, but we did not add it to the usage stats, which would be very useful. This adds it.
Also makes a best-effort attempt to detect homebrew installs, by looking t the executable path.

Add Deploy Mode to usage stats.

---

CHANGELOG.md
component/pyroscope/ebpf/ebpf_linux.go
component/pyroscope/ebpf/ebpf_linux_test.go
go.mod
go.sum

Bum pyroscope ebpf dependency to include fixes for issues https://github.com/grafana/pyroscope/pull/2788 (causing unoptimal pprof profiles for python profiles) and https://github.com/grafana/pyroscope/pull/2778 (causing mem leak  preventing profiling regular processes istead of kthreads)

pyroscope.ebpf: update dependency 

---

docs/sources/flow/reference/components/otelcol.processor.filter.md

Remove doc ref for a unusable ref for `otelcol.processor.filter` metric block
Fixes #5907

doc(flow/ref/comp): remove nonsensical ref in otelcol.processor.filter

---

component/common/loki/client/internal/marker_file_handler.go
component/common/loki/client/internal/marker_file_handler_test.go
integration-tests/tests/otlp-metrics/otlp_metrics_test.go
integration-tests/tests/read-log-file/read_log_file_test.go
integration-tests/tests/scrape-prom-metrics/scrape_prom_metrics_test.go

Fixes broken windows tests possibly coming from: https://github.com/grafana/agent/pull/5590 & https://github.com/grafana/agent/pull/5753
We will want to follow up on the second one which is disabled for windows in this PR to get CI working again.

Fix windows tests that are failing CI on main

---

component/faro/receiver/sourcemaps.go
go.mod
go.sum
pkg/integrations/v2/app_agent_receiver/utils.go
pkg/util/wildcard/match.go
pkg/util/wildcard/match_test.go

Turns out vendored minio dep used for faro receiver has AGPL license. This PR removes the dependency, instead copying in relevant code from older Apache licenesed version of minio.

chore(deps): remove minio dependency

---

pkg/flow/flow.go
pkg/flow/internal/controller/loader.go

This PR just renames one function.
In this case we don't evaluate the dependencies, we evaluate the dependants of the updated nodes.
From the dag definition:
// Dependants returns the list of Nodes that depend on n: all Nodes for which an edge to n is defined.
func (g *Graph) Dependants(n Node) []Node
// Dependencies returns the list of Nodes that n depends on: all Nodes for which an edge from n is defined.
func (g *Graph) Dependencies(n Node) []Node

Rename EvaluateDependencies to EvaluateDependants

---

CHANGELOG.md
component/otelcol/connector/servicegraph/servicegraph.go
component/otelcol/connector/servicegraph/servicegraph_test.go
docs/sources/flow/reference/components/otelcol.connector.servicegraph.md

This PR updates the default store ttl for this component from 2ms to 2s.
See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29723

otelcol.connector.servicegraph: update default store ttl value

---

CHANGELOG.md
component/prometheus/exporter/blackbox/blackbox.go
component/prometheus/exporter/blackbox/blackbox_test.go
converter/internal/staticconvert/internal/build/blackbox_exporter.go
converter/internal/staticconvert/testdata-v2/integrations_v2.river
converter/internal/staticconvert/testdata/integrations.river
docs/developer/writing-exporter-flow-components.md
docs/sources/flow/reference/components/prometheus.exporter.blackbox.md
docs/sources/flow/release-notes.md

Fixes #5940 
Should this be a breaking change? I gave it some thoughts and unless we specify an interface to allow interchangeability (which is awkward, IMO), breaking change it is since `label` block is mandatory atm.

feat!(exporter/blackbox): use required name attr instead label for target block

---

docs/sources/flow/_index.md
docs/sources/flow/getting-started/_index.md
docs/sources/flow/getting-started/configure-agent-clustering.md
docs/sources/flow/getting-started/migrating-from-operator.md
docs/sources/flow/getting-started/migrating-from-prometheus.md
docs/sources/flow/getting-started/migrating-from-promtail.md
docs/sources/flow/getting-started/migrating-from-static.md
docs/sources/flow/monitoring/_index.md
docs/sources/flow/monitoring/debugging.md
docs/sources/flow/reference/_index.md
docs/sources/flow/reference/cli/_index.md
docs/sources/flow/release-notes.md
docs/sources/flow/setup/_index.md
docs/sources/flow/setup/configure/_index.md
docs/sources/flow/setup/configure/configure-kubernetes.md
docs/sources/flow/setup/configure/configure-linux.md
docs/sources/flow/setup/configure/configure-macos.md
docs/sources/flow/setup/configure/configure-windows.md
docs/sources/flow/setup/install/_index.md
docs/sources/flow/setup/install/binary.md
docs/sources/flow/setup/install/docker.md
docs/sources/flow/setup/install/kubernetes.md
docs/sources/flow/setup/install/linux.md
docs/sources/flow/setup/install/macos.md
docs/sources/flow/setup/install/windows.md
docs/sources/flow/setup/start-agent.md

The table of contents is generated during Markdown processing and shortcodes with `{{< VAR_NAME >}}` syntax haven't been rendered at that point.
Recent changes to use a cascading variable for the Grafana Agent Flow product name use the `{{< VAR_NAME >}}` shortcode in many of the headings. The result is the heading anchor link URLs contain `hahahugoshortcodes0hbhb` in place of `Grafana Agent Flow`
To fix this we have to use `{{% VAR_NAME %}}` shortcode syntax in the headings only. This tells Hugo to render the shortcode before the markdown... and...  anchor link URLs look normal.

Replace < with % in var references in headings

---

docs/sources/flow/_index.md
docs/sources/flow/getting-started/_index.md
docs/sources/flow/getting-started/configure-agent-clustering.md
docs/sources/flow/getting-started/migrating-from-operator.md
docs/sources/flow/getting-started/migrating-from-prometheus.md
docs/sources/flow/getting-started/migrating-from-promtail.md
docs/sources/flow/getting-started/migrating-from-static.md
docs/sources/flow/monitoring/_index.md
docs/sources/flow/monitoring/debugging.md
docs/sources/flow/reference/_index.md
docs/sources/flow/reference/cli/_index.md
docs/sources/flow/release-notes.md
docs/sources/flow/setup/_index.md
docs/sources/flow/setup/configure/_index.md
docs/sources/flow/setup/configure/configure-kubernetes.md
docs/sources/flow/setup/configure/configure-linux.md
docs/sources/flow/setup/configure/configure-macos.md
docs/sources/flow/setup/configure/configure-windows.md
docs/sources/flow/setup/install/_index.md
docs/sources/flow/setup/install/binary.md
docs/sources/flow/setup/install/docker.md
docs/sources/flow/setup/install/kubernetes.md
docs/sources/flow/setup/install/linux.md
docs/sources/flow/setup/install/macos.md
docs/sources/flow/setup/install/windows.md
docs/sources/flow/setup/start-agent.md

(cherry picked from commit 7e0bf25ed090a92d235b506aa021605be7f25e0f)
Cherry pick 7e0bf25ed090a92d235b506aa021605be7f25e0f

Replace < with % in var references in headings (#5975)

---

cmd/internal/flowmode/cmd_convert.go
cmd/internal/flowmode/cmd_convert_test.go

fix for static mode extra-args

---

component/remote/vault/vault_test.go
pkg/operator/build_hierarchy_test.go
pkg/operator/hierarchy/hierarchy_test.go
pkg/operator/kubelet_test.go
pkg/operator/operator_test.go
pkg/util/k8s/k8s_test.go

The [commented issue](https://github.com/testcontainers/testcontainers-go/issues/1359) has been fixed in testcontainers-go v0.25.0, which is already present in `go.mod`
N/A
N/A
N/A

chore: re-enable K8s-related unit tests

---

component/remote/vault/vault_test.go
pkg/operator/build_hierarchy_test.go
pkg/operator/hierarchy/hierarchy_test.go
pkg/operator/kubelet_test.go
pkg/operator/operator_test.go
pkg/util/k8s/k8s_test.go

This reverts commit a964cae6c8b379dc68e13001235d38b03765ba77.

Revert "chore: re-enable K8s-related unit tests (#5944)"

---

docs/sources/flow/reference/components/prometheus.scrape.md
go.mod

Thanks to @Gusser93's discovery, the doc reference on `__param_` is incorrect. [Prometheus's doc for reference](https://github.com/prometheus/prometheus/blob/5d5303c746a4609520cd3d910fd445596fb86522/docs/configuration/configuration.md?plain=1#L3185)
Fixes #5995

doc(prom/scrape): correct reference for `__param_` label in

---

docs/README.md
docs/developer/writing-docs.md
docs/sources/flow/_index.md

Adds a description of the new docs hierarchy that matches the input from discussion on https://github.com/grafana/agent/issues/5949
After merging, the next step will be to actually do the reorg using the existing documentation pages. We'll put existing pages in their best fitting new categories, even if they're not 100% compliant to start with - we'll be cleaning them up afterwards. And we'll be able to add new content, e.g. in the Tasks section.

Docs reorg: part 1: add section definitions

---

CHANGELOG.md
component/prometheus/exporter/kafka/kafka.go
component/prometheus/exporter/kafka/kafka_test.go
converter/internal/staticconvert/internal/build/kafka_exporter.go

Use rivertypes.Secret for sensitive fields instead of Prometheus' secret type.
I checked other components for this specific issue and didn't find anything. 
Fixes #6044.

prometheus.exporter.kafka: use correct secret type

---

converter/internal/staticconvert/internal/build/builder.go
converter/internal/staticconvert/internal/build/eventhandler.go
converter/internal/staticconvert/testdata-v2/integrations_v2.river
converter/internal/staticconvert/testdata-v2/integrations_v2.yaml
converter/internal/staticconvert/testdata-v2/unsupported.diags
converter/internal/staticconvert/testdata-v2/unsupported.river
converter/internal/staticconvert/testdata-v2/unsupported.yaml
converter/internal/staticconvert/validate.go

Wire up for eventhandler integration in the static to flow converter

---

CHANGELOG.md
pkg/integrations/windows_exporter/windows_exporter_windows.go

The perflib query wasnt being set. It isnt upstream either but have a PR to fix their issue too. This means the perflib will try to grab everything which can lead to timeouts.
Fixes https://github.com/grafana/agent/issues/6036
Fixes https://github.com/grafana/agent/issues/6034
Fixes https://github.com/grafana/agent/issues/6004

Add call to set the perflib query.

---

CHANGELOG.md
component/discovery/kubelet/kubelet.go
component/discovery/kubelet/kubelet_test.go
docs/sources/flow/reference/components/discovery.kubelet.md

Previously, any paths added to the `url` argument of `discovery.kubelet` was overwritten with `/pods`. This prevented using urls to the Kubelet that required paths (e.g. using an API server proxy). This change appends `/pods` to the end of the URL, rather than assigning it as the path.
Fixes #5625

Append, rather than set, '/pods' to the path in discovery.kubelet

---

CHANGELOG.md
docs/sources/_index.md
docs/sources/_index.md.t

Updates documentation to remove support for windows 2012 in line with [microsoft guidelines](https://learn.microsoft.com/en-us/lifecycle/announcements/windows-server-2012-r2-end-of-support) on Oct 2023. Also did minor cleanup of changelog file.

remove windows 2012 support

---

docs/sources/flow/reference/components/otelcol.exporter.loadbalancing.md
docs/sources/flow/setup/deploy-agent.md
docs/sources/static/configuration/traces-config.md
docs/sources/static/set-up/deploy-agent.md

When load balancing traces over multiple Agent instances, there are lots of potential issues that our users need to watch out for. These docs updates go into detail and provide examples. 
Some things are still not complete:
- I still have to add some more info regarding Static mode.
- Ideally we could also add pictures with the architecture.
- I need to make a working Static config which uses the Kubernetes resolver.
- I'm still not sure if the locations in the docs which I edited are the most appropriate ones. Especially the "Deploy Grafana Agent" page.

Explain tracing load balancing in more detail

---

CHANGELOG.md
Makefile
component/loki/source/docker/docker.go
component/loki/source/docker/docker_test.go
docs/sources/flow/reference/components/loki.source.docker.md

The `discovery.docker` component was initially built with Prometheus service discovery in mind; this means that it will report a different target for each port, network and network interface that a container exposes/belongs to, so that it can be scraped accordingly.
This means, that when `discovery.docker` is used as an input to loki.source.docker, it will set up unnecessary load on the Docker API by trying to fetch logs for the same container ID multiple times. This PR makes it so that during a component Update, the targets are deduplicated based on the container ID, keeping only the first one.
Related to: #4403
I'd like to gather some more evidence until we say this fixes #4403 outright, so keeping this PR in draft in the meantime.
I've run a simplistic benchmark with a chatty container …

loki.source.docker: deduplicate matching container IDs

---

CHANGELOG.md
component/prometheus/exporter/kafka/kafka.go
component/prometheus/exporter/kafka/kafka_test.go
pkg/integrations/kafka_exporter/kafka_exporter.go

prometheus.exporter.kafka `instance` option is ignored in river.config.
I'm trying to start grafana-agent with a simple config, where kafka_uris has more than 1 node:
```
prometheus.exporter.kafka "LABEL" {
kafka_uris = ["kafka1:9092", "kafka2:9092"]
instance = "test-instance"
}
```
Getting error message:
```
Error: /etc/agent/config.river:1:1: Failed to build component: building component: an automatic value for `instance` cannot be determined from 2 kafka servers, manually provide one for this integration
1 |   prometheus.exporter.kafka "LABEL" {
|  _^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2 | |     kafka_uris = ["kafka1:9092", "kafka2:9092"]
3 | |     instance = "test-instance"
4 | | }
| |_^
5 |
```
`instance` option is ignored.
The proposed PR fixes things for me.

prometheus.exporter.kafka: fix for  config option is ignored

---

docs/sources/static/set-up/install/install-agent-kubernetes.md

This commit modifies the Kubernetes installation instructions for static mode to use the Grafana Agent Helm chart instead of the abandoned production/kubernetes manifests.
This change needs to be backported pretty far back. References to the old folder exist as far back as v0.25, but we should only backport this as far back as the introduction of Flow mode, and find an alternative for versions prior to that (such as version pinning the old directory instead of having it use the main branch). 
Related to #6077.

docs: remove reference to production/kubernetes

---

docs/sources/_index.md
docs/sources/static/set-up/install/install-agent-kubernetes.md

As part of #6077, folders referenced by older versions of documentation will no longer work when pointing to the main branch. These links are now being pinned to the agent version that the versioned documentation is associated with.
This PR will be backported all the way to v0.25, but each backport will require a small amount of changes to modify the cascade variable.

[release-v0.36] docs: pin version to removed folders

---

docs/sources/flow/reference/components/otelcol.exporter.prometheus.md

Fixes #5986
`resource_to_telemetry_conversion` is generally not what the users want to use. This makes it a bit more clear.
We can also backport this to v0.39, once it's available.

Clarify usage of resource_to_telemetry_conversion

---

docs/sources/flow/reference/components/pyroscope.scrape.md

Adding extra information which me and @thampiotr recently learned while tweaking Agents running `pyroscope.scrape`.
The PR also cleans up the docs in general.
I am not sure who should review this PR from the Docs squad. IIUC @clayton-cornell is normally helping with Agent docs whereas @knylander-grafana usually helps with Pyroscope docs :)

Improve the docs of pyroscope.scrape

---

docs/sources/_index.md
docs/sources/static/set-up/install/install-agent-kubernetes.md

As part of #6077, folders referenced by older versions of documentation will no longer work when pointing to the main branch. These links are now being pinned to the agent version that the versioned documentation is associated with.

[release-v0.34] Backport 6096 to release v0.34

---

docs/sources/_index.md
docs/sources/set-up/_index.md

As part of #6077, folders referenced by older versions of documentation will no longer work when pointing to the main branch. These links are now being pinned to the agent version that the versioned documentation is associated with.

[release-v0.32] docs: pin version to removed folders

---

CHANGELOG.md
pkg/metrics/agent_test.go
pkg/metrics/http.go
pkg/metrics/instance/instance.go
pkg/metrics/instance/instance_test.go
pkg/metrics/instance/manager.go
pkg/metrics/instance/manager_test.go
pkg/metrics/instance/noop.go

This PR circumvents a duplicate metrics registration panic that appeared in v0.37 in static mode.
> NOTE: This PR can be more easily reviewed commit-by-commit.
When calling the `/agent/api/v1/metrics/instance/{instance}/write` endpoint to push metrics directly into a metrics instance's WAL in static mode, the PushMetricsHandler used to recreate the prometheus write handler every time.
Since a metrics was introduced to keep track of invalid samples in the upstream Prometheus code meant that on every subsequent call, a panic was raised.
The fix here is to create and store the write handler once when the metrics instance is first initialized and introducing a new method on the Instance interface to fetch it whenever metrics are pushed. A test has been amended to make sure that re-creating a …

pkg/metrics: fix a panic when accepting network remote write requests

---

CHANGELOG.md
go.mod
go.sum

Bump a dependancy `github.com/grafana/pyroscope-go` to v0.1.6, which supports Go 1.22 since https://github.com/grafana/pyroscope-go/pull/55.
* fixes #6138

Bump grafana/pyroscope-go to v0.1.6 to support Go 1.22

---

operations/helm/charts/grafana-agent/CHANGELOG.md
operations/helm/charts/grafana-agent/README.md
operations/helm/charts/grafana-agent/ci/topologyspreadconstraints-values.yaml
operations/helm/charts/grafana-agent/templates/controllers/_pod.yaml
operations/helm/charts/grafana-agent/values.yaml
operations/helm/tests/topologyspreadconstraints/grafana-agent/templates/configmap.yaml
operations/helm/tests/topologyspreadconstraints/grafana-agent/templates/controllers/deployment.yaml
operations/helm/tests/topologyspreadconstraints/grafana-agent/templates/rbac.yaml
operations/helm/tests/topologyspreadconstraints/grafana-agent/templates/service.yaml
operations/helm/tests/topologyspreadconstraints/grafana-agent/templates/serviceaccount.yaml

Adds configuration to support topology spread constraints in the helm chart useful for deployment or statefulset controller types.
This allows pods to be distributed evenly across availability zones for example.
Fixes #5939

feat(operations/helm) add topology spread constraints

---

pkg/metrics/instance/instance_test.go

Last PR that fixed the static mode write handler introduced a flaky test.
I'm removing the offending condition so that we don't break everyone's macOS runners and see if it makes sense to introduce something else in its place in an upcoming PR.

Remove flaky test condition for static mode write handler

---

CHANGELOG.md
packaging/grafana-agent-flow/windows/install_script.nsis

Previously if the environment var existed the installer would fail. Likely in asking for confirmation to overwrite. This follows the pattern of Arguments reg key
Fixes #6179

add nsis check for environment var

---

CHANGELOG.md
pkg/flow/internal/controller/loader.go
pkg/flow/module_eval_test.go

* Add a test in the first commit
* Add a fix in the second commit
Fixes #6199
Wrote a slightly different, smaller test than the draft branch mentioned on the issue.
Before the fix, running `go test ./pkg/flow/ -count 10 -test.run "TestUpdates_TwoModules*"` would usually catch the bug:
```
--- FAIL: TestUpdates_TwoModules_SameCompNames (3.01s)
module_caching_test.go:200:
Error Trace:	/Users/piotr/workspace/agent/pkg/flow/module_caching_test.go:200
Error:      	Condition never satisfied
Test:       	TestUpdates_TwoModules_SameCompNames
FAIL
FAIL	github.com/grafana/agent/pkg/flow	19.395s
FAIL
```
After the fix, it doesn't fail.

Fix non-unique ID used in worker pool

---

CHANGELOG.md
docs/sources/flow/release-notes.md
pkg/flow/internal/controller/loader.go
pkg/flow/module_test.go

Services should only be configurable within the main config. A module should not have the possibility to modify the behavior of a service running at root level. In this PR, I added a check to prevent this from happening.
Fixes #6174

Prohibit the configuration of services within modules

---

go.mod
go.sum

This upgrade bring this one [change](https://github.com/grafana/river/pull/41) which is needed for the UI of the new modules .
Closes #3244.

Upgrade river dependency to main

---

component/otelcol/processor/processortest/compare_signals.go
component/otelcol/processor/processortest/compare_signals_test.go
component/otelcol/processor/processortest/processortest.go
go.mod

This fixes occurrences of flaky tests such as [this one](https://github.com/grafana/agent/actions/runs/7488444309/job/20382930718?pr=6111#step:4:246) and [this one](https://drone.grafana.net/grafana/agent/15864/5/2). I am also attaching printouts of those two failed tests, in case the links are no longer valid one day:
[flaky_test_1.txt](https://github.com/grafana/agent/files/14027178/flaky_test_1.txt)
[flaky_test_2.txt](https://github.com/grafana/agent/files/14027180/flaky_test_2.txt)

Ignore order or OTLP resources in tests.

---

docs/rfcs/0000-template.md
docs/rfcs/0001-designing-in-the-open.md
docs/rfcs/0002-integrations-in-operator.md
docs/rfcs/0003-new-metrics-subsystem.md
docs/rfcs/0004-agent-flow.md
docs/rfcs/0005-river.md
docs/rfcs/0006-clustering.md
docs/rfcs/0006-future-of-agent-operator.md
docs/rfcs/0007-flow-modules.md
docs/rfcs/0008-backwards-compatibility.md

We haven't been updating the status line from RFCs to reflect their current status. This commit removes the status line from every RFC, with the exception of RFC-0003 which has been explicitly abandoned in favor of flow mode.

docs/rfcs: remove Status line from RFCs

---

docs/sources/flow/tutorials/flow-by-example/_index.md

Previously, "Flow by example" was sandwiched between two non-folder tutorials.
Before and after:

docs: move "Flow by example" folder to top of tutorials list

---

CHANGELOG.md
operations/agent-flow-mixin/alerts/clustering.libsonnet

- Removed `ClusterLamportClockDrift` and `ClusterLamportClockStuck` alerts from
Grafana Agent Mixin to focus on alerting on symptoms.
- Increased clustering alert periods to 10 minutes to improve the
signal-to-noise ratio in Grafana Agent Mixin.
Based on internal team discussion.

Tweak clustering alerts

---

docs/sources/operator/getting-started.md

This PR updates the documented URL for the Agent Operator CRDs

Update URL destination for Agent Operator CRDs

---

docs/sources/flow/_index.md

This PR removes the `{{< param "PRODUCT_NAME" >}}` Hugo shortcode from headings. If we use this shortcode in the heading text Hugo rewrites the anchor to say `#hahahugoshortcodes3hbhb` wherever the shortcode is used.

Fix heading remove variable

---

operations/agent-flow-mixin/dashboards.libsonnet
operations/agent-flow-mixin/dashboards/opentelemetry.libsonnet

The mixin for Static mode already has a few dashboards. This PR adds the same ones + a few more to the Flow mixin.
For now the dashboards are mostly tracing-specific. Over time we will add logs and metrics support. We will also add dashboards for more components.

Add OpenTelemetry dashboards to the Flow mixin

---

operations/agent-flow-mixin/dashboards/prometheus.libsonnet

This is an unreleased feature, so no need to update the changelog. 
* The % Y axis used a fraction not multiplied by 100.
* Added the `in <cluster>` to make it a bit more clear how the chart doesn't take into account other dash template variables from drop-downs.

Fix wrong Y axis on new chart

---

CHANGELOG.md
component/otelcol/config_debug_metrics.go
component/otelcol/exporter/loadbalancing/loadbalancing.go
component/otelcol/exporter/loadbalancing/loadbalancing_test.go
component/otelcol/exporter/logging/logging.go
component/otelcol/exporter/otlp/otlp.go
component/otelcol/exporter/otlp/otlp_test.go
component/otelcol/exporter/otlphttp/otlphttp.go
component/otelcol/exporter/otlphttp/otlphttp_test.go
docs/sources/flow/release-notes.md
docs/sources/shared/flow/reference/components/otelcol-debug-metrics-block.md

In #4769, I suggested that `disable_high_cardinality_metrics` default to `false` for a few reasons:
- Agent Flow was already showing high cardinality metrics, and removing them would have been a breaking change.
- OTel Collector enables these high cardinality metrics by default.
Unfortunately, it seems that those high cardinality metrics seem to really cause an understandable inconvenience for users. In the spirit of providing good defaults, it'd be best to exclude such metrics by default.
This will also simplify Static mode -> Flow converters, because high cardinality metrics are already disabled by default in Static mode.
I suspect that one day OTel Collector will have to also exclude these metrics by default. At the moment it's not a huge issue for the Collector, because you'd have to …

Change the default value of disable_high_cardinality_metrics to "true".

---

CHANGELOG.md
go.mod
go.sum

Fixes #6264 
This points our repo at [this branch](https://github.com/grafana/prometheus/tree/cmp_header_order) which is based off the branch we are previously pointed at.
Once https://github.com/prometheus/prometheus/pull/13497 is merged, we can restore agent to mainline prometheus.

fix for errors sending to amazon prometheus

---

integration-tests/common/metric.go
integration-tests/common/metrics_assert.go
integration-tests/utils.go

This PR brings two improvements:
- fix the bug where the log channel would be left open when running a single test, resulting in a deadlock
- add a check to verify whether all expected metrics are stored in Mimir. This is helpful when debugging tests that have a lot of metrics (see: https://github.com/grafana/agent/pull/6269/files#diff-bb1325adc8282ffc9334543dfce1011becc1ab20bd04a4358b8af96336f60d87)

Integration tests improvements

---

CHANGELOG.md
cmd/internal/flowmode/cmd_run.go

I am explicitly not listing the settings in the docs at this time, since we may figure out the default is good enough and can ignore using them.

Set mutex and block profiling

---

CHANGELOG.md
component/prometheus/scrape/scrape.go
component/prometheus/scrape/scrape_test.go
converter/internal/prometheusconvert/component/scrape.go
converter/internal/prometheusconvert/testdata/scrape.river
docs/sources/flow/reference/components/prometheus.scrape.md

Added upstream 4 months ago: https://github.com/prometheus/prometheus/pull/13060
#5921
I have cherry-picked the commit originally in #5972; I did not yet change the default to true, because I'm unsure where that would go.
- NA Config converters updated - this was done previously

Add track_timestamps_staleness

---

build-image/Dockerfile
build-image/windows/Dockerfile

Update build-image to use Go 1.22. Other instances of the Go version will be updated in a follow up PR that updates our CI to use the new build-image.

build-image: bump Go to 1.22

---

CHANGELOG.md
component/discovery/discovery.go
component/loki/source/podlogs/reconciler.go

fix(comp): prevent divide-by-zero error when calculating array size for sharded targets

---

CHANGELOG.md
docs/sources/flow/reference/components/prometheus.exporter.mssql.md
docs/sources/static/configuration/integrations/mssql-config.md

Updates MSSQL Integration documentation to explicitly mention some of the windows authentication options that can be used within the `connection_string` config param for both static and flow modes.
NA

MSSQL Integration - Update documentation with extra windows authentication details

---

CHANGELOG.md
cmd/internal/flowmode/cmd_run.go
docs/sources/flow/reference/config-blocks/remotecfg.md
go.mod
go.sum
pkg/flow/flow_services.go
service/http/http_test.go
service/remotecfg/noop.go
service/remotecfg/remotecfg.go
service/remotecfg/remotecfg_test.go
service/service.go

This PR introduces a new service that makes it possible for Grafana Agent to run configuration fetched via a remote endpoint.
The PR is more easily reviewable going commit-by-commit.
My main concern is whether the instantiation of the new controller makes sense, both now and long term with the upcoming redesign of Modules.

Introduce remotecfg service

---

converter/internal/staticconvert/internal/build/eventhandler.go
converter/internal/staticconvert/testdata-v2/unsupported.diags
docs/sources/flow/reference/components/loki.source.docker.md
docs/sources/flow/reference/components/loki.source.file.md
docs/sources/flow/reference/components/loki.source.kubernetes_events.md

The static mode integration for k8s events has a `cache_path` argument which Flow mode doesn't have. These changes make it more clear to the users why such an argument is missing from Flow mode.

Docs for k8s event logs: clarify equivalent of Static mode's cache_path in Flow mode.

---

component/loki/source/docker/internal/dockertarget/target_test.go

This test has a flaky test which sometimes triggers a data race warning: https://drone.grafana.net/grafana/agent/16422/1/2.
I could not reproduce the race locally.
I noticed that Stop() is already called in processLoop function which sets the readiness to false when it exits.
In the test I added a readiness check before performing a restart.

Dockertarget test: fix data race

---

cmd/internal/flowmode/cmd_run.go
pkg/flow/flow_services.go
service/http/http_test.go
service/remotecfg/remotecfg_test.go
service/service.go
service/ui/ui.go
web/api/api.go

This PR enables the Host interface to access other running services. Currently, this simplifies the handling around the UI service and the cluster.Cluster interface it calls to, but in the future this can also help the remotecfg service populate some UI interface.
cc @rfratto from a TODO comment as he's already thought about this in the past.

Allow the Host interface to return services.

---

pkg/metrics/instance/instance_integration_test.go

This test would sometimes not pass on windows, making our main build fail (see https://drone.grafana.net/grafana/agent/16444/2/2).
When testing I also noticed that when running it many times on Mac it would also fail.
The fix makes sure that the context is properly canceled before exiting the test

Fix flaky test metrics pkg

---

pkg/flow/internal/controller/component_node_manager.go
pkg/flow/internal/controller/custom_component_registry.go
pkg/flow/internal/controller/loader.go

Fix two data races with mutex.

Fix two data races in declare tests

---

docs/sources/flow/reference/components/loki.process.md

This was a source of confusion (#4337) and took a while to identify. It's not very obvious...

Mention `stage.pack` in the `stage.timestamp` docs.

---

component/discovery/process/discover.go

Quite common with docker container UIDs not resolving on the host or in  another container.
This will basically move on in those cases, rather than dropping the whole process.
Unsure if this should also be a lower level log message, potentially only debug.

discovery.process: Accept failing username detection

---

.github/workflows/autolock.yml

Old issues and PRs occasionally get comments well after they have been closed. These comments can lead to community frustration, as closed issues and PRs aren't actively monitored.
This commit introduces a new CI job to automatically lock closed issues and PRs after 30 days of inactivity. A `frozen-due-to-age` label is added to denote why the issue has been locked.
This CI job is deliberately configured to silently close issues without adding a comment to avoid notification noise for maintainers; adding a label takes the place of a comment.

ci: autolock closed issues and PRs after 30 days

---

docs/sources/flow/reference/components/prometheus.remote_write.md
docs/sources/shared/flow/reference/components/write_relabel_config.md

Signed-off-by: Paschalis Tsilias <paschalist0@gmail.com>
(cherry picked from commit 92dd33b3533767479a13a04aa6ddc9ee02cdaef2)
Backport https://github.com/grafana/agent/commit/92dd33b3533767479a13a04aa6ddc9ee02cdaef2 from https://github.com/grafana/agent/pull/6395

[release-v0.38] docs: fix write_relabel_config block reference (#6395)

---

integration-tests/README.md
integration-tests/tests/unix/unix_metrics_test.go
integration-tests/utils.go

The test does not run on darwin OS because of the component prometheus.exporter.unix not exporting the expected metrics.

Restrict unix integration-test to run on linux only

---

converter/internal/otelcolconvert/converter_helpers.go
converter/internal/otelcolconvert/converter_kafkareceiver.go
converter/internal/otelcolconvert/testdata/kafka.river
converter/internal/otelcolconvert/testdata/kafka.yaml

Converting this component is more complicated than other receivers due to its usage of internal struct types. We work around internal structs by converting to `map[string]any` when necessary, including a conversion back to a concrete struct type where it's exposed to us.
Due to the nature of this component using internal types, the test covers more fields than normal to ensure the mapstructure usage is correct.
Closes #6425.

otelcolconvert: support converting kafkareceiver

---

converter/internal/common/river_utils.go
converter/internal/common/river_utils_test.go
converter/internal/otelcolconvert/converter_jaegerreceiver.go
converter/internal/otelcolconvert/converter_kafkareceiver.go
converter/internal/otelcolconvert/converter_opencensusreceiver.go
converter/internal/otelcolconvert/converter_otlpexporter.go
converter/internal/otelcolconvert/converter_otlpreceiver.go
converter/internal/otelcolconvert/converter_zipkinreceiver.go

Follow up on https://github.com/grafana/agent/pull/6464#discussion_r1498140245

otelcolconvert: automatically sync DebugMetrics with Flow defaults

---

CHANGELOG.md
component/all/all.go
component/otelcol/connector/host_info/config.go
component/otelcol/connector/host_info/config_test.go
component/otelcol/connector/host_info/connector.go
component/otelcol/connector/host_info/connector_test.go
component/otelcol/connector/host_info/factory.go
component/otelcol/connector/host_info/factory_test.go
component/otelcol/connector/host_info/grafanacloud.go
component/otelcol/connector/host_info/grafanacloud_test.go
component/otelcol/connector/host_info/host_metrics.go
component/otelcol/connector/host_info/host_metrics_test.go
docs/sources/flow/reference/compatibility/_index.md
docs/sources/flow/reference/components/otelcol.connector.host_info.md
go.mod

Introduce `otelcol.connector.host_info` component.

Add `otelcol.connector.host_info` component

---

component/otelcol/receiver/jaeger/jaeger.go
component/otelcol/receiver/jaeger/jaeger_test.go
component/otelcol/receiver/kafka/kafka.go
component/otelcol/receiver/kafka/kafka_test.go
component/otelcol/receiver/opencensus/opencensus.go
component/otelcol/receiver/opencensus/opencensus_test.go
component/otelcol/receiver/otlp/otlp.go
component/otelcol/receiver/otlp/otlp_test.go
component/otelcol/receiver/vcenter/vcenter.go
component/otelcol/receiver/vcenter/vcenter_test.go
component/otelcol/receiver/zipkin/zipkin.go
component/otelcol/receiver/zipkin/zipkin_test.go

High cardinality metrics were disabled by default in exporters in #6255, but I forgot to update the receivers. This PR will do that.

Disable high cardinality metrics in receivers.

---

component/otelcol/connector/host_info/host_metrics.go
docs/sources/flow/reference/components/otelcol.connector.host_info.md

This updates the documentation to include the output block for the `otelcol.connector.host_info` component. 
* This component was introduced in #6410
* I'm also fixing a shadowed variable the linter didn't catch

update docs for otelcol.connector.host_info

---

converter/internal/otelcolconvert/converter_k8sattributesprocessor.go
converter/internal/otelcolconvert/testdata/k8sattributes.river
converter/internal/otelcolconvert/testdata/k8sattributes.yaml

Closes #6452
~Leaving this as draft for now, I gotta figure out how the jaeger-collector/jaeger-agent end up excluded as defaults.~
We have drifted from the upstream defaults, I've opened issue #6499 to keep track of this.

otelcolconvert: support converting k8sattributes processor

---

docs/sources/flow/_index.md
docs/sources/flow/reference/config-blocks/argument.md
docs/sources/flow/reference/config-blocks/declare.md
docs/sources/flow/reference/config-blocks/export.md
docs/sources/flow/reference/config-blocks/http.md
docs/sources/flow/reference/config-blocks/import.file.md
docs/sources/flow/reference/config-blocks/import.git.md
docs/sources/flow/reference/config-blocks/import.http.md
docs/sources/flow/reference/config-blocks/import.string.md
docs/sources/flow/reference/config-blocks/remotecfg.md

This PR  cleans up some of the relrefs (focus on `config-blocks`), converting relrefs to qualified URL links, or `doc/reference` links. This is part of the work required to prepare the markdown for future releases and restructuring.
Refer to: https://grafana.com/docs/writers-toolkit/write/shortcodes/#relref 
This PR is not a full edit of the content. The focus is on the relrefs, but some other minor cleanup i included (table formatting, contractions, and some semantic linebreaks).

General cleanup of relref links

---

CHANGELOG.md
component/common/loki/client/internal/metrics.go
component/common/loki/client/manager_test.go

Fix an issue where re-creating a write client led to a duplicate metrics collector registration panic.
Fixes #6510.

loki.write: fix duplicate metrics collector registration

---

docs/sources/flow/reference/components/loki.rules.kubernetes.md

The stability label in the doc was different from the one in the code

Fix stability label in loki kubernetes rules doc

---

component/otelcol/config_filter.go
converter/internal/otelcolconvert/converter_helpers.go
converter/internal/otelcolconvert/converter_spanprocessor.go
converter/internal/otelcolconvert/testdata/span.river
converter/internal/otelcolconvert/testdata/span.yaml
converter/internal/otelcolconvert/testdata/span_full.river
converter/internal/otelcolconvert/testdata/span_full.yaml

Closes #6455
I had to add a few more encode helper methods to access internal slice/string types.
I was worried about the number of nested fields, but I used all the options with a span.yaml like the following and got eveything ported over to the River config without any panics.
<details>
```
receivers:
otlp:
protocols:
grpc:
http:
exporters:
otlp:
endpoint: database:4317
balancer_name: pick_first
sending_queue:
queue_size: 5000
processors:
span:
name:
from_attributes: ["db.svc", "operation"]
separator: "::"
to_attributes:
rules:
- ^\/api\/v1\/document\/(?P<documentId>.*)\/update$
status:
code: Error
description: "some error description"
include:
match_type: "strict"
attributes:
- key: "key1"
value: "value1"
span_names: ["span1", "span2"]
span_kinds: ["spankind1", "spankind2"]
log_bodies: …
```

otelcolconvert: support converting span processor

---

CHANGELOG.md
pkg/flow/logging/logger.go

During the initial evaluation, the logging node is updated with the correct format and tries to log the data that it had buffered. This works for the standard output but it doesn't for the other receivers because the components that own them are not running yet (they are not ready to receive data from the receiver channel). This results in an error.
This fix ignores the error, which is the same behavior as before the introduction of the buffer via #5992 
This is still not ideal because the first logs won't reach the receivers. The buffer should allow us to only send the logs to the components when they are ready but this requires much more effort.
Fixes #6542

Fix logging node buffer

---

CHANGELOG.md
pkg/flow/logging/logger.go
pkg/flow/logging/logger_test.go

There may be situations where the flow mode logger receivers a nil value, potentially due to misconfiguration or a component which exports its values only after being ran.
Closes #6557.
This fixes an issue that can legitimately happen normally, but I'm not convinced it's specifically the problem that #6557 ran into. #6557 seems to indicate a deeper problem where the evaluated graph only contained the `logging` node writing to a `null` River value. With the configuration provided in the bug report, I simply can't see how that would happen. If there is a deeper issue, hopefully we find it later, as it would likely surface in other ways that this PR doesn't address.

flow/logging: check for nil values when writing logs

---

docs/sources/flow/tasks/migrate/from-operator.md

It seems `PodLogs` is meant in this peace of text, but `LogInstance` is written. This because in the next line it says LogInstances are deprecated.

docs: correct writing mistake to `PodLogs`

---

example/docker-compose/grafana/dashboards/agent-logs-pipeline.json
example/docker-compose/grafana/dashboards/agent-remote-write.json
example/docker-compose/grafana/dashboards/agent-tracing-pipeline.json
operations/agent-static-mixin/dashboards.libsonnet

This makes it for easier querying on the backend of your choice. I've verified by comparing the resulting dashboards in main and the fix branch
```
mixtool generate dashboards mixin.libsonnet --directory fix1
```
I'm adding the new parameter on the existing helper instead of refactoring to use `addMultiTemplateWithAll`, should be enough for now.

agent-static-mixin: include custom 'all' value

---

internal/converter/internal/otelcolconvert/pipeline_group.go
internal/converter/internal/otelcolconvert/testdata/inconsistent_processor.river
internal/converter/internal/otelcolconvert/testdata/inconsistent_processor.yaml

This PR fixes otelconvert to not panic when a processor is not consistently used throughout all signals.
Fixes #6584
The testcase added here doesn't really fit in with the others (which were per-component) but I didn't think it made sense to add a new directory or anything.

otelconvert: fix panic for pipelines with no processors

---

internal/component/otelcol/connector/spanmetrics/spanmetrics.go
internal/component/otelcol/connector/spanmetrics/types.go
internal/converter/internal/otelcolconvert/converter_spanmetricsconnector.go
internal/converter/internal/otelcolconvert/otelcolconvert.go
internal/converter/internal/otelcolconvert/pipeline_group.go
internal/converter/internal/otelcolconvert/testdata/spanmetrics.river
internal/converter/internal/otelcolconvert/testdata/spanmetrics.yaml
internal/converter/internal/otelcolconvert/testdata/spanmetrics_full.river
internal/converter/internal/otelcolconvert/testdata/spanmetrics_full.yaml

NOTE: This PR can be reviewed commit-by-commit.
This PR extends the current framework for converting OpenTelemetry Collector configs into Flow mode configs to support connectors. It also handles conversion for the spanmetrics connector to verify that it works properly.
Connectors are somewhat weirder since from the context of OTel service pipelines they're just valid definition to receiver and exporter component IDs, but underneath they don't match the same component.Kind.
I still want to go through more [complex configuration examples](https://github.com/open-telemetry/opentelemetry-collector/blob/main/connector/README.md) and verify that this works well for multiple groups and I suspect there might be a better abstraction for filtering out components per their respective Kinds, so I'm …

otelconvert: extend framework for connector components

---

CHANGELOG.md

In https://github.com/grafana/agent/pull/6559/files the release note went to a wrong place as this PR was open while new version was released.

Fix release note went to wrong place

---

internal/flow/internal/controller/metrics.go

This commit adds native histogram to Flow controller metrics (component evaluation time and component evaluation wait time).
For the scope of this commit, both classic and native histograms are used for these metrics. A future commit will remove the classic histogram.
The settings I picked came from the [Mimir documentation for native histograms](https://grafana.com/docs/mimir/latest/send/native-histograms/).

flow: add native histograms to Flow controller metrics

---

operations/agent-flow-mixin/dashboards/controller.libsonnet
operations/agent-flow-mixin/dashboards/utils/panel.jsonnet

This commit adds support for native histograms in controller metrics. For basic backwards compatibility, the panels will show either native histograms or classic histograms, but not both at the same time (due to how the "or" operator works in Prometheus).

agent-flow-mixin: visualize native histograms

---

operations/agent-flow-mixin/dashboards/controller.libsonnet

If both classic and native histograms are visualized concurrently, the old query would not consistently work properly in Grafana, as the `or` operator would return both classic and native histograms.
This would cause Grafana to visualize the histograms inconsistently, sometimes showing nothing for time ranges where native histogram data should be available.

agent-flow-mixin: fix visualization for concurrent classic and native histograms

---

operations/agent-flow-mixin/dashboards/controller.libsonnet

Native histograms do not have an `le` label, so there is no point in specifying `sum by (le)`.
This change was tested and makes no visual difference to the panels.

agent-flow-mixin: remove unnecessary `sum by (le)` for native histograms

---

CHANGELOG.md
internal/static/metrics/instance/instance.go
internal/static/metrics/instance/instance_test.go

Props to @rfratto for troubleshooting and guidance, I'm just implementing the idea here :D 
Fixes #6548

fix(static/metrics/instance): fix duplicate metrics registration panic when recreating the instance

---

docs/sources/static/configuration/integrations/statsd-exporter-config.md

Correct YAML representation for the config is `relay_addr`, as addressed [here](https://github.com/grafana/agent/blob/main/internal/static/integrations/statsd_exporter/statsd_exporter.go#L74).
Fixes #6601.

chore(doc): correct cfg for statsd_exporter relay address

---

internal/component/loki/source/docker/internal/dockertarget/target_test.go

The callback for one of the assert.EventuallyWithT calls incorrectly passed the test-wide *testing.T instance. This causes the assert.EventuallyWithT call to always return on the first tick, regardless of whether the assertion passed.
This means that on slower machines, the first assertion would fail, the assert.EventuallyWithT call would return prematurely, and the rest of the test would fail in turn.

dockertarget: fix flaky test

---

internal/component/local/file_match/file_test.go

It seems like `local.file_match` doesn't need the fix from https://github.com/grafana/loki/pull/9831. 
Adding a test to prove this and keep it working. 
Fixes #6158

Add test for creating a file in a path that is excluded

---

CHANGELOG.md
go.mod
internal/component/discovery/aws/ec2.go
internal/component/discovery/aws/lightsail.go
internal/component/remote/s3/watcher.go

`github.com/aws-sdk-go` has been announced to be in maintenance mode July 31, 2024. It's better to future-proof by moving to `aws-sdk-go-v2` and also 1 less dependency.

chore: migrate away from `aws-sdk-go` v1

---

docs/sources/flow/concepts/clustering.md
docs/sources/flow/reference/cli/run.md
docs/sources/flow/reference/components/prometheus.operator.probes.md
docs/sources/flow/tasks/configure-agent-clustering.md
docs/sources/flow/tasks/distribute-prometheus-scrape-load.md

This backports PR #6629 to the v0.40 release branch.

docs: remove beta label from clustering

---

CHANGELOG.md
internal/component/loki/source/api/internal/lokipush/push_api_server.go
internal/component/loki/source/api/internal/lokipush/push_api_server_test.go

This pull-request fixes a bug in loki.source.api, where incoming structured metadata and parsed fields are not passed further.
Fixes #6493

loki.source.api: fix a bug where incoming structured metadata and parsed are ignored

---

docs/sources/flow/tasks/metamonitoring.md

This PR adds a new Task page for configuring a meta-monitoring pipeline for the agent's internal metrics, logs and traces data.
I tried to keep the page as self-contained as possible, but didn't get to the same level as other task pages to (eg. `collect-opentelemetry-data.md`).
I expect this will need a round or two of polish, but that at least it can serve as a starting point.

docs: add task page for setting up metamonitoring

---

docs/sources/flow/reference/config-blocks/import.git.md
docs/sources/flow/reference/config-blocks/import.http.md
docs/sources/flow/reference/config-blocks/import.string.md

This PR removes the beta label from the import.http and import.string components. The new modules have started picking up use and we don't anticipate breaking changes in the foundational way that these components work.

docs: remove beta labels from import.http, import.git, import.string

---

README.md
docs/sources/_index.md
docs/sources/_index.md.t
docs/sources/flow/_index.md

This PR adds documentation references to Grafana Agent Flow's role as an OpenTelemetry collector distribution in the main landing page as well as the root of the Flow mode docs.

docs: reference Grafana Agent Flow as an OTel Collector distribution

---

.drone/drone.yml
CHANGELOG.md
build-image/Dockerfile
build-image/windows/Dockerfile
cmd/grafana-agent-operator/Dockerfile
cmd/grafana-agent/Dockerfile
cmd/grafana-agent/Dockerfile.windows
cmd/grafana-agentctl/Dockerfile
cmd/grafana-agentctl/Dockerfile.windows
docs/Makefile
go.mod
internal/cmd/integration-tests/configs/otel-metrics-gen/Dockerfile
internal/cmd/integration-tests/configs/prom-gen/Dockerfile
tools/make/build-container.mk

Upgrade Go to 1.22.1
Fixes https://github.com/grafana/agent-squad/issues/274

Upgrade Go to 1.22.1

---

go.mod

Retracting a couple of accidentally-pushed Git tags when testing a GitHub action 2 years ago 😬 
Closes #6654

go.mod: retract accidentally pushed tags

---

docs/sources/flow/reference/components/otelcol.auth.oauth2.md
internal/component/otelcol/auth/oauth2/oauth2.go
internal/converter/internal/otelcolconvert/converter_oauth2clientauthextension.go
internal/converter/internal/otelcolconvert/testdata/oauth2.river
internal/converter/internal/otelcolconvert/testdata/oauth2.yaml

Closes #6420
Please take a second look as a sanity check, since this is supposed to work for both the static mode tracing subsystem _and_ the OTel collector so I'm not sure if there's anything else I haven't considered

otelcolconvert: support converting oauth2 client auth extension

---

cmd/grafana-agent/Dockerfile.windows
cmd/grafana-agentctl/Dockerfile.windows

Attempt to fix `main` issues:
```
go: remove C:\go\pkg\mod\golang.org\toolchain@v0.0.1-go1.22.1.windows-amd64\bin\go.exe: Access is denied.
The command 'cmd /S /C ""C:\Program Files\git\bin\bash.exe" -c "RELEASE_BUILD=${RELEASE_BUILD} VERSION=${VERSION} GO_TAGS='builtinassets' make agent && go clean -cache -modcache""' returned a non-zero code: 1
```
https://drone.grafana.net/grafana/agent/17297/7/2

Attempt to fix main: separate clean in windows docker images

---

internal/component/otelcol/processor/transform/transform.go
internal/converter/internal/otelcolconvert/converter_helpers.go
internal/converter/internal/otelcolconvert/converter_transformprocessor.go
internal/converter/internal/otelcolconvert/testdata/transform.river
internal/converter/internal/otelcolconvert/testdata/transform.yaml

Closes #6456.
I've tried this with the full example configuration available over at [the upstream processor's README](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) and it converted without issues.
It required adding the same helpers as in #6504 so there might a temporary conflict.
<details>
```
transform:
error_mode: ignore
trace_statements:
- context: resource
statements:
- keep_keys(attributes, ["service.name", "service.namespace", "cloud.region", "process.command_line"])
- replace_pattern(attributes["process.command_line"], "password\\=[^\\s]*(\\s?)", "password=***")
- limit(attributes, 100, [])
- truncate_all(attributes, 4096)
- context: span
statements:
- set(status.code, 1) where attributes["http.path"] == "/health"
- …
```

otelcolconvert: support converting transform processor

---

internal/component/registry.go
internal/flow/flow_services_test.go
internal/flow/internal/controller/loader.go
internal/flow/internal/controller/loader_test.go
internal/service/cluster/cluster.go
internal/service/http/http.go
internal/service/labelstore/service.go
internal/service/otel/otel.go
internal/service/remotecfg/remotecfg.go
internal/service/service.go
internal/service/ui/ui.go

This commit adds stability levels to services. Every service, with the exception of remotecfg, is then given a stability level of stable. remotecfg is given a stability level of "beta."

service: allow services to have defined stability levels

---

operations/agent-flow-mixin/dashboards/controller.libsonnet
operations/agent-flow-mixin/dashboards/opentelemetry.libsonnet
operations/agent-flow-mixin/dashboards/utils/panel.jsonnet

Stacked panels show us the total number of units for all pods. It makes the dashboards easier to read when there are lots of pods.
This PR also fixes a minor bug where the units in the "Number of units in the batch" panel were wrong.

Use stacked panels in OTel dashboards

---

.drone/drone.yml
.drone/pipelines/build_images.jsonnet
.github/workflows/check-linux-build-image.yml
CHANGELOG.md
build-image/Dockerfile
build-image/windows/Dockerfile
cmd/grafana-agent-operator/Dockerfile
cmd/grafana-agent/Dockerfile
cmd/grafana-agent/Dockerfile.windows
cmd/grafana-agentctl/Dockerfile
cmd/grafana-agentctl/Dockerfile.windows
component/loki/source/api/internal/lokipush/push_api_server.go
component/loki/source/api/internal/lokipush/push_api_server_test.go
docs/Makefile
docs/sources/flow/reference/components/module.git.md
go.mod
integration-tests/configs/otel-metrics-gen/Dockerfile
integration-tests/configs/prom-gen/Dockerfile
internal/vcs/git.go
pkg/flow/import_test.go
tools/make/build-container.mk

Cherry pick the following PRs:
Change git operations from fetch to pull (#6668)
Attempt to fix main: separate clean in windows docker images (#6671)
Upgrade Go to 1.22.1 (#6646)
Update build image to Go 1.22.1 (#6650)
loki.source.api: fix a bug where structured metadata is not passed downstream (#6508)
This is following step 1 of[ patch release instructions](https://github.com/grafana/agent/tree/main/docs/developer/release#patch-release-publish-latest-version).

Cherry picks for v0.40.3

---

CHANGELOG.md
docs/sources/flow/reference/components/otelcol.receiver.opencensus.md
docs/sources/flow/release-notes.md
internal/component/otelcol/receiver/opencensus/opencensus.go
internal/converter/internal/otelcolconvert/testdata/opencensus.river

This commit re-syncs `otelcol.receiver.opencensus` with the upstream defaults, namely changing the default listen port from 4317 to 55678.
This is considered a breaking change; a section has been written in the upgrade guide notifying users to explicitly set the endpoint to the previous port to retain old behavior when upgrading.
Closes #6489.

otelcol.receiver.opencensus: sync with upstream defaults

---

docs/sources/flow/reference/components/module.file.md
docs/sources/flow/reference/components/module.git.md
docs/sources/flow/reference/components/module.http.md
docs/sources/flow/reference/components/module.string.md
docs/sources/flow/release-notes.md

The deprecation status of classic modules was constrained to the concept page of modules. This commit adds the deprecation notice to each component reference page and mentions it in the release notes.

docs: make deprecation of classic modules more clear

---

docs/sources/flow/reference/components/module.file.md
docs/sources/flow/reference/components/module.git.md
docs/sources/flow/reference/components/module.http.md
docs/sources/flow/reference/components/module.string.md
docs/sources/flow/release-notes.md

The deprecation status of classic modules was constrained to the concept page of modules. This commit adds the deprecation notice to each component reference page and mentions it in the release notes.
(cherry picked from commit 9d65d9f483ea2690f34681431dd32b6356a6026f)

[release-v0.40] Backport #6709 to release-v0.40

---

CHANGELOG.md
docs/sources/flow/tasks/debug.md
operations/agent-flow-mixin/alerts/clustering.libsonnet

- Rename the ClusterSplitBrain alert to a more descriptive name and improve its description
- Increase the time interval for this alert - to reduce noise during rollouts on large clusters
- Add a short note to docs about the possibility of metrics gaps appearing to look like clustering alerts
Fixes #4991

Tweak clustering alerts in the mixin

---

CHANGELOG.md
go.mod
go.sum
internal/static/integrations/gcp_exporter/gcp_exporter.go

This PR switches our stackdriver_exporter version to an internal fork with a patch to ensure `sum` and `count` metrics from delta histograms behave as expected. Patch PR is here: https://github.com/grafana/stackdriver_exporter/pull/1.

gcp_exporter: Use fork with a fix for delta histogram sum + count

---

CHANGELOG.md
docs/sources/flow/reference/components/prometheus.exporter.vsphere.md
docs/sources/flow/release-notes.md

The intent was the prometheus.exporter.vsphere was deprecated in v0.40, but this was mistakenly omitted from the release. This commit adds the deprecation notice.
Note that while the replacement component, otelcol.receiver.vcenter, is still marked as experimental, it wasn't intentional that prometheus.exporter.vsphere received the "stable" label, and it should have similarly been marked experimental.

add announcement that prometheus.exporter.vsphere was deprecated in v0.40

---

CHANGELOG.md
docs/sources/flow/reference/components/prometheus.exporter.vsphere.md
docs/sources/flow/release-notes.md

The intent was the prometheus.exporter.vsphere was deprecated in v0.40, but this was mistakenly omitted from the release. This commit adds the deprecation notice.
(cherry picked from commit ddacaec2b5aac063658c8724389d3c31892b0074)

[release-v0.40] add announcement that prometheus.exporter.vsphere was deprecated in v0.40

---

docs/sources/flow/reference/components/loki.source.kubernetes.md
docs/sources/flow/reference/components/loki.source.podlogs.md
docs/sources/flow/reference/components/prometheus.operator.servicemonitors.md
docs/sources/flow/reference/components/prometheus.scrape.md
docs/sources/flow/reference/components/pyroscope.scrape.md

Clustering is now graduated to GA / stable. We have left accidentally some labels that say it's beta in ref docs.

Fix incorrect clustering beta labels

---

docs/rfcs/0008-backwards-compatibility.md
docs/sources/flow/reference/cli/convert.md

Converter code is not cheap to maintain, and in some cases can bring in many dependencies that are otherwise unused, making project maintainance more difficult.
This change explicitly marks converter code as exempt from backwards compatibility guarntees, allowing its removal between minor versions if a converter is no longer needed and maintainers don't want to wait for the next major release to remove it.
The RFC for backwards compatibility guarantees is also updated to make it clear that some functionality may opt out of backwards compatibility guarantees, which includes the `convert` and `tools` commands.

docs: exempt converters from backwards compatibility guarantees

---

docs/sources/flow/reference/config-blocks/http.md

Recently, some cipher suites were deprecated in Go 1.22, per https://github.com/golang/go/issues/63413. As a result, certain cipher suites are no longer allowed in recent version of Grafana Agent (0.40.2), including these two:
- TLS_RSA_WITH_AES_256_GCM_SHA384
- TLS_RSA_WITH_AES_128_GCM_SHA256
This PR updates the table to show "no" for these two cipher suites.
Fixes [#9622](https://github.com/grafana/support-escalations/issues/9622)

Update cypher suite support

---

CHANGELOG.md
docs/sources/flow/reference/components/mimir.rules.kubernetes.md
internal/component/mimir/rules/kubernetes/types.go

Changes the default interval on which rules are synced from Mimir via `mimir.rules.kubernetes` when there are otherwise no changes to the `PrometheusRule` resources. This reduces load on the Mimir ruler APIs. Changes to `PrometheusRule` resources still result in immediately applying changes and syncing state with Mimir.
N/A
N/A

Reduce default sync_interval for mimir.rules.kubernetes

---

internal/component/otelcol/exporter/prometheus/internal/convert/convert.go

I've recently came across the issue that delta sums or counts were not exported to Prometheus. A simple log line would have saved a few hours investigating.

Log dropped delta sum

---

internal/flow/internal/controller/loader.go
internal/flow/internal/controller/metrics.go
internal/flow/internal/controller/node_builtin_component.go
internal/flow/internal/controller/node_builtin_component_test.go
internal/flow/internal/controller/node_config_import.go
internal/flow/internal/controller/node_custom_component.go
operations/agent-flow-mixin/alerts/controller.libsonnet
operations/agent-flow-mixin/dashboards/controller.libsonnet
operations/agent-flow-mixin/dashboards/prometheus.libsonnet

This PR amends the registerers and loggers we propagate into the graph to separate the so that the parent component/controller IDs are stored into a separate label.
This makes these metrics easier to read and manage and unlocks other solutions for large names in the case of nested modules in the future.
> NOTE: Please review this PR commit-by-commit and look at the extended commit messages. Each contains a snippet of how this change affects the Agent's logs and metrics
The metrics and logs examples are validated using the following example that uses nested modules.
```
--- entrypoint.river ---
logging {
format = "json"
}
import.file "a_namespace" {
filename = "a.river"
}
local.file "default" {
filename = "entrypoint.river"
}
a_namespace.a "default" {
a_argument = 47
}
--- a.river --- …
```

flow: separate parent component and controller IDs into new labels

---

CHANGELOG.md
internal/static/integrations/azure_exporter/azure_exporter.go

Fix logic bug preventing subscription scoped requests from working. Subscription scoped requests take far fewer API calls so are much more valuable for preventing rate limiting.
None, noticed this bug while tracking down what was going on in, https://github.com/grafana/agent/issues/6637

azure_exporter: Fix bug which prevents subscription scope from working with only a single region

---

internal/component/loki/rules/kubernetes/rules.go
internal/component/mimir/rules/kubernetes/rules.go

Replaces use of the deprecated method `workqueue.NewNamedRateLimitingQueue` with `workqueue.NewRateLimitingQueueWithConfig`.
N/A
N/A
- [na] CHANGELOG.md updated
- [na] Documentation added
- [na] Tests updated
- [na] Config converters updated

Replace use of deprecated Kubernetes workqueue method

---

operations/agent-flow-mixin/alerts.libsonnet

I saw that the OpenTelemetry alerts weren't wired in alerts.libsonnet meaning they wouldn't be rendered.

agent-flow-mixin: wire in OpenTelemetry alerts

---

operations/agent-flow-mixin/alerts/opentelemetry.libsonnet

It is a convention in Agent alerts to sum by at least `cluster` and `namespace`, and it also makes the alerts more useful.

Sum in alerts by cluster and namespace

---

internal/component/pyroscope/scrape/target.go
internal/component/pyroscope/scrape/target_test.go

Backport of https://github.com/grafana/alloy/pull/662

Backport: pyroscope.scrape: standarize profile names

---

internal/component/pyroscope/java/asprof/asprof.go

Backport of https://github.com/grafana/alloy/pull/661

Backport: pyroscope.java: add glibc detection for arm64

---

CHANGELOG.md
go.mod
go.sum
internal/component/loki/process/metric/metricvec.go
internal/component/loki/process/stages/decolorize.go
internal/component/loki/process/stages/drop.go
internal/component/loki/process/stages/eventlogmessage.go
internal/component/loki/process/stages/extensions.go
internal/component/loki/process/stages/geoip.go
internal/component/loki/process/stages/json.go
internal/component/loki/process/stages/limit.go
internal/component/loki/process/stages/match.go
internal/component/loki/process/stages/metric.go
internal/component/loki/process/stages/metric_test.go
internal/component/loki/process/stages/multiline.go
internal/component/loki/process/stages/pack.go
internal/component/loki/process/stages/pipeline.go
internal/component/loki/process/stages/sampling.go
internal/component/loki/process/stages/stage.go
internal/component/loki/process/stages/structured_metadata.go

[Backport](https://github.com/grafana/alloy/pull/836) from the Alloy repo. This will fix a [bug](https://github.com/grafana/loki/pull/12795) with the static mode where the logs pipeline isn't being shut down properly.
Unfortunately, it will not fix the [issue](https://github.com/grafana/agent/issues/2754) of reloading the config when a loki process metrics stage is set. Although this was [fixed in Promtail](https://github.com/grafana/loki/pull/11882), the code path for Agent Static and Flow seems to be different and the Promtail fix doesn't work.

Update Loki dependency

---

CHANGELOG.md

I put in the wrong date in the changelog... Thankfully we haven't announced the release yet.
@rfratto, is it a big problem that the CI has already ran for the 0.40.5 tag with the old date? Do we need to delete the artifacts, or can we just overwrite the tag?

Fix date of 0.40.5 release (release)

---

CHANGELOG.md

I put in the wrong date in the changelog... Thankfully we haven't announced the release yet.

Fix date of 0.40.5 release

---

docs/sources/flow/concepts/custom_components.md
docs/sources/flow/tasks/metamonitoring.md
docs/sources/shared/wal-data-retention.md

This PR catches and fixes some 404 errors in the Agent docs.
The Start/Stop link in the shared WAL topic was removed. This topic is shared across multiple products and the destination is different depending on the product. It was simpler to just remove the xref link that try to sort out the various destinations. The xref link isn't that important to the understanding of the topic.

Fix 404 errors and bad canonical URLs in Agent docs

---

docs/sources/data-collection.md
docs/sources/flow/setup/install/_index.md
docs/sources/static/_index.md
docs/sources/static/api/_index.md
docs/sources/static/configuration/_index.md
docs/sources/static/configuration/create-config-file.md
docs/sources/static/configuration/flags.md
docs/sources/static/configuration/metrics-config.md
docs/sources/static/configuration/scraping-service.md
docs/sources/static/operation-guide/_index.md
docs/sources/static/release-notes.md
docs/sources/static/set-up/install/_index.md
docs/sources/static/set-up/install/install-agent-binary.md
docs/sources/static/set-up/install/install-agent-docker.md
docs/sources/static/set-up/install/install-agent-linux.md
docs/sources/static/set-up/install/install-agent-macos.md
docs/sources/static/set-up/install/install-agent-on-windows.md
docs/sources/static/set-up/start-agent.md

You can use `ref` URIs in admonitions (or any shortcodes) because they are inline and not subject to the issues noted in the [`admonition` shortcode](https://grafana.com/docs/writers-toolkit/write/shortcodes/#code-shortcode:~:text=to%20core%20understanding.-,WARNING,For%20more%20information%2C%20refer%20to%20Markdown%20Reference%20Links%20in%20Shortcodes.,-Examples).
The `ref` URIs perform the same pattern matching as `docs/reference` but don't require the use of reference-style links and the destinations are ordinary (full) URLs that can include version substitution. Unlike `docs/reference`, the implementation doesn't use `relref` so you don't have to be careful with omitting trailing slashes and the links will follow redirects.
Documentation: …

[release-v0.35] Replace docs/reference shortcode with ref URIs

---

docs/sources/_index.md
docs/sources/about.md
docs/sources/data-collection.md
docs/sources/flow/setup/install/_index.md
docs/sources/operator/release-notes.md
docs/sources/static/_index.md
docs/sources/static/api/_index.md
docs/sources/static/configuration/_index.md
docs/sources/static/configuration/create-config-file.md
docs/sources/static/configuration/flags.md
docs/sources/static/configuration/metrics-config.md
docs/sources/static/configuration/scraping-service.md
docs/sources/static/operation-guide/_index.md
docs/sources/static/release-notes.md
docs/sources/static/set-up/install/_index.md
docs/sources/static/set-up/install/install-agent-binary.md
docs/sources/static/set-up/install/install-agent-docker.md
docs/sources/static/set-up/install/install-agent-linux.md
docs/sources/static/set-up/install/install-agent-macos.md
docs/sources/static/set-up/install/install-agent-on-windows.md
docs/sources/static/set-up/start-agent.md

You can use `ref` URIs in admonitions (or any shortcodes) because they are inline and not subject to the issues noted in the [`admonition` shortcode](https://grafana.com/docs/writers-toolkit/write/shortcodes/#code-shortcode:~:text=to%20core%20understanding.-,WARNING,For%20more%20information%2C%20refer%20to%20Markdown%20Reference%20Links%20in%20Shortcodes.,-Examples).
The `ref` URIs perform the same pattern matching as `docs/reference` but don't require the use of reference-style links and the destinations are ordinary (full) URLs that can include version substitution. Unlike `docs/reference`, the implementation doesn't use `relref` so you don't have to be careful with omitting trailing slashes and the links will follow redirects.
Documentation: …

[release-v0.36] Replace docs/reference shortcode with ref URIs

---

CHANGELOG.md
static/integrations/snmp_exporter/snmp_exporter.go

Fixes #6918
This was validated as fixed by reproducing the error on main and then validating the fix on this branch with the following config (thanks @ptodev):
```
server:
log_level: debug
integrations:
snmp:
enabled: true
scrape_interval: 1m
scrape_timeout: 30s
snmp_targets:
- name: testing
address: demo.pysnmp.com
module: if_mib
auth: public_v2
```

fix for panic with snmp exporter from the recent version upgrade

---

docs/sources/flow/tasks/debug.md
docs/sources/flow/tasks/opentelemetry-to-lgtm-stack.md
docs/sources/static/configuration/integrations/cloudwatch-exporter-config.md

Doc build reports show missing alt text and several broken image links. This PR adds the missing alt text and corrects the bad/broken image links.

Add alt text and fix broken image links

---

docs/sources/operator/release-notes.md

Fix build warning:
```
WARN /docs/grafana-cloud/send-data/agent/operator/release-notes/: [render-link] no matching project prefix was found for the ref URI release-notes-static
```

FIx ref pattern

---

docs/sources/flow/tasks/debug.md
docs/sources/flow/tasks/opentelemetry-to-lgtm-stack.md
docs/sources/static/configuration/integrations/cloudwatch-exporter-config.md

Backport https://github.com/grafana/agent/commit/a834fa5ce6116d06ada51f6bd76ae77d14c7ab61 from https://github.com/grafana/agent/pull/6955

[release-v0.40] Add alt text and fix broken image links

---

CHANGELOG.md
cmd/grafana-agent-service/service_test.go
internal/util/syncbuffer.go
static/logs/logs.go
static/logs/logs_test.go
static/metrics/agent.go
static/metrics/agent_test.go
static/traces/instance.go
static/traces/traces_test.go

When a config reload is triggered, the config shouldn't be reloaded if it hasn't changed. Unfortunately, there was a bug which prevented this for the "metrics" and "logs" subsystems:
* The `X-Agent-Id` header isn't in the user-defined config.
* In the "logs" subsytem, the `scrape_configs`/`static_configs` section, there might be a `targets: [localhost]` which was [added by default](https://grafana.com/docs/loki/latest/send-data/promtail/configuration/#static_configs) by Promtail because the user didn't set it explicitly
For example, when using [static_mode.yaml.txt](https://github.com/user-attachments/files/16016252/static_mode.yaml.txt), the Agent tries interprets the new config as [example_incoming.yaml.txt](https://github.com/user-attachments/files/16016270/example_incoming.yaml.txt). …

Fix issue with unnecessary config reload in static mode

---

CHANGELOG.md
docs/sources/flow/reference/components/loki.process.md
internal/component/loki/process/process.go
internal/component/loki/process/process_test.go
internal/util/unregisterer.go
internal/util/unregisterer_test.go
static/logs/logs_test.go
static/traces/traces_test.go

There is a longstanding bug which prevents the agent config from being reloaded when there is a `metrics` stage in a logging pipeline. 
Fixes #2754

Fix issue with config reload when using a log pipeline with a metric stage

---

build-image/Dockerfile
build-image/windows/Dockerfile

This PR needs to be merged in order for #6980 to be updated to use the new base image. #6980 will update Agent to use Go 1.22.5.

Update build image to Go 1.22.5

---

.drone/drone.yml
.drone/pipelines/build_images.jsonnet
build-image/README.md
docs/developer/updating-go.md

Apparently #6982 missed a few things that need changing, so I'm changing them now. I'm also adding docs to reflect my understanding of the Go update process.

Update build image and add docs

---

static/logs/logs_test.go

This PR escapes characters in Prometheus label values. A test [has been failing](https://drone.grafana.net/grafana/agent/18150/2/2) on the main branch due to it:
```
--- FAIL: TestLogs (5.08s)
logs_test.go:130: 
Error Trace:	C:/drone/src/static/logs/logs_test.go:130
Error:      	Received unexpected error:
converting reader to metric families failed: text format parsing error in line 4: invalid escape sequence '\U'
Test:       	TestLogs
```

Fix a broken Windows test

---

.github/workflows/check-linux-build-image.yml
.github/workflows/integration-tests.yml
.github/workflows/trivy.yml
CHANGELOG.md
cmd/grafana-agent-operator/Dockerfile
cmd/grafana-agent/Dockerfile
cmd/grafana-agentctl/Dockerfile
internal/cmd/integration-tests/utils.go

Update Ubuntu to latest LTS as Ubuntu Mantic is EOL since July 11, 2024 (https://wiki.ubuntu.com/Releases) and Wiz.io is complaining about this.
I tested the build by running `make images`.

sec: Upgrade Ubuntu to latest LTS version

---

CHANGELOG.md
internal/component/loki/process/process.go
internal/component/loki/process/process_test.go

A goroutine wasn't being stopped in Update, which resulted in a memory leak.
The same change [was also introduced to Alloy](https://github.com/grafana/alloy/pull/1431).

Fix memory leak in loki.process on config update

---

CHANGELOG.md
internal/flow/declare_test.go
internal/flow/internal/controller/component_references.go

backport of https://github.com/grafana/alloy/pull/769

Backport controller refs order wiring

---

CHANGELOG.md
internal/flow/internal/controller/node_config_import.go

backport from https://github.com/grafana/alloy/pull/646
The tests are not backported because they require enhancements which were only made in Alloy

Backport: nest datapath in parents to prevent collision in nested import.git

---

CHANGELOG.md
internal/component/loki/source/docker/docker.go
internal/component/loki/source/docker/docker_test.go
internal/component/loki/source/docker/internal/dockertarget/target.go
internal/component/loki/source/docker/runner.go

backport https://github.com/grafana/alloy/pull/742

backport container restart support in loki source

---

internal/agentseed/agentseed.go

I suspect this is the cause of some inconsistent data we are seeing. This return should always have been here.

agentseed: make sure we have a valid uid, or regenerate

---

CHANGELOG.md

This was removed by accident, because I merged #7016 to `main` instead of the release branch

Bring back "main" section to changelog

---

CHANGELOG.md
go.mod
go.sum

Similar to a [fix for Alloy](https://github.com/grafana/alloy/pull/2300).
Memory profile of an Agent prior to the change:
And a profile after the change:

Upgrade goccy/go-json to v0.10.4

---

CHANGELOG.md
cmd/grafana-agent/Dockerfile

Porting [this fix](https://github.com/grafana/alloy/pull/726) from Alloy to Agent. It is requested by users whose Agents fail to start due to a "operation not permitted" error.
The reason why Agent requests `cap_net_bind_service` is that it listens on port 80 [by default](https://github.com/grafana/agent/blob/d26ecfdc9c50fc23e4577ca58cdf1b9401c60cb8/operations/helm/charts/grafana-agent/values.yaml#L54). Thus, if someone configures Alloy with the non-root user with ID 473, they'd need that capability. However, this is As the Alloy issue states, Docker has been enabling that capability by default for a long time now. So even for non-root users we wouldn't really need to set it.
Since only non-root users would encounter this, and non-root support is experimental, it's ok to remove the …

Remove set bind permissions

---

CHANGELOG.md
internal/component/loki/source/podlogs/podlogs.go

Porting [a fix from Alloy](https://github.com/grafana/alloy/pull/2187).

Fix issue which disables clustering unintentionally.

---

CHANGELOG.md
internal/component/pyroscope/scrape/manager.go
internal/component/pyroscope/scrape/manager_test.go

Porting [a fix from Alloy](https://github.com/grafana/alloy/pull/1833).

Remove Pyroscope scrape loops for no longer active targets

---

docs/sources/flow/reference/components/prometheus.exporter.windows.md

Document URL:
https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.exporter.windows/#collectors-list
The netframework_* links reference a nonexistent file.  They should link to https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.netframework.md
Fixes [#14217](https://github.com/grafana/support-escalations/issues/14217)

Update netframework link destinations

---

.drone/drone.yml
.drone/pipelines/publish.jsonnet
.drone/util/secrets.jsonnet

- GCR is deprecated and the `updater` image stored there is no longer being updated
- Added the new secret to access the GAR `updater` image
- Updated image URL
See [this issue](https://github.com/grafana/deployment_tools/issues/197258) and [this issue](https://github.com/grafana/deployment_tools/issues/134736) for more information.

use GAR instead of GCR for updater image

---

docs/sources/flow/reference/components/prometheus.exporter.blackbox.md

Add info about 10s upper limit for `timeout` attribute in `config` argument.
Related to: https://github.com/grafana/alloy/pull/3234
Fixes https://github.com/grafana/support-escalations/issues/15590

Add info about 10s upper limit in blackbox exporter

---

internal/web/ui/package.json
internal/web/ui/src/features/component/ComponentBody.tsx
internal/web/ui/src/features/component/style.ts
internal/web/ui/yarn.lock

Updates minor deps in the UI for security patch currency.
Also removes react-syntax-highlighter which does two things:
1. Addresses a security issue with prismjs
2. Addresses a performance issue when displaying components in the UI

deps: ui: minor updates, remove react-syntax-highlighter
