README.md

Based on feedback received. This adds more context to the scaling issues that Grafana Labs has seen with Prometheus. 
This change also adds more context to the trade-off of only having server-side alerts, and clarifies that we are vendoring Prometheus itself rather than recreating its functionalities.

Clarify limitations and scaling issues, and usage of Prometheus

---

README.md
docs/maintaining.md

A `release` branch has been added to always refer to the latest release tag. This must be updated as part of the post-release process. Instructions on doing this have been added to the maintainers manual.

Update release instructions for release branch

---

pkg/prometheus/host_filter.go
pkg/prometheus/host_filter_test.go

Previously, the `host_filter` code was looking for a label called `__meta_kubernetes_pod_node_name`. This label is only available when using the `role: pod` matcher within the `kubernetes_sd_configs` config block.
When using `role: node`, which is common for the cadvisor and kubelet jobs, the metalabel for the node name is instead called `__meta_kubernetes_node_name`. `host_filter` wasn't checking for this
label and so any `role: node` job was getting filtered out.

pkg/prometheus: fix host_filter not matching `role: node` k8s SD jobs

---

cmd/agent/main.go
pkg/config/config.go
pkg/config/config_test.go

Closes https://github.com/grafana/agent/issues/49 
Added a couple of tests to show `UnmarshalStrict` catching issues. 
Also wanted to move the config structure out of `main.go`, but happy to undo leave it where it was and move tests to `cmd/` if that's preferable.

Enable strict yaml parse

---

pkg/prometheus/ha/codec.go
pkg/prometheus/ha/http.go
pkg/prometheus/ha/sharding.go
pkg/prometheus/instance/instance.go
pkg/prometheus/instance/marshal.go
pkg/prometheus/instance/remote_write.go

The fix from #63 didn't fix everything: since `agentctl` also marshals the config to YAML, secrets were being removed before they even reached the config API. 
This PR completely removes the Secret type to allow RemoteWriteConfigs to be arbitrarily marshalled back and forth between YAML. Sanitization now happens on demand rather than being forced by the marshaling.
Closes #62, and reverts some of #63.

Duplicate RemoteWriteConfig without the Secret type

---

cmd/agentctl/main.go
pkg/agentctl/sync.go
pkg/agentctl/sync_test.go

Fixes #65 by adding a dry-run flag to the existing `agentctl config-sync`. In the dry-run path the address is never used but still a required flag. If we want we can create a separate command for dry-running config-sync that doesn't mark the addr flag as required.

Added dry run flag to agentctl config-sync cmd

---

production/tanka/grafana-agent/config.libsonnet

The pod was failing for me in my deployment until I changed this

Fix typo in tanka config

---

README.md
docs/README.md
docs/maintaining.md
go.mod
go.sum
vendor/github.com/prometheus/prometheus/config/config.go
vendor/github.com/prometheus/prometheus/prompb/remote.proto
vendor/modules.txt

This PR also adds instructions for how we'll maintain the `grafana/prometheus` repository and how we'll coordinate features to get them merged upstream.
Closes #5 since we're tweaking our vendoring strategy.

update to latest release-2.17.1-grafana

---

CHANGELOG.md
pkg/agentctl/sync.go
pkg/agentctl/sync_test.go
pkg/prometheus/instance/marshal.go
pkg/prometheus/instance/marshal_test.go

The instance.UnmarshalConfig function will now do strict decoding. This commit also changes agentctl to use this function instead of reimplementing the same functionality.

enable strict YAML parsing for uploading a new config to config API

---

production/grafana-agent-mixin/mixin.libsonnet

The previous Jsonnet code wasn't adding the folder to the dashboard objects. This commit maps over the dashboards and properly adds the folder key.

fix issue where agent dashboards weren't properly assigned a folder

---

production/kubernetes/agent.yaml
production/kubernetes/build/jsonnetfile.json
production/kubernetes/build/jsonnetfile.lock.json
production/kubernetes/build/vendor/github.com/grafana/jsonnet-libs/ksonnet-util/kausal.libsonnet

Reran `make example-kubernetes` to rerender the Kubernetes manifest and had to rerun `jb install`, which was required before the render would work. 
Fixes #77.

re-render Kubernetes manifest to include fix from #71

---

pkg/prometheus/agent.go
pkg/prometheus/agent_test.go
pkg/prometheus/instance/instance.go
pkg/prometheus/instance/instance_test.go
pkg/prometheus/wal/wal.go

As part of #83, the instance package will have to be utilized in a new way for running integrations (i.e., running an instance that does not have a discovery component).
To prepare for this change, the instance package was in need of a refactoring to simplify how the instance objects are used. Now, instead of an instance immediately starting when it is created, it must be started explicitly through the `Run` function. `Run` is a blocking operation and will only exit on error or when the context is canceled. Changing to this allowed for cleaning up a lot of code callers required to watch the lifecycle of the Instance.
Note that the code for unregistering WAL metrics is no longer needed as the WAL is now created when Run is called.
Running an instance with a discovery manager is still …

simplify instance creation and lifecycle

---

pkg/prometheus/instance/instance.go

The implementation of #83 will require the ability to replace the Prometheus discovery manager with a custom component that outputs discovered targets. The first half of this is to couple the Prometheus
discovery manager and host filtering as a single "actor" that can be swapped out with another implementation.

couple discovery and host filtering

---

pkg/config/config.go
pkg/config/config_test.go
pkg/prom/agent.go
pkg/prom/agent_test.go
pkg/prom/ha/http.go
pkg/prom/ha/http_test.go
pkg/prom/ha/server.go
pkg/prom/ha/server_test.go
pkg/prom/instance/instance.go
pkg/prom/instance/instance_test.go

Prometheus was doing some validations on the `remote_write` and `scrape_config` sections per config that we weren't doing yet. To make this a little easier, ApplyDefaults and Validate have been merged.
The scraping service PutConfiguration endpoint will now apply the defaults to the config before passing it through to the KV store; invalid configs will be prevented from reaching the KV store and errors will be returned to the client.
When migrating to this change, if any invalid configs exist in the KV store, the Agent will refuse to start them and log an error. The configs in the KV store should be updated to fix the invalid settings before the Agent will be able to run it.
Fixes #80.

use remote_write and scrape_config validations from Prometheus

---

pkg/prom/agent.go
pkg/prom/agent_test.go
pkg/prom/instance/instance.go
pkg/prom/instance/instance_test.go

PR #92 accidentally removed unmarshaling the default config values into the instance configs, which led to a 0s `wal_truncate_frequency`, causing the WAL to get truncated every spare CPU cycle.
This PR adds them back and adds new tests and validations to make sure it won't happen again.

Add back in instance config defaults on unmarshal

---

pkg/prom/config_manager.go
pkg/prom/config_manager_test.go

When running the scraping service, if a config has a new version with changes uploaded to the API and subsequently shards to the same node running the previous version of that config, a deadlock will occur. 
The issue is:
1. `ApplyConfig` is holding onto the mutex 
2. `ApplyConfig` calls `Stop`. This cancels the context and waits for the `done` channel to close. 
3. The `done` channel is only closed after the mutex is locked.
Item 1 and item 3 will both try to obtain a lock on the mutex, causing a deadlock.

Fix deadlock when applying changes for an existing config

---

pkg/prom/wal/wal.go
production/grafana-agent-mixin/dashboards.libsonnet
production/grafana-agent-mixin/debugging.libsonnet
production/grafana-agent-mixin/mixin.libsonnet
production/tanka/grafana-agent/config.libsonnet

grafana/jsonnet-libs#261 updates labels to make instance labels unique. This commit sycnes with that change, but subsequently makes an overdue change by going through all the dashboards and fixing various issues with them.
The new dashboards are compatible with the new labeling scheme, but also fixes some problems:
1. Make sure the unloved Agent and Agent Prometheus Remote Write runs correct queries and account for the instance_name labels
2. Use proper graph label values in Agent Operational
3. Allow to filter Agent Operational graph by container
As part of making the Agent dashboard useful, a new metric has been added to track samples added to the WAL over time.
Closes #73.

update labels to current jsonnet-libs standard and fix dashboards

---

pkg/prom/agent.go
pkg/prom/agent_test.go
pkg/prom/instance/instance.go
pkg/prom/wal/wal.go

Couple of small clean-up commits around config parsing, and then a fix for #106.
New here, do let me know if I should be doing anything here differently!
I found the code around `ApplyDefaults` a bit confusing: Pretty sure that second loop that's removed in https://github.com/grafana/agent/commit/15659e6865fafdad0e5061084985dd61cc2f13ae was redundant, but actually there's a third call via `validateInstance` which doesn't make a whole lot of sense to me. At least it doesn't crash anymore now (for me :TM:).
Fixes #106

Fix zero default scrape interval by initializing global config stanza with defaults (fixes #106)

---

production/kubernetes/agent.yaml
production/tanka/grafana-agent/config.libsonnet

It was accidentally removed when the scraping service config was added. See #108 for pointing this out.

Re-enable host_filter for the agent daemonset

---

docs/configuration-reference.md

This PR tries to clarify the descriptions of `wal_truncate_frequency` and `remote_flush_deadline`, #108 pointed out that the descriptions are unclear (and in the case of `remote_flush_deadline`, just completely incorrect).
/cc @weeco

Clarify wal_truncate_frequency and remote_flush_deadline

---

README.md
docs/getting-started.md
production/kubernetes/README.md
production/kubernetes/install.sh
tools/release-note.md

So `install.sh` requires `envsubst` which isn't a standard POSIX tool, but part of GNU gettext and not installed e.g. on macOS by default.
Probably it would be a good idea to make the script more portable longer-term (I imagine macOS users in particular are a non-negligible part of the user base), but this should make it fail a bit more nicely. (I added in `curl` too, which is kind of pointless but it felt ugly to not ask for both tools.)
I also tried documenting the requirement in the various places the install script was mentioned (there's way too many of those 😅 ).

Be explicit about envsubst requirement in install.sh

---

docs/configuration-reference.md
pkg/integrations/config/config.go
pkg/integrations/manager.go

This PR presents a temporary workaround for #113 by letting users remove series they don't want from integrations. 
The documentation for #104 will have to rebase onto this change since the common set of config options has been expanded.

Allow for specifying relabel_configs and metric_relabel_configs for integrations

---

cmd/agent/main.go
pkg/config/config.go
pkg/config/config_test.go
pkg/integrations/node_exporter/config.go

Previously, ApplyDefaults was invoked immediately after the config file was loaded. This was fine prior to #107, where unmarshaling the file did not override any values specified by command line flags. However, as #107 added back UnmarshalYaml to prom.Config, the flag value was getting wiped and anything specified only by flags would fail to load.

apply defaults for the config after parsing flags 

---

example/k3d/environment/main.jsonnet
pkg/config/config_test.go
pkg/prom/agent.go
pkg/prom/ha/client/client.go
pkg/prom/ha/server.go
pkg/util/defaults.go
production/tanka/grafana-agent/scraping-svc/main.libsonnet

Implementing `yaml.Unmarshaler` by setting the default object (i.e., the "Prometheus way" of doing it) interferes with default values initialized through command line flags. As the Agent uses config objects from both Prometheus and Cortex, these two mechanisms of applying defaults were stepping over each other.
The new methodology for applying defaults is as follows:
1. Every config object within pkg/prom should have a DefaultConfig object.
2. When that config object relies on default values from flags, there should be a GetDefaultConfig function within the package that creates a temporary FlagSet for getting default values. The DefaultConfig for the package should be the result of calling this function.
3. Every Config object must implement yaml.Unmarshaler to assign the default object. …

Load default values from flagset defaults when unmarshaling to YAML

---

example/docker-compose/vendor/grafana-agent-mixin
production/kubernetes/agent.yaml
production/kubernetes/build/template/main.jsonnet
production/kubernetes/build/vendor/grafana-agent
production/tanka/grafana-agent/config.libsonnet
production/tanka/grafana-agent/grafana-agent.libsonnet

I genuinely think #124 describes the problem way better than what I would ever be able to phrase, so I won't paraphrase.
The work done here refers to the second solution mentioned in the issue where we'll deploy a single replica deployment to scrape for `default/kubernetes` explicitly. 
Closes #124.

Scrape default/kubernetes in host_filter mode

---

docs/api.md
pkg/prom/agent.go
pkg/prom/agent_test.go
pkg/prom/http.go
pkg/prom/http_test.go
pkg/prom/instance/instance.go

`/agent/api/v1/targets` is a new API endpoint that will return info on all scrape targets currently being scraped by the running Agent. Targets from other Agents (i.e., in scraping service mode), will not be returned.
This API exposes the same information present on the Prometheus UI page for targets.
Provides some of #6.

Create scrape targets API

---

pkg/prom/wal/series.go
pkg/prom/wal/wal.go

Overall, this PR should result in less spikey memory usage and may demonstrate a measurable decrease in memory usage overall. Active series will now be reported more accurately.
Several small issues were fixed in particular:
1. Match the upstream TSDB usage of the WAL where series are prevented from getting deleted if they were pending a commit.
2. Match the upstream TSDB usage of the WAL to only delete the lower 2/3rds of segments when truncating the WAL.
3. The deleted series metric was being incorrectly reported.
4. We revert the behavior of not tracking labels for active series. This caused many issues and only marginally improved memory usage. Not tracking labels caused series to get double-counted when they went stale. Reverting this change does make memory usage marginally worse, …

improve memory stability and performance of WAL

---

pkg/integrations/manager_test.go
pkg/prom/agent.go
pkg/prom/agent_test.go
pkg/prom/http.go
pkg/prom/http_test.go
pkg/prom/instance/noop.go
pkg/prom/instance_manager.go
pkg/prom/instance_manager_test.go

This PR refactors `InstanceManager` to make it responsible for running instances, rather than deferring to a function which creates and runs them. This now makes `InstanceManager` aware of the running instance interfaces, opening the door for implementing #140. 
Note that with this PR, `pkg/prom.Agent` does very little outside of exposing an HTTP API and gluing various things together.

pkg/prom: refactor InstanceManager

---

.golangci.yml
pkg/prom/agent_test.go
pkg/prom/http_test.go
pkg/prom/instance/errors.go
pkg/prom/instance/instance.go
pkg/prom/instance/instance_integration_test.go
pkg/prom/instance/noop.go
pkg/prom/instance_manager.go
pkg/prom/instance_manager_test.go

This PR introduces an `Update` method against the `Instance` that allows for applying new changes found on `remote_write` and `scrape_configs` sections. If any other field changes, `Update` will return `ErrInvalidUpdate`, which will cause the `InstanceManager` to do the normal "restart" (i.e., shut down old instance, bring up new one with modified config).
Future changes may loosen the restriction on what is able to be dynamically updated, but I suspect that `scrape_configs` and `remote_write` are going to be far more common than anything else. 
Some code cleanup can be found as part of this PR: fakes that have been called mocks have been updated to use their proper name.
Closes #140.

allow dynamic updating of instance scrape_configs and remote_write

---

docs/README.md
docs/configuration-reference.md
docs/operation-guide.md
pkg/prom/agent.go
pkg/prom/agent_test.go
pkg/prom/instance/group_manager.go
pkg/prom/instance/group_manager_test.go
pkg/prom/instance/instance.go
pkg/prom/instance/instance_integration_test.go
pkg/prom/instance/instance_test.go
pkg/prom/instance/manager.go

This PR adds [shared instances](https://docs.google.com/document/d/1MmQepMgdbGitt414EoeOtES1KBXu6TWYAhA0XaiF8Wc/edit?usp=sharing), which _should_ be a notable resource utilization enhancement when an Agent runs a significant number of instance configs. 
This changes default behavior of the Agent to share instances, and is a _breaking change_ for metrics; metrics around instances are now grouped by the shared instances rather than individual instance configs (when the feature is enabled). A future PR may remove support for non-shared instances. 
Early performance testing shows that this matches the utilization of having a single instance vs running multiple instances. It's hard to determine how significant that difference is in theory, but users that find their resource utilization has …

Implement shared instances

---

cmd/agent/main.go
pkg/loki/loki.go

If Loki isn't configured, then `promtail.New` will fail since it expects at least one client config to be present. However, this means that no Loki instance is created and calling stop on it is a nil reference, throwing a panic.
This commit returns an empty Loki when Promtail isn't configured, and explicitly exits if `loki.New` returns an error.
Fixes #153.

pkg/loki: return empty loki when no configuration is present

---

CHANGELOG.md
pkg/prom/instance/instance.go

Set custom User-Agent for remote_write

---

CHANGELOG.md
cmd/agent/main.go
pkg/prom/agent.go
pkg/prom/agent_test.go
pkg/prom/http_test.go
pkg/prom/instance/counting_manager.go
pkg/prom/instance/counting_manager_test.go
pkg/prom/instance/manager.go
vendor/github.com/prometheus/client_golang/prometheus/testutil/lint.go
vendor/github.com/prometheus/client_golang/prometheus/testutil/promlint/promlint.go
vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
vendor/modules.txt

Instance sharing broke the `active_configs` metric, which started to represent the number of instances (e.g., configs post-sharing) instead. Knowing exactly how many configs exist _pre-sharing_ is still useful, so this PR:
1. renames the old metric to `active_instances` 
2. reintroduces the `active_configs` metric to accurately track the number of configs before instance sharing is applied.

track number of active configs vs instance

---

CHANGELOG.md
docs/configuration-reference.md
pkg/integrations/config/config.go
pkg/integrations/manager.go
pkg/integrations/manager_test.go

Users may want to run integrations in an Agent without remote_writing the data anywhere. This is particularly useful when running the scraping service; you might have an Agent running node_exporter on every node but you want the metrics to be collected centrally from the scraping service. 
This PR allows for disabling the scraping of enabled integrations either globally or per-integration.

Make scraping integrations optional

---

CHANGELOG.md
cmd/agent/main.go
pkg/config/config.go
pkg/integrations/manager.go
pkg/loki/loki.go
pkg/prom/agent.go

This PR makes the `prometheus`, `loki`, and `integrations` subsystems optionally loaded depending on if they are defined in the configuration file. This allows to provide a config file that only enables Loki mode without setting the WAL directory for Prometheus.
Fixes #170.

Make subsystems optional

---

CHANGELOG.md
pkg/prom/ha/http.go
pkg/prom/ha/http_test.go
pkg/prom/ha/sharding.go
pkg/prom/instance/instance.go
pkg/prom/instance/instance_test.go

Instance sharing broke an accidental behavior of instance configs when using the scraping service mode: job names did not have to be unique across multiple instances. This was caused by each instance config (previously) being given its own dedicated set of Prometheus components. 
Now that components are shared, `job_name`s must be globally unique. The HTTP API for storing configs will now retrieve all existing configs to validate uniqueness of the job_name. This also opens up an opportunity for a race condition of two conflicting configs being applied concurrently. To avoid the race condition, this PR also prevents concurrent requests against the PUT API. 
Note that this is a breaking change of an undocumented feature, but it brings instance configs sin line with how Prometheus handles …

Config API: Enforce unique job names across all configs

---

pkg/prom/ha/server.go

Updating the Cortex vendor for importing Loki broke the scraping service. Two KV clients get initialized: one directly for storing configs and one indirectly by creating a Cortex ring client. The Cortex ring client wraps the registerer passed to the KV client with a call to kv.RegistererWithKVName. Not doing this leads to an inconsistency on constant labels added to the KV metrics and causes a panic from the
Prometheus client_golang package.
The CHANGELOG isn't updated since this bug isn't present on any current release.

fix panic when starting scraping service

---

docs/configuration-reference.md

Removes an old reference to node_exporter command line flags before they were removed.
Fixes #176.

Fix instructions for node_exporter

---

CHANGELOG.md
docs/operation-guide.md
pkg/prom/instance/group_manager.go
pkg/prom/instance/group_manager_test.go

In the instance sharing mode, `remote_write` configs with a custom name (`remote_names`) were being copied from the first member of the group. This causes the `remote_name` to change when the first element is removed, which is an unexpected behavior. This particularly affects scraping service users, where the stored configs already have defaults applied, including the generated `remote_name` for each instance config.
`remote_names` are now forced to be the combination of the fix six characters of the group name and `remote_write` config hash separated by a hypen. A future enhancement may wish to consider non-autogenerated names when grouping `remote_write` configs, but that change is out of scope here.

override remote_name when grouping configs

---

CHANGELOG.md
pkg/prom/wal/wal.go
pkg/prom/wal/wal_test.go

There was a rare scenario that the Agent may be shut down in the middle of a truncation. The WAL was able to be closed in the middle of a truncation, which caused a panic.
This change:
- disallows closing the WAL in the middle of a mutation to the WAL
- disallows mutations to the WAL following the WAL being closed
Fixes #179

Prevent WAL from being changed after it is closed

---

README.md
docs/getting-started.md
example/k3d/environment/main.jsonnet
production/kubernetes/README.md
production/kubernetes/agent-loki.yaml
production/kubernetes/build/build.sh
production/kubernetes/build/templates/loki/main.jsonnet
production/kubernetes/build/templates/loki/spec.json
production/kubernetes/install-loki.sh
production/tanka/grafana-agent/v1/internal/kubernetes_logs.libsonnet
production/tanka/grafana-agent/v1/lib/loki.libsonnet
tools/release-note.md

This acts as the counterpart to the Prometheus installation script but installs a separate deployment of the Agent for collecting logs. Right now the scripts will remain separated we can provide these instructions across an entire Grafana Cloud stack instead of per data source. 
Closes #156 as an example that the Tanka configs can generate the Agent with functional Loki support.

Add Loki installation script

---

CHANGELOG.md
pkg/build/build.go

After Loki support was added, it was running an init function to set build information after we ran our init function for the same purpose. This caused the build information to be misreported when running the Agent with the --version flag.
This is a temporary workaround until grafana/loki#2603 is released and vendored in the Agent.

Fix build info

---

pkg/prom/wal/series.go
pkg/prom/wal/wal.go

This changes the `seriesHashmap` to refer directly to a `memSeries` rather than a tuple of `(refID, labels)`. This is also what Prometheus does, but was changed early in the design of the Agent before the shared interner existed to lower memory usage. 
The problem with having a `seriesHashmap` that indirectly refers to a series is the requirement of holding two separate locks simultaneously. The garbage collection goroutine _also_ needs to hold two separate locks, which can cause a deadlock if these two goroutines run at the same time. Referring directly to the memory series pointer removes the need for holding two locks when looking up a series. 
Closes #184.

fix deadlock when one series is added while another is deleted

---

CHANGELOG.md
pkg/prom/instance/instance.go

Prometheus applies component updates in a specific order. In particular, the scrape manager needs to be applied before the discovery manager. 
If this order is not kept, there's a chance the discovery manager will send a target for a new job to the scrape manager before the scrape manager is aware of the job. If this happens, the scrape manager drops all targets associated with that job and will not retry.

fix Prometheus component update order when updating an Instance config

---

docs/configuration-reference.md

Based on the related config file, docker needs to mount sys but not dev.

Docker mount sys not dev

---

.github/workflows/containerize.yml
.github/workflows/release.yml
.github/workflows/test.yml
CHANGELOG.md
Makefile
cmd/agent/Dockerfile.buildx
cmd/agentctl/Dockerfile.buildx
tools/cross_build.bash

This PR adds support for building arm64 and arm/v7 Docker images alongside publishing ARM binaries as part of a release. Internally uses `docker buildx` and `seego` to build the Agent with CGO_ENABLED=1. 
To test locally, setup a buildx context if one isn't already available and run `IMAGE_PREFIX=<your dockerhub username> CROSS_BUILD=true make agent-image`. The image will be pushed immediately after building, which is a limitation of buildx. 
CI has been updated to try to parallelize the efforts here as much as possible. When building a new master commit, tests will run first and then the `agent` and `agentctl` images will build in parallel. The same change has been applied for the release: test first, then bundle release assets and build the containers all in parallel.
Note that the CI …

ARM Docker images and release binaries

---

pkg/integrations/manager.go
pkg/integrations/manager_test.go

The relabel rules being generated for the instagrations did not fill out all required fields. This works in shared instance mode, where the pre-grouped instances are "copied" by marshaling them to YAML and unmarshaling them back. The process of unmarshaling from YAML was filling out all required fields for us.
As distinct instance mode does not marshal/unmarshal configs being applied, this invalid behavior was hidden from the default config settings.
Closes #199

fix crash in integrations with distinct instance mode

---

CHANGELOG.md
pkg/integrations/manager.go
pkg/integrations/manager_test.go

Windows generated invalid metrics paths with \ separating URL components.
Closes #197

fix integrations on Windows

---

CHANGELOG.md
docs/api.md
pkg/prom/ha/http.go
pkg/prom/ha/http_test.go

Support URL-encoded config paths in the scraping service config API

---

README.md
docs/configuration-reference.md
docs/getting-started.md
example/docker-compose/agent/config/agent.yaml
production/kubernetes/README.md
production/kubernetes/agent-bare.yaml
production/kubernetes/agent-loki.yaml
production/kubernetes/agent-tempo.yaml
production/kubernetes/agent.yaml
production/kubernetes/build/build.sh
production/kubernetes/build/templates/bare/spec.json
production/kubernetes/build/templates/base/spec.json
production/kubernetes/build/templates/loki/spec.json
production/kubernetes/build/templates/tempo/main.jsonnet
production/kubernetes/build/templates/tempo/spec.json
production/kubernetes/install-loki.sh
production/kubernetes/install-tempo.sh
production/tanka/grafana-agent/v1/README.md
production/tanka/grafana-agent/v1/lib/tempo.libsonnet
production/tanka/grafana-agent/v1/main.libsonnet
tools/release-note.md

This PR does a few things:
1. Add basic support for configuring the Tempo subsystem within the v1 Tanka library.
1. Utilize the tanka configs to expose a sane default config `production/kubernetes/agent-tempo.yaml`.
1. Add a bash script to render environment variables in the default config. (This is inline with the other "install" bash scripts).
1. Rename `remote_write` in the Tempo config to `push_config`. `remote_write` should be reserved for fields that act fully like the Prometheus `remote_write`; an array with the standard fields. Once the Tempo subsystem supports an array of targets to write spans to, a `remote_write` field name can return.

Add installation script for tracing

---

CHANGELOG.md
docs/configuration-reference.md
pkg/prom/ha/server.go

This PR adds a `reshard_timeout` configuration option that can optionally add a timeout when performing cluster-wide or local reshards. 
This PR also prevents the join process from failing and stopping the server; if an Agent encounters an error on the initial join, the reshard intervals will eventually correct the problems.

Support timeouts for resharding the scraping service cluster

---

CHANGELOG.md
docs/configuration-reference.md
pkg/config/config.go
pkg/integrations/manager.go
pkg/integrations/manager_test.go

This PR changes the mechanism for which the `replace_instance_label` config option is applied; rather than being applied through `write_relabel_configs`, it is now applied as the first `relabel_config` when relabeling targets.
This allows users to replace the instance label with their own value, and even use the existing overwritten instance label for creating the final result.
This slightly changes the behavior of the integrations. Before, the final `instance` label was computed by `remote_write`. Now that it's done by `relabel_configs`, the final instance label is being stored in the WAL. I don't anticipate this causing a problem for anyone. 
Fixes #220

Allow overriding instance label when replace_instance_label is set

---

CHANGELOG.md
pkg/prom/ha/sharding.go

When getting a config from the KV store failed, the underlying error was not being logged.

Log error message when retrieving KV configs

---

CHANGELOG.md
pkg/integrations/common/collector_integration.go
pkg/integrations/node_exporter/node_exporter.go
pkg/integrations/process_exporter/process-exporter_linux.go

Some existing dashboards for exporters depend on an `<exporter name>_build_info` metric existing. Dashboards might put it in a panel, but some dashboards might also use it for discovering instance labels to use. As the Agent wasn't creating this metric, it would break these existing dashboards.
This PR adds `<integration>_build_info` metrics to increase compatibility with existing exporter dashboards. Note that the build info exposed will be the build information for the Agent process and not the embedded version of the exporter.

add <integration>_build_info metrics to every integration

---

CHANGELOG.md
docs/configuration-reference.md
pkg/prom/instance/instance.go
pkg/prom/instance/marshal_test.go

It's suspected that immediately deleting data from the WAL as soon any sample with that given timestamp is `remote_written` is error prone, with one potential scenario described in #248. Similarly, it's possible that the 
WAL may grow forever in cases of long-running network outages, as described by #226.   
This PR adds two new options, `min_wal_time` and `max_wal_time`, to control the bounds of how long data may exist for within the WAL. 
The default setting for `min_wal_time` is 5m, which should be ample time for remote_write to give up on a failed batch. Users are free to set `min_wal_time` to anything, including 0s to retain the old behavior. 
The default setting for `max_wal_time` is 4h, and must be greater than `min_wal_time`. 
Closes #138.
Closes #226.
I ran a test to ensure that …

add min_wal_time and max_wal_time to bound WAL data lifetime

---

.github/depcheck.yml
.github/workflows/depcheck.yml

Add a `depcheck` workflow which uses [depcheck](https://github.com/rfratto/depcheck) for checking if any Go dependencies or manually listed deps are outdated. Currently set to `dry_run` which won't actually create any issues; a follow up PR will turn that off and configure running the workflow every 24 hours.

Add depcheck workflow

---

.github/workflows/depcheck.yml

Follow up to #259 that enables depcheck to create issues and schedules it to run every 24 hours. 
The [last dry run](https://github.com/grafana/agent/runs/1455196016?check_suite_focus=true) of the depcheck workflow was functional.

enable and schedule depcheck to run every day at midnight

---

CHANGELOG.md
production/kubernetes/agent-tempo.yaml
production/kubernetes/build/templates/tempo/main.jsonnet

The port name limit is 15 characters and the names given (when combined
with the generated prefix `agent-`), were too long, so the manifest was
failing to be applied.
Closes #251

shorten agent tempo port names

---

CHANGELOG.md
pkg/build/build.go
pkg/loki/loki.go

Fixes #188
The hack that forced the Agent after Loki in the dependency graph is no longer needed; my PR to Loki (which has been vendored for a while) fixed the issue that required it.

Override Promtail User-Agent header

---

CHANGELOG.md
production/kubernetes/agent-bare.yaml
production/kubernetes/agent-loki.yaml
production/kubernetes/agent-tempo.yaml
production/kubernetes/agent.yaml
production/tanka/grafana-agent/grafana-agent.libsonnet
production/tanka/grafana-agent/v1/internal/agent.libsonnet

Some pod controllers on Kubernetes may require an explicit command set if args is also set. See #279 for an example of this, which seems to be Azure-based. 
Closes #279

explicitly add command to Agent manifests

---

CHANGELOG.md
Makefile

Adds a release of `agentctl` into the deb and rpm packages.

Add agentctl to deb/rpms

---

cmd/agentctl/main.go
pkg/client/grafanacloud/client.go
pkg/client/grafanacloud/client_test.go
production/grafanacloud-install.sh

Adds a Grafana Cloud-specific install script that does the following:
1. Downloads the rpm or deb Agent package and installs it 
2. Uses a new hidden `agentctl` command to generate the config file using an internal Grafana Cloud API 
3. Enables and starts the service. 
This script can be used by setup instructions on Grafana Cloud. 
This currently won't work completely as `grafana-agentctl` isn't installed by the 0.9.0 binaries. To reproduce locally, install agentctl as `grafana-agentctl`. A 0.9.1 release is needed for this script to work fully on its own.

Add grafanacloud-specific install script

---

docs/getting-started.md

The Dockerfile's CMD statement clearly expects the config file to be present at `/etc/agent/agent.yaml` location but following instructions in Getting Started guide gets potential user nowhere with error `error loading config file /etc/agent/agent.yaml: error reading config file: open /etc/agent/agent.yaml: no such file or directory`.

Getting started guide: correct the config file path

---

cmd/agentctl/main.go
docs/configuration-reference.md
docs/getting-started.md
docs/maintaining.md
docs/operation-guide.md
docs/overview.md
pkg/config/config.go
pkg/integrations/manager.go
pkg/prom/instance/instance.go
pkg/tempo/promsdprocessor/prom_sd_processor.go
pkg/tempo/tempo.go

Signed-off-by: yeya24 <yb532204897@gmail.com>
Some typo fix.

Fix some typos

---

CHANGELOG.md
production/kubernetes/agent-loki.yaml
production/tanka/grafana-agent/v1/lib/loki.libsonnet

The `/var/log` folder is used by default for storing the last read file offset. We were previously mounting this path as readonly. Writing the positions.yaml to this folder helps the Agent recover from a crash and not resend logs that were already sent to Loki.
This change reflects what the official Promtail configs do.

don't mount /var/log as readonly

---

CHANGELOG.md
docs/configuration-reference.md
pkg/prom/agent.go
pkg/prom/agent_test.go
pkg/prom/cleaner.go
pkg/prom/cleaner_test.go
pkg/prom/http_test.go
pkg/prom/instance/instance.go
pkg/prom/instance/manager.go
pkg/prom/instance/manager_test.go
pkg/prom/instance/noop.go
pkg/prom/wal/util.go
pkg/prom/wal/wal.go

Remove WAL directories that are no longer associated with a `ManagedInstance`
that this agent is responsible for. The storage directories used by active
instances are compared to all subdirectories under the `wal_directory` root.
Any that are not associated with an instance and that haven't been modified
in over a configured amount of time are removed.
How often the check is run and the cutoff for how recently a WAL must have
been modified are controlled by the `wal_cleanup_period` and
`wal_cleanup_age` settings respectively, under the top-level Prometheus
configuration. When omitted, they default to a period of 30 minutes and
recently modified threshold of 12 hours.
Fixes #132

Clean up abandoned WAL directories

---

CHANGELOG.md
cmd/agent/Dockerfile
cmd/agent/Dockerfile.buildx

Corresponds to grafana/loki#2957, needed for reading journals that have `+ZSTD` compression which is starting to become standard.

Update libsystemd version in Docker containers

---

CHANGELOG.md

Having the warning prefix every version is getting silly. I've created #317 to track the issue and added a consolidated warning at the top of the CHANGELOG.

consolidate FreeBSD warnings

---

docs/configuration-reference.md

Prometheus 2.21 added an experimental `target_limit` that wasn't added to the Agent documentation.

document experimental prometheus target_limit

---

CHANGELOG.md
docs/configuration-reference.md
go.mod
go.sum
pkg/integrations/manager.go
pkg/prom/ha/codec_test.go
pkg/prom/instance/group_manager.go
pkg/prom/instance/group_manager_test.go
pkg/prom/instance/instance.go
pkg/prom/instance/instance_integration_test.go
pkg/prom/instance/instance_test.go
pkg/prom/instance/marshal_test.go
pkg/prom/instance/remote_write.go
pkg/prom/instance/sigv4.go
pkg/prom/instance/sigv4_test.go
vendor/github.com/prometheus/prometheus/storage/remote/storage.go
vendor/github.com/prometheus/prometheus/storage/remote/write.go
vendor/modules.txt

This PR adds a SigV4 mechanism for authenticating `remote_write` requests.

add sigv4 as a custom authentication method for remote_write data

---

CHANGELOG.md
production/kubernetes/agent.yaml
production/tanka/grafana-agent/config.libsonnet
production/tanka/grafana-agent/v1/internal/kubernetes_instance.libsonnet

Agent scrapes the K8s API server using Prometheus K8s service discovery. If using the "endpoints" role (as is currently done in the manifest), the TLS `server_name` parameter must be set to the K8s API server Service name (`kubernetes` by default), which resolves to the ClusterIP address contained in the X.509 client cert used for authentication. If omitted, Prom service discovery will use the Endpoints object IP address, which is not referenced in the cert and will cause an error. Tested on DigitalOcean Kubernetes. This may be provider-specific? To investigate on GCP, etc. 
See Slack thread.

Resolve K8s API server IP using DNS

---

CHANGELOG.md
Makefile
tools/cross_build.bash

Adds ARMv6 release builds and Docker images for `agent` and `agentctl` to support older Raspberry Pi devices.

support ARMv6 linux builds

---

CHANGELOG.md
production/kubernetes/agent-sigv4.yaml
production/kubernetes/build/build.sh
production/kubernetes/build/templates/base-sigv4/main.jsonnet
production/kubernetes/build/templates/base-sigv4/spec.json
production/kubernetes/install-sigv4.sh
production/tanka/grafana-agent/config.libsonnet

Adds a sigv4-specific install script. 
Also fixes bug where the deployment scrape config was included with host filtering enabled, where the inverse should've been true. (cc @hjet, this fixes the duplicate default/kubernetes job)

add sigv4 install script, fix bug

---

CHANGELOG.md
README.md
docs/getting-started.md
production/README.md
production/kubernetes/README.md
production/kubernetes/agent-bare.yaml
production/kubernetes/agent-loki.yaml
production/kubernetes/agent-sigv4.yaml
production/kubernetes/agent-tempo.yaml
production/kubernetes/agent.yaml
production/kubernetes/build/templates/bare/main.jsonnet
production/kubernetes/build/templates/base-sigv4/main.jsonnet
production/kubernetes/build/templates/base/main.jsonnet
production/kubernetes/build/templates/loki/main.jsonnet
production/kubernetes/build/templates/tempo/main.jsonnet
production/kubernetes/install-bare.sh
production/kubernetes/install-loki.sh
production/kubernetes/install-sigv4.sh
production/kubernetes/install-tempo.sh
production/kubernetes/install.sh
production/tanka/grafana-agent/grafana-agent.libsonnet
production/tanka/grafana-agent/v1/main.libsonnet
tools/release-note.md

Allows a custom installation namespace in the Kubernetes install scripts through replacing an environment variable. 
This also tweaks errors to the sigv4 script found when testing out #334.
Closes #319

allow specifying installation namespace in script

---

CHANGELOG.md
cmd/agentctl/main.go

Perform basic YAML and type checking for an Agent configuration file
and exit with `1` if there are any errors loading, parsing, or validating
the file.
Fixes #329

Configuration file validation subcommand for agentctl

---

CHANGELOG.md
docs/api.md
pkg/prom/http.go
pkg/prom/http_test.go

Adds discovered labels of the targets in `/agent/api/v1/targets`, making it easier to understand what labels the target had pre- and post- relabeling.

include discovered labels in /agent/api/v1/targets

---

docs/getting-started.md

Added clarifying rules from https://github.com/grafana/agent/issues/316#issuecomment-756910864 for the default script config to scrape pods.

Add note on rules for scraping pods

---

.github/depcheck.yml
go.mod
go.sum
vendor/modules.txt

Upstream PR has been merged, we can use it directly now

remove use of consul_exporter fork

---

CHANGELOG.md
pkg/prom/ha/server.go

Changes the replication strategy used by the Agents to ignore unhealthy nodes. This allows for configs to automatically roll over to the next available Agent. 
Also adds ring metrics, which weren't being registered before. 
Closes #130.
Tested this in the k3d environment, appears to work.

Allow failed agents in ring

---

.github/workflows/containerize.yml
Makefile

Switches the Containerize workflow to use `docker/setup-qemu-action@v1` and `docker/setup-buildx-action@v1` instead of the manual commands, which seemed to be prone to a race condition where the ARM builders weren't immediately available.

Fix CI flakiness on merge jobs

---

CHANGELOG.md
docs/scraping-service.md
pkg/prom/ha/sharding.go

Sharding will now be performed based on the name of the config file instead of the contents of the config file. This guarantees that in a static ring, the same config name will always hash to the same Agent. This improves guarantees of the hashing, but also ensures that changing a config will not cause it to move to another Agent and cause gaps in metrics as the scrape responsibility moves.

scraping service: shard only on instance config name instead of contents

---

CHANGELOG.md
production/kubernetes/agent-sigv4.yaml
production/kubernetes/agent.yaml
production/tanka/grafana-agent/config.libsonnet
production/tanka/grafana-agent/v1/internal/kubernetes_instance.libsonnet

Per https://github.com/grafana/agent/pull/352 and other user feedback, the default scrape configuration results in a large number of metrics being shipped out of the box, which can create a significant storage costs.
Using guidelines from https://grafana.com/docs/grafana-cloud/billing-and-usage/prometheus/usage-reduction-k8s/, this temporary fix only scrapes a handful of API server metrics by default instead of scraping everything (~20k active series). 
The inclusion criteria is basically "are these API server metrics referenced in a [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) dashboard." If they are referenced in a recording rule, they are not included here. 
This is not a perfect solution to this problem, but a temporary patch to make the default less …

Only keep certain K8s API server metrics by default

---

production/grafanacloud-install.sh

#344 changed the architecture filename on the x86_64 rpms/debs to amd64 to align with the binaries, but this file wasn't updated.

fix architecture path for system packages in grafanacloud-install script

---

.github/workflows/containerize.yml
.github/workflows/release.yml
CHANGELOG.md
Makefile
cmd/agent/Dockerfile
cmd/agent/Dockerfile.buildx
cmd/agentctl/Dockerfile
cmd/agentctl/Dockerfile.buildx
tools/seego/Dockerfile

The `seego` abstraction made it unclear which version of Go was being used. This PR:
1. Makes it consistently 1.15.7 
2. Overrides the base `seego` image with 1.15.7.

Update Go and use consistent version across distributions

---

CHANGELOG.md
cmd/agent/Dockerfile
cmd/agent/Dockerfile.buildx
cmd/agentctl/Dockerfile
cmd/agentctl/Dockerfile.buildx
go.mod
tools/seego/Dockerfile
vendor/modules.txt

I noticed Go 1.15.8 got released right after I merged #383 🙃

update to go 1.15.8

---

CHANGELOG.md
cmd/agentctl/main.go

allow relying on the default value of the -addr flag in config-sync

---

CHANGELOG.md
production/grafanacloud-install.sh

Allows passing an `ARCH` environment variable to specify which system package is downloaded. 
cc @hoenn @richardqlam

Support other architectures in installation script

---

CHANGELOG.md
docs/configuration-reference.md
pkg/prom/instance/instance.go

This PR increases the WAL truncation frequency default to 60 minutes to reduce the likelihood of samples being moved to a checkpoint when remote_writes are failing. 
An extra measure has been added to the truncate loop where a WAL truncate will be skipped if the last remote_write timestamp hasn't changed. This applies after the `min_wal_time` and `max_wal_time` checks so data older than `max_wal_time` should continue to be deleted.
Fixes #400 (kind of, it's not perfect, but it's significantly better).

Reduce likelihood of data loss when remote endpoint has an outage

---

CHANGELOG.md
docs/configuration-reference.md
pkg/integrations/config/config.go
pkg/integrations/manager.go

Adds `wal_truncate_frequency` as a common integration setting, allowing to override the forced default. 
Closes #390  
Blocked by #401.

Allow specifying wal truncate frequencies per integration

---

.github/workflows/containerize.yml
CHANGELOG.md
docs/maintaining.md
docs/operation-guide.md
packaging/deb/grafana-agent.service
packaging/grafana-agent.yaml
packaging/rpm/grafana-agent.service
production/tanka/grafana-agent/v1/lib/integrations.libsonnet
production/tanka/grafana-agent/v1/lib/loki.libsonnet
production/tanka/grafana-agent/v1/lib/prometheus.libsonnet
production/tanka/grafana-agent/v1/lib/tempo.libsonnet

Master branch will be renamed once this is merged.

Update references to old "master" branch to "main"

---

CHANGELOG.md
docs/configuration-reference.md
pkg/prom/instance/sigv4.go
pkg/prom/instance/sigv4_test.go

Allows for inferring the sigv4 region from environment variables or the shared config file. The region specified in the Agent YAML serves as the final override.

infer sigv4 region from environment

---

pkg/prom/ha/server.go
pkg/prom/ha/sharding.go

This is needed for the config reloading, but is already handled today: when the overall Agent stop, it stops all intances, including ones retrieved via the scraping service. However, if _just_ the scraping service was stopped, then its instances would continue running in the background. This fixes that problem.

Scraping service: stop scraping service instances on partial shutdown

---

Makefile
go.mod
pkg/loki/loki.go
pkg/loki/loki_test.go
pkg/prom/instance/instance.go
pkg/util/unregisterer.go
pkg/util/untab.go
vendor/modules.txt

This PR adds an `ApplyConfig` field for applying a new config to the Loki subsystem. This isn't hooked into anything for now, but will be used as part of #147. 
It works by checking to see if a Loki instance config has changed, and replacing the Promtail instance if it has. Instances that have been removed from the updated config will be shut down. 
Related to #147, but doesn't implement it fully.

Implement ApplyConfig for Loki

---

CHANGELOG.md
docs/configuration-reference.md
pkg/integrations/postgres_exporter/postgres_exporter.go

Adds `query_path` and `disable_default_metrics` to postgres_exporter, which were missing from the initial implementation.

Add query_path and disable_default_metrics to postgres_exporter

---

CHANGELOG.md
docs/configuration-reference.md
pkg/tempo/config.go
pkg/tempo/config_test.go

This PR exposes compression for the tempo trace export section, which is already supported by the vendored OTLP exporter.  Supported compressions are gzip or none.  
As discussed, it now defaults to enabling gzip, but can be disabled with "none".
n/a

Default enable compression for trace export

---

CHANGELOG.md
pkg/prom/instance/instance.go

A remote_write timestamp of 0 preventing truncations from occurring. Ignoring 0s was an unnecessary safety measure, and only caused problems when considering the min/max WAL sample lifetime.
Closes #409.

allow 0 as a valid truncation timestamp

---

pkg/prom/ha/server.go
pkg/prom/ha/server_test.go
pkg/prom/ha/sharding.go
pkg/prom/ha/sharding_test.go

This PR simplifies the scraping service sharding mechanism by removing the scraping service manager and performing ownership checking locally directly in the shard logic. 
This removes the need for a ton of code. 
Previously hashing was used to cache whether an instance needed to be updated and ignoring the ApplyConfig if it didn't. This hasn't been necessary for a while; ApplyConfig for an unmodified instance is a no-op. 
(Internal change, no changelog or documentation)

Simplify sharding logic

---

CHANGELOG.md
pkg/client/client.go
pkg/prom/ha/codec.go
pkg/prom/ha/codec_test.go
pkg/prom/ha/http.go
pkg/prom/ha/http_test.go
pkg/prom/ha/server.go
pkg/prom/ha/server_test.go
pkg/prom/ha/sharding.go
pkg/prom/ha/sharding_test.go

This PR changes the Codec used to operate on the raw config strings instead of `instance.Configs`. This is primarily to serve #147 which will need the ability to re-apply global defaults to configs retrieved from the config store.

Use a text-based codec for interacting with config store KV 

---

pkg/integrations/manager_test.go
pkg/prom/agent.go
pkg/prom/ha/http.go
pkg/prom/ha/server.go
pkg/prom/ha/sharding.go
pkg/prom/instance/manager.go
pkg/prom/instance/manager_test.go

This PR commit reduces the number of places defaults are applied to instance configs to just:
1. When the Agent YAML is unmarshaled
2. When the instance config is loaded from the KV store
This makes it easier to follow the lifetime of an instance config. 
Done in relation to #147.
Internal change, nothing here needed.

change the default application semantics of instance configs

---

pkg/prom/ha/server.go
pkg/prom/ha/sharding_test.go
pkg/prom/instance/configstore/codec.go
pkg/prom/instance/configstore/codec_test.go
pkg/prom/instance/configstore/errors.go
pkg/prom/instance/configstore/remote.go
pkg/prom/instance/configstore/store.go
pkg/prom/instance/configstore/unique.go

This PR starts the work of decoupling the configuration store from the scraping service. This will eventually be needed to [make the KV-based configuration store optional](https://docs.google.com/document/d/1fiLXOMzX-ljOYeBIf-bN4FMPnDT2db807lf6k41daVQ/edit#), but is more immediately useful to `/-/reload` (#147) where we may want to dynamically update the configuration for a store. 
Related to #147.
Not hooked in yet. I didn't want to delete too much code from `pkg/prom/ha` so this didn't become _too_ hard to review. 
The HTTP API for the config store would move to this new package too. 
Tagging @mattdurham and @56quarters to get some early thoughts. This will be a pretty drastic change from how the scraping service was handled before.

Decouple configuration store from scraping service

---

pkg/prom/instance/configstore/errors.go
pkg/prom/instance/configstore/remote.go
pkg/prom/instance/configstore/remote_test.go
pkg/prom/instance/configstore/store.go

Adds tests for the remote configstore introduced in #445. 
The `Watch` API was changed here. I found out that (at least) with the Consul testing client from Cortex, delete messages aren't broadcasted. This makes me wary of an API that tries to keep track of the state of events that might not fire, so I've changed the Watch API to only return received events.

Add tests for the Remote configstore

---

pkg/prom/instance/configstore/api.go
pkg/prom/instance/configstore/api_test.go

Ports over the HTTP code of the scraping service to the configstore.
Once again, not hooked in anywhere, and the old code still exists for now.

Add HTTP api for configstore

---

docs/configuration-reference.md

Fix the syntax in the docs used for environment variable substitution.

Fix environment variable substitution syntax

---

pkg/agentproto/func.go
pkg/prom/cluster/config.go
pkg/prom/cluster/node.go
pkg/prom/cluster/node_test.go
pkg/util/test_logger.go

This is the first of a few PRs to migrate the `pkg/prom/ha` logic to a `pkg/prom/cluster` package.
This first PR re-implements membership within the cluster to a dedicated `node` type. The `node` type will be used for ensuring the Agent maintains appropriate membership in the proper cluster as the config changes. 
Reshards are triggered during the membership cycle:
- All Agents will be told to reshard when a node joins (including the joining Agent)
- All Agents will be told to reshard when a node leaves (excluding the leaving Agent)
Believe it or not, still working on #147.
This isn't hooked into anything yet, and won't be hooked up until all pieces are migrated. Tests still needed, so I'm opening this in draft.

Add pkg/prom/cluster package with membership management

---

pkg/prom/cluster/config_watcher.go
pkg/prom/cluster/config_watcher_test.go

`configWatcher` is an internal component that watches a ConfigStore and applies config as they get changed. It also has a polling mechanism to do a full sync against the state of the config store. This is the other half of the existing functionality of `pkg/prom/ha` and pairs with the work from #461. 
Still doing #147 🙃

pkg/prom/cluster: add config watcher

---

pkg/prom/cluster/cluster.go
pkg/prom/cluster/config_watcher.go
pkg/prom/cluster/node.go
pkg/prom/instance/configstore/api.go

Glues together the new cluster package.
Notably no integration tests here. I think enough of the logic is covered to fall back on the smoke tests, which I'll do in the next PR when I replace the old package with the new one.

Glue together the new cluster package

---

pkg/prom/agent.go
pkg/prom/instance/modal_manager.go

Implements ApplyConfig for `pkg/prom.Agent`. 
Related to #147.
Alternative implementation of #435.
I don't really like how this works, and needing to have a goroutine to apply changed configs in the background feels bad. I've given some thought on other ways to do this, but this seems like the less ridiculous so far.

implement ApplyConfig for pkg/prom

---

pkg/integrations/agent/agent.go
pkg/integrations/collector_integration.go
pkg/integrations/integration.go
pkg/integrations/manager.go
pkg/integrations/manager_test.go
pkg/integrations/node_exporter/node_exporter.go
pkg/integrations/node_exporter/node_exporter_test.go
pkg/integrations/process_exporter/process-exporter.go
pkg/integrations/process_exporter/process-exporter_linux.go
pkg/integrations/redis_exporter/redis_exporter_test.go
pkg/integrations/statsd_exporter/statsd_exporter.go

Implements ApplyConfig for integrations.
This requires a change to the integration interface to no longer register routes directly to mux. This is because mux is unable to unregister routes. The new approach is to expose the HTTP handlers that expose metrics, and look up the handler at request time.
Related to #147. 
Everything still seems to work after local testing. The new approach here is pretty similar, but stores the goroutines in a map (kind of like the basic instance manager) so they can be stopped independently. 
One interesting detail here: when "updating" an integration (stopping the old goroutine and starting a new one), the new goroutine does not wait for the previous one to stop. I don't believe this will cause any problems, but we might have to change this behavior later.

ApplyConfig for integrations

---

production/kubernetes/agent-bare.yaml
production/kubernetes/agent-loki.yaml
production/kubernetes/agent-tempo.yaml
production/kubernetes/build/templates/bare/main.jsonnet
production/tanka/grafana-agent/v1/internal/agent.libsonnet
production/tanka/grafana-agent/v1/lib/deployment.libsonnet

A DaemonSet deployment of the Agent is only useful when paired with a Deployment for scraping resources that don't live within the cluster. This makes the Agent more confusing to configure and manage, since two ConfigMaps have to be juggled, and even reduces performance due to the potential of overloading the Kubernetes API if the number of cluster nodes is high.
This PR changes the DaemonSet deployment of the "bare" (i.e., configmapless install) that will be used by Grafana Cloud to use a single-replica Deployment.
The bare install was never documented or referenced anywhere, so I don't think we need to add a changelog entry for it.

Change configless Agent k8s install to use a deployment

---

CHANGELOG.md
docs/configuration-reference.md
docs/getting-started.md
example/docker-compose/agent/config/agent.yaml
pkg/tempo/config.go
pkg/tempo/config_test.go
pkg/tempo/instance.go
production/kubernetes/agent-tempo.yaml
production/kubernetes/build/templates/tempo/main.jsonnet
production/tanka/grafana-agent/v1/README.md
production/tanka/grafana-agent/v1/lib/tempo.libsonnet

Adds support for multiple backends in a tracing pipeline. `push_config` is deprecated in favor of `remote_write` and `batch`, which configure the multiple exporters.
`remote_write` still uses `PushConfig`, but the idea is to rename it and remove the `Batch` field once the `push_config` is removed from the config.
Closes https://github.com/grafana/agent/issues/466

Support mirror traffic pipelines

---

CHANGELOG.md
cmd/agent/entrypoint.go
docs/api.md
pkg/config/config.go
pkg/integrations/config/config.go
pkg/integrations/consul_exporter/consul_exporter.go
pkg/integrations/dnsmasq_exporter/dnsmasq_exporter.go
pkg/integrations/elasticsearch_exporter/elasticsearch_exporter.go
pkg/integrations/manager.go
pkg/integrations/manager_test.go
pkg/integrations/memcached_exporter/memcached_exporter.go
pkg/integrations/mysqld_exporter/mysqld-exporter.go
pkg/integrations/node_exporter/config.go
pkg/integrations/postgres_exporter/postgres_exporter.go
pkg/integrations/process_exporter/config.go
pkg/integrations/redis_exporter/redis_exporter.go
pkg/integrations/register.go
pkg/integrations/statsd_exporter/statsd_exporter.go
pkg/integrations/windows_exporter/config.go
pkg/loki/config.go
pkg/prom/agent.go
pkg/prom/cluster/client/client.go
pkg/prom/instance/instance.go
pkg/prom/instance/marshal_test.go
pkg/tempo/config.go

Marks all fields as `omitempty` and adds support for a `/-/config` endpoint that marshals out the current loaded configuration over HTTP. 
Some of this implementation accidentally snuck into #493, sorry!
There was a bug where an empty list of integrations was not marshaling correctly, but that has been fixed with this PR (and a new test to make sure we don't regress).

Add /-/config endpoint

---

CHANGELOG.md
pkg/agentctl/cardinality.go
pkg/agentctl/samples.go
pkg/prom/instance/instance.go

Closes WALs after agentctl finishes doing analysis.
Fixes #506

close WALs after calculating cardinality/sample stats

---

CHANGELOG.md
pkg/prom/wal/wal.go
pkg/prom/wal/wal_test.go

Copies the Prometheus TSDB label validation code to the WAL appender.
Fixes #527

Validate labels

---

docs/configuration-reference.md

Add the lost and forgotten windows_exporter configuration documentation
Relates to #475 
- [NA] CHANGELOG updated 

Windows doc

---

docs/migration-guide.md

Add migration guide in v0.14.0 for `push_config` deprecation. Initially nothing was added because `push_config` is still supported, but seeing only `remote_write` in the reference and examples with no migration guide can be very confusing.
None
None

Add migration guide for push_config deprecation

---

CHANGELOG.md
docs/configuration-reference.md
pkg/tempo/config.go
pkg/tempo/config_test.go

This PR adds an optional `headers` field to `remote_write`s in Tempo. Headers specified through that field are passed on to remote writers. 
Closes #535 
I will update documentation and CHANGELOG in upcoming commits.

Add headers field to Tempo's remote_write  

---

pkg/tempo/promsdprocessor/prom_sd_processor.go

Noticed this while working on other changes. I believe we were using the wrong logger in our SD processor.

Tempo: Use correct logger in Prom SD

---

CHANGELOG.md
packaging/windows/install_script.nsis

Windows auto start

---

CODEOWNERS
CODE_OF_CONDUCT.md
GOVERNANCE.md
MAINTAINERS.md

Add a governance, code of conduct, maintainers, and CODEOWNERS.
Unlike the other governance docs, this one does not include an announcement or users mailing list. This repository should be used for both, instead. The sentences relevant to announcements and the users mailing list have been removed.

Add governance

---

CHANGELOG.md
docs/configuration-reference.md
pkg/tempo/config.go
pkg/tempo/config_test.go

Add a hardcoded namespace to "brand" the metrics as tempo metrics. Metrics can still be further namespace'd.
This comment: https://github.com/grafana/deployment_tools/pull/9416#discussion_r612409931

Add harcoded namespace to spanmetrics

---

CHANGELOG.md
pkg/config/config.go
pkg/config/config_test.go

#545 found that defining _just_ an `integrations` block prevented integrations from being scraped. This was found to be because the default scrape_interval and scrape_timeout weren't being applied when `prometheus` wasn't present in the config file. 
This change ensures that defaults are applied appropriately to empty files (or files without a given section). Only defaults for integrations and prometheus need to be defined, as integrations depends on prometheus (and no other subsystem has defaults).
Fixes #545

Apply defaults to undefined sections

---

pkg/config/config.go
pkg/config/config_test.go

PR #546 introduced a default value for the overall Config struct which
overwrote the defaults coming from flags. This commit ensures that
flag-level defaults take precedence.
(Not updating changelog since the bug was introduced before a tag)

fix default values applied to Config

---

pkg/prom/cluster/config_watcher_test.go
pkg/prom/instance/group_manager.go
pkg/prom/instance/manager.go
pkg/prom/instance/modal_manager.go

An internal-only change for now that adds the ability to retrieve a managed instance by name. In the case of instances being grouped, the running group gets returned instead.

add ability to get an instance by name

---

CHANGELOG.md
example/k3d/environment/main.jsonnet
pkg/prom/agent.go
pkg/prom/agent_test.go
pkg/prom/instance/group_manager.go
pkg/prom/instance/instance.go
pkg/prom/instance/instance_integration_test.go
pkg/prom/instance/instance_test.go

This PR fixes an issue where the global settings were not being read by instances when reloading. This was because the global settings were passed to the constructor of instances, but never updated when applying the new instance settings.
This could be reproduced by adding a new external_label and reloading the config. The new label will not be present on newer sent metrics. 
This PR fixes that problem by adding the global config to be a part of the instance config struct. It cannot be marshaled into the instance, and must be set manually by the code before applying the changes.
There are two code paths to consider here:
1. The scraping service will re-read the global config on the next reshard tick.
2. Non-scraping service will apply the global config as soon as the new config is read …

metrics: read global config when reloading instances

---

example/docker-compose/cortex/config/cortex.yaml
example/docker-compose/docker-compose.integrations.yaml
example/docker-compose/docker-compose.scraping-service.yaml
example/docker-compose/docker-compose.yaml
example/k3d/lib/cortex/cortex-config.libsonnet
example/k3d/lib/cortex/main.libsonnet

Updates from a very old Cortex to the latest one to take advantage of blocks storage. Uses the [example single-process config](https://github.com/cortexproject/cortex/blob/master/docs/configuration/single-process-config-blocks.yaml) for configuring Cortex.
I'd consider this an "internal change," so nothing to do here.

update cortex for example/docker-compose and example/k3d to use blocks

---

pkg/tempo/config.go
pkg/tempo/config_test.go
pkg/tempo/instance.go
pkg/tempo/remotewriteexporter/exporter.go
pkg/tempo/remotewriteexporter/exporter_test.go
pkg/tempo/remotewriteexporter/factory.go

Fixes a race condition where the agent will fail to boot if the prometheus
instance that it's set to use to remote write metrics in the tracing
pipeline is not ready yet.

Retry getting prom instance in Tempo start up

---

CHANGELOG.md
docs/configuration-reference.md
docs/getting-started.md
docs/migration-guide.md
production/README.md
production/grafanacloud-install.sh
production/kubernetes/agent-bare.yaml
production/kubernetes/agent-loki.yaml
production/kubernetes/agent-sigv4.yaml
production/kubernetes/agent-tempo.yaml
production/kubernetes/agent.yaml
production/kubernetes/build/lib/version.libsonnet
production/kubernetes/install-bare.sh
production/kubernetes/install-loki.sh
production/kubernetes/install-sigv4.sh
production/kubernetes/install-tempo.sh
production/kubernetes/install.sh
production/tanka/grafana-agent/v1/main.libsonnet

I squashed the changelogs from all release candidates, removing bugfixes that only applied to a changed introduced in a previous release candidate.

Prepare for 0.14.0 release

---

production/README.md

Fixes the example which currently fails as it tries to execute the entirety of the entrypoint string. It also simplifies the example by mounting the volumes into the places expected by the image cmd.
fixes #614

doc: Correct and simplify "Running the Agent with Docker" example

---

docs/configuration-reference.md

Prometheus 2.26 updated the queue_config defaults. The values listed in the Agent's configuration reference were for the 2.25 values, and were out of sync with the version of Prometheus being used. 
(#120 would be nice here)

Update queue_config defaults in docs to match latest Prometheus defaults

---

Makefile

Wanted to run the agent on an [Ubiquiti EdgeRouter X](https://www.ui.com/edgemax/edgerouter-x/). This device architecture is MIPS, hence the need for a MIPS little endian (LE) build of the agent. 
Not sure you're interested of building and releasing MIPS version, but it would be nice if you could support it via the Makefile at least. Probably a few network devices/routers out there which is MIPS-based. For now I'll try to keep these changes in my fork. Let me know if this is interesting and/or whether I should add support for the other MIPS architectures in the Makefile or anything else that's missing.
Reference/guide/scripts/binaries for running the agent on Ubibuiti EdgeRouter: https://github.com/marefr/grafana-agent-edgeos
```
> lscpu  
Architecture:          mips
Byte Order: …
```

Support building MIPS (LE)

---

docs/configuration-reference.md

node_exporter integration doc is missing some parameters that enable the agent to monitor the node network instead of just the pod's
`hostPID: true` is in the upstream node_exporter [doc](https://github.com/prometheus-community/helm-charts/blob/f905bb896007b5fb63cb34e1717865d432cb6547/charts/prometheus-node-exporter/templates/daemonset.yaml#L131)
`hostNetwork: true` so we have access to node network ([doc](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces))
`dnsPolicy: ClusterFirstWithHostNet` so we can still resolve cluster dns names ([doc](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy))

Add missing network options to node_exporter doc

---

CHANGELOG.md
pkg/tempo/remotewriteexporter/exporter.go

Append ts in milliseconds as expected, instead of nanoseconds
Fixes https://github.com/grafana/agent/issues/617

Fix remote write exporter not pushing span metrics

---

CHANGELOG.md
pkg/prom/instance/host_filter.go
pkg/prom/instance/host_filter_test.go
pkg/prom/instance/instance.go

This change introduces a patching mechanism for `scrape_configs` to make performance-related tweaks for host filtering. The first performance tweak is to add a selector for `role: pod` to only look for pods on the same node as the Agent. 
This code is heavily inspired by (copied from) [Promtail](https://github.com/grafana/loki/blob/966bed72d3247a15c7f94a14ca13b536edb30f74/clients/pkg/promtail/targets/file/filetargetmanager.go#L95-L105).
Fixes #48.

Improve performance of kubernetes_sd_configs when using host_filter

---

CHANGELOG.md
pkg/client/grafanacloud/client.go
pkg/client/grafanacloud/client_test.go

Changes the cloud-config command to attempt parsing the response body before returning an error that the response code was unexpected. 
Fixes #360 
Closes #629 (dupe of #360)

Display specific error messages when cloud-config fails

---

.github/workflows/containerize.yml
.github/workflows/force_release.yml
.github/workflows/release.yml
.github/workflows/test.yml
.gitignore
Makefile
cmd/agent-operator/Dockerfile
cmd/agent-operator/Dockerfile.buildx
tools/release-note.md

Adds agent-operator as a release asset. This only includes it as a Docker image, since it doesn't make much sense (IMO, at least for now) for it to also be a plain binary, given its intention to run on Kubernetes.

Include agent-operator as a release asset

---

cmd/agent-operator/README.md
docs/getting-started.md
docs/operator/README.md
docs/operator/architecture.md
docs/operator/faq.md
docs/operator/getting-started.md
docs/operator/maintainers-guide.md

Adds docs for the Grafana Agent Operator introduced in #549.

docs for the Grafana Agent Operator

---

docs/operator/faq.md

(Done as a part of #656, but can be merged independently)

update Operator FAQ to describe custom scrape jobs

---

CHANGELOG.md
pkg/prom/wal/wal.go

Prometheus 2.26 changed the storage interface, removing the `AddFast` and `Add` methods, replacing with a single `Append` method. This also changed the expectation that `Append` should _not_ return `storage.ErrNotFound` on an invalid ref ID like `AddFast` used to. 
The 2.26 scraper will fail the scrape if `storage.ErrNotFound` is returned, and failed scrapes won't clear the cache, so the target will continue to fail to be scraped for the remainder of the process lifetime. This can be triggered primarily by a target going down for 2 GC cycles, when ref IDs of stale series are purged.
Fixes #659

don't return ErrNotFound on bad ref in Append

---

pkg/operator/config/config.go
pkg/operator/config/config_test.go
pkg/operator/config/templates/component/kube_sd_config.libsonnet
pkg/operator/config/templates/component/pod_monitor.libsonnet
pkg/operator/config/templates/component/probe.libsonnet
pkg/operator/config/templates/component/remote_write.libsonnet
pkg/operator/config/templates/component/service_monitor.libsonnet
pkg/operator/config/templates/prometheus.libsonnet
pkg/operator/config/templates_test.go
pkg/operator/config/utils.go
pkg/operator/resources.go

This PR adds tests to validate the operator and fixes various small issues:
1. BearerTokenFile doesn't exist for PodMonitors
2. MatchLabels may be null
3. Fix `pod_monitor.libsonnet` import
4. Use `yaml.v3` for Jsonnet `unmarshalYAML`, which unmarshals to
`map[string]interface{}` instead of `map[interface{}]interface{}`
5. Define `SHARDS` as an environment variable so custom scrape jobs can
reference it
The unit tests are quite a bit longer than I'd like them to be, but I can't think of a way to break them up any more, and they were useful for finding a few extra things I missed.
Feel free to just 🙈 through the tests, I suspect the Jsonnet code might not survive very long. Cue one day?

Operator: tests and fix various small issues

---

CHANGELOG.md
docs/configuration-reference.md
docs/migration-guide.md
pkg/tempo/config.go
pkg/tempo/config_test.go
pkg/tempo/instance.go

Add TLS config options for tempo remote_write. `insecure_skip_verify` is moved to `tls_config`
Fixes https://github.com/grafana/agent/issues/662.

Add TLS config options for tempo remote_write

---

CHANGELOG.md
pkg/prom/wal/wal.go
pkg/prom/wal/wal_test.go

`biggestRef` was incorrectly initialized to 0, which only works when there's no other segments, since that code is being called per-segment. If there was a segment with no series in it (which always happened with a new WAL is opened for writing), then the series ID will always be set to 0 and will always overlap with other metrics. 
This bug depends on an instance being restarted or the process crashing and restarting to trigger.
Fixes #675

Initialize biggest ref to existing ref when reading a segment

---

CHANGELOG.md
pkg/operator/defaults.go

Oops :) This wasn't being updated along with releases and was stuck at v0.14.0.

Update operator to use v0.16.1 by default

---

CHANGELOG.md
docs/configuration-reference.md
pkg/tempo/config.go
pkg/tempo/config_test.go

Support for OTLP HTPP trace exporter.
Fixes https://github.com/grafana/agent/issues/663.

Add OTLP HTPP exporter support

---

production/tanka/grafana-agent/v1/lib/integrations.libsonnet
production/tanka/grafana-agent/v1/main.libsonnet

This fixes a couple small issues with the `withIntegrations` jsonnet method for tanka deploys.
It also implements the `integrationsMixin` conditionally for the node_exporter integration, adding the necessary host volume mounts, and privileged container config.
N/A
Don't mind the name of my branch. I had initially committed some changes to *always* apply the integrations mixin since that was my use-case. I later realized it's not much more effort to do it "right" and contribute the fixes back.

Tanka Jsonnet Integrations Fixes

---

docs/upgrade-guide.md

Changed the Migration guide to Upgrade guide
Added metadata
Changed heading levels
I'm leaving this as one file for now, but when you get to 1.X, I recommend starting a new file and actually having proper release notes or What's new articles.

Docs: Renamed Migration guide and updated headings

---

docs/getting-started/_index.md
docs/getting-started/install-agent-on-windows.md

Moved files to getting-started folder
Renamed windows.md
I couldn't figure out where the example at the end of windows.md should go.

Docs: Getting started

---

docs/configuration-reference.md

Fixes an indentation error in the docs: automatic logging is at the top level of instance config
See the actual config struct
https://github.com/grafana/agent/blob/50efa00ac3edeec52353549d4e786126cbd35370/pkg/tempo/config.go#L107-L137

Docs: automatic logging is at the top level of instance config

---

cmd/agent/entrypoint.go
docs/api.md

Add `POST` method for `reload` config http endpoint.
Fixes #610

Add post method for config reload api

---

pkg/tempo/promsdprocessor/prom_sd_processor.go

Hi agent team! 👋 
This is a tiny PR to add a debug log in the prom service discovery processor. Something that will be helpful in discovering when attributes are not auto-added to spans.
Signed-off-by: Annanay <annanay.agarwal@grafana.com>

Add debug log in prom-sd processor to indicate missing ip tag

---

production/grafana-agent-mixin/dashboards.libsonnet
production/grafana-agent-mixin/mixin.libsonnet
production/grafana-agent-mixin/utils.libsonnet

This changes the following:
- fix `Scrape failures` queries to use the proper variables like the rest of queries
- add `grafana-agent-mixin` tag to all dashboards to allow easy link and discovery
n.a.
n.a.

Update dashboards setup in production mixin.

---

CHANGELOG.md
pkg/prom/cluster/cluster.go

Fixes a race condition while initializing the cluster. There was even a comment warning about this exact thing happening but the lock wasn't ever held when calling `Reshard`. 
Fixes #688.
The race checker should've caught this but it's difficult to reproduce in a test since it depends on the speed of CPUs, the work done when spinning up the cluster, and how many CPUs are available for scheduling goroutines.

fix race condition in initializing cluster

---

production/tanka/grafana-agent/v1/lib/integrations.libsonnet

When an integration is applied using the tanka library, it sets the daemonset or deployment to use host networking, but it does not change the DNS policy.
In my environment, this meant it could not write to my local cortex at `cortex.cortex.svc.cluster.local` because it couldn't resolve it.
N/A

Set DNSPolicy correctly when host network is used in daemonset

---

CHANGELOG.md
Makefile
cmd/agent/entrypoint.go
docs/configuration/tempo-config.md
docs/upgrade-guide.md
pkg/config/config.go
pkg/config/config_test.go
pkg/logs/config.go
pkg/logs/config_test.go
pkg/logs/logs.go
pkg/logs/logs_test.go
pkg/operator/config/templates/agent-logs.libsonnet
pkg/tempo/automaticloggingprocessor/automaticloggingprocessor.go
pkg/tempo/automaticloggingprocessor/automaticloggingprocessor_test.go
pkg/tempo/automaticloggingprocessor/factory.go
pkg/tempo/config.go
pkg/tempo/config_test.go
pkg/tempo/contextkeys/keys.go
pkg/tempo/instance.go
pkg/tempo/tempo.go

Renames the `loki` subsystem to `logs`, deprecating the old name. `loki`-named fields will continue to work until a further release that fully removes them.
Related to #722.
@mapno does `logs_tag` make sense for the overrides in automatic_logging? Should it be `logs_instance_tag`? I'm not 100% sure what it does.

Rename "loki" to "logs"

---

cmd/agent/entrypoint.go

The documentation for [`signal.Notify`](https://pkg.go.dev/os/signal#Notify) says:
> Package signal will not block sending to c: the caller must ensure that c has sufficient buffer space to keep up with the expected signal rate. For a channel used for notification of just one signal value, a buffer of size 1 is sufficient. 
This PR adds a buffer to the channel introduced in #710.

Use buffered channel for signal.Notify

---

production/kubernetes/README.md
production/kubernetes/install-bare.sh

Directs users away from the install-bare.sh script which is used only for Grafana Cloud and will eventually be removed in favor of Helm charts.

Add install-bare.sh warning

---

CHANGELOG.md
docs/configuration/_index.md
pkg/config/config.go
pkg/config/config_test.go

Environment variable patterns from `-config.expand-env` (`${HOSTNAME}`) can look exactly like regex capture group references (`${1}`), causing the latter to get trimmed out from the file. This PR checks to see if the environment name is a number, and if it is, will keep the reference intact.
Closes #692.
This is kind of a hacky fix. Windows technically supports numeric environment variables (IIRC), and also this will replace other functions like `${1=default}` with `${1}`. But it might be good enough for now, since the latter would only be valid on Windows and I suspect would be an extremely rare use case.

Ignore regex capture groups when expanding environment vars

---

CHANGELOG.md
docs/configuration/loki-config.md
docs/getting-started/install-agent-on-windows.md
pkg/logs/logs.go
pkg/logs/logs_test.go

I noticed a problem with #748 where positions directories weren't being created properly. This PR will create the positions directory at the config level (since they can be different and we intend to automatically create them)..

Logs:  create positionsdir per config

---

pkg/operator/config/logs_templates_test.go
pkg/operator/config/templates/agent-logs.libsonnet
pkg/operator/config/templates/component/logs/client.libsonnet
pkg/operator/config/templates/component/logs/external_labels.libsonnet
pkg/operator/config/templates/logs.libsonnet

Adds the `cluster` label to all logs found by the Grafana Agent Operator deployment. This matches the behavior of the cluster label added for metrics. The replica label isn't added since there is no concept of replicas for logs.
Found during #748.

operator: add cluster label to all logs

---

pkg/operator/apis/monitoring/v1alpha1/types.go
production/operator/crds/monitoring.grafana.com_grafana-agents.yaml

This PR si fixing a typo in the `GrafanaAgent` CRD which was probably introduced by copying description for `spec.secrets` to `spec.configMaps`.

Fixing typo in the GrafanaAgents CRD

---

go.mod
pkg/operator/config/config_references.go
pkg/operator/config/config_references_test.go
pkg/util/structwalk/structwalk.go
pkg/util/structwalk/structwalk_test.go

Modifies the AssetReferences code to no longer manually traverse the resource hierarchy and instead use reflection to find all secret and configmap selectors.
This allows AssetReferences to always work regardless of changes we make to the CRDs and removes the risk of forgetting to update it.

Operator: use reflection to discover references to secrets and configsmaps

---

docs/configuration/tempo-config.md
docs/upgrade-guide.md
example/docker-compose/agent/config/agent-scraping-service.yaml
pkg/tempo/config.go
pkg/tempo/config_test.go
pkg/tempo/instance.go

Split load balancing from tail sampling, as it can be useful for other purposes too, such as service graphs or other processors that benefit from having complete traces.
Need to be merged before https://github.com/grafana/agent/pull/756

Split load balancing

---

CHANGELOG.md
Makefile
pkg/operator/selector_eventhandler_test.go

This test does download and invoke kubebuilder-tools, to make sure there
is no extra steps needed just to run this one test.
(https://github.com/grafana/agent/issues/731#issuecomment-878255964).
However, distros usually build and run tests in a sandbox with network
access disabled, causing this test to fail.
Introduce a `online` flag, defaulting to false, and skip this test as
long as `-online` is not passed.
CI, which invokes `make test` deliberately sets this to true, to have
coverage for that test provided by CI.
Fixes #731.

TestEnqueueRequestForSelector: only run test if -online flag is set

---

production/kubernetes/README.md
production/kubernetes/agent-bare.yaml
production/kubernetes/agent-loki.yaml
production/kubernetes/agent-tempo.yaml
production/kubernetes/build/templates/tempo/main.jsonnet
production/tanka/grafana-agent/v1/internal/agent.libsonnet
production/tanka/grafana-agent/v1/lib/deployment.libsonnet

This PR moves quickstart deployment and configuration instructions into the Cloud docs. In addition, the trace collector Agent is rolled out as a Deployment instead of a DaemonSet by default. Tested with the Grafana [demo app](https://github.com/grafana/tns) and Grafana Cloud.
Broken link pending https://github.com/grafana/website/pull/5340

Use Deployment for traces quickstart

---

production/kubernetes/agent-loki.yaml
production/tanka/grafana-agent/v1/main.libsonnet

Cleans up small bug from https://github.com/grafana/agent/pull/772 where `HOSTNAME` is set twice

Remove duplicate HOSTNAME env var

---

docs/getting-started/_index.md

The original [documentation](../operator/_index.md) makes the link broken; removing the _index.md part should fix it based on similar links in this and other pages.

the Operator-specific documentation

---

CHANGELOG.md
docs/configuration/integrations/_index.md
docs/configuration/integrations/github-exporter-config.md
example/docker-compose/agent/config/agent-local.yaml
go.mod
go.sum
pkg/integrations/github_exporter/github_exporter.go
pkg/integrations/install/install.go

Github exporter integration

---

CHANGELOG.md
pkg/integrations/node_exporter/config.go

This adds `darwin` to the switch statement for the `node_exporter` default config, making it so that filesystem metrics are actually collected.
Fixed #818 
- [N/A] Documentation added

Fix filesystem collector defaults on darwin / Mac OS

---

CHANGELOG.md
pkg/util/logger_windows.go

Previously passing the array to the logger would cause only "\n" to be logged, flattening out the array allows info to be logged correctly.
Closes #828

Fix issue where windows logger info messages only log "\n"

---

example/k3d/environment/main.jsonnet
production/tanka/grafana-agent/v1/lib/tempo.libsonnet

This applies the tempo config change defined [here](https://github.com/grafana/agent/blob/ff545a16c02bc3877de7df7b6327ef963d94401e/docs/upgrade-guide/_index.md#tempo-split-grouping-by-trace-from-tail-sampling-config) to the k3d example project + tempo.libsonnet.

Match tempo.libsonnet and example k3d with latest load_balancing config

---

.github/depcheck.yml

Use https://github.com/rfratto/depcheck/commit/ce563b5a4d94dfcc73aa91373c0b747964aa19eb to configure depcheck to ignore Prometheus release candidates and not create issues for them.

depcheck: Ignore Prometheus release candidates

---

pkg/integrations/redis_exporter/redis_exporter.go

Super minor, but I was running the agent with log_level=debug and noticed that my Redis exporter config wasn't being logged correctly:
```
ts=2021-08-19T13:41:55Z level=info msg="Receiver started." component=tempo tempo_config=default kind=receiver name=jaeger
ts=2021-08-19T13:41:55.5608507Z level=debug integration=redis_exporter msg="initialising redis_exporer with config %v"
```
(No breaking changes so I haven't updated other things)

Fix Redis exporter initialization log

---

CHANGELOG.md
cmd/agent/entrypoint.go
pkg/config/config.go
pkg/integrations/manager.go
pkg/integrations/manager_test.go

We are doing a yaml compare of the IntegrationsManager config on reload to see if anything changed. Prometheus settings are not applied to the Integration configs the IntegrationManager has so it looks like nothing changed and we short circuit out. 
This change adds the global Prometheus Config to the IntegrationManager config to avoid short circuiting. There's also some small logging changes I kept that made it a little easier while troubleshooting. 
Fixes #827 

Fix issue with global scrape_interval changes not reloading integrations

---

example/k3d/scripts/create.bash

Fedora 34 requires mapping /dev/mapper to the k3d container: https://k3d.io/faq/faq/#issues-with-btrfs

Fix k3d create script on Fedora 34

---

CHANGELOG.md
pkg/metrics/instance/configstore/remote.go

Registers `agent_configstore_consul_request_duration_seconds` to track the time it takes to do a consul list using the optimization shortcut. 
Note that the metric must have a different name due to it being a separate histogram, and the underlying metric used by Cortex's kv store is not exposed so we have to make our own.
Fixes #855

Register missing metric

---

CHANGELOG.md
pkg/tempo/tempo.go
pkg/util/logger.go

This adds caller information to the logger used primarily throughout the agent. This also adds caller info to the tempo logger which uses a different library. The format for that library is slightly different though
Fixes #684 
The issue is here, https://github.com/grafana/agent/blob/1278506dcc74cd7818c436b1ad0e2d494d9bb8f1/cmd/agent/main.go#L58-L78 The call `cfgLogger = util.GoKitLogger(logger)` adds caller info via `log.With` which makes a new instance. The new instance becomes `cfgLogger` but `logger` is still used because of type differences.
- [ x ] CHANGELOG updated 
- [ na ] Documentation added
- [ na ] Tests updated : I couldn't come up with a clean way to test this change

Add caller information to logs

---

CHANGELOG.md
cmd/agent/entrypoint.go
docs/upgrade-guide/_index.md
pkg/config/config.go
pkg/config/config_test.go
pkg/metrics/agent.go
pkg/metrics/cluster/client/client.go

Aliases `prometheus` to `metrics` and deprecates the former. 
Related to #722. 
Does not touch the tracing configs yet, that will be done in a follow up PR.

Rename prometheus to metrics

---

CHANGELOG.md
docs/configuration/prometheus-config.md
pkg/metrics/cluster/cluster.go
pkg/metrics/cluster/config.go
pkg/metrics/cluster/config_watcher.go
pkg/metrics/cluster/node.go

Config refresh timeout should honor the timeout, but the lifecycle timeout should use a background context.
Closes #856 
Closes #857 
Closes #877 

Honor config refresh timeout, remove timeout for lifecycle and instead use background context

---

docs/upgrade-guide/_index.md
pkg/tempo/config.go
pkg/tempo/config_test.go

When extracting load balancing from tail sampling, only the the load_balancing block was moved into its own block, but the receiver's port was left in tail_sampling.
This means that the receiver port for load_balancing could not be configured without tail_sampling.
Now it's moved to load_balancing as receiver_port.
It also includes a fix for when using load balancing where pipelines wouldn't be split if tail sampling wasn't enabled as well.
Change is not in the CHANGELOG since the load balancing change hasn't been released yet.

Move port to load_balancing config as receiver_port

---

CHANGELOG.md
cmd/agentctl/main.go
pkg/client/grafanacloud/client.go
pkg/client/grafanacloud/client_test.go
production/grafanacloud-install.sh

Change the Grafana Cloud client to accept the API url as a parameter,
or default to the hardcoded value if it's empty.
Also update the installation script to look for a new environment
variable `GCLOUD_API_URL`.
n.a.
n.a.

agentctl: allow specifying Grafana Cloud's API url in cloud-config cmd

---

.github/workflows/publish.yml

Syncs `docs` dir to the website. Fixes https://github.com/grafana/website/issues/5440.
Todo:

add docs sync

---

CHANGELOG.md
docs/configuration/tempo-config.md
docs/upgrade-guide/_index.md
example/docker-compose/agent/config/agent.yaml
pkg/tempo/config.go
pkg/tempo/config_test.go
pkg/tempo/instance.go
pkg/tempo/remotewriteexporter/factory.go

I think this is the only thing mentioning `prom`/`prometheus` in the tracing code. Let me know if I missed something else.
Related to #722.

Rename prom_instance -> metrics_instance

---

CHANGELOG.md
pkg/tempo/promsdprocessor/prom_sd_processor.go

tempo agent: if relabel config drops target, don't attempt to process it.
This avoids e.g. logging a warning when a target is intentionally dropped
#904
The current setup for testing doesn't have any easy path to test output of logging; so I wasn't able to add a test for this.

tempo: if relabel config drops target, don't attempt to process (#904)

---

docs/operator/getting-started.md

Update `## Deploy GrafanaAgent` section to include additional kubelet metrics.  Reason:  When checking the metrics sent to Grafana Cloud, we noticed that some of kubelet metrics (cpu/memory usage) was missing.  On the agent, we are using the backwards compatibility with the Prometheus Operator CRDs ServiceMonitor and PodMonitor , so that metric instance discovery is exactly as it is with our hosted prometheus.
Update `## Deploy GrafanaAgent` section to include additional kubelet metrics.  Reason:  When checking the metrics sent to Grafana Cloud, we noticed that some of kubelet metrics (cpu/memory usage) was missing.  On the agent, we are using the backwards compatibility with the Prometheus Operator CRDs ServiceMonitor and PodMonitor , so that metric instance discovery is exactly as it is …

Update for `## Deploy GrafanaAgent` clusterrole

---

CHANGELOG.md
docs/configuration/prometheus-config.md
go.mod
pkg/metrics/cluster/cluster.go
pkg/metrics/cluster/config.go
pkg/metrics/instance/configstore/kv/client.go
pkg/metrics/instance/configstore/kv/client_test.go
pkg/metrics/instance/configstore/kv/consul/client.go
pkg/metrics/instance/configstore/kv/consul/client_test.go
pkg/metrics/instance/configstore/kv/consul/metrics.go
pkg/metrics/instance/configstore/kv/consul/mock.go
pkg/metrics/instance/configstore/kv/etcd/etcd.go
pkg/metrics/instance/configstore/kv/etcd/mock.go
pkg/metrics/instance/configstore/kv/kv_test.go
pkg/metrics/instance/configstore/kv/metrics.go
pkg/metrics/instance/configstore/kv/mock.go
pkg/metrics/instance/configstore/kv/multi.go
pkg/metrics/instance/configstore/kv/multi_test.go
pkg/metrics/instance/configstore/kv/prefix.go
pkg/metrics/instance/configstore/remote.go
pkg/metrics/instance/configstore/remote_test.go

The cortex kv package is focused heavily on a hash ring, making it increasingly inappropriate to use as a KV store for the configstore, which has different expectations about how it will be consumed. This initial PR does a basic copy
of the cortex package (from the specific version of Cortex we're already depending on) into configstore.
Initial changes from the Cortex package:
- Memberlist is removed
- cortex_ metrics have been reprefixed with agent_
This is a medium-term fix. I do not anticipate that the configstore package will exist forever, but we need a way to make it performant for now until we have something long-term in place.
This also unveiled a bug in updating the cluster config. Oops!
This PR also immediately uses the new package, which doesn't require much except to point at …

[dev.scraping-service-scalability] Fork the cortex ring/kv package for use with the configstore

---

.gitignore

#925 found that the .gitignore was being too aggressive: we don't want to ignore all vendor folders, just the Go module vendor folder. 
This commit changes the .gitignore to be explicit about what is being ignored at the root path.

update .gitignore to be explicit about root paths

---

example/docker-compose/grafana/dashboards/agent-operational.json
example/docker-compose/grafana/dashboards/agent-remote-write.json
example/docker-compose/grafana/dashboards/agent.json
production/grafana-agent-mixin/dashboards.libsonnet
production/grafana-agent-mixin/mixin.libsonnet
production/grafana-agent-mixin/utils.libsonnet

This PR has a handful of small changes to the mixin dashboards
- Adds a samples rate panel back to the remote write dashboard based on the newer prom one, https://github.com/prometheus/prometheus/blob/main/documentation/prometheus-mixin/dashboards.libsonnet#L143
- Flips `Created Series` back to `Appended Samples` (I changed this here, https://github.com/grafana/agent/pull/878/files#diff-0ffb78c3d3889793bebfb96a62bc7291cff9b69cc100278a96f16a6461de784c, because I didn't see the new metric)
- Partitions targets by pod on the main dashboard
- Adds the operational dashboard to the mixin
- All dashboards should be 1h range with a 30s refresh now
I tested out the changes using the k3d example
- [ na ] CHANGELOG updated 
- [ na ] Documentation added
- [ na ] Tests updated

Mixin Dashboard Updates

---

CHANGELOG.md
pkg/metrics/instance/configstore/kv/client.go
pkg/metrics/instance/configstore/kv/consul/client.go
pkg/metrics/instance/configstore/kv/etcd/etcd.go
pkg/metrics/instance/configstore/kv/kv_test.go
pkg/metrics/instance/configstore/kv/metrics.go
pkg/metrics/instance/configstore/kv/mock.go
pkg/metrics/instance/configstore/kv/multi.go
pkg/metrics/instance/configstore/kv/pair/kvp.go
pkg/metrics/instance/configstore/kv/prefix.go
pkg/metrics/instance/configstore/remote.go

#802 introduced a short-term fix for #789. Now that we're making a growing amount of changes to how we interact with the KV store, it's a good opportunity to move those changes to the fork of the KV package introduced in #927. 
This PR should be equivalent in performance to the Consul change, but now works for ETCD as well. 
This is the first change to the kv interface to make `List` always return key value pairs instead of just keys.
Need to update the CHANGELOG to reference that the metrics changed names again.

[dev.scraping-service-scalability] Move #802 fix to kv fork

---

.drone/drone.yml
CHANGELOG.md
cmd/agent/agent-local-config.yaml
docs/getting-started/create-config-file.md
docs/scraping-service/_index.md
example/docker-compose/agent/config/agent-local.yaml
example/docker-compose/agent/config/agent-scraping-service.yaml
example/docker-compose/agent/config/agent.yaml
example/k3d/environment/main.jsonnet
example/k3d/smoke/main.jsonnet
example/k3d/smoke/monitoring/prometheus_monitoring.libsonnet
packaging/grafana-agent.yaml
packaging/windows/install_script.nsis
production/tanka/grafana-agent/config.libsonnet

This PR changes most of our documentation and examples to use 1m has the default scrape interval. Also changes our testing/smoke test environments to also use 1m. 
Closes #755
Closes #919 
- [] Documentation added
- [] Tests updated

Standardize default scrape interval to 1m

---

CHANGELOG.md
pkg/metrics/instance/configstore/kv/consul/client.go
pkg/metrics/instance/configstore/kv/consul/mock.go
pkg/metrics/instance/configstore/kv/etcd/etcd.go
pkg/metrics/instance/configstore/kv/kv_test.go
pkg/metrics/instance/configstore/kv/pair/kvp.go

The Cortex KV package had ignore deleted events from etcd because other implementations didn't detect when a key had gone away. 
This PR detects deleted keys in Consul by keeping track of configs that go away in between List calls. 
Note that there's no guarantee a delete event will be detected if there are multiple sequential calls to WatchPrefix. If a key is deleted in between calls, the subsequent call will be unaware that the key used to exist. I believe the same effect exists for the etcd watch though: the etcd watch only returns mutation events from the start of the watch, and keys may be deleted in between. 
Despite this, it still may be worthwhile to have this enhancement, since it's better than it was before and will detect most deletes.

[dev.scraping-service-scalability] Catch delete events from kv.WatchPrefix

---

docs/api/_index.md
docs/configuration/_index.md
docs/configuration/integrations/mongodb_exporter-config.md
docs/configuration/logs-config.md
docs/configuration/metrics-config.md
docs/operation-guide/_index.md
example/k3d/environment/main.jsonnet
pkg/config/config_test.go
pkg/metrics/cluster/client/client.go
pkg/operator/config/config_test.go
pkg/operator/config/templates/agent-metrics.libsonnet
pkg/operator/config/templates/metrics.libsonnet
pkg/traces/contextkeys/keys.go
pkg/traces/instance.go
pkg/traces/remotewriteexporter/exporter.go
production/kubernetes/build/templates/loki/main.jsonnet
production/tanka/grafana-agent/v1/README.md
production/tanka/grafana-agent/v1/lib/deployment.libsonnet
production/tanka/grafana-agent/v1/lib/metrics.libsonnet
production/tanka/grafana-agent/v1/main.libsonnet

Related to #739. 
Closes #722 (:tada:)
This doesn't change any `agent_prometheus_` metrics name. It also doesn't change `prometheus_remote_write` in integrations. Not sure if we want to do that?

Rename Prometheus to Metrics in docs / jsonnet

---

docs/configuration/logs-config.md

We need to note users about using backslashes in agent config file, and about not supported backticks too.
Also I've added error messages text for quicker finding the solution by error text.

Add note about using backslashes and backticks

---

CHANGELOG.md
pkg/integrations/manager.go
pkg/metrics/cleaner.go
pkg/metrics/cluster/config_watcher.go
pkg/metrics/instance/configstore/api.go
pkg/metrics/instance/manager.go
pkg/metrics/instance/modal_manager.go

Metrics prefixed with `agent_prometheus_` will now be prefixed with `agent_metrics_` instead.
We might not want to do this, mostly opening for spurring a discussion.

Rename metrics in the metrics subsystem

---

CHANGELOG.md
cmd/agent-operator/agent-example-config.yaml
cmd/agent-operator/example-grafana.yaml
docs/operator/getting-started.md
pkg/operator/clientutil/clientutil.go
pkg/operator/kubelet.go
pkg/operator/kubelet_test.go
pkg/operator/operator.go
pkg/operator/resources_metrics.go

Enables the operator to manage a Kubelet service, creating one endpoint per node in the cluster. This allows users to define a cAdvisor/Kubelet ServiceMonitor for collecting metrics. Previously, this had to be done by using additional manually-created scrape configs with custom `kubernetes_sd_configs` rules. 
Fixes #885.
This copies the Prometheus Operator default of not providing this behavior OOTB and _must_ be configured by passing the flag. cc @hjet for the Helm charts.

Operator: Add support for managing a kubelet service

---

docs/configuration/traces-config.md

Added comment with examples how to fill port of `remote_write` tempo endpoint for local and on-premises instances.
For new users it's unclear which port to choose, and in most cases they try to fill the default `3200` Tempo port, instead of gRPC receiver port.

Add note about ports in tempo remote_write enpoint

---

CHANGELOG.md
docs/configuration/traces-config.md
pkg/traces/automaticloggingprocessor/automaticloggingprocessor.go
pkg/traces/automaticloggingprocessor/automaticloggingprocessor_test.go

Replace dots for underscores in autologged labels.
Loki only accepts alphanumeric and "_" as valid characters for labels. Attributes containing dots are replaced for underscores
Fixes https://github.com/grafana/agent/issues/941

Replace dots for underscores in autologged labels

---

CHANGELOG.md

Due to our holding off on some merges til v0.19.0 was released, when changes were merged they were mistakenly added to v0.19.0 release

Update changelog with some bad merges that added notes to v0.19.0

---

CHANGELOG.md
production/grafana-agent-mixin/dashboards.libsonnet

If samples are getting backlogged, it may be due to latency between the agent and the backend it is sending to.
Replaced the differential panel which doesn't add much to the timestamp panel to the left, and essentially duplicates the differential samples rate panel below.
Before:
After:
- NA Documentation added
- NA Tests updated

Show remote write latency on dashboard

---

pkg/metrics/cluster/config_watcher.go

Since this message is logged periodically and an implementation detail we can
log it at a debug level.
Resolves #1048

Log config watcher reshard timer at debug level

---

CHANGELOG.md
packaging/rpm/control/postinst

The env variables in add_to_logging_group() did not match the names set at the start of the post install script.
Correct names of user & group environment variables so uniform name is used throughout.

Use correct user/group env variables

---

CHANGELOG.md
pkg/operator/resources_metrics.go

The MetricsInstance Service created by Operator was using port `9090` when the Agent ContainerPorts [are set to 8080](https://github.com/grafana/agent/blob/beccf9b6f9d32298571dbba2038763b5be19fe02/pkg/operator/resources_metrics.go#L230). This PR fixes this bug.

Operator: Fix metrics service port

---

CHANGELOG.md
pkg/operator/resources_metrics.go

Currently operator tries to create a single govern service for all Agents. It fails due to multiple controller owners for a single k8s object.
PR creates a govern service dedicated to a `Grafana Agent`.
Fixes https://github.com/grafana/agent/issues/964

Create a govern metrics service per Grafana Agent

---

CHANGELOG.md
pkg/operator/config/logs_templates_test.go
pkg/operator/config/templates/component/logs/relabel_config.libsonnet

Discovered a bug today while testing Operator/PodLogs with some relabel_configs (this is from Operator logs):
```
level=error ts=2021-11-04T21:45:36.41286717Z component=controller.grafanaagent name=grafana-agent namespace=default msg="error during reconciling" err="unable to build config: RUNTIME ERROR: no such file: ./relabel_config.libsonnet\n\tcomponent/logs/pod_logs.libsonnet:5:28-63\tthunk <new_relabel_config> from <$>\n\tcomponent/logs/pod_logs.libsonnet:138:19-37\tfunction <anonymous>\n\t<std>:247:50-62\tfunction <anonymous>\n\t\t\n\text/optionals.libsonnet:40:17-50\tfunction <anonymous>\n\tagent-logs.libsonnet:(20:28)-(45:3)\tthunk from <function <anonymous>>\n\text/marshal.libsonnet:3:44-50\tthunk from <function <anonymous>>\n\text/marshal.libsonnet:3:18-51\tfunction …
```

Operator: Add relabel_config.libsonnet to logs templates dir

---

CHANGELOG.md
go.mod
go.sum
pkg/traces/servicegraphprocessor/factory.go
pkg/traces/servicegraphprocessor/processor.go
pkg/traces/servicegraphprocessor/processor_test.go
pkg/traces/servicegraphprocessor/store.go
pkg/traces/servicegraphprocessor/store_test.go

The implementation with the cache library had a ver bad performance,
specially when calling `Items()`, since it would create a new map
and copy all items to it.
This commit changes the implementation to use a map and a list with a mutex.
The list is used to keep track of the oldest items.
Saw significant improvements in CPU usage. A new profile showed the processor to take ~2.55% of total CPU time.
- ~[ ] Documentation added~

Service graphs performance improvements

---

go.mod
go.sum

This PR updates grafana/prometheus dependency to a branch created on release-2.31.0-grafana with bboreham:improve-rw-sharding merged in.
https://github.com/grafana/prometheus/tree/improve-rw-sharding

[dev.improve-rw-sharding] update grafana/prometheus to 9c127431b579

---

CHANGELOG.md
docs/operator/helm-getting-started.md
production/README.md

This adds a quickstart guide for deploying Agent Operator using Helm and configuring a base set of custom resources for metrics and logs. There is some overlap with the existing getting started guide (and really only the first steps will be different), so perhaps _this_ should become the main quickstart and have an optional section for manually deploying CRDs and Agent Operator? Or move that to its own doc? Or just have both these guides live in parallel to one another.

[Operator] Add Helm quickstart guide

---

production/grafanacloud-install.sh

A bug in `production/grafanacloud-install.sh` results in the script not exiting properly when `retrieve_config` fails. It also prints an ugly error message which this hides.
Fixes #599 
Typically I would use something like `set -o pipefail` in bash scripts to handle a case like this but I believe that's not POSIX compliant nor available in dash.

handle retrieve_config failures

---

go.mod
go.sum
pkg/integrations/node_exporter/config.go
pkg/integrations/node_exporter/node_exporter_linux.go

Update github.com/go-kit/kit to v0.12.0 to take advantage of the go-kit/log shim introduced in that version. 
Companion PR to #1094, but ensures that dependencies still using the old logging module will continue to work.

Update github.com/go-kit/kit to v0.12.0

---

CHANGELOG.md
docs/configuration/integrations/node-exporter-config.md
docs/configuration/integrations/process-exporter-config.md
docs/getting-started/_index.md
docs/operator/custom-resource-quickstart.md
docs/operator/getting-started.md
docs/upgrade-guide/_index.md
example/docker-compose/grafana/dashboards/agent-operational.json
example/docker-compose/grafana/dashboards/agent-remote-write.json
example/docker-compose/grafana/dashboards/agent.json
pkg/operator/defaults.go
production/README.md
production/grafanacloud-install.sh
production/kubernetes/agent-bare.yaml
production/kubernetes/agent-loki.yaml
production/kubernetes/agent-traces.yaml
production/kubernetes/build/lib/version.libsonnet
production/kubernetes/install-bare.sh
production/tanka/grafana-agent/v1/main.libsonnet
production/tanka/grafana-agent/v2/internal/base.libsonnet
production/tanka/grafana-agent/v2/internal/syncer.libsonnet

Prepare for v0.21.0 release by following the [release procedure](https://github.com/grafana/agent/blob/main/cmd/agent/DEVELOPERS.md#performing-the-release)

0.21.0 release prep

---

CHANGELOG.md
pkg/integrations/postgres_exporter/postgres_exporter.go
pkg/integrations/postgres_exporter/postgres_exporter_test.go

This PR fix issue `postgres_exporter.parsePostgresURL()` that causes the grafana-agent service wont start.
Fixes #1110

Fix parsePostgresURL issue

---

CHANGELOG.md
pkg/metrics/agent.go

This avoids noisy logs when someone uses the agent only for logs/traces.
Fixes #735

Don't create a WAL cleaner when there's no configured WAL directory.

---

.drone/drone.yml

This deploys agent to dev on a merge to main.
Depends on https://github.com/grafana/deployment_tools/pull/19936
Currently this automation only opens a PR, but I want to double check things and then I'll deploy directly to dev without a PR.
Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>

Setup CD for agent

---

CHANGELOG.md
docs/configuration/traces-config.md
pkg/traces/config.go
pkg/traces/promsdprocessor/factory.go
pkg/traces/promsdprocessor/prom_sd_processor.go
pkg/traces/promsdprocessor/prom_sd_processor_test.go

Improves pod association in PromSD processor by adding new techniques to get the IP of the trace sender.
Fixes https://github.com/grafana/agent/issues/1095

Traces: Improved pod association in PromSD processor

---

CHANGELOG.md
docs/configuration/_index.md
pkg/config/config.go
pkg/config/remote_config.go
pkg/config/remote_config_test.go

This PR adds a simple remote configuration framework and implements an http(s) provider. More providers to come in following PRs.
https://github.com/grafana/agent/issues/1121  (partially)
Currently the http remote provider supports basic auth, by passing the password, or a password file. To enable the feature, pass the `-experiment.config-urls.enable` flag when starting the agent.
The following command line flags have been added for auth for the http/https provider:
* `-config.url.basic-auth-user`
* `-config.url.basic-auth-password-file`

remote config with http(s) provider

---

CHANGELOG.md
pkg/integrations/postgres_exporter/postgres_exporter.go
pkg/integrations/postgres_exporter/postgres_exporter_test.go

A recent change broke the usage of POSTGRES_EXPORTER_DATA_SOURCE_NAME for the postgres_exporter.
As the incorrect variable was checked in the if clause, it always raises an error.
As I'm not familiar with the codebase (and more generally go) it would take me a lot of time to add a regression test for this. It would be great if someone else could do this.

Fix POSTGRES_EXPORTER_DATA_SOURCE_NAME usage for postgres_exporter

---

CHANGELOG.md
packaging/deb/grafana-agent.service
packaging/environment-file
packaging/rpm/grafana-agent.service

This PR removes the log-level flag from the systemd unit file, so that only the value from the config file is taken into consideration.
Fixes #1172
None.
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

Remove log-level flag from systemd unit file

---

CHANGELOG.md
docs/configuration/_index.md
pkg/config/config.go
pkg/config/config_test.go
pkg/config/features/features.go
pkg/config/features/features_test.go

This commit introduces a new package, pkg/config/features, which allows defining a set of features and validating whether flags associated with those features are allowed to be set.
Closes #1163
Renames the `config-urls` feature flag to `remote-configs`, since they might not necessarily be URLs forever.
Removes the old `--experiment.config-urls.enable` flag in favor of `--enable-features=remote-configs`.

config/features: create package to standardize experimental features

---

cmd/agent/agent-local-config.yaml
pkg/integrations/install/install.go
pkg/integrations/install/shims.go
pkg/integrations/v2/metricsutils/metricshandler_integration.go
pkg/integrations/v2/metricsutils/versionshim.go
pkg/integrations/v2/register.go
pkg/integrations/v2/register_test.go

Shimming is done by changing how the integration registration works; a new RegisterDynamic function is introduced. This function allows registering any type as an integration and converting it to a Config later. Here be dragons; this should be removed whenever we no longer have a need for it.
I tried pretty hard to do this another way, but the fact that unmarshaled integrations will almost always be the zero value for the registered type prevents something less confusing. Instead, we marshal/unmarshal the "real" type (i.e., the v1 integration) and define a wrapper to work around our constraints.

[dev.multiple-integrations] integrations/v2: allow shimming between v1 and v2 integrations.

---

CHANGELOG.md
docs/upgrade-guide/_index.md
pkg/integrations/config/config.go
pkg/integrations/manager.go
pkg/integrations/manager_test.go
pkg/integrations/register.go
pkg/integrations/register_test.go

This PR reverts 69ba2ddfa9483cc8ac6e010dd7abccd319580c80 in favor of allowing the new subsystem to handle multiple instances of integrations.
This PR also removes the `wal_truncate_frequency` field from integrations as it is the only field from old integrations that does not have a current counterpart, and gives negative performance implications to the current integrations by existing.

[dev.multiple-integrations] Revert deprecated changes

---

pkg/integrations/agent/agent.go
pkg/integrations/cadvisor/common.go
pkg/integrations/consul_exporter/consul_exporter.go
pkg/integrations/dnsmasq_exporter/dnsmasq_exporter.go
pkg/integrations/elasticsearch_exporter/elasticsearch_exporter.go
pkg/integrations/github_exporter/github_exporter.go
pkg/integrations/integration.go
pkg/integrations/kafka_exporter/kafka_exporter.go
pkg/integrations/manager.go
pkg/integrations/manager_test.go
pkg/integrations/memcached_exporter/memcached_exporter.go
pkg/integrations/mongodb_exporter/mongodb_exporter.go
pkg/integrations/mysqld_exporter/mysqld-exporter.go
pkg/integrations/node_exporter/config.go
pkg/integrations/postgres_exporter/postgres_exporter.go
pkg/integrations/process_exporter/config.go
pkg/integrations/redis_exporter/redis_exporter.go
pkg/integrations/register.go
pkg/integrations/register_test.go
pkg/integrations/statsd_exporter/statsd_exporter.go
pkg/integrations/windows_exporter/config.go
pkg/util/yaml.go

This PR removes the requirement that `integrations.Config` implement a method to expose common config settings.
Instead, common configs are now automatically unmarshaled alongside integrations. 
While this is somewhat useful for reducing the smallest amount of boilerplate, it is more immediately useful for #1183, which will use a _different_ set of common configs when running with the integrations-next feature flag. 
This is some unfortunate complexity 😞 The requirement of strictly marshaling/unmarshaling into two inlined types where one may implement yaml.Unmarshaler is mostly why this is a pain.
Internal change, nothing here needed.

pkg/integrations: decouple common config from integration-specific configs

---

example/docker-compose/agent/config/agent-integrations-next.yaml
example/docker-compose/docker-compose.integrations-next.yaml
pkg/integrations/consul_exporter/consul_exporter.go
pkg/integrations/dnsmasq_exporter/dnsmasq_exporter.go
pkg/integrations/elasticsearch_exporter/elasticsearch_exporter.go
pkg/integrations/github_exporter/github_exporter.go
pkg/integrations/install/shims.go
pkg/integrations/kafka_exporter/kafka_exporter.go
pkg/integrations/memcached_exporter/memcached_exporter.go
pkg/integrations/mongodb_exporter/mongodb_exporter.go
pkg/integrations/mysqld_exporter/mysqld-exporter.go
pkg/integrations/postgres_exporter/postgres_exporter.go
pkg/integrations/redis_exporter/redis_exporter.go
pkg/integrations/statsd_exporter/statsd_exporter.go
pkg/integrations/v2/agent/agent.go
pkg/integrations/v2/metricsutils/versionshim.go
pkg/integrations/v2/register_test.go

This PR completes the core of the dev branch, opting in the following current integrations to support multiple instances for integrations-next:
- consul_exporter
- dnsmasq_exporter
- elasticsearch_exporter
- github_exporter
- kafka_exporter
- memcached_exporter
- mongodb_exporter
- mysqld_exporter
- postgres_exporter
- redis_exporter
- statsd_exporter
Other integrations do not opt in and therefore only support being unmarshaled from the singleton, non-`_config` syntax.
A docker compose environment is included for testing.

[dev.multiple-integrations] Multiple instances of integrations

---

CHANGELOG.md
cmd/agent/service_windows.go

This PR starts the command loop for handling windows service messages immediately instead of waiting for the agent to fully load. It still ensures that the config is loaded correctly. There are some possible race conditions but those are if the service is told to shutdown so impact is low. ie if you start the service then immediately send the stop signal, the entrypoint stop command may not be called.
Closes #1128 
- [na] Documentation added
- [na] Tests updated

Windows Service accept commands immediately

---

CHANGELOG.md
packaging/windows/install_script.nsis

This is a change to the installer to quote the executable paths so that they are not vulnerable to the unquoted path.
Closes #1213

Fix error with not quoting the install path for agent on windows.

---

CHANGELOG.md
docs/configuration/integrations/cadvisor-config.md
pkg/integrations/cadvisor/cadvisor.go

The `cadvisor` metrics configuration has a couple bugs:
- When configuring `disabled_metrics` or `enabled_metrics`, only the last metric value will be applied.
The [`MetricSet.Set`](https://github.com/google/cadvisor/blob/e0fab6233991e198fe53c25ee031e3d5a42c3f05/container/factory.go#L123-L136) method takes a comma-separated list of metrics and overwrites the metric set. It does not add the given metric to the set.
- Explicitly configuring `disabled_metrics` to be an empty list does not enable all metrics. Instead, the default disable metrics are still disabled.
The current implementation does not differentiate between an absent configuration and an explicit empty configuration.

Fix cadvisor metrics configuration

---

docs/configuration/integrations/mongodb_exporter-config.md

Fixes a typo where "properly" is improperly spelled as "prorperly", and the wrong grammar is used "for you metrics" in the MongoDB Exporter docs

Fix typos in Mongodb Exporter docs

---

example/k3d/smoke/main.jsonnet
production/tanka/grafana-agent/v2/README.md
production/tanka/grafana-agent/v2/internal/controllers/statefulset.libsonnet
production/tanka/grafana-agent/v2/internal/helpers/service.libsonnet
production/tanka/grafana-agent/v2/main.libsonnet

Add a helper method that allows people to create associated services
for deployment, statefulset, or daemonset Agents. This is particularly
useful for Agents that need to accept traces since they are pushed
to the agent and clients need a consistent URL.
Signed-off-by: Nick Pillitteri <nick.pillitteri@grafana.com>

Jsonnet: add withService() helper for all v2 controllers

---

CHANGELOG.md
example/docker-compose/grafana/dashboards/agent-remote-write.json
production/grafana-agent-mixin/dashboards.libsonnet

While p99 latency is an indicator of problems, overall throughput is more dependent on mean latency so add it to the panel.
Before:
After:
Or, selecting just one mean:
- NA Tests updated

Remote write dashboard: add mean latency

---

CHANGELOG.md
example/docker-compose/grafana/dashboards/agent-remote-write.json
production/grafana-agent-mixin/dashboards.libsonnet

Instead of showing the diff between in and out rates, show them both.
The total rate is key information alongside shards, latency, etc., and the differential can be inferred from looking at in and out rates, or the backlog on the top line.
Making these panels the same width as those nearby also aids readability.
Dropped samples already had a separate panel.
Before:
After:
- NA Tests updated

Remote write dashboard: show the sample rates

---

docs/getting-started/_index.md

Replace relative path with full URL to the `production/kubernetes`.
The curent link is returning a 404 [here](https://grafana.com/docs/agent/latest/getting-started/#kubernetes-manifests)

Fix kubernetes directory link

---

CHANGELOG.md
pkg/traces/automaticloggingprocessor/automaticloggingprocessor.go

Fix panic when using 'stdout' in automatic logging

Fix panic when using 'stdout' in automatic logging

---

pkg/config/integrations_test.go
pkg/integrations/v2/register.go
pkg/integrations/v2/subsystem_test.go

(No changelog entry because integrations-next isn't released yet)
(This was only a problem for v2 integrations, the v1 shims were fine)

integrations-next: fix bug where v2 integrations were not being strictly unmarshaled

---

pkg/traces/automaticloggingprocessor/automaticloggingprocessor.go
pkg/traces/automaticloggingprocessor/automaticloggingprocessor_test.go

https://github.com/grafana/agent/pull/1233 did not actually fix the issue. This is a complete fix with tests.
Reusing the same changelog entry.

Fix panic in automatic logging with stdout backend

---

pkg/util/yaml.go
pkg/util/yaml_test.go

It's common for config types to have implement yaml.Unmarshaler for:
* Applying defaults
* Applying extra logic post-unmarshal
If these config types were unmarshaled through util.UnmarshalYAMLMerged, the yaml.Unmarshaler implementation would never complete successfully, preventing the post-unmarshal logic from running.
This issue was introduced in #1192, but went unnoticed until #1228 implemented yaml.Unmarshaler to perform field migrations. #1240 reported the issue.
This commit fixes the bug by performing a second non-strict unmarshal to ensure that all input values unmarshal successfully, with the exception of unmarshal errors unrelated to unrecognized field names.
Fixes #1240
This is hacky, but it's worthwhile noting that util.UnmarshalYAMLMerged is a temporary workaround needed for …

pkg/util: support custom yaml.Unmarshaler implementations for util.UnmarshalYAMLMerged

---

example/k3d/jsonnetfile.lock.json

This PR bumps the `grafana/grafonnet-lib` to the commit which introduced the `graph_panel.interval` attribute so that the k3d environment can be applied using tanka.
This PR fixes #1245 
I'm not sure to which version we should bump the dependency to; either to just the one that introduces the 'interval' attribute to the latest, or if you have some other idea; I'd be happy to hear about it.
I'm not sure if any of the following are required

Update k3d example grafana/grafonnet-lib version

---

production/tanka/grafana-agent/config.libsonnet
production/tanka/grafana-agent/scraping-svc/main.libsonnet

Since we can't have both `prometheus:` and `metrics:` keys in our config, use the first one until it's time for its proper deprecation.
This PR fixes #1255 
We could also go the other way around, and change the `prometheus:` key in scraping-svc to `metrics:`.
However I'm not sure if there's anything else depending on scraping-svc; in any case the changes could be made to both places in a later deprecation/cleanup PR.
What do you think?

Use new `metrics:` key in example config

---

docs/configuration/integrations/node-exporter-config.md

i found a typo in the documentation
- [na] CHANGELOG updated 
- [na] Documentation added
- [na] Tests updated

corrected typo

---

.drone/drone.yml
CHANGELOG.md
docs/configuration/integrations/node-exporter-config.md
docs/configuration/integrations/process-exporter-config.md
docs/getting-started/_index.md
docs/operator/custom-resource-quickstart.md
docs/operator/getting-started.md
docs/upgrade-guide/_index.md
pkg/operator/defaults.go
production/README.md
production/grafanacloud-install.sh
production/kubernetes/agent-bare.yaml
production/kubernetes/agent-loki.yaml
production/kubernetes/agent-traces.yaml
production/kubernetes/build/lib/version.libsonnet
production/kubernetes/install-bare.sh
production/tanka/grafana-agent/v1/main.libsonnet
production/tanka/grafana-agent/v2/internal/base.libsonnet
production/tanka/grafana-agent/v2/internal/syncer.libsonnet

Prepare for v0.22.0 release by following the [release procedure](https://github.com/grafana/agent/blob/main/cmd/agent/DEVELOPERS.md#releasing)

prepare for v0.22.0 release

---

pkg/metrics/instance/instance.go

After Robert's PR in (prometheus/prometheus#9333) we can now set `scrape.UserAgent` when the `instance` package is imported. I believe this may be the only required change, but let me know if I've missed anything.
This PR closes #910. I think at least, I'm still looking into how scraping mode works and  whether we have more work to do.

Set custom User-Agent header when scraping metrics

---

cmd/agent-operator/Dockerfile.buildx

This PR attempts to fix the "Build Containers" stage of our pipeline that was broken by #1278.
In other images, we download and use a custom Go version, but in the agent-operator build we were still using the one pre-packed with seego; ergo why everything passed locally and failed remotely on Drone.
No linked issue
I pushed this to a dev branch (`grafana:dev.fix-containerize-stage-go117`) to see whether the "Containerize" step runs successfully. It seems like it does
https://drone.grafana.net/grafana/agent/1379/1/2

Use custom Go version in agent-operator Dockerfile

---

Makefile
build-image/Dockerfile

(also use a consistent base image tag instead of latest)

Update agent-build-image for go 1.17

---

CHANGELOG.md
pkg/metrics/instance/manager.go

As mentioned in the linked issue, the ListInstances() method may return nil values in `map[string]ManagedInstance`, when an instance's process has not launched yet.
For instances that aren't ready yet this can result to panics in two places
- When WALCleaner runs, trying to get an instance's storage directory
- When someone calls `/agent/api/v1/targets` to list an instance's active targets
This PR tries to amend the issue by skipping over nil values in ListInstances(); so these instances will have their WAL cleaned and will be listed on the endpoint the next time that the method is called.
This PR closes #1126.
Do y'all think we should add a test for this?

Skip non-ready entries when listing instances

---

CHANGELOG.md
docs/configuration/traces-config.md
pkg/traces/promsdprocessor/prom_sd_processor.go
pkg/traces/promsdprocessor/prom_sd_processor_test.go

Fix panic in prom_sd_processor when address is empty and configs docs
Fixes https://github.com/grafana/agent/issues/1276 and https://github.com/grafana/agent/issues/1277

Fix panic in prom_sd_processor when address is empty

---

CHANGELOG.md
pkg/operator/config/metrics_templates_test.go
pkg/operator/config/templates/component/metrics/remote_write.libsonnet

proxyUrl from MetricsInstance wasn't not being used in the generated config. 
Fixes #1297

Operator: generate proxy_url for remote_write

---

CHANGELOG.md
docs/configuration/integrations/integrations-next/_index.md
pkg/integrations/v2/common/metrics.go
pkg/integrations/v2/metricsutils/metricshandler_integration.go
pkg/integrations/v2/metricsutils/metricshandler_integration_test.go

This PR adds the ability to define a set of extra labels for integration SD and autoscrape through a common `extra_labels` config. 
This is needed for #1224, where integrations are expected to have a set of labels which represents metadata from the owning `MetricsIntegration`.
Note that this is different than configuring `relabel_configs` or `metric_relabel_configs` within autoscrape; any label specified `extra_labels` affects both autoscrape and the integrations SD API, while the relabel configs only impact autoscrape.

integrations-next: Add extra_labels to inject extra labels for an integration

---

docs/getting-started/create-config-file.md

Updated the URL for agent configuration reference.
The existing URL in this doc currently returns a 404: https://grafana.com/docs/agent/latest/getting-started/configuration/_index.md

updated config URL

---

CHANGELOG.md
pkg/integrations/node_exporter/config.go

Noticed this while working on dynamic configuration, space where one should not be

Fix typo in node_exporter

---

CHANGELOG.md
pkg/metrics/instance/marshal.go
pkg/metrics/instance/marshal_test.go

This is an attempt to re-allow inlined credentials in remote_write URLs.
The underlying issue will be dealt with by metrics V2, and while no issues have been raised by the community yet, it might be worth fixing.
This fixes #1211 
I checked that when calling /-/config, the secret there is scrubbed.
Also, I kinda abused an existing RetainSecrets test (adding credentials both inline and in a basic_auth block), but I don't believe this small change warrants 40 extra lines of test code.

Allow remote_write URL credentials

---

CHANGELOG.md
pkg/metrics/wal/series.go
pkg/metrics/wal/wal.go
pkg/metrics/wal/wal_test.go

This PR attempts to stop the Grafana Agent from sending duplicate exemplars, to avoid incurring extra I/O costs to the receiving side.
To achieve that, it adds a memExemplar struct to keep exemplars in memory. It's used to cache the latest exemplar (for series that have them) in a new field of stripeSeries, utilizing the same mechanism to distribute the lock contention.
This fixes #1282 
- I sketched out this with a couple of other approaches, either moving this one level up as a separate entry in the `Storage` struct, or in a separate `exemplars.go` file next to `series.go`. I didn't really like either of those options, I feel that this might be an acceptable solution comparing the added complexity with the benefit of keeping the code in one place
- Resources-wise, this will allocate …

Stop appending duplicate exemplars

---

CHANGELOG.md
pkg/integrations/v2/controller.go
pkg/integrations/v2/controller_metricsintegration_test.go
pkg/integrations/v2/controller_test.go
pkg/integrations/v2/workers.go

Modifies integrations-next to wait for integrations to fully exit before stopping them. This prevents two instances of the same integration (with different configs) from being run concurrently, and also ensures that integrations fully stop when shutting down the agent. 
Fixes #1317.

integrations-next: wait for integrations to exit after stopping them

---

example/k3d/README.md

This is in response to some feedback @tpaschalis had in https://github.com/grafana/agent/pull/1326 when attempting to run the smoke test locally. Since we now push crow and smoke images to an internal registry,  users who do not have access will need to build these images locally before running the smoke test.

add notes in smoke readme

---

pkg/operator/build_hierarchy.go
pkg/operator/build_hierarchy_test.go
pkg/operator/hierarchy/selector.go

The initial implementation of hierarchy.KeySelector injected a FieldSelector when listing Secrets and ConfigMaps to immediately return the single object being queried for.
This causes a problem with the client generated by the controller-runtime framework, where the client is wrapped in a cache and field indexer (where only the namespace is indexed by default).
This commit avoids using the field selector and the index lookup. The resulting behavior aligns more closely with discovering other resources in the hierarchy (i.e., ServiceMonitors), where the List call is also insufficient and needs post-processing via Matches to find the final list of resources.
Given the controller-runtime client uses an informer for reads, all relevant Secrets and ConfigMaps are already in-memory anyway, and …

operator/hierarchy: stop using field selector when listing Secrets & ConfigMaps

---

CHANGELOG.md
docs/configuration/integrations/integrations-next/app-o11y-receiver-config.md
pkg/integrations/v2/app_o11y_receiver/config/config.go
pkg/integrations/v2/app_o11y_receiver/handler/handler.go
pkg/integrations/v2/app_o11y_receiver/handler/handler_test.go

Adds api key support to app o11y receiver. `api_key` can be configured for receiver, and if it is, it is required to be provided via `x-api-key` header on the http request.
fixes #1294

[dev.frontend-receiver] Add API key support to app o11y receiver

---

go.mod
go.sum
pkg/integrations/v2/app_o11y_receiver/app_o11y_receiver.go
pkg/integrations/v2/app_o11y_receiver/exporters/loki.go
pkg/integrations/v2/app_o11y_receiver/exporters/receiver_metrics.go
pkg/integrations/v2/app_o11y_receiver/exporters/receiver_metrics_test.go
pkg/integrations/v2/app_o11y_receiver/handler/handler.go
pkg/integrations/v2/app_o11y_receiver/handler/handler_test.go
pkg/integrations/v2/app_o11y_receiver/models/measurement_test.go
pkg/integrations/v2/app_o11y_receiver/tools/ratelimiting/ratelimiter.go

Adds introspective prom metrics to app o11y receiver. These include:
* HTTP handler metrics using https://github.com/slok/go-http-metrics
* `app_o11y_receiver_export_errors`, countervec for receiver exporter errors, labeled per exporter
* `app_o11y_receiver_total_logs`, `app_o11y_receiver_total_measurements`, `app_o11y_receiver_total_exceptions`, counters for various types of events ingested
fixes #1299
Since this is a dev branch so far, should we roll all changes into a single item on the CHANGELOG until it gets merged into main? :thinking:

[dev.frontend-receiver] app o11y receiver internal metrics

---

production/tanka/grafana-agent/v2/main.libsonnet

Discovered a bug in agent jsonnet when attempting to use `withVolumesMixin`.  This fixes it and allows you to create an agent with volumes, for example:
```
gragent.new(name='grafana-agent', namespace=namespace) +
gragent.withVolumesMixin([volume.fromSecret(remote_write.secret.prefix + remote_write.name, remote_write.secret.prefix + remote_write.name)]) +
```
When doing the above with the previous code, it would recurse into `withVolumesMixin` until max stack frames are exceeded causing an error.
Didn't file an issue for this.

update withVolumesMixin for agent jsonnet

---

CHANGELOG.md
docs/configuration/integrations/integrations-next/eventhandler-config.md
pkg/integrations/v2/eventhandler/eventhandler.go
pkg/integrations/v2/eventhandler/integration.go

Can just configure this using `external_labels`, no need to add to integration config. No integration test at the moment for this, but manually tested w/ a k3d cluster and Grafana Cloud
As discussed today with @rfratto @rlankfo

Configure cluster label using logs client external_labels param

---

CHANGELOG.md
pkg/config/config_test.go
pkg/metrics/instance/configstore/api_test.go
pkg/metrics/instance/instance.go
pkg/metrics/instance/marshal_test.go

initially I was going to make this config update in our dependency on `grafana/prometheus` to a version that defaults send_exemplars to true in remote_write config. See https://github.com/grafana/prometheus/pull/26. Opting to do this in init() function in the agent instead since this isn't something that would end up going upstream.
Closes https://github.com/grafana/agent/issues/1116

default send_exemplars to true in remote_write config

---

CHANGELOG.md
docs/configuration/integrations/integrations-next/eventhandler-config.md
pkg/integrations/v2/eventhandler/eventhandler.go

To enable correlation in K8s integration dashboards, we need labels to be configured in a specific way. 
This makes the `job` label configurable and also moves most existing labels to the log line where we have more flexibility with regex matching

Update eventhandler labels

---

CHANGELOG.md
cmd/agent/entrypoint.go
pkg/integrations/v2/autoscrape/autoscrape_test.go
pkg/metrics/agent.go
pkg/metrics/agent_test.go
pkg/metrics/http_test.go
pkg/metrics/instance/instance.go
pkg/metrics/instance/manager.go
pkg/metrics/instance/manager_test.go
pkg/metrics/instance/noop.go
pkg/traces/remotewriteexporter/exporter_test.go

This is a revival of #1047 (I'd work from there, but I can't push on rfratto's fork) and an attempt to add a readiness check based on whether the metrics instances are initialized, up and running.
This fixes #1009 
I was able to see this behavior changing by adding some custom delay to the instance's Run() method and the function passed to the agent's actor channel, loadWAL or replaceWAL.
Before (main branch):
```
./agent -config.file agent-local-config.yaml &> mylog &; while gsleep 0.5s; do curl localhost:12345/-/ready; done
[1] 69466
curl: (7) Failed to connect to localhost port 12345: Connection refused
curl: (7) Failed to connect to localhost port 12345: Connection refused
Agent is Ready.
Agent is Ready.
Agent is Ready. …
```

Add readiness check to metrics component

---

docs/user/configuration/integrations/node-exporter-config.md

which should be `privileged` instead of `priviliged`
- [*] CHANGELOG updated 
- [*] Documentation added
- [*] Tests updated

[docs] fix typo of node-exporter-config  

---

example/k3d/smoke/main.jsonnet
production/tanka/grafana-agent/smoke/main.libsonnet
tools/smoke/internal/smoke.go

This uses write_relabel_configs in remote write to drop the avalanche metrics in smoke.

add fake remote_write endpoint to smoke program

---

CHANGELOG.md
production/kubernetes/agent-loki.yaml
production/kubernetes/build/templates/loki/main.jsonnet

This PR parameterizes the `namespace` field in the sample logs K8s manifests. This will allow users to install them using `envsubst` and `install-bare.sh` (and consequently also the K8s integration onboarding plugin using the same method we use for metrics). Ideally we should rename `install-bare` but since this deployment path will soon be deprecated, we can punt on this for now. 
I will update the Cloud docs K8s/Agent/Logs quickstart accordingly.
Regenerated manifests using `make example-kubernetes`

Parametrize logs DaemonSet K8s manifests

---

go.mod

Main merge 2

---

pkg/integrations/cadvisor/cadvisor.go
pkg/integrations/cadvisor/cadvisor_test.go
pkg/integrations/cadvisor/common.go
pkg/integrations/integration.go
pkg/integrations/v2/integrations.go

This adds the expected zero value for `raw_cgroup_prefix_allowlist` as the default for the cadvisor integration configuration.
Fixes #1281 
- N/A Documentation added
- N/A Tests updated

cadvisor config Fixes #1281

---

CHANGELOG.md
pkg/traces/remotewriteexporter/exporter.go
pkg/traces/remotewriteexporter/factory.go
pkg/traces/traces_test.go

Config field `const_labels` have different types in the remotewriterexporter than it has in the [main config type](https://github.com/grafana/agent/blob/main/pkg/traces/config.go#L255). This causes an error when starting the agent:
```
error reading exporters configuration for \"remote_write\": 1 error(s) decoding:\n\n* 'const_labels[0]' has invalid keys: key, some"
```
With this example config:
```yaml
server:
log_level: info
http_listen_port: 12345
traces:
configs:
- name: test
receivers:
zipkin:
endpoint: 0.0.0.0:9999
remote_write:
- endpoint: traces.local:5555
insecure: false
tls_config:
insecure_skip_verify: true
spanmetrics:
metrics_instance: test
const_labels:
some: "somevalue"
key: "value"
```
The previous implementation also had a bug in the mapstructure field, where both value …

Parse const_labels correctly in exporter

---

CHANGELOG.md
pkg/traces/remotewriteexporter/exporter.go

Because of an [upstream fix](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2837/files), the metric have duplicate `_total` suffixes and comes out as `traces_spanmetrics_calls_total_total`
I wanted to write a test for this as well, but didn't find a way of doing it, since the name is being created in the processor upstream. If you have any suggestions on a test, please let me know.

remove duplicate suffix from calls_total spanmetric

---

CHANGELOG.md
go.mod
go.sum

This fixes a race condition where the Prometheus Discovery Manager is updated at the same time as processing a new set of scrape targets.
Closes #1450

Update Prometheus dependency to 2.31.1

---

pkg/integrations/v2/controller.go
pkg/integrations/v2/controller_test.go
pkg/integrations/v2/register.go
pkg/integrations/v2/register_test.go

This PR relaxes the restrictions on how v2 integrations are unmarshaled so that any integration, regardless of type, can be unmarshaled as an JSON object or an array.
Introducing this change makes it *much* easier for the operator to generate configs for integrations, as we no longer have to switch between the _configs and non-_configs key based on the integration being generated.
With this change, configurations like these are now valid:
```yaml
integrations:
node_exporter_configs:
- {}
```
Such a configuration would not be recommended to users, but as there is only one defined instance of node_exporter, it still satisfies the singleton requirements. It is unlikely that we would document this is possible.
Instead, the following configuration would still be documented and recommended for …

integrations-next: allow all integrations to be unmarshaled as an array or object

---

docs/user/configuration/dynamic-config.md

Adding the title should fill the page name in the left menu. Currently there's a blank, clickable link in place there. 
This should also fix the rendering the *Reference* relref links in each section
I've also been super confused with how relref links work, and hopefully we get a nicer way of previewing documentation builds soon.

Add title, fix links in dynamic configuration docs

---

docs/user/getting-started/create-config-file.md

I think this should work, in the same way that this relref works [here](https://github.com/grafana/agent/blob/449db00d930fc5429fab5edd7c525c2c9cb72f16/docs/user/operator/architecture.md?plain=1#L53) on [this page](https://grafana.com/docs/agent/latest/operator/architecture/)
```
https://grafana.com/docs/agent/latest/operator/architecture/ --> https://grafana.com/docs/agent/latest/configuration/
https://grafana.com/docs/agent/latest/getting-started/create-config-file/ --> https://grafana.com/docs/agent/latest/configuration/
```
Fixes #1467

Fix link on 'Create a config file' guide

---

.github/pull_request_template.md
CHANGELOG.md

This restores the ordering we try to keep for our CHANGELOG, and adds a
note into the pull_request_template for contributors to retain that
order.
I also did some formatting and reclassified/rephrased some entries.

CHANGELOG: fix entries

---

.github/workflows/publish.yml
docs/Makefile
docs/README.md

Adds a test to confirm the website builds before syncing the docs.
Also adds a docs Makefile and updates the readme with instuctions on how to preview the docs locally from this repo.

add website test for docs sync, add docs preview/readme

---

production/kubernetes/agent-bare.yaml

Remove server.http.address flag in main to fix CrashLoopBackOff when following docs grafana-easystart-app/integrations-management/integrations/kubernetes
N / A
"Happy path" doesn't work when following agent installation on K8s (grafana-easystart-app/integrations-management/integrations/kubernetes)

Remove server.http.address flag in main k8s manifest :)

---

production/tanka/grafana-agent/smoke/main.libsonnet

b0c1e45c4ab884fd51c85687f51142ef85d2ca5d accidentally removed setting
`-log.level` in the smoke binary as part of removing the deprecated
`-log.level` field from agent code.

Partially revert b0c1e45c

---

example/k3d/smoke/main.jsonnet

Building a new crow was overriding the jsonnet default listen address, we need to merge the config overrides instead of providing a whole new set.

k3d/smoke: don't override crow args

---

CHANGELOG.md
production/grafana-agent-mixin/mixin.libsonnet

The mixin used to make the `grafanaDashboardFolder` key a part of the dashboard json, this
is not correct. This PR moves the attribute to the same level as the `grafanaDashboards`,
as such it will be consumed by the Grafana jsonnet library as a mixin.
NA

fix(mixin): grafanaDashboardFolder is a top-level attribute

---

production/grafanacloud-install.sh

Adds progress bar and removes silent flag when downloading agent deb package via curl. Sometimes the deb package can take a long time to download - Showing progress bar will provide feedback on when the agent install will complete.
Ref: https://curl.se/docs/manpage.html

Show curl progress bar agent install

---

pkg/operator/config/config.go
pkg/operator/config/config_test.go
pkg/operator/config/integration_templates_test.go
pkg/operator/config/metrics_templates_test.go
pkg/operator/config/templates/agent-integrations.libsonnet
pkg/operator/config/templates/component/metrics/external_labels.libsonnet
pkg/operator/config/templates/integrations.libsonnet

This PR adds the ability to generate an integrations-specific agent config for the operator. It is not wired in anywhere; nothing will currently generate the config.
Related to #1414 
(Supersedes the original attempt at #1314)

[dev.operator-integrations] pkg/operator/config: Generate config for integrations

---

.github/pull_request_template.md
CHANGELOG.md
docs/developer/contributing.md

Follow up on #1494. 
This PR reformats the entirety of the changelog to be (subjectively) more readable. There are now h3-level headers for change types rather than changes being tagged with `[TYPE]`. 
I've also changed the order in which we show changes to:
1. Security fixes 
2. Breaking changes 
3. Deprecations 
4. Features 
5. Enhancements
6. Bugfixes
7. Other changes 
Previously, the order was:
1. Features 
2. Enhancements 
3. Bugfixes 
4. Changes (breaking + non-breaking) 
5. Deprecations 
Security fixes has been given its own section rather than being merged in as an enhancement or bugfix. I have hopefully chosen an order which puts a focus on things we want people to read first before digging into more details.

Reformat changelog to improve readability

---

CHANGELOG.md
production/kubernetes/README.md
production/kubernetes/agent-bare.yaml
production/kubernetes/agent-loki.yaml
production/kubernetes/agent-traces.yaml
production/kubernetes/build/build.sh
production/kubernetes/build/jsonnetfile.json
production/kubernetes/build/jsonnetfile.lock.json
production/kubernetes/build/templates/bare/main.jsonnet
production/kubernetes/build/templates/loki/main.jsonnet
production/kubernetes/build/templates/traces/main.jsonnet
production/tanka/grafana-agent/v2/internal/base.libsonnet
production/tanka/grafana-agent/v2/internal/controllers/daemonset.libsonnet
production/tanka/grafana-agent/v2/internal/controllers/deployment.libsonnet
production/tanka/grafana-agent/v2/internal/helpers/k8s.libsonnet
production/tanka/grafana-agent/v2/internal/helpers/logs.libsonnet

This PR migrates the generation of K8s manifests in `production/kubernetes` to `v2` of the Tanka jsonnet library.
Summary of changes to manifests:
- (all) Change default Agent http port to `80` from misc other ports (`8080`, `12345`, etc)
- `agent-bare.yaml`
- Becomes a `StatefulSet` (prev `Deployment`)
- Add headless Service for `StatefulSet`
- `agent-loki.yaml`
- `machine-id` (journal) vol disabled by default
- `agent-traces.yaml`
- make namespace templatable
- change svc port names (no functional change)
- remove config generation from jsonnet (`TODO` in a future PR: add this to tanka/v2 jsonnet library)
Fixes https://github.com/grafana/agent/issues/451
~~Still need to test these on clusters and update docs but submitting for preliminary review~~
Tested manifests on a DOKS cluster

Migrate K8s quickstart manifests to tanka v2

---

CHANGELOG.md
cmd/agentctl/main.go

Setting a timeout for the execution of this command lower than the HTTP Transport timeout (30s) 
leads to show messages that are not very clear to users when this is exceeded as it explained in 
#1410. This PR increased the timeout for  `context.Background()` to 60s. 
Change this would  trigger first the HTTP client transport timeout first and show 
`dial tcp: i/o timeout`.
Fixes #1410

Set timeout 2x as default HTTP Transport for agentctl

---

CHANGELOG.md
production/kubernetes/agent-bare.yaml
production/kubernetes/build/templates/bare/main.jsonnet

This enables `integrations-next` by default in `agent-bare.yaml`. 
Please note: https://github.com/grafana/agent/issues/1262

Enable integrations-next by default in agent-bare.yaml

---

CHANGELOG.md
production/kubernetes/agent-traces.yaml
production/kubernetes/build/templates/traces/main.jsonnet

Move default OTLP port to `4317` in line with the default exposed by `agent` binary.
Fixes https://github.com/grafana/agent/issues/1536

Issue 1536 - OTLP Default Port

---

pkg/metrics/instance/instance.go
pkg/metrics/instance/instance_test.go

Prometheus Agent extended the API of remote.Storage to natively find the lowest sent timestamp across all queues. Now that we're embedding a new enough version of Prometheus, we can remove our old hack of collecting metrics to find the timestamp.
N/A
CHANGELOG not needed; this is a purely internal change to simplify some of our code.

metrics/instance: use native Prometheus capabilities to get rw timestamp

---

.gitignore
CHANGELOG.md
cmd/agent/Dockerfile
cmd/agent/Dockerfile.buildx
docs/user/getting-started/_index.md
pkg/metrics/agent.go
pkg/metrics/cluster/config.go

This PR contains a number of small changes:
* Remove the already-deprecated `-prometheus.*` flags in favor of their `-metrics.*` counterparts. `-prometheus.*` flags were first deprecated in v0.19.0.
* Fix an issue where some flags were prefixed with `-metrics.service..` instead of `-metrics.service.` (two dots instead of the intended one).
* Default the WAL directory for metrics to `data-agent/`, which is the same default value Prometheus Agent uses.
N/A

Update flags used for metrics

---

CHANGELOG.md
Makefile
tools/release-note.md

This PR adds builds for linux/ppc64le into Makefile. 
It builds correctly on my test system and creates all the packages. Obvious change to add a new architecture. ppc64le is in use on some of the biggest supercomputers (https://www.top500.org/lists/top500/2021/11/ - Nr. 2 and 3), on OpenPOWER (https://osuosl.org/, CERN, etc.) and on IBM Power Systems.

builds for linux/ppc64le

---

.drone/drone.yml
.github/workflows/test.yml
.github/workflows/test_packages.yml
Makefile
packaging/linux_packages_test.go

It was previously impossible to abort a `make` target which ran a docker container. Ensuring that the `--init -it` flags are passed to docker run guarantee that the user can always Ctrl+C to cancel the target and the container.
This commit also adds the `--rm` flag to commands that were missing it.

Makefile: ensure that Docker containers can be canceled by the user

---

example/k3d/README.md

Following the steps of how to run smoke tests led to have pods crash looping because
images where not found. This PR clarifies the extra step where the images need to
be imported in order to run the smoke test.

Improve documentation on how to run Smoke Tests

---

Makefile

$IMAGE_BRANCH_TAG must not be an empty string for building images. This defaults $IMAGE_BRANCH_TAG for release candidates to be the same as $RELEASE_TAG.
This will redundantly cause the image to be tagged twice as $RELEASE_TAG, but will avoid build errors.

Makefile: support release candidate versions

---

.drone/drone.yml
.github/workflows/test.yml
.github/workflows/test_packages.yml
CHANGELOG.md
cmd/agent-operator/Dockerfile
cmd/agent-operator/Dockerfile.buildx
cmd/agent/Dockerfile
cmd/agent/Dockerfile.buildx
cmd/agentctl/Dockerfile
cmd/agentctl/Dockerfile.buildx
docs/developer/contributing.md
go.mod
go.sum
tools/crow/Dockerfile
tools/crow/Dockerfile.buildx
tools/seego/Dockerfile
tools/smoke/Dockerfile
tools/smoke/Dockerfile.buildx

Makes the following minor changes throughout the repo:
* Update base image for Docker containers to Bullseye 
* Update Go version to 1.18.0
* Remove unnecessary Dist job during release, since `make dist` is re-ran as a part of `make publish`. 
* Remove unnecessary build stage when testing Windows/macOS; `make test` should already cover building the binaries, and doing the builds add 5-6 minutes to the total CI time
Closes #1576
rfratto/seego has also been updated to use bullseye.

Update base image and go

---

cmd/agentctl/main.go

This updates the import order to move our version info import so version info doesn't get overridden by loki build package.
Fixes failures we were seeing in homebrew/homebrew-core workflow when upgrading agent formula to v0.24.0:
https://github.com/Homebrew/homebrew-core/pull/98774

udpate import order in agentctl main.go

---

example/k3d/scripts/smoke-test.bash

Add seconds as unit of time measure when script mentions TEST_DURATION  in smoke test script.

Improve debug messages on smoke test script

---

CHANGELOG.md
cmd/agent/entrypoint.go
docs/user/api/_index.md
go.mod
go.sum
pkg/logs/http.go
pkg/logs/http_test.go
pkg/logs/logs.go

Add HTTP endpoints to fetch active instances and targets for the Logs subsytem.
-  `GET /agent/api/v1/logs/instances`
-  `GET /agent/api/v1/logs/targets`
Related to https://github.com/grafana/agent/issues/1404

Add Logs system API endpoints for instance and targets

---

CHANGELOG.md
go.mod

This bumps the version of github-exporter to the latest upstream commit, fixing numerous bugs since the latest development release.
Closes #1588.
Additionally, a retroactive changelog entry for #1584 is added.

Bump GitHub exporter version

---

CHANGELOG.md
pkg/logs/logs.go

This PR embeds time zone data with for the logs package.
Fixes #1571
Before merging, I'd like to verify that this actually fixes the issue on Windows machines. I tried to check the before/after behavior with our Windows Github Action runners here https://github.com/tpaschalis/agent/pull/29/commits/6427836d95e3b4addef8e19a54e35242c6a6f978, but it passes even with the current main branch.
I'm not sure if the %ZONEINFO% variable is correctly set or if it's somethig else?
Also, this change inflates our binary data by about 400KB.

Embed time zone data for logs package

---

.github/dependabot.yml

Usage of a temporary fork for go.opentelemetry.io/collector requires special handling of OpenTelemetry-related modules. Instead of having dependabot try to auto-update them, we should investigate them on a case-by-case basis.
Closes #1512

dependabot: ignore opentelemetry-related dependencies

---

CHANGELOG.md
pkg/operator/config/config_test.go
pkg/operator/config/metrics_templates_test.go
pkg/operator/config/templates/component/metrics/remote_write.libsonnet

PR #1441 introduced a change to use password_file for basic auth, but
accidentally also generated a username_file field which doesn't exist.
This is a partial revert of #1441, keeping only the password_file change.
Fixes #1601

pkg/operator/config: don't set non-existent username_file field

---

CHANGELOG.md
pkg/config/config.go
pkg/server/config.go
pkg/server/logger_test.go

This PR re-introduces the correct default log level and log format, after being removed in https://github.com/grafana/agent/commit/b0c1e45c4ab884fd51c85687f51142ef85d2ca5d.
They used to have their default values implicitly set when registering the `-log.level` and `-log.format` flags, but it fell through when changing from weaveworks/common/server with agent/pkg/server.
There are a couple of places and ways to go about it, reintroducing them in main.go, in the server.Config.RegisterFlags method, or the server.Config.UnmarshalYAML method.
I prefer the option presented here, allowing the correct default values to be set, whether the `server:` top-level block exists in the YAML or not.
Fixes #1586 
Is there any test we should …

Set up the default logger parameters

---

CHANGELOG.md
docs/user/configuration/flags.md
pkg/config/config.go
pkg/metrics/instance/global.go
pkg/metrics/instance/instance.go

This adds a feature flag for enabling [extra scrape metrics](https://prometheus.io/docs/prometheus/2.31/feature_flags/#extra-scrape-metrics). 
Closes https://github.com/grafana/agent/issues/1073
This is still experimental in prometheus so I've included the feature flag (instead of defaulting this to true). The latest version of prometheus includes additional scrape metrics which aren't included yet in the agent. See https://prometheus.io/docs/prometheus/latest/feature_flags/

enable extra scrape metrics

---

CHANGELOG.md
docs/user/configuration/integrations/integrations-next/eventhandler-config.md
pkg/integrations/v2/eventhandler/eventhandler.go
pkg/integrations/v2/eventhandler/integration.go

Add extra identifying labels to `eventhandler` config
Closes #1549 
`job: integrations/kubernetes/eventhandler` will be changed to `job: integrations/eventhandler` when we do the next K8s integration release

Add extra eventhandler labels

---

go.mod
go.sum

This version includes key metrics to be used in MacOS integration: https://github.com/prometheus/node_exporter/commit/4f27a4fd8efacdf4f738cf3608dbaee972bbf548
Is this something we can do?
cc @tpaschalis @rlankfo

Bump node_exporter version to include macos memory metrics

---

pkg/cluster/gossip_test.go

`gossip_test.go` fails on Ubuntu 20.04. It seems it checks for hardcoded network interfaces `eth0` or `en0`, but Ubuntu and most likely other distros use [predictable network interface names](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/), so ethernet can look like `enp4s0f1`. 
This PR fixes it  by getting interface list via `net.Interfaces()`. Not 100% this is appropriate, but it does make the test pass :) I opened an [issue on the upstream ckit repo as well
](https://github.com/rfratto/ckit/issues)

Make gossip test work on Ubuntu

---

.github/workflows/markdown.links.config.json

CI fails because [links do github docs can't be accessed by markdown links checker](https://github.com/github/docs/issues/17358). Let's temporarily ignore them to keep things moving?

[ci] do not check github docs links

---

pkg/integrations/node_exporter/config.go

To exclude 'useless' map autohome datapoints on Mac:
```
agent % df -h
Filesystem       Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk3s1s1  926Gi   19Gi  642Gi     3%  553785 9712948015    0%   /
devfs           204Ki  204Ki    0Bi   100%     706          0  100%   /dev
/dev/disk3s6    926Gi   20Ki  642Gi     1%       0 9713501800    0%   /System/Volumes/VM
/dev/disk3s2    926Gi  418Mi  642Gi     1%    1172 9713500628    0%   /System/Volumes/Preboot
/dev/disk3s4    926Gi  590Mi  642Gi     1%     207 9713501593    0%   /System/Volumes/Update
/dev/disk1s2    500Mi  6.0Mi  481Mi     2%       4    5119996    0%   /System/Volumes/xarts
/dev/disk1s1    500Mi  7.2Mi  481Mi     2%      23    5119977    0%   /System/Volumes/iSCPreboot
/dev/disk1s3    500Mi  608Ki  481Mi …
```

Add 'autofs' to darwin FilesystemFSTypesExclude

---

docs/developer/contributing.md
docs/user/configuration/integrations/integrations-next/ebpf-config.md
pkg/integrations/v2/ebpf/integration.go
pkg/integrations/v2/ebpf/integration_stub.go

This PR constraints the eBPF integration to be only built on AMD64 systems, since cross-compilation fails on other architectures
No filed issues.
If we think the current solution (limiting access to users running on a certain architecture) is acceptable, we can go ahead with it. It's not a defacto limitation of eBPF as a technology, but a limitation of our current dependencies.
If we would like to amend this, we can go ahead with the other PR which reverts the entire integration and revisit it once upstream packaging for the bcc toolchain is improved.

Add amd64-specific build tag for eBPF integration

---

cmd/agentctl/Dockerfile
cmd/agentctl/Dockerfile.buildx

We've recently introduced an eBPF integration. In the process, we should have also updated the agentctl build image to include the necessary libraries, as it imports the new `ebpf` package.
No issue filed
Hopefully, this is the last change required... The "Containerize" step in Drone, runs the following commands
https://github.com/grafana/agent/blob/9f03dcf4f001ae2c7cd178b5ddc997428db92a14/.drone/drone.yml#L108-L113
Only `agent` and `agentctl` happen to import the integration package, thus requiring these extra libraries.

Add ebpf bindings to agentctl build image

---

docs/user/configuration/traces-config.md

Add `receiver_port` config option for load balancing to the docs, which was missing.

Add receiver_port config option in load_balancing

---

CHANGELOG.md
go.mod
go.sum
pkg/metrics/instance/configstore/api_test.go
pkg/metrics/instance/host_filter_test.go
pkg/metrics/instance/marshal_test.go

Update **prometheus/common** `v0.32.1`-> `v0.33.0`, enabling:
- `proxy_url` on `oauth2` (metrics and logs) [prom docs](https://prometheus.io/docs/prometheus/2.27/configuration/configuration/#oauth2)
- `prometheus/common` adds `http2_enabled` as default = true (tests aligned)
Fixes #1702 
N/A
- ~[ ] Documentation added~ [Prometheus docs](https://prometheus.io/docs/prometheus/2.27/configuration/configuration/#oauth2) needs to get updated, but is not yet

Allow proxy_url on oauth2 for metrics and logs

---

CHANGELOG.md
pkg/integrations/v2/controller.go

Prefix Path did not have a closing `/` so if an instance name was a prefix of another then the smaller one always took precedence. 
Closes #1718 

Instance Name Prefixing Issue

---

cmd/agentflow/README.md
cmd/agentflow/example-config.flow
cmd/agentflow/main.go

This commit introduces cmd/agentflow as a separate binary which allows for developers to test components end-to-end and merge them into the main branch without having to add flow support into cmd/agent itself.
After Flow is ready for wider use, cmd/agentflow will be replaced with native cmd/agent support.

cmd/agentflow: introduce temporary agentflow main package for prototyping

---

cmd/agentflow/README.md
cmd/agentflow/main.go
pkg/flow/flow_http.go
pkg/flow/internal/dag/marshal.go
pkg/flow/internal/dag/marshal_test.go
pkg/flow/internal/graphviz/graphviz.go
pkg/flow/internal/graphviz/grpahviz_test.go

Adds a /debug/graph endpoint to render the currently loaded dependency graph (with transitive reduction applied).

agentflow: add /debug/graph endpoint to render current dependency DAG

---

cmd/agentflow/README.md
cmd/agentflow/main.go
component/component.go
component/component_health.go
pkg/flow/flow_http.go
pkg/flow/flow_http_test.go
pkg/flow/internal/controller/component.go
pkg/flow/internal/controller/component_write.go
pkg/flow/internal/controller/component_write_test.go
pkg/flow/internal/controller/loader.go
pkg/flow/internal/testcomponents/passthrough.go

The `/-/config` endpoint renders the current state of all components, with expressions evaluated, back as HCL to the user. 
`/-/config?debug=1` may be invoked to add health information per-component along with component-specific debug information if a component implements the `component.DebugComponent` interface.

Flow: add /-/config endpoint

---

pkg/flow/hcltypes/optional_secret.go
pkg/flow/hcltypes/optional_secret_test.go
pkg/flow/hcltypes/secret.go
pkg/flow/hcltypes/secret_test.go

Closes #1688.
Secret
------
hcltypes.Secret allows components to declare a value as sensitive.
Secret types are never shown to the user at the /-/config endpoint,
appearing as `(secret)`.
Both strings and OptionalSecrets may be converted into a Secret.
Secrets may be converted back to OptionalSecrets, but may never be
converted back into a string.
OptionalSecret
--------------
hcltypes.OptionalSecret allows components to configure whether a string
value is sensitive. This is useful for components like local.file where
some files contain sensitive information and others don't.
Both strings and Secrets may be convertd into an OptionalSecret.
OptionalSecrets may be converted into Secrets. OptionalSecrets may only
be converted back into a string if their underlying value is not marked
as …

flow/hcltypes: add a Secret and OptionalSecret type

---

pkg/flow/flow.go
pkg/flow/internal/controller/component.go
pkg/flow/internal/controller/loader.go

- Don't pass unchanged arguments to components to avoid unnecessary expensive component updates.
- Ignore unchanged exports from components to avoid unnecessary re-evaluations.
- When dequeuing a changed component, only re-evaluate its dependencies. There's no point in re-evaluating the changed component since none of its arguments would need reprocessing.

flow: remove unnecessary component evaluations

---

docs/user/configuration/integrations/integrations-next/_index.md

We currently don't mention how users should add relabelling steps when running integrations-next.
These two keys are not available in the `autoscrape.Global` struct, but have to be configured per-integration in `autoscrape.Config`.
Closes #1731

Document relabelling in integrations-next

---

CHANGELOG.md
cmd/agentctl/main.go
pkg/client/grafanacloud/client.go
pkg/client/grafanacloud/client_test.go
production/grafanacloud-install.sh

This PR adds a `--platforms` flag to the `agentctl cloud-config` command. 
Last quarter, we enhanced our cloud API to receive filters based on platforms and include/exclude options. This enabled us to have both Linux and macOS integrations based on `node_exporter` and avoiding errors about duplicate keys; the Grafana Cloud API would be smart enough to request platform-specific configuration bring only one of the two keys.
Currently, when new users go through onboarding, they're using the `grafanacloud-install.sh` script to retrieve their Cloud configuration locally. If they have both the Linux and macOS integrations, calling the cloud-config command will return a 500 error with a message along the lines of 
```msg="could not …
```

Add --platforms flag to agentctl cloud-config command

---

pkg/integrations/v2/app_agent_receiver/config.go
pkg/integrations/v2/app_agent_receiver/config_test.go

Unmarshalling app agent receiver config multiple times might fail because it's default config was not properly copied each time, with `LogsLabels` map only being copied by reference and ending up with items from previous instance.
This PR fixes the problem by instantiating new `LogsLabels` map every time.

bug: fix bunmarshalling app agent receiver config multiple times

---

CHANGELOG.md
pkg/config/config.go
pkg/config/config_test.go

With the change to server flags, the GRPC flags were not being propagated correctly to the life cycle listener.

Scraping Service needs to honor the new server flags.

---

.drone/drone.yml

Fixes build failure due to `go get` deprecation in go1.18:
See https://drone.grafana.net/grafana/agent/2728 for example.

update go get to go install

---

component/local/file/file.go
component/local/file/file_test.go
docs/flow/components/local.file.md
docs/flow/secrets.md
pkg/flow/hcltypes/optional_secret.go
pkg/flow/hcltypes/optional_secret_test.go
pkg/flow/hcltypes/secret.go

This PR creates documentation for the newly introduced `local.file` component (#1746). 
I've temporarily placed this in `docs/flow` while Grafana Agent Flow is still being worked on. This should eventually be moved to the `docs/sources` once the MVP is ready for shipping to users.
Note that there is much more to document regarding Grafana Agent Flow, and this is just serves as an example for how reference-level documentation for components should be written. Higher level documentation explaining how to use Flow and common use cases should be done in a later PR.

docs/flow: Document local.file and secrets

---

CHANGELOG.md
pkg/operator/config/config_test.go
pkg/operator/config/utils.go

`gopkg.in/yaml.v3` doesn't handle converting numeric json types properly.
Fixes #1788

switch to sig.k8s.io/yaml package for unmarshalYAML in operator

---

CHANGELOG.md
pkg/traces/config.go
pkg/traces/config_test.go

Set include_metadata to true by default for OTLP traces receivers.
Adding this metadata to requests is extremely useful for the PromSD processor, which relies on getting the IP of the batch sender in order to attach attributes to traces. One of the methods it uses for getting the IP is inspecting the context received, with the hope that it contains metadata from the connection from where the batch came from. This is rarely the case since it's disabled by default.
Fixes https://github.com/grafana/agent/issues/1721

Set include_metadata to true by default for OTLP traces receivers

---

pkg/metrics/wal/wal.go
pkg/metrics/wal/wal_test.go

This allows overriding the reference id with a global reference id provider. By default `NewStorage` works are before, but if calling `NewStorageWithRefidSource` you can pass in a custom provider. A global provider is available. This will allow us to move forward with flow
- [NA] CHANGELOG updated

Global refid usage in wal

---

pkg/operator/resources_metrics.go

(fixes #1817)
The name passed to `generatePodTemplate` is only used for the config secret to mount.
Since there is no sharded config generated, just use the original agent name (without `shard-n` snuck in.)

operator: Generate pod template from non-sharded agent name.

---

CHANGELOG.md
go.mod
go.sum

Promtail has had a longstanding issue with relative symlinks (see
grafana/loki/#1240 , grafana/loki/#4905 , and grafana/tail/#11 ). This was fixed
in grafana/tail/#12 but was never pulled into agent. In this commit we update
grafana/tail to pull in this fix.
grafana/loki#1240 and grafana/loki/#4905
This commit was created by updating the commit hash for tail and then running
`go mod tidy`.

update promtail to fix relative symlinks

---

README.md
docs/sources/cookbook/dynamic-configuration/01_Basics/01_Structure.md
docs/sources/cookbook/dynamic-configuration/01_Basics/02_Instances.md
docs/sources/cookbook/dynamic-configuration/01_Basics/03_Integrations.md
docs/sources/cookbook/dynamic-configuration/01_Basics/04_Logs_and_Traces.md
docs/sources/cookbook/dynamic-configuration/02_Templates/01_Looping.md
docs/sources/cookbook/dynamic-configuration/02_Templates/02_Datasources.md
docs/sources/cookbook/dynamic-configuration/02_Templates/03_Datasource_and_Objects.md

The latest change (renaming the technical documentation directory), broke two things: our logo on the repo root README and the Github links to snippets in the dynamic configuration cookbook.
This PR amends the paths in those two cases. I've also grepped to see if there's any other "docs/user" or "../user" paths remaining, but there wasn't anything.
No issue files
None.

Fix links referencing old documentation path

---

CHANGELOG.md
cmd/agent/entrypoint.go
docs/sources/configuration/integrations/integrations-next/snmp-config.md
docs/sources/configuration/integrations/snmp-config.md
docs/sources/cookbook/dynamic-configuration/01_Basics/01_assets/final.yml
docs/sources/cookbook/dynamic-configuration/01_Basics/02_assets/final.yml
docs/sources/cookbook/dynamic-configuration/01_Basics/03_assets/final.yml
docs/sources/cookbook/dynamic-configuration/01_Basics/04_assets/final.yml
docs/sources/cookbook/dynamic-configuration/02_Templates/01_assets/final.yml
docs/sources/cookbook/dynamic-configuration/02_Templates/02_assets/final.yml
docs/sources/cookbook/dynamic-configuration/02_Templates/03_assets/final.yml
docs/sources/cookbook/dynamic-configuration/03_Advanced_Datasources/01_assets/final.yml
docs/sources/upgrade-guide/_index.md
pkg/config/config.go
pkg/config/config_test.go
pkg/config/dynamicloader_configs_test.go
pkg/config/integrations.go
pkg/integrations/manager.go
pkg/server/config.go
pkg/server/flags.go
pkg/server/server.go
pkg/server/server_test.go
pkg/server/testdata/windows/agent-config.yml
tools/crow/main.go

Many `server` YAML fields were deprecated in v0.24.0 and scheduled for removal in v0.26.0. This commit removes those fields in favor of just using the flags.
This also removes the logic for determining listen address by examining both the configured listen address and listen host/port combination, as the latter was only available in the flags. This simplifies the fix introduced by #1762, which can reliably look up the port used for the
gRPC server.

remove deprecated server YAML fields in favor of static flags

---

.drone/drone.yml
.github/workflows/test.yml
Makefile

Remove the Github Actions Windows Test and use Drone as the default. The Github Action has increasingly been harder to successfully succeed due to issues outside the test. Utilizing the grafana drone system we have much more control over the machines running. In testing the windows tests have been reduced by half in time.

Switch from Github Windows to Drone Testing

---

CHANGELOG.md
pkg/integrations/v2/app_agent_receiver/handler.go
pkg/integrations/v2/app_agent_receiver/handler_test.go

App agent receiver rate limiting feature is not working due to some mistaken assumptions. It was using `Reserve()` method which is not intended for our use case of skipping events. This PR switches to using the `Allow()` method.

Bug: fix rate limiting for app agent receiver intgeration

---

docs/sources/configuration/metrics-config.md
docs/sources/configuration/traces-config.md

Update docs with 2.34 prometheus version, 2.27 links were broken.

Fix documentation for specific version

---

CHANGELOG.md
pkg/integrations/mongodb_exporter/mongodb_exporter.go

When we updated MongoDB it also changed the behavior to requiring which metrics to collect. Added the collect all = true fixes that. Compared the metrics from a previous version and this version, this version has all the previous metrics and adds roughly 100 more, so collect all seems reasonable.
Closes #1834

Update MongoDB to use the collect all flag

---

pkg/river/ast/ast.go
pkg/river/parser/internal.go
pkg/river/printer/printer.go
pkg/river/printer/printer_test.go
pkg/river/printer/testdata/.gitattributes
pkg/river/printer/testdata/block_comments.expect
pkg/river/printer/testdata/block_comments.in
pkg/river/printer/testdata/example.expect
pkg/river/printer/testdata/example.in
pkg/river/printer/trimmer.go
pkg/river/printer/walker.go
pkg/river/token/file.go

river/printer is a pretty-printer of River AST nodes, which will be used for error message formatting when a specific AST node should be displayed to the user.
Much of the implementation river/printer is inspired by go/printer, and so the way it formats files is very similar. For example, this input:
```
secure = true // Enable secure mode
access_log = "/tmp/access_log.txt" // Enable access log
```
is transformed to be aligned with [elastic tabstops](https://nickgravgaard.com/elastic-tabstops/):
```
secure     = true                  // Enable secure mode
access_log = "/tmp/access_log.txt" // Enable access log
```
The formatting rules applied by river/printer are purposefully not formally specified to allow them to change over time as formatting recommendations are established. …

river: add river/printer package

---

.drone/drone.yml
Makefile
packaging/rpm/gpg-sign.sh

Sign the RPM packages in releases with the Grafana key (packages.grafana.com/gpg.key)
We're building a central package repository and all (RPM) packages need to be signed with that key

RPM: GPG signing

---

.github/workflows/bump-formula-pr.yml

The previous pattern matched -rc.* tags, but an accidental push to -rc0 can cause unwanted PRs (grafana/homebrew-grafana#34, Homebrew/homebrew-core#105564).

CI: prevent all -rc* tags from opening formula PRs

---

docs/sources/configuration/server-config.md

The documentation has these two fields prefixed by `client_`, while in the actual code they aren't.
https://github.com/grafana/agent/blob/2366945e5ea88bffdef4d1949b0353ce82d03374/pkg/server/tls.go#L42-L43
Leaving the error here for future grepping :)
```
2022-07-12 13:24:45.760650 I | error loading config file agent-local-config.yaml: yaml: unmarshal errors:
line 11: field client_subject_regex not found in type server.WindowsClientFilter
line 12: field client_template_id not found in type server.WindowsClientFilter
```
Nothing in particular.

Fix docs for Windows certificate store

---

.drone/drone.yml

Additionally, this removes Lint as a dependency to running the Test jobs so they can run in parallel without having to wait for the Lint to finish.
If Lint fails, the pipeline will still be marked as a failure.

Drone: use grafana/agent-build-image:0.14.0-windows

---

pkg/river/internal/value/errors.go
pkg/river/internal/value/value.go
pkg/river/internal/value/value_test.go

Adds a `Value.Call` method which can invoke function values. 
This supports variadic functions; passing all Values as arguments to the function. See the tests for examples of calling functions in various configurations.
Additionally, if the function call has a `(T, error)` return type, and the error is non-nil, the error will be returned as the error for the Call method.

river/internal/value: support calling function values

---

pkg/river/parser/internal.go
pkg/river/parser/testdata/block_names.rvr

This PR updates the river parser with a new helper to validate that block labels are valid identifiers (eg. don't contain spaces).
Fixes #1893

river/parser: Enforce block labels to be valid identifiers

---

.github/workflows/stale.yml

actions/stale just released v5.1.0 which includes the ability to set a close reason for stale issues. Setting it to [`not_planned`][not_planned] will mark issues as [not-planned][] and can be filtered for when searching through issues.
I don't think we need to update the `uses:` field of the action, and it'll use the latest v5.Y.Z release.
Note that even though GitHub's blog announcement post says `not-planned` with a hyphen, the action expects to see `not_planned` with an underscore.
[not_planned]: https://github.com/actions/stale#close-issue-reason
[not-planned]: https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/

actions/stale: set close-issue-reason to not_planned

---

CHANGELOG.md
pkg/operator/config/templates/component/metrics/service_monitor.libsonnet

The label name used here was wrong; it should match what Prometheus operator uses: https://github.com/prometheus-operator/prometheus-operator/blob/e0f7fea10258dcf5db63aee64a892420ac90009a/pkg/prometheus/promcfg.go#L840-L856

operator/config: fix label used when targetPort is set in ServiceMonitor

---

CHANGELOG.md
Makefile
packaging/linux_packages_test.go

This PR utilizes Makefile's [target-specific variables](https://www.gnu.org/software/make/manual/html_node/Target_002dspecific.html) to override `CGO_FLAGS` when building linux/amd64 binaries and packages for distributions.
This change will
Fixes #1923.
This does make the Makefile a tad more complicated, plus if we ever change CGO_FLAGS we'll also need to remember to change it here, but I believe this is one of the less intrusive solutions to this problem.
Please let me know if I've missed any corner cases here :)

Use opt-out flag for ebpf_exporter when building release artifacts

---

pkg/river/internal/rivertags/rivertags.go
pkg/river/internal/rivertags/rivertags_test.go
pkg/river/internal/value/decode.go
pkg/river/internal/value/tag_cache.go
pkg/river/internal/value/type.go
pkg/river/internal/value/type_test.go
pkg/river/internal/value/value.go
pkg/river/internal/value/value_object.go
pkg/river/internal/value/value_object_test.go
pkg/river/token/builder/builder.go

This PR fixes how blocks are represented from objects and lists with the following rules:
1. A block name `a.b.c` is represented as a deeply nested object, where `a` is the top level key, `b` is a key inside `a`, and `c` is a key inside `b`. The block itself is then inside of `c`. 
2. A labeled block is represented as a key following the block name, where the key name is the label value. The block itself is then inside the label key. 
3. An array or slice of labeled blocks is rolled up into a single object, with each label being a key. 
1. This implicitly requires that labels are unique per block name. 
2. Like normal, an array or slice of _unlabeled_ blocks is still an array. 
For example, this file:
```river
discovery.kubernetes "pods" {} 
discovery.kubernetes "namespaces" {} …
```

river/internal/value: fix block representation in objects and lists

---

pkg/river/internal/value/capsule.go
pkg/river/internal/value/decode.go
pkg/river/internal/value/decode_test.go
pkg/river/internal/value/type.go
pkg/river/internal/value/type_test.go
pkg/river/internal/value/value.go
pkg/river/internal/value/value_object_test.go
pkg/river/token/builder/builder.go
pkg/river/token/builder/builder_test.go
pkg/river/token/builder/value_tokens.go

This PR introduces three small additions required for a River equivalent of our [hcltypes][] package:
1. Define a Capsule interface which explicitly marks a Go type as being a capsule. This is needed for Go types which should be capsules but whose underlying types are non-capsules by default. For example: 
```go
type Secret string
// RiverCapsule ensures that Secret values are treated as a capsule.
func (s Secret) RiverCapsule() {}
``` 
2. Define a ConvertibleFromCapsule and ConvertibleIntoCapsule extension interfaces to allow converting capsule values from and to other Go values respectively. For a Secret type, this will be used to allow converting a string into a Secret, but not a Secret into a string. Two interface types are defined to allow ConvertibleFromCapsule to be implemented on …

River: capsule markers, capsule conversion, and custom tokenization 

---

pkg/river/internal/value/decode.go
pkg/river/internal/value/decode_test.go
pkg/river/internal/value/value.go
pkg/river/token/builder/builder_test.go
pkg/river/token/builder/value_tokens.go

This PR makes two small changes:
1. Fixes a bug where it wasn't possible to perform custom conversions between two capsule types.
2. Implements custom logic for encoding and decoding time.Duration as strings.

river: fix custom capsule conversions & support time.Duration

---

go.mod
go.sum
pkg/river/ast/ast.go
pkg/river/ast/walk.go
pkg/river/diag/diag.go
pkg/river/diag/printer.go
pkg/river/diag/printer_test.go
pkg/river/internal/value/decode.go
pkg/river/internal/value/decode_test.go
pkg/river/internal/value/type.go
pkg/river/internal/value/value.go
pkg/river/internal/value/value_test.go
pkg/river/parser/error_test.go
pkg/river/parser/internal.go
pkg/river/parser/parser.go
pkg/river/parser/parser_test.go
pkg/river/printer/printer.go
pkg/river/printer/walker.go
pkg/river/token/builder/builder.go
pkg/river/token/builder/builder_test.go
pkg/river/token/builder/token.go
pkg/river/token/builder/value_tokens.go

This PR fixes 7 small issues I found while testing River for Flow, and adds one new feature (river/diag). 
The small changes / bug fixes are as follows: 
* river/internal/value: Add support for an Unmarshaler interface so types can hook custom logic into decoding (e.g., like for applying default values) 
* river/ast: Create an ast.Walk function to allow for walking the AST. This also changes separates IdentExpr into an Ident so AST visitors can guarantee when an IdentExpr is part of an expression. This will be used for determining what references a Flow component is making to other Flow components. 
* river/token/builder: Support writing out comments. 
* river/token/builder: Allow encoding bodies from Go values. This was a missing piece of functionality needed to implement the /-/config …

River: various small fixes

---

component/common/appendable/appendable.go
component/metrics/mutate/mutate.go
component/metrics/scrape/scrape.go
component/metrics/scrape/scrape_test.go
component/metrics/scrape/types.go

This behavior appeared when we changed the `type struct { receivers []*metrics.Receiver }` definition to the `type FlowAppendable []*metrics.Receiver` type alias in 7be5f6c04c3d8b814c1c74de40d46bb7ce7c1f37.
This PR fixes the panic which occurs when the `metrics.scrape` component tries to forward to a nil receiver by reverting to the previous behavior
Fixes #1945

Fix metrics.scrape panic with nil receiver

---

component/metrics/scrape/types.go
docs/flow/components/metrics.scrape.md

All sensitive attributes should use the rivertypes.Secret type and not raw strings.

metrics.scrape: use rivertypes.Secret for sensitive attributes

---

pkg/river/internal/value/value.go
pkg/river/token/builder/builder_test.go
pkg/river/token/builder/value_tokens.go

This change consistently prints object keys which come from unordered objects (i.e., a map[string]V). All other types of River objects have ordered keys, and can be printed in normal order.

river/token/builder: print keys in sorted order for unordered objects

---

cmd/agent/flow.go
cmd/agent/main.go

This makes /-/config now aligned with the existing /debug/graph and /debug/pprof endpoints.
This commit also unexports functions that didn't need to be exported, so their required godoc comments can be removed.

Flow: change /-/config to /debug/config

---

component/metrics/scrape/types.go

The upstream model.Duration type is an alias for time.Duration. 
By using that alias from the decoding level, the `/debug/config` endpoint will report these values as numbers.
```
scrape_interval  = 60000000000
scrape_timeout   = 10000000000
```
To make use of the fix on https://github.com/grafana/agent/commit/1fda90adc917c8d107e2e2a0207611adc43222b4 where we added support for time.Duration marshalling as a readable string in River, we have to defer this conversion to a later point in time.
With this change, the durations are reported as expected.
```
scrape_interval  = "1m0s"
scrape_timeout   = "10s"
```
No issue filed

flow: Use time.Duration for metrics.scrape config block

---

pkg/river/printer/testdata/object_align.expect
pkg/river/printer/testdata/object_align.in
pkg/river/printer/walker.go

Align object literal field names similar to attributes in blocks so that 
```river
{
short_key = "value",
longer_key = "value",
}
```
becomes 
```river 
{
short_key  = "value",
longer_key = "value",
} 
```
Similarly to attributes in blocks, alignment with the previous field only applies if the previous field spanned a single line. These two field names will never be aligned:
```river 
{
array_across_multiple_lines = [
0,
1,
2,
],
other_key = "value",
} 
```

river/printer: align object literal values

---

pkg/river/parser/internal.go
pkg/river/parser/testdata/assign_block_to_attr.river

This changes error reporting from the parser to cover three new cases:
1. Parse errors which occur on the same line as the previously reported parse error are now ignored.
2. If a TERMINATOR (newline) is not found at the end of a statement, tokens are consumed until a qualifying TERMINATOR is found. Qualifying TERMINATORs are TERMINATORS which end all accumulated pairs of curly brances, square brackets, and parenthesis encountered while consuming tokens.
3. If a user is trying to assign a block to an attribute (e.g., using it as an expression), a specific error is returned to them to let them know that is not acceptable by the parser.
Fixes #1964

river/parser: improve error reporting

---

cmd/agent/flow.go
pkg/flow/flow_http.go
pkg/flow/internal/controller/loader.go
pkg/flow/internal/controller/value_cache.go

/debug/scope prints the variables varaible to be referenced by other
components.
For cmd/agent/example-config.river, the following is printed:
```river
{
local = {
file = {
this_file = {
content = "Change me!",
},
},
},
metrics = {
remote_write = {
default = {
receiver = capsule("metrics.Receiver"),
},
},
scrape = {
default = {},
},
},
}
```
This is useful for debugging errors where the scope isn't updated with expected values, something @captncraig and I ran into while testing #1941.

Flow: Add /debug/scope endpoint

---

cmd/agent/example-config.river
tools/riverfmt/main.go

This is an initial commit for a basic formatting tool for River files. 
* Supports formatting stdin: `cat file.river | riverfmt` 
* Supports rewriting files: `riverfmt -w file.river` 
* Supports printing diff to stdout: `riverfmt file.river`

tools/riverfmt: introduce riverfmt for formatting files

---

pkg/river/vm/vm.go
pkg/river/vm/vm_test.go

This changes errors such as
```
Error: ./cmd/agent/example-config.river:16:21: local.file.this_file does not have field named "kontent"
15 |         "__address__"   = "demo.robustperception.io:9090",
16 |         "dynamic_label" = local.file.this_file.kontent,
|                           ^^^^^^^^^^^^^^^^^^^^
17 |     }]
```
into the more expected form
```
Error: ./cmd/agent/example-config.river:16:42: field "kontent" does not exist
15 |         "__address__"   = "demo.robustperception.io:9090",
16 |         "dynamic_label" = local.file.this_file.kontent,
|                                                ^^^^^^^
17 |     }]
```

river/vm: improve error messages for invalid field names

---

operations/river-jsonnet/jsonnetfile.json

This allows river-jsonnet to be versioned separately from other dependencies.
Created using `jb init`.

operations/river-jsonnet: add jsonnetfile.json

---

component/common/config/types.go
component/metrics/remotewrite/types.go

Add http_client_config to remote write flow

Add client_config block to remote_write

---

component/metrics/remotewrite/remote_write.go
pkg/flow/internal/controller/loader.go

The fanout appender should be used for appending metrics so the prometheus_remote_storage_highest_timestamp_in_seconds metric gets updated.
Also fixes the `agent_component_evaluation_seconds` histogram and the `agent_component_controller_evaluating` metrics to track whether a runtime reevaluation is ongoing, not just graph loads.

metrics.remote_write: use correct storage.Appendable when writing metrics

---

pkg/flow/flow.go

This fixes a bug where only a single changed component was reevaluated, even if other components were in the queue. This potentially caused some components to never get evaluated, depending on the luck of the draw from what gets dequeued.

flow: evaluate everything in queue when queue changes

---

pkg/river/internal/value/decode.go
pkg/river/internal/value/decode_benchmarks_test.go

Benchmark results:
```
name             old time/op    new time/op    delta
ObjectDecode-10    5.83µs ± 2%    5.68µs ± 2%   -2.54%  (p=0.000 n=10+10)
name             old alloc/op   new alloc/op   delta
ObjectDecode-10    3.97kB ± 0%    3.67kB ± 0%   -7.66%  (p=0.000 n=9+10)
name             old allocs/op  new allocs/op  delta
ObjectDecode-10       125 ± 0%       106 ± 0%  -15.20%  (p=0.000 n=10+10)
```
This gives a tiny performance boost for decoding map values, but it creates far less garbage.
Other low-hanging fruit optimizations are possible, but I wanted to start with this one.

river: reuse memory when decoding a map

---

component/component.go
pkg/river/internal/value/decode.go
pkg/river/internal/value/decode_test.go
pkg/river/internal/value/value.go
pkg/river/vm/vm.go

This change modifies River so that decoded values only make a copy when the Go values do not match directly.
This means that pointer addresses, map references, and slice references are preserved.
When direct assignment is performed, River bypasses invoking the TextUnmarshaler and river.Unmarshaler interfaces.
As an exception, copies are made if the target Go type has an interface{} anywhere within its type definition, since interface{} values are expected to decode into known types (where River objects always decode into map[string]interface{}, etc).
This change make sa dramatic improvement to object decoding:
```
name             old time/op    new time/op    delta
ObjectDecode-10    5.84µs ± 2%    0.04µs ± 1%  -99.27%  (p=0.000 n=19+18)
name             old alloc/op   new alloc/op …
```

River: preserve pointers and references when decoding

---

operations/agent-flow-mixin/dashboards.libsonnet
operations/agent-flow-mixin/dashboards/controller.libsonnet
operations/agent-flow-mixin/dashboards/utils/dashboard.jsonnet
operations/agent-flow-mixin/dashboards/utils/panel.jsonnet
operations/agent-flow-mixin/grizzly.jsonnet
operations/agent-flow-mixin/jsonnetfile.json
operations/agent-flow-mixin/mixin.libsonnet

This introduces an agent-flow-mixin for users to visualize and alert on the behavior of Grafana Agent Flow.
This first commit introduces a prototype of a controller dashboard that can be used for monitoring Flow controller information. A grizzly.jsonnet file has been included for locally prototyping the mixin.
The code isn't very pretty, but hopefully maintainable enough.
Future PRs will be used to add alerts and other dashboards.

Introduce agent-flow-mixin

---

CHANGELOG.md
pkg/traces/promsdprocessor/prom_sd_processor.go
pkg/traces/promsdprocessor/prom_sd_processor_test.go

When the PromSD processor is using the `connection`  method to deduce the IP address of the client sending the span, remove any port number from the address string before matching against known IP addresses.
Fixes #1984
I tested this change in the scenario where my trace spans were not getting any pod information attached.  After this change, there are `pod` and `container` labels in the `Process` section of the spans.

Remove any port number from the incoming connection address for PromSD processing

---

component/discovery/discovery.go
component/discovery/kubernetes/k8s.go
component/metrics/scrape/scrape.go
component/metrics/scrape/scrape_test.go
component/targets/mutate/mutate.go
component/targets/mutate/mutate_test.go

To be able to take advantage of the performance improvement from #2016, the various Flow components need to use a common Target type, since values can only be directly assigned if the Go types are exactly the same.

Flow: use common Target type amongst related components

---

CHANGELOG.md
pkg/metrics/agent.go

Register the prometheus discovery metrics. Its not ideal since it uses the default register but during normal operation that is the register passed into the New agent.

Register metrics

---

pkg/river/internal/stdlib/stdlib.go
pkg/river/internal/value/raw_function.go
pkg/river/internal/value/value.go
pkg/river/vm/vm_stdlib_test.go

This introduces the concept of a "raw function" which can be used to implement River functions that don't decode to Go values.
Then, `concat` is changed to be implemented as a raw function. This has a dramatic impact on its performance:
```
name       old time/op    new time/op    delta
Concat-10    23.3µs ± 1%     2.3µs ± 2%  -90.27%  (p=0.000 n=19+18)
name       old alloc/op   new alloc/op   delta
Concat-10    21.3kB ± 0%     1.5kB ± 0%  -93.14%  (p=0.000 n=20+20)
name       old allocs/op  new allocs/op  delta
Concat-10       451 ± 0%        20 ± 0%  -95.57%  (p=0.000 n=20+20)
```
`concat` is in the hot path for Flow when there are many service discoveries updating at the maximum rate (once per 5 seconds).

river: have `concat` bypass decoder

---

CHANGELOG.md
pkg/integrations/apache_http/apache_http.go
pkg/integrations/v2/apache_http/apache_http.go

When the apache_http integration config does not include the `instance` parameter, a nil pointer dereference seg fault occurs.
With this config;
```
integrations:
apache_http_configs:
- autoscrape:
enable: true
metrics_instance: grafana-agent/primary-me
scrape_uri: http://apache.default.svc.cluster.local/server-status?auto
```
The result is;
```
docker run --rm -it -v $(pwd):/config grafana/agent:v0.26.0 -config.file=/config/apacheagent.yaml -enable-features integrations-next
ts=2022-08-10T17:01:37.16927698Z caller=server.go:191 level=info msg="server listening on addresses" http=127.0.0.1:12345 grpc=127.0.0.1:12346 http_tls_enabled=false grpc_tls_enabled=false
ts=2022-08-10T17:01:37.17115058Z caller=node.go:85 level=info agent=prometheus component=cluster msg="applying config" …
```

Don't use the optional config parameter (instance) as the Identity on apache_http integration v2

---

operations/river-jsonnet/builder.jsonnet
operations/river-jsonnet/internal/utils.jsonnet
operations/river-jsonnet/main_test.jsonnet
operations/river-jsonnet/manifest.jsonnet

`std.prune` removes all hidden fields. This commit changes River expressions to have a non-hidden field which indicates that it's an expression.
The new object is constructed with a name which is very unlikely to appear as a key in an object literal to avoid invalid manifests from being generated.

operations/river-jsonnet: allow river.expr() to be used with std.prune()

---

production/tanka/grafana-agent/smoke/main.libsonnet
tools/smoke/internal/smoke.go

This adds an option to return 500 on the fake remote write endpoint used in the smoke test 1% of the time if enabled.

simulate errors on remote write endpoint

---

CODEOWNERS
MAINTAINERS.md

This change marks @marctc and @captncraig as maintainers of the following packages:
* cmd/agent-operator 
* pkg/operator 
* pkg/integrations 
Also removes Brenda as a maintainer of docs, which was left in by accident after removing her as a code owner.

add Craig and Marc as maintainers of operator and integrations

---

production/grafanacloud-install.ps1

For the windows integration - the default windows event log configuration contains relative bookmark file paths.
```
job_name: integrations/windows-exporter-application
windows_events:
use_incoming_timestamp: true
bookmark_path: "./bookmark-application.xml"
eventlog_name: "Application"
xpath_query: '*'
labels:
job: integrations/windows_exporter
relabel_configs:
- source_labels: ['computer']
target_label: 'agent_hostname'
pipeline_stages:
- json:
expressions:
source: source
- labels:
source:
```
When running the agent with relative paths in bookmark_path - the agent service fails to start as it is not able to create these files in the relative paths. This PR appends %APPDATA% into all bookmark_path (s) present in the agent config when installing the agent for windows though the powershell …

Append APPDATA to bookmark files in agent config for Windows event logs

---

CHANGELOG.md
cmd/agent-operator/Dockerfile
cmd/agent-operator/Dockerfile.buildx

This should lower the security footprint of the operator significantly, since it relies on many fewer things than the agent itself.
[distroless](https://github.com/GoogleContainerTools/distroless) is a much smaller, debian based image. It still has a few CVE hits from libc and openssl, but fewer than the full debian image. Tested working in my local cluster.

agent-operator: base image off of distroless base image.

---

example/k3d/smoke/monitoring/prometheus_monitoring.libsonnet
production/grafana-agent-mixin/alerts.libsonnet

This PR tunes the threshold of vulture alerting when traces are not found in Tempo

Tune threshold of vulture alerts

---

cmd/agent/flow.go
cmd/agent/flow_run.go
cmd/agent/main.go
docs/flow/reference/cli/run.md

This changes
```
ENABLE_FLOW_EXPERIMENTAL=true agent --config.file=/path/to/file.river
```
to 
```
ENABLE_FLOW_EXPERIMENTAL=true agent run /path/to/file.river
```
Help text is added to help users understand basic information about Flow. 
Additionally, `ENABLE_FLOW_EXPERIMENTAL=1` is also accepted to enable Flow.

Flow: use cobra for the CLI and add an `agent run` command

---

production/grafanacloud-install.sh

grafanacloud-install.sh is the only place which doesn't refer to the version with the `v` prefix, so it tends to be missed when bumping the version references.
```
$ RELEASE_VERSION=v0.26.1 
$ echo "${RELEASE_VERSION#v}" 
0.26.1
```

production: make it harder to forget updating grafanacloud-install.sh

---

docs/flow/reference/flags.md

There is no general set of command-line flags that should be documented; instead, each cli command will document its command line flags. Command line flags for `run` are already documented in reference/cli/run.md.

docs/flow: remove reference/flags.md

---

docs/rfcs/0005-river.md
docs/rfcs/xxxx-river.md

This RFC expands on the expressions design proposed by #1546 with a suggestion that a custom config language for Flow expressions is required to make Flow be as useful and powerful as possible. The current implementation of Flow uses HCL, but with the number of changes I had to make to HCL to get things to work, it doesn't appear to be the best fit. 
I would prefer not creating a new language, but I see it as our only option for Flow. Most of this RFC focuses on the rationale for how I reached this conclusion, why existing languages aren't the best fit, and why it's important to do this for Flow earlier instead of later.
Additionally, in light of proposing a new language, I focus on reducing the learning curve as much as possible to reduce friction from users migrating from the existing …

[RFC] River: A Flow-optimized config language

---

docs/flow/concepts/_index.md
docs/flow/concepts/component_controller.md
docs/flow/concepts/components.md
docs/flow/concepts/configuration_language.md
docs/flow/reference/cli/run.md

The "concepts" section should explain everything there is to know about Flow at a high-level: 
1. What components are 
2. What the component controller is, how components get evaluated, component health
3. What the configuration language is 
If this is missing any other high-level documentation for Flow, please let me know and I'll add it. 
I think we'll want to eventually have high-level documentation for concepts like Prometheus metrics and service discovery, but I'm leaving that out for now to just focus on Flow-specific things.

docs/flow: Add documentation for Flow concepts

---

docs/flow/reference/stdlib/json_decode.md

The export of local.file is called `content`, not `contents`:
https://github.com/grafana/agent/blob/fa4e86ede73c320849476ff384f8dd7632bd4061/component/local/file/file.go#L72

docs/flow: fix typo in json_decode examples

---

.drone/drone.yml

go get for installing binaries is deprecated in go 1.18.
Trying to see if this fixes the release.
https://go.dev/doc/go-get-install-deprecation

Use go install to install binaries in drone 

---

CHANGELOG.md
pkg/integrations/snmp_exporter/snmp_exporter.go
pkg/integrations/v2/snmp_exporter/snmp.go
pkg/integrations/v2/snmp_exporter/snmp_exporter.go
pkg/integrations/v2/snmp_exporter/snmp_exporter_test.go

The SNMP config was not correctly setting additional scrape params (`module`, and `walk_params` specifically) when they defined in the configuration file. This would result in incomplete service discovery, and scraping a target without those values.
Partially #2017
I am also experiencing a yaml unmarshal error which I'm trying to track down when using the agent operator and the SNMP integration. Time will tell if I can sort it out.

SNMP Exporter Scrape Configs

---

CHANGELOG.md
pkg/integrations/v2/app_agent_receiver/logs_exporter.go
pkg/integrations/v2/app_agent_receiver/logs_exporter_test.go
pkg/integrations/v2/app_agent_receiver/payload.go
pkg/integrations/v2/app_agent_receiver/payload_test.go
pkg/integrations/v2/app_agent_receiver/receiver_metrics_exporter.go
pkg/integrations/v2/app_agent_receiver/receiver_metrics_test.go
pkg/integrations/v2/app_agent_receiver/testdata/payload.json

Adds Event kind to app-agent-receiver payload, modeled after [OTEP for Events API](https://github.com/open-telemetry/oteps/blob/main/text/0202-events-and-logs-api.md). [Issue to add Events API support on the grafana javascript agent side](https://github.com/grafana/grafana-javascript-agent/issues/48).
Fixes #2062

app-agent-receiver: add Event kind to payload

---

component/all/all.go
component/discovery/relabel/relabel.go
component/discovery/relabel/relabel_test.go
docs/flow/reference/components/discovery.relabel.md

As described in #2059, we would like to set up some conventions in the naming of Flow component.
This PR renames the `targets.mutate` component and adds it under the discovery namespace as `discovery.relabel`.
No issue filed
None, for now.

flow: rename targets.mutate component to discovery.relabel

---

build-image/Dockerfile

This will introduce 0.15.0 of the build-image, which contains all the tooling needed for building the agent locally and through CI.
The base image is rfratto/viceroy, which is a rewrite of rfratto/seego which is a little easier to work with. Note that while rfratto/viceroy has an arm64 image, grafana/agent-build-image doesn't (yet) and only amd64 images will be produced for the 0.15.0 release. 
If there are any missing tools here needed for any Github Action or Drone job, please let me know: this should be the only image we need and have all of the dependencies already installed. 
Related to #2052.

Introduce new consolidated build-image

---

cmd/agent-operator/Dockerfile
cmd/agent-operator/Dockerfile.buildx
cmd/agent/Dockerfile
cmd/agent/Dockerfile.buildx
cmd/agentctl/Dockerfile
cmd/agentctl/Dockerfile.buildx

`ubuntu:jammy` is slightly smaller than `debian:bullseye-slim`, and has 0 high or critical vulnerabilities in trivy.
If it works, this could solve a lot of problems.
It runs for me locally, but still needs verification of the cgo bits:

Use ubuntu base image

---

docs/flow/_index.md
docs/flow/concepts/_index.md
docs/flow/getting_started.md
docs/flow/reference/_index.md
docs/flow/reference/cli/_index.md
docs/flow/reference/stdlib/_index.md
docs/flow/reference/stdlib/json_decode.md

Adds content to:
* docs/flow/_index.md
* docs/flow/getting_started.md
* docs/flow/reference/_index.md
* docs/flow/reference/cli/_index.md
The information presented in `docs/flow/reference/_index.md` and `docs/flow/reference/cli/_index.md` is pretty minimal. I'd appreciate any feedback on if there's more information we should add there or if it's good for now.

docs/flow: flesh out basic docs files

---

CHANGELOG.md
pkg/operator/resources_pod_template.go
pkg/operator/resources_pod_template_test.go

Signed-off-by: Hassan Syed <hassan.syed@paymentsense.com>
The agent workloads cannot be scheduled on AWS Fargate as the `config-reloader` container sets `SecurityContext.Privileged` property. There is some discourse [here](https://github.com/grafana/agent/issues/1928#issuecomment-1190296733) asserting that the property is not needed.
The updated operator has been tested in:
* AWS Fargate: metrics only.
* GKE: Loki and metrics.

operator - remove privileged property from security context

---

docs/sources/set-up/_index.md
docs/sources/set-up/install-agent-linux.md

This PR adds a section in the docs explaining how to install the Agent
using Linux package managers either for deb or rpm packages.
Closes #844
I couldn't test for RPM-based Linux but I tested for deb and it
worked.

docs: Add section how to install Agent on Linux

---

CHANGELOG.md
docs/sources/operator/custom-resource-quickstart.md
pkg/operator/apis/monitoring/v1alpha1/types.go
pkg/operator/resources_pod_template.go
production/operator/crds/monitoring.grafana.com_grafanaagents.yaml
production/operator/crds/monitoring.grafana.com_integrations.yaml

This PR adds the ability to disable the reporting of usage of feature flags
to grafana when using the Agent Operator
Closes #1856 
After running `make crd` it changed quite a lot the current CRDs.
Please, look if anything critical changed.

Add field to Operator to disable report usage

---

pkg/river/vm/op_binary.go

This PR allows us to side-step an edge case in Go's string formatting described in #2107 where `%s` in uint8 (byte) slices doesn't recurse each element to call its String() but treats the whole slice as a string.
Fixes #2107
The allowed operands are now reported correctly.
```
ts=2022-09-02T14:14:25.417997Z level=error msg="failed to evaluate component" component=local.file.this_file err="decoding River: ./cmd/agent/example-config.river:11:18: true should be one of [number string] for binop <, got bool"
ts=2022-09-02T14:14:25.418241Z component=prometheus.remote_write.default subcomponent=rw level=info remote_name=618d80 url=http://localhost:9009/api/prom/push msg="Replaying WAL" queue=618d80
Error: …
```

river: fix error message about allowed operands

---

pkg/river/internal/stdlib/stdlib.go
pkg/river/vm/vm_stdlib_test.go

In River's documentation we refer to this function as `json_decode` while its currently exposed as `unmarshal_json`.
We should sync the two; I'm not sure which of the two should be preferred but I opted to go with the first one on this PR. Let me know if you think we should go the other way around.
No PR filed.

river: sync name of stdlib function for decoding JSON

---

.drone/drone.yml
Makefile-v2.mk
build-image/Dockerfile

Updates Drone to build arm64 variants of grafana/agent-build-image, primarily for Apple Silicon users. 
Also ensures that `libbpfcc-dev` is always installed for amd64, which is the only architecture that eBPF works on right now. 
This will tag 0.15.1 of the build image.

Support arm64 variant of grafana/agent-build-image

---

cmd/agent/example-config.river
component/prometheus/scrape/scrape.go
component/prometheus/scrape/scrape_test.go
component/prometheus/scrape/types.go
docs/flow/reference/components/prometheus.scrape.md

This PR aims to provide a round of polish to the `prometheus.scrape` component.
More specifically: 
* Removes the requirement to pass a `job_name`, which was a leftover from when the component could configure multiple targets at the same time. The reported job_name will be set to the component's ID (prometheus.scrape.label).
* Removes the `scrape_config` block to allow for a flatter configuration. The only nested blocks now is `http_client_config`. Note: I tried to simply embed the previously-defined Config field, but unfortunately it broke River's unmarshalling, and ended up not recognizing even the previously-present fields, so I had to widen the scope of changes.
* Made a final comparison between the fields defined in …

flow: polish prometheus.scrape component

---

.github/workflows/publish-documentation-next.yml
.github/workflows/publish-documentation-versioned.yml

This PR separates the `publish.yml` GitHub action into two
a) A new, simpler one which just pushes docs whenever there's a new commit on `main`.
b) An updated version of the previous one, which uses the `has-matching-release-tag` custom action to perform a stricter check and only push documentation if there's already a published tag with the same name.
The same approach is used by Mimir's [workflows](https://github.com/grafana/mimir/tree/main/.github/workflows) and while I think we could maybe fit everything into one Action, I believe it's worth it to follow a common approach, with simpler building blocks that other projects can reuse more easily.
Fixes #1782

Separate Github Actions to avoid publishing rc documentation as stable

---

pkg/usagestats/reporter.go

Fix typo in usagestats reporter log message.
Think the original message comes unchanged from Loki code.

Fix typo in usagestats reporter log message.

---

docs/flow/config-language/components.md
docs/flow/config-language/files.md
docs/flow/config-language/syntax.md

This is an initial stab at adding slightly more detailed documentation for River's files, the language syntax and handling of components.
I think that there's significant overlap with what we thought would go under `config-language/_index.md` in #2093 which leads me to think that we should have something more or different here? 
I'm not entirely sure _what_ that would be though right now, looking forward to your feedback

river: add documentation for language concepts

---

example/k3d/environment/main.jsonnet
production/tanka/grafana-agent/grafana-agent.libsonnet
production/tanka/grafana-agent/scraping-svc/main.libsonnet

- Agent pods were crashlooping due to outdated configuration format and flags

Fix k3d examples

---

pkg/river/vm/vm.go
pkg/river/vm/vm_block_test.go

This adds a diagnostic positioned at invalid attribute and block names rather than the surrounding block, turning this error:
```
Error: ./cmd/agent/example-config.river:6:1: Failed to build component: decoding River: unrecognized block name "invalid_block"
5 |
6 | | local.file "this_file" {
|  _^^^^^^^^^^^^^^^^^^^^^^^^
7 | |     // Must be running from the root directory of the repository for this relative
8 | |     // path to work.
9 | |     filename = "./cmd/agent/test-local-file.txt"
10 | |     detector = "fsnotify"
11 | |
12 | |     invalid_block {
13 | |         hello = "world"
14 | |     }
15 | | }
| |_^
16 |
```
into this:
```
Error: ./cmd/agent/example-config.river:12:2: unrecognized block name "invalid_block"
11 |
12 |     invalid_block {
|     ^^^^^^^^^^^^^
13 |         hello = …
```

river/vm: enhance error message for unrecognized attribute/block names

---

README.md
docs/sources/_index.md

While v0.28 is still planned for 2022-09-27, removing the specific date gives us wiggle room for when the release gets published.

remove specific date for v0.28 release

---

docs/flow/concepts/components.md

Just keeping the documentation page up to date after renaming the discovery.k8s component to discovery.kubernetes.
No issue files

flow: amend docs after renaming component to discovery.kubernetes

---

tools/ci/docker-containers

It looks like not all the images are getting consistently built and pushed. We need to make sure the commands are running to help debug the problem.

tools/ci: add options to print commands before building Docker containers

---

docs/flow/monitoring/_index.md
docs/flow/monitoring/component_metrics.md
docs/flow/monitoring/controller_metrics.md
docs/flow/monitoring/debugging.md

This PR adds documentation for how to monitor and debug Grafana Agent Flow. 
The UI is described here, but I've purposefully left screenshots out for the time being until the UI is merged in main (since some details may change in the meantime).

docs/flow: add monitoring docs

---

tools/ci/docker-containers

This fixes an issue introduced by #2139 where adding `set -u` caused bash to fail on the first line which referenced an unbound environment variable.

tools/ci/docker-containers: explicitly define used environment variables

---

docs/flow/reference/components/prometheus.relabel.md

Add a reference page for the prometheus.relabel component, much like discovery.relabel.

flow: add reference page for prometheus.relabel component

---

pkg/river/parser/internal.go
pkg/river/parser/testdata/invalid_object_key.river

After a recent discussion with @rfratto about River only allowing string map keys, we noticed that the error was not terminating correctly.
This PR contains an approach for fixing the reported error by advancing directly to the assignment operator instead of attempting to simply consume any strings or identifiers in sequence.
A side-effect of this change is that `parseField()` no longer returns a nil `ast.ObjectField`, but rather an empty one in case of errors. I didn't see any issues with that in any caller, but I'll look once more.

river: improve diagnostic for invalid object keys

---

cmd/agent-operator/DEVELOPERS.md
docs/developer/releasing.md

After merging [new Makefile structure](https://github.com/grafana/agent/pull/2130), we forgot to update documentation
pointing to new make targets. This PR fixes with new ones.

Fix make commands in docs

---

pkg/river/encoding/map.go

Sort object keys so River objects backed by Go maps appear in a consistent order.

river/encoding: sort object keys

---

cmd/agent/example-config.river
docs/flow/reference/components/prometheus.remote_write.md

This PR adds documentation for the prometheus.remote_write component. This is the biggest component documentation by far, with the largest number of potentially nested blocks.
I'm using a different way of referring to nested blocks here to make the documentation hopefully easier to navigate: 
```
```
Run `make docs` from the `docs/` folder to see how this page renders in practice. 
This header refers to the `basic_auth` block nested inside of `http_client_config` (which is itself nested inside of `endpoint`). I chose this representation since `endpoint.http_client_config.basic_auth` would be potentially misleading as a block name. We may want to go back and change other components documentation to use this form if we think it helps. 
I'm also duplicating information here; there are two …

docs/flow: document prometheus.remote_write

---

pkg/flow/internal/controller/loader.go
pkg/flow/internal/controller/loader_test.go
pkg/flow/internal/testcomponents/singleton.go
pkg/river/ast/ast.go
pkg/river/parser/internal.go

This PR enforces that singleton components _must_ have a label and that non-singleton components _must not_ have one. 
The error reporting looks like this
```
Error: ./example-config.river:13:1: Component "local.file" must have a label
12 |
13 | local.file {
| ^^^^^^^^^^
14 | }
Error: ./example-config.river:16:1: Singleton component "prometheus.integration.node_exporter" must not have a label
15 |
16 | prometheus.integration.node_exporter "foo" {
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17 | }
```
No issue filed specifically for the handling of singleton components, but should deal with #2095.
* We could add this check in an earlier point eg. in `flow.ReadFile()`, but that would stop at the first error and not allow us to …

flow: handle singleton components

---

cmd/agent/flow.go
cmd/agent/flow_fmt.go
docs/flow/reference/cli/_index.md
docs/flow/reference/cli/fmt.md

The `agent fmt` subcommand formats the specified River configuration file.
The `agent fmt` subcommand behaves similarly as `tools/riverfmt`, but uses Cobra instead.
Closes #2150.

Flow: add `agent fmt` subcommand to format files

---

cmd/agent/flow_run.go
docs/flow/reference/cli/run.md
web/ui/assets_builtin.go
web/ui/assets_nobuiltin.go
web/ui/src/contexts/PathPrefixContext.tsx
web/ui/ui.go

This commit exposes the Flow UI from Grafana Agent Flow's HTTP server. By default, the UI is available via the the `/` path. The path where the UI (and the UI's API) is hosted can be changed via the `--server.http.ui-path-prefix` flag.
By default, Grafana Agent Flow will look for the UI at the `./web/ui/build` path relative to the working directory from where Grafana Agent Flow is running. A built UI at `./web/ui/build` can be baked into the binary by setting a `builtinassets` build flag when building.
To build the UI, run `go generate -tags builtinassets ./web/ui` or run `yarn && yarn build` from the `./web/ui` directory. 
This change does not yet modify the Makefile or Dockerfile to include the builtin UI from release assets. This will be done in a future change.

cmd/agent: expose the Flow UI from the HTTP server

---

build-image/Dockerfile

This commit adds NodeJS LTS (v16) and Yarn for building the UI. This has been tested to work through the following steps:
```
$ docker build -t grafana/agent-build-image:0.16.0 ./build-image
$ docker run --rm -it -v `pwd`:/src -w /src grafana/agent-build-image:0.16.0
$ cd web/ui
$ yarn
$ yarn run build
```
Once this is merged into main, build-image/v0.16.0 will be tagged.

build-image: add NodeJS and Yarn for building the UI

---

.drone/drone.yml
Makefile
cmd/agent-operator/Dockerfile
cmd/agent/Dockerfile
cmd/agentctl/Dockerfile
tools/crow/Dockerfile
tools/make/build-container.mk
tools/make/packaging.mk
tools/smoke/Dockerfile

This updates the following to embed the Grafana Agent Flow UI by default:
* The grafana/agent Docker image
* Release assets produced by `make dist`
This uses the new grafana/agent-build-image:0.16.0 release which includes Node.JS and Yarn.

Bundle UI by default in Docker images and dist assets

---

docs/flow/reference/components/prometheus.integration.node_exporter.md
docs/flow/reference/components/prometheus.integrations.node_exporter.md

This PR adds a reference page for the `prometheus.integration.node_exporter` component.
It borrows much terminology from the existing documentation page for the node_exporter integration, so hopefully the information is not misleading on them both.
Let me know if I'm missing anything important we should let users know!

 docs/flow: add reference page for prometheus.integration.node_exporter component

---

component/discovery/relabel/relabel.go
component/discovery/relabel/relabel_test.go
component/prometheus/relabel/relabel.go
docs/flow/reference/components/discovery.relabel.md
docs/flow/reference/components/prometheus.relabel.md
docs/flow/tutorials/assets/flow_configs/multiple-inputs.flow
docs/flow/tutorials/assets/flow_configs/relabel.flow
docs/flow/tutorials/chaining.md

This PR updates both prometheus.relabel and discovery.relabel to use `rule` as the sub-block name. This should help with the repetitiveness of typing `metrics_relabel_config` and `relabel_config` over and over again.
No issue filed

flow: rename relabeling sub-blocks to 'rule'

---

docs/flow/_index.md
docs/flow/concepts/components.md
docs/flow/concepts/configuration_language.md
docs/flow/config-language/expressions/referencing_exports.md
docs/flow/config-language/expressions/types_and_values.md
docs/flow/getting_started.md
docs/flow/tutorials/assets/flow_configs/agent.flow
docs/flow/tutorials/assets/flow_configs/multiple-inputs.flow
docs/flow/tutorials/assets/flow_configs/relabel.flow
docs/flow/tutorials/chaining.md
docs/flow/tutorials/collecting-prometheus-metrics.md
pkg/river/parser/testdata/assign_block_to_attr.river
web/ui/src/features/component/types.ts

This PR cleans up some references to previous component and field names after the recent namespacing and component cleanup.
Did I miss anything? Did you spot any more of those?

docs/flow: fix mentions of previous component names and fields

---

web/ui/src/features/component/ComponentGraph.tsx

`decrossOpt` is far too slow for large graphs above 45 components. This commit changes the layout parameters to be better optimized for larger graphs.
Fixes #2188.

ui: Use faster layout parameters when drawing component graph

---

docs/flow/reference/components/discovery.kubernetes.md
docs/flow/reference/components/prometheus.remote_write.md

First draft. 
- Http stuff copied from prometheus.scrape. Would be great to have a way to include a partial.
- Some of the selector stuff is copied and adapted from prometheus docs, or links out. Because some of it is a little tricky, and I'm not sure how much we want to duplicate, or re-state.

Flow: Docs for discovery.kubernetes

---

web/ui/src/features/component/ComponentView.tsx

Anchor links broke when adding the <base> element; using the react-router Link component fixes this by prefixing the current route before the anchor.
Tested locally with `EXPERIMENTAL_ENABLE_FLOW=1 go run ./cmd/agent run ./cmd/agent/example-config.river --server.http.ui-path-prefix=/test`

web/ui: fix anchor links

---

component/discovery/relabel/relabel_test.go
component/prometheus/remotewrite/remote_write_test.go
pkg/river/river.go
pkg/river/river_test.go

This commit introduces a high-level river.Marshal* and river.Unmarshal* API. The API serves mostly as documentation for how to properly use the low level APIs.
Flow component tests which previously used the low-level APIs have been replaced with the high-level APIs.
Sorry for the size of this PR :) Almost of the entirety of the new size is documentation.

pkg/river: introduce high-level marshal/unmarshal API

---

CHANGELOG.md

[This comment][comment] pointed out that the blackbox_exporter integration was accidentally added to the v0.27.0 release notes, even though it missed that release window.
[comment]: https://github.com/grafana/agent/pull/1997#issuecomment-1257158405

CHANGELOG: move blackbox_exporter integration to proper release

---

docs/sources/flow/config-language/expressions/operators.md

Fixes rendering of `||` operator messing with the Markdown table.

docs/flow: fix rendering of 'logical or' operator

---

component/otelcol/consumer.go
component/otelcol/exporter/exporter.go
component/otelcol/exporter/exporter_test.go
component/otelcol/internal/lazyconsumer/lazyconsumer.go
component/otelcol/internal/scheduler/host.go
component/otelcol/internal/scheduler/scheduler.go
pkg/flow/componenttest/componenttest.go

This commit introduces a new package, `component/otelcol/exporter`, which exposes a generic Flow component implementation which can run OpenTelemetry Collector exporters.
There is some stuff left to do for this implementation to be complete:
* A Zap logging adapter needs to be created to correctly process logs from OpenTelemetry Collector components.
* Component-specific metrics are currently ignored.
* Component-specific traces are currently ignored.
All of the above will be done in separate PRs.
As of this commit, there are no registered `otelcol.exporter.*` components. Implementations for OpenTelemetry Collector Flow components will be done in future PRs.
Related to #2213, and based off of the original prototyping done in #1843.

component/otelcol/exporter: create exporter component abstraction

---

docs/sources/flow/reference/components/discovery.kubernetes.md
docs/sources/flow/reference/components/discovery.relabel.md
docs/sources/flow/reference/components/local.file.md
docs/sources/flow/reference/components/prometheus.integration.node_exporter.md
docs/sources/flow/reference/components/prometheus.relabel.md
docs/sources/flow/reference/components/prometheus.remote_write.md
docs/sources/flow/reference/components/prometheus.scrape.md
docs/sources/flow/reference/components/remote.s3.md

This PR changes the component references to use a consistent structure:
* Examples have been moved to the bottom of the page, and a Usage section has been moved to where Examples used to be. 
* Components that have blocks now have a h2 for `Blocks` and one h3 per defined block.

docs: Use consistent structure for Flow component references

---

docs/sources/flow/concepts/configuration_language.md
docs/sources/flow/config-language/_index.md
docs/sources/flow/config-language/syntax.md
docs/sources/flow/reference/components/prometheus.integration.node_exporter.md
docs/sources/flow/tutorials/collecting-prometheus-metrics.md

Placeholders should be all-uppercase SNAKE_CASE with no other special characters denoting a placeholder (such as angle brackets).

docs/flow: use consistent placeholders

---

docs/sources/flow/reference/components/prometheus.integration.node_exporter.md

This isn't ideal, but allows the page to be navigated until we can make style changes for it to display better inside the table.

docs/flow: fix instances where default strings overflow page width

---

.github/workflows/test.yml

I've noticed that there's some cache misses for the CI even though they should exist. I want to see if using the builtin cache option for actions/setup-go fixes our issues.

CI: use cache option for actions/setup-go

---

.github/workflows/test.yml

This makes sure macOS works against main, but more importantly it will create a reusable build cache, which is required for future PRs to be able to reuse the cache.
For details, refer to https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

CI: run macOS tests when a push to main happens

---

packaging/deb/grafana-agent.service
packaging/rpm/grafana-agent.service

Setting the WorkingDirectory allows the grafana-agent service to run relative to /var/lib/grafana-agent. This means that the default storage location will be relative to a path which is writable by the grafana-agent user.
Fixes #2217.

packaging: set WorkingDirectory for systemd services

---

component/otelcol/exporter/exporter.go
component/otelcol/internal/zapadapter/zapadapter.go
component/otelcol/internal/zapadapter/zapadapter_test.go
component/otelcol/receiver/receiver.go

This introduces component/otelcol/internal/zapadapter, which creates a *zap.Logger instance from a github.com/go-kit/log.Logger instance. This is then used when creating OpenTelemetry Collector components, allowing us to continue to use github.com/go-kit/log consistently throughout Flow.
Related to #2213.

component/otelcol: use zap adapter to accept logs from wrapped components

---

component/otelcol/processor/processor.go
component/otelcol/processor/processor_test.go
component/otelcol/receiver/receiver.go

This commit introduces a new package, component/otelcol/processor, which exposes a generic Flow component implementation which can run OpenTelemetry Collector processors.
This package acts like a combination of #2227 and #2254, both exposing consumers for other consumers to send telemetry data to be processed, and accepting a list of consumers to determine where to forward processed data. 
Like #2227 and #2254, it leaves some work unfinished for future PRs:
* Component-specific metrics are currently ignored.
* Component-specific traces are currently ignored.
As of this commit, there are no registered `otelcol.processor.*` components. Implementations for OpenTelemetry Collector Flow components will be done in future PRs.
Related to #2213.

component/otelcol/processor: create processor component abstraction

---

.github/workflows/add-to-project.yml
component/otelcol/receiver/otlp/otlp_test.go

This PR adds a GitHub Action where new issues will automatically get added to the Grafana Agent project board. It uses [actions/add-to-project](https://github.com/actions/add-to-project) to work.

ci: automatically add new issues to Grafana Agent project board

---

CHANGELOG.md
component/all/all.go
component/otelcol/processor/batch/batch.go
component/otelcol/processor/batch/batch_test.go
docs/sources/flow/reference/components/otelcol.processor.batch.md
docs/sources/flow/reference/components/otelcol.receiver.otlp.md

Introduce a new `otelcol.processor.batch` component.
Closes #2285.

otelcol.processor.batch: new component

---

CHANGELOG.md
component/all/all.go
component/otelcol/config_compression.go
component/otelcol/config_grpc.go
component/otelcol/config_queue.go
component/otelcol/config_retry.go
component/otelcol/config_timeout.go
component/otelcol/config_tls.go
component/otelcol/exporter/otlp/otlp.go
component/otelcol/exporter/otlp/otlp_test.go
component/otelcol/processor/batch/batch.go
docs/sources/flow/reference/components/otelcol.exporter.otlp.md
docs/sources/flow/reference/components/otelcol.processor.batch.md
docs/sources/flow/reference/components/otelcol.receiver.otlp.md

Introduce an `otelcol.exporter.otlp` component which wraps around the upstream otlp (gRPC) exporter.
I've left two pieces of work to be done in future PRs:
* `otelcol.exporter.otlp` doesn't support authentication yet.
* #2345 
Closes #2288.

otelcol.exporter.otlp: new component

---

component/otelcol/auth/auth.go
component/otelcol/auth/auth_test.go

OpenTelemetry Collector supports many extensions. Extensions are used as a generic way to put "everything else" into OpenTelemetry. To quote their [documentation](https://pkg.go.dev/go.opentelemetry.io/collector@v0.61.0/component#Extension):
> Extension is the interface for objects hosted by the OpenTelemetry Collector that don't participate directly on data pipelines but provide some functionality to the service, examples: health check endpoint, z-pages, etc.
There are two types of extensions relevant to us:
* [Authentication extensions][auth-ext]: used for both client and server authentication.
* [Storage extensions][storage-ext]: used for external storage of state.
Other extensions, such as [awsproxy][] are useful but better suited as generic Flow components rather than being shoved in …

component/otelcol/auth: create auth extension component abstraction

---

component/all/all.go
component/otelcol/auth/auth.go
component/otelcol/auth/basic/basic.go
component/otelcol/auth/basic/basic_test.go
component/otelcol/config_grpc.go
component/otelcol/exporter/otlp/otlp.go
docs/sources/flow/reference/components/otelcol.auth.basic.md
docs/sources/flow/reference/components/otelcol.exporter.otlp.md
go.mod
go.sum

Introduce an `otelcol.auth.basic` component which wraps around the upstream basicauth extension and allows other components to use it.
This also updates the `otelcol.exporter.otlp` component to accept a reference to the extension and use it for authentication.
Closes #2354.

otelcol.auth.basic: new component

---

CHANGELOG.md
component/all/all.go
component/otelcol/receiver/jaeger/jaeger.go
component/otelcol/receiver/jaeger/jaeger_test.go
docs/sources/flow/reference/components/otelcol.receiver.jaeger.md

Introduce an `otelcol.receiver.jaeger` component which wraps around the otelcol-contrib jaeger reciever.
Closes #2290.

otelcol.receiver.jaeger: new component

---

docs/sources/flow/reference/components/otelcol.processor.batch.md
docs/sources/flow/reference/components/otelcol.receiver.jaeger.md
docs/sources/flow/reference/components/otelcol.receiver.otlp.md
docs/sources/shared/flow/otelcol/output-block.md
docs/sources/shared/index.md

This PR headless pages to reuse Flow config blocks.
To view locally, run `make docs` from docs/ and look at an example page using the new shared snippet: http://localhost:3002/docs/agent/latest/flow/reference/components/otelcol.processor.batch/#output-block

Docs: reuse flow config blocks

---

CHANGELOG.md
production/kubernetes/agent-traces.yaml
production/kubernetes/build/templates/traces/main.jsonnet

Expose Grafana Agent traces Kubernetes with port 4318 to OTLP exporter sustain both gRPC and HTTP protocols.
Fixes #2339
I'm participating in Hactoberfest 2022 so If you Ok with the changes could you please add a "HACKTOBERFEST-ACCEPTED" label to it.

Grafana Agent traces Kubernetes support OTLP with HTTP protocol

---

pkg/river/internal/stdlib/stdlib.go
pkg/river/internal/value/decode_benchmarks_test.go
pkg/river/internal/value/type.go
pkg/river/internal/value/value.go
pkg/river/internal/value/value_test.go
pkg/river/vm/vm_stdlib_test.go

This commit changes the representation of objects and maps from `[]interface{}` and `map[string]interface{}` to use `[]value.Value` and `map[string]value.Value` respectively.
This fixes #2362, an issue where interface-based capsule values where losing type information and being coerced to a type based on the actual value backing the interface.
This also greatly improves the performance of creating arrays and objects, which no longer need to be inidividually copied in a loop:
```
name                   old time/op    new time/op    delta
Object/Non-capsule-10    1.84µs ± 8%    0.00µs ± 0%   -99.89%  (p=0.000 n=19+19)
Object/Capsule-10        1.82µs ± 4%    0.00µs ± 0%   -99.89%  (p=0.000 n=20+19)
Array/Non-capsule-10      389ns ± 2%      19ns ± 2%   -95.20%  (p=0.000 n=19+18) …
```

river/internal/value: change representation of objects and maps

---

CHANGELOG.md

Features should be listed before Enhancements: https://github.com/grafana/agent/blob/main/docs/developer/contributing.md#updating-the-changelog

Fix CHANGELOG order

---

CHANGELOG.md

Since there's a lot of new Flow components in the upcoming release, it might make sense to group them under a single bullet point instead of listing them out individually at the top level of the features header.

CHANGELOG: group new Flow components under a single bulletpoint

---

CHANGELOG.md
component/prometheus/relabel/relabel.go
component/prometheus/relabel/relabel_test.go

Adds caching to prometheus relabel, it's probably not the end goal because there are cases where the cache can leak. IE if you have two relabel components in a series, the second one starts caching results from the first, and the configuration on the first changes so it never sends the value that the second was caching. 
The more complex solution would be to also add a time-based eviction notice, but that seemed to complex for an edge case. Adding it to the global cache would likely allow one component to have a timer and notify callers that the cache can be evicted. Since all metrics call back to get a global id it has the most knowledge. I think submodules complicate the global cache and am wary of adding that to global cache at the moment.
Closes #2324

Add initial support for prometheus relabel caching

---

docs/sources/shared/flow/reference/components/rule-block.md

This PR fixes the documentation of capture groups for the prometheus.relabel and discovery.relabel components. The old notation was valid when using HCL in previous Flow iterations, but is different now as we switched to River.
No issue filed

docs/flow: Fix capture group reference documentation

---

docs/sources/flow/reference/components/otelcol.processor.memory_limiter.md

Fix the same 
No issue filed
Ran `make docs` to see how it looks.

docs/flow: Add zero-width space in title to prevent overflowing in rendered docs

---

.github/workflows/add-to-project.yml

This reverts commit bf8675a1cecc4427fe7e1ce59a1a77d9f424e12e.
PRs from forks cannot automatically be added to projects because secrets are not exposed.

Revert "Automatically assign new PRs to project board (#2349)"

---

component/otelcol/exporter/otlp/otlp_test.go
component/otelcol/internal/scheduler/scheduler.go

I noticed some [flaky test runs](https://github.com/grafana/agent/actions/runs/3284481234/jobs/5410488587) in the otelcol.exporter.otlp tests.
I wasn't able to reproduce locally (even with `go test -count=5000 ./component/otelcol/exporter/otlp`), but the fixes here should more or less cover it.

otelcol.exporter.otlp: fix test flakes

---

tools/make/packaging.mk

This PR adds Makefile targets to build FreeBSD/AMD64 images for the agent. It also adds the FreeBSD target to the list of binaries to be generated and packed with each new release.
Fixes #2415
I'm not sure about what was the reason for the `$(error invalid flag $(1)))` that was present in the previous listing of FreeBSD, am I missing something I should add here?
https://github.com/grafana/agent/blob/9fd7d9b325f78153b7b525ddda28d2a2d3e1ccb6/Makefile#L52

Add Makefile targets for FreeBSD/AMD64

---

CHANGELOG.md
docs/sources/flow/config-language/expressions/referencing_exports.md
docs/sources/flow/reference/config-blocks/_index.md
docs/sources/flow/reference/config-blocks/logging.md
pkg/flow/config.go
pkg/flow/config_test.go
pkg/flow/flow.go
pkg/flow/flow_test.go
pkg/flow/internal/controller/component_references.go
pkg/flow/internal/controller/config.go
pkg/flow/internal/controller/loader.go
pkg/flow/internal/controller/loader_test.go

This is a first approach for allowing Flow's special [config blocks](https://grafana.com/docs/agent/latest/flow/reference/config-blocks/) to reference other components, that can be extended to allow for more config blocks in the future.
One way to achieve this is to pre-populate the DAG with a new type of ConfigNode.
This approach gathers all config blocks (just logging for now) when `Apply`ing a configuration file, and uses them to build a NewConfigNode before adding the rest of the components to the graph. The ConfigNode is then wired along all other ComponentNodes, to detect references to components.
The ConfigNode is prepopulated with the default argument options for the various config blocks, and uses the passed blocks …

flow: Allow config blocks to reference component exports

---

operations/agent-flow-mixin/dashboards.libsonnet
operations/agent-flow-mixin/dashboards/controller.libsonnet
operations/agent-flow-mixin/dashboards/resources.libsonnet
operations/agent-flow-mixin/dashboards/utils/dashboard.jsonnet

Add a Resources dashboard which shows, at a high level, the current resource consumption of Grafana Agent. 
This dashboard is intended to be platform-agnostic so it functions regardless of how Grafana Agent is deployed. 
There are three rows:
* High level resource consumption (CPU + memory)
* Application level resource consumption (GC + goroutines + Go heap memory) 
* Network consumption (machine-wide, not agent process-specific)
The network row might be confusing to people as it shows network usage for the whole machine. However, the info tooltip for the two panels explains this. 
The changelog isn't updated since we're currently not treating the mixin as a release asset.

agent-flow-mixin: add Resources dashboard

---

CHANGELOG.md
pkg/integrations/blackbox_exporter/blackbox_exporter.go
pkg/integrations/blackbox_exporter/blackbox_exporter_test.go
pkg/integrations/v2/blackbox_exporter/blackbox.go
pkg/integrations/v2/blackbox_exporter/blackbox_test.go

When using blackbox integration, either in v1 or v2, configured modules
for an specific target are not properly set and it uses `http_2xx` by default.
This PR fixes this issue.
Fixes #2400

Fix usage of modules in Blackbox integration

---

CHANGELOG.md
component/prometheus/relabel/relabel.go
component/prometheus/remotewrite/remote_write.go

This commit changes Flow Prometheus components which export receivers to immediately export their receivers on component construction. Receivers for these components remain the same through the process lifetime, so there's no need for them to emit exports at run or update time.
This is also a minor (but likely immeasurable) performance enhancement, where components depending on `prometheus.remote_write` or `prometheus.relabel` won't be forced to update twice in a row near the process start time. 
The CHANGELOG has been updated to reflect the performance improvement angle, since it is the only way for the changes to be observed by end users.
Closes #1946.

`prometheus.*` components: immediately export receiver on component construction

---

CHANGELOG.md
pkg/traces/config.go
pkg/traces/config_test.go

There used to be a panic due to a configuration such as this:
```
server:
log_level: info
traces:
configs:
- name: default
receivers:
otlp:
```
The panic message was not clear and user friendly. The new message makes it much more clear to the user why the agent failed to start.
Fixes https://github.com/grafana/agent/issues/2347
I wrote a new "Test" function, instead of adding the test to an already existing function such as ```TestOTelConfig()```. This is because I would have had to add a 2nd ```expectedError``` field, which would only be used by this test. However, if you think there is a value in adding this test to the ```TestOTelConfig()``` function, please let me know and I will move it there.
Also, I think updating documentation is not needed., so I'll ignore that checkbox below.

Avoid a panic with an invalid traces configuration

---

CHANGELOG.md
docs/sources/configuration/integrations/integrations-next/eventhandler-config.md
pkg/integrations/v2/eventhandler/integration.go

As part of the effort of completing #2017 we realized that eventhandler integration
didn't include `instance` into the config which allows also to override the instance
key for that integration.
#2366

integrations: add missing setting to override eventhandler instance

---

CHANGELOG.md
component/otelcol/auth/headers/headers.go
component/otelcol/auth/headers/headers_test.go
docs/sources/flow/reference/components/otelcol.auth.headers.md
go.mod
go.sum

Introduce an `otelcol.auth.headers` component which wraps around the upstream `headerssetter` extension and allows other components to use it.
Closes #2356.

otelcol.auth.headers: new component

---

pkg/river/encoding/attribute.go
pkg/river/encoding/block.go
pkg/river/encoding/encoding_test.go
pkg/river/internal/value/value.go

This change is similar to the fix introduced in #2369, where calling the `Interface()` method on River values forced a type change from an interface-based capsule to an any-type capsule. This caused the UI to crash when displaying an otelcol component (see #2361).
The new `value.FromRaw` method allows constructing a River value from a reflect.Value directly, avoiding the need to convert to interface{}.
As part of this change, a `!reflect.Value.IsZero()` check has been added for safety; this shouldn't happen in most circumstances unless a value.Null is trying to be encoded.
The CHANGELOG wasn't updated because this behavior only occurs when a component exports a capsule type, which was first introduced in the otelcol.* components which have yet to be released.
Fixes #2361.

river/encoding: fix issue where interface capsules were downcasted to empty objects

---

CHANGELOG.md
pkg/operator/config/metrics_templates_test.go
pkg/operator/config/templates/component/metrics/remote_write.libsonnet

- Operator CRDs allow defining bearer tokens for remote writes, but the fields are never mapped to the final configuration.
- Adds mapping to render them when defined.
- See https://prometheus.io/docs/prometheus/2.34/configuration/configuration/#remote_write
- Fixes #2332

Operator: Add support for bearer token for metrics remote write

---

cmd/agent-operator/DEVELOPERS.md
docs/sources/operator/api.md
pkg/operator/apis/monitoring/v1alpha1/types_integrations.go
pkg/operator/apis/monitoring/v1alpha1/types_logs.go
production/operator/crds/monitoring.grafana.com_grafanaagents.yaml
production/operator/crds/monitoring.grafana.com_integrations.yaml
production/operator/crds/monitoring.grafana.com_logsinstances.yaml
production/operator/crds/monitoring.grafana.com_podlogs.yaml

Edited
agent/operator/apis/monitoring/v1alpha1/
deployment.go
doc.go
group.go
types_integrations.go
types_logs.go
Will finish editing topics in this issue: https://github.com/grafana/agent/issues/2452
Fixes #2451

Docs: CRD reference topic edits

---

CHANGELOG.md

grafana/agent#2319 updated a bunch of module dependencies, but accidentally listed them as changes for the already-released v0.28.0 release rather than in Main.
While moving the changes, I made them align with how the new Flow components are referenced and assigned authorship credit.

CHANGELOG: fix misplaced changes

---

component/all/all.go
component/otelcol/auth/basic/basic.go
component/otelcol/auth/bearer/bearer.go
component/otelcol/auth/headers/headers.go

This PR registers the missing `otelcol.auth.headers` and `otelcol.auth.bearer` components from the all.go file.
It also fixes their export types, as it produced a panic. For future grepping purposes, the resulting error was like
```
panic: Component otelcol.auth.bearer.creds changed Exports types from otelcol.ConsumerExports to auth.Exports
```
No issue filed
We barely test these components as-is, should we add a check maybe there?

flow: Register remaining otelcol.auth.* components and fix their export types

---

pkg/util/testappender/compare.go
pkg/util/testappender/dto_sort.go
pkg/util/testappender/internal/dtobuilder/dtobuilder.go
pkg/util/testappender/internal/dtobuilder/sort.go
pkg/util/testappender/testappender.go
pkg/util/testappender/testappender_test.go

`util/testappender` is a new package which introduces utilities for testing code which write metrics to storage.Appender implementations.
`testappender.Appender` implements the `storage.Appender` interface and generates a slice of Prometheus `*dto.MetricFamily` upon calling Commit. The resulting slice of families can be retrieved through the MetricFamilies method.
Then, `testappender.Compare` introduces a utility method to compare a set of metric families against an expected string. The string can be reprsenting either Prometheus' or OpenMetrics' text exposition format.
N/A
I have to clean up the code a little more, so this is being opened in draft for now.

Add utilities for testing code which send data to storage.Appenders

---

.github/workflows/test.yml
.github/workflows/test_packages.yml
CHANGELOG.md
Makefile
build-image/Dockerfile
build-image/windows/Dockerfile
go.mod

This updates the GitHub Actions and build image to use Go 1.19.2 for builds. After this PR, a new build image tag will need to be cut and a follow up PR will be needed to update everything. 
We should probably wait until the [1.19.3 release](https://groups.google.com/g/golang-nuts/c/0D1HwgYge94/m/SO3Tr1zBBwAJ) is available and use that instead, but I'm still opening this in draft just to queue up the work. 
This also removes `-gcflags "all=-N -l"` from our debug flags to allow tests to pass again. Those flags, which disable optimizations and inlining, should now be the responsibility of tools like delve and GoLang to inject. Passing the flags in Go 1.19 causes issues for Macs (see issue 54291 in the Go repo).

Use Go 1.19 for builds

---

CHANGELOG.md
component/all/all.go
component/otelcol/exporter/prometheus/internal/convert/cache.go
component/otelcol/exporter/prometheus/internal/convert/convert.go
component/otelcol/exporter/prometheus/internal/convert/convert_test.go
component/otelcol/exporter/prometheus/prometheus.go
component/prometheus/fanout.go
docs/sources/flow/reference/components/otelcol.exporter.prometheus.md
go.mod

This PR adds a new `otelcol.exporter.prometheus` Flow component, and is the counterpart to #2462. This component: 
1. Accepts OpenTelemetry metrics from other `otelcol` components.
2. Converts metrics into the Prometheus format.
3. Forwards converted metrics to a set of provided `prometheus` components.
Closes #2302.
The component implements the required portions of the OpenTelmemetry [Metrics Data Model][] specification.
The following optional portions of the specification are left unimplemented for this initial commit:
1. Metrics aggregated with delta temporality are dropped and no delta-to-cumulative transformation takes place.
2. Exemplars are dropped.
[Metrics Data Model]: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md

New component: `otelcol.exporter.prometheus`

---

docs/sources/cookbook/dynamic-configuration/01_Basics/02_Instances.md

Link to final.md was pointing to the wrong assets folder

Fix link to final.md

---

operations/agent-flow-mixin/dashboards.libsonnet
operations/agent-flow-mixin/dashboards/prometheus.remote_write.libsonnet

This PR adds a new dashboard to agent-flow-mixin to monitor the behavior of prometheus.remote_write components:

operations/agent-flow-mixin: add dashboard for prometheus.remote_write

---

CHANGELOG.md
docs/sources/operator/api.md
docs/sources/operator/custom-resource-quickstart.md
pkg/operator/apis/monitoring/v1alpha1/types_metrics.go
pkg/operator/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
pkg/operator/config/config_test.go
pkg/operator/config/templates/component/metrics/remote_write.libsonnet
production/operator/crds/monitoring.grafana.com_grafanaagents.yaml
production/operator/crds/monitoring.grafana.com_metricsinstances.yaml

Grafana Agent already supports Oauth2 configuration, but the Grafana agent operator did not.  This PR adds the support for the agent operator as well.
Fixes #2416
Updated the crds with `make generate-crds`, but this also lead to the oauth2 option for the Grafana agent. I'm not sure if this intended or not.

Enable oauth2 remote_write configuration for Grafana Agent Operator

---

.drone/drone.yml

The agent-smoke-test environment is being terminated in favor of the normal agent environment.

Remove CD to agent-smoke-test environment

---

CHANGELOG.md
pkg/flow/flow.go

If a config node appeared in the references list for a given node, the graph page would fail to load because a reference to a non-existant node would be defined.
This temporarily works around the issue by skipping over DAG edges to a config node.
A longer term fix would be to add support for config blocks in the UI so users can see how they evaluated.
This is behavior which can be observed from v0.29.0, but I'm not sure if it warrants a patch release.

Flow UI: skip over config nodes in the DAG

---

component/otelcol/exporter/prometheus/prometheus.go
component/prometheus/fanout.go
component/prometheus/fanout_test.go
component/prometheus/relabel/relabel.go
component/prometheus/scrape/scrape.go
docs/sources/flow/reference/components/prometheus.relabel.md
docs/sources/flow/reference/components/prometheus.scrape.md

Add metrics on relabeling and fanout. Fanout will appear on anything using the fanout appended so added that metric to the individual component doc metrics. 
Closes #2408
Moved the write latency to the fanout appender to track how long a total transaction takes.

Add relabel metrics and fanout

---

CHANGELOG.md
docs/sources/flow/reference/stdlib/concat.md
docs/sources/flow/reference/stdlib/discovery_target_decode.md
docs/sources/flow/reference/stdlib/env.md
docs/sources/flow/reference/stdlib/json_decode.md
pkg/river/internal/stdlib/stdlib.go
pkg/river/vm/vm_stdlib_test.go

`discovery_target_decode` decodes a target list in the style of Prometheus HTTP or file service discovery into a list of `discovery.*`-compatible targets.
Because there currently aren't any `discovery.file` or `discovery.http` components, `discovery_target_decode` acts as a replacement so that `local.file` or `remote.http` (#2495) can be used. This also enables HTTP SD-formatted files to be sourced from `remote.s3`.
Related to #2270.

river/stdlib: add discovery_target_decode function

---

cmd/agent/example-config.river
pkg/flow/internal/controller/loader.go
pkg/flow/internal/controller/loader_test.go

This PR adds traces to graph evaluations:
A log line is emitted whenever a partial or full graph evaluation starts including the trace id to assist in finding traces from logs.

flow/internal/controller: Trace graph evaluations

---

tools/make/packaging.mk

When I added the FreeBSD/AMD64 targets in tools/make/packaging.mk, I accidentally included a call to `make generate-ui` when building the agentctl binary. This is not required and will increase the binary size for no reason, so this PR is removing the call.
No issue filed

Remove call to 'make generate-ui' in agentctl's FreeBSD target

---

CHANGELOG.md
component/all/all.go
component/discovery/discovery.go
component/discovery/docker/docker.go
component/discovery/kubernetes/kubernetes.go
docs/sources/flow/reference/components/discovery.docker.md
docs/sources/flow/reference/components/discovery.kubernetes.md

Introduce a `discovery.docker` component which polls a Docker Engine host for a list of containers on a set interval.
Closes #2263.

discovery.docker: new component

---

CHANGELOG.md
component/otelcol/exporter/prometheus/internal/convert/convert.go
component/prometheus/fanout.go
component/prometheus/interceptor.go
component/prometheus/relabel/relabel.go
component/prometheus/relabel/relabel_test.go
component/prometheus/remotewrite/remote_write.go
component/prometheus/scrape/scrape_test.go

This commit allows exemplars to be passed around in Prometheus component pipelines. To support this change, the prometheus.Interceptor struct was extended to support intercepting any call to the Appendable interface.
Support for metadata is also added, though that code path is currently not invoked in our usage of the Prometheus scraper.
Fixes #2420.

Support exemplars in Prometheus component pipelines

---

CHANGELOG.md
cmd/agent/flow.go
cmd/agent/main.go
cmd/agent/mode.go
docs/sources/flow/_index.md
docs/sources/flow/config-language/files.md
docs/sources/flow/getting_started.md
docs/sources/flow/tutorials/assets/docker-compose.yaml
docs/sources/flow/tutorials/collecting-prometheus-metrics.md
docs/sources/upgrade-guide/_index.md

As part of Grafana Agent Flow being beta, the `AGENT_MODE=flow` environment variable is now preferred for enabling Grafna Agent Flow. Support for `EXPERIMENTAL_ENABLE_FLOW=1` continues to work but is deprecated and will be removed in v0.32.
Closes #2377.

Graduate Grafana Agent Flow to beta

---

CHANGELOG.md
component/all/all.go
component/loki/relabel/metrics.go
component/loki/relabel/relabel.go
component/loki/relabel/relabel_test.go
docs/sources/flow/reference/components/loki.relabel.md

The PR adds a `loki.relabel` component that receives log entries and rewrites their label set using relabeling rules. This functionality was not available in Promtail, where relabeling would only happen for targets, and any label manipulation after the log had been scraped had to be done with stages pipelines, so it needs some back-and-forth.
We didn't have to bring any new Promtail code for this one, for now.
Fixes #2514 
* Since relabeling can be resource-intensive, I've introduced a cache field in the Component struct. Since the relabeling happens only on the same goroutine as the component is running, there was no need to protect it with a mutex.
* As the log entries do not provide any indication of 'staleness', like …

 Flow: add loki.relabel component

---

component/common/loki/positions/positions.go
component/common/loki/positions/positions_test.go
component/common/loki/positions/write_positions_unix.go
component/common/loki/positions/write_positions_windows.go
component/loki/source/file/decompresser.go
component/loki/source/file/file.go
component/loki/source/file/tailer.go

In #2503 we introduced a new `loki.source.file` component, which tails files from disk and sends scraped log entries to other loki.* components.
There are a few omissions with the component current component implementation.
* On Update() it stops and re-creates all readers, even if it's not required
* It does not support tailing multiple files with the same path but different label sets (last one currently wins)
* It cannot expose target labels in DebugInfo
Some of this behavior stems from Promtail's positions file implementation which indexes _only by path_.
This PR updates the `positions` package to index files by both path _and_ the label set.
This will allow for smarter handling when updating the status of targets, …

Flow: Add support for labels in loki components positions file

---

cmd/agent/Dockerfile
tools/make/packaging.mk

This PR adds the new build tag which Promtail needs to scrape journald logs. The PR can be used as the base for a patch release to fix this issue.
Fixes #2641.
A changelog entry will be added in Step 2 of our [relase process](https://github.com/grafana/agent/blob/main/docs/developer/releasing.md) for patch releases.

Add 'promtail_journal_enabled tag' to build pipeline

---

cmd/agent/Dockerfile

I am pretty sure the quotes here are needed for the dockerfile build.
I don't think this is worth another patch release. We should be able to force-update the existing 0.30.1 tag and re-trigger the build. Unless we really think this needs a 0.30.2.

(build) fix quoting in dockerfile for 0.30.1

---

CHANGELOG.md
docs/sources/configuration/integrations/blackbox-config.md
docs/sources/configuration/integrations/consul-exporter-config.md
docs/sources/configuration/integrations/dnsmasq-exporter-config.md
docs/sources/configuration/integrations/elasticsearch-exporter-config.md
docs/sources/configuration/integrations/kafka-exporter-config.md
docs/sources/configuration/integrations/memcached-exporter-config.md
docs/sources/configuration/integrations/mongodb_exporter-config.md
docs/sources/configuration/integrations/postgres-exporter-config.md
docs/sources/configuration/integrations/statsd-exporter-config.md
docs/sources/configuration/integrations/windows-exporter-config.md

include_exporter_metrics only applies to node_exporter and redis_exporter, this was a problem in our documentation.
Closes #751

Remove `include_exporter_metrics` from all integrations except redis and node_exporter.

---

Makefile
component/all/all.go
pkg/util/eventually.go
pkg/util/eventually_test.go
tools/agentlint/go.mod
tools/agentlint/go.sum
tools/agentlint/internal/findcomponents/findcomponents.go
tools/agentlint/main.go

This PR introduces a custom linter as `tools/agentlint`. Initially, it only has one pass: ensure that Flow components are imported.
It will investigate `./component/all`, doing the following:
1. Retrieve the list of direct imports of `./component/all`.
2. Examine packages in `./component/...` to determine which declare a Flow component.
1. A package declares a Flow component if it has an `init` function which calls `component.Register`.
3. Ensure that `./component/all` imports all of the discovered component packages.
Run `make agentlint` to build the linter at `./build/agentlint`. 
To run it locally, run the following, and observe that no errors are reported:
```
agentlint ./...
```
You can remove an entry from `./component/all` and rerun to observe errors being reported. 
The linter is …

tools/agentlint: introduce custom linting

---

component/common/loki/positions/positions_test.go

This fixes an issue where Windows runs would fail with the nanosecond sync period

Switch from nanoseconds to seconds.

---

cmd/grafana-agent-operator/Dockerfile

The source binary wasn't updated from #2677.

grafana-agent-operator: fix typo in Dockerfile

---

CHANGELOG.md
component/all/all.go
component/otelcol/receiver/kafka/kafka.go
component/otelcol/receiver/zipkin/zipkin.go
docs/sources/flow/reference/components/otelcol.receiver.otlp.md
docs/sources/flow/reference/components/otelcol.receiver.zipkin.md

This commit adds otelcol.receiver.zipkin as a new Flow component, wrapping around the upstream zipkin receiver from the OpenTelemetry Collector otelcol-contrib distribution.
otelcol.receiver.zipkin spawns an HTTP server which can read Zipkin-formatted traces over the network.
Closes #2293.

otelcol.receiver.zipkin: new component

---

CHANGELOG.md
component/loki/source/file/file.go

This commit changes the debug info for loki.source.file to list the targts in their own blocks instead of as a massive attribute. This aligns how targets are shown to how they are shown in prometheus.scrape, and I (personally) find it generally easier to read.

loki.source.file: put individual targets into blocks (debuginfo)

---

CHANGELOG.md
component/prometheus/relabel/relabel.go

This PR clones the label set before applying relabels. Not cloning lead to two problems:
1. It forces the computed ID of the incoming series to change (as its labels changed), which causes duplicate relabeling caching.
2. It can cause obscure bugs with relabel rules being applied, such as a `keep` action which doesn't work after modifying the original slice.

prometheus.relabel: clone labels before relabeling

---

CHANGELOG.md
component/common/loki/types.go
component/common/relabel/relabel.go
component/discovery/relabel/relabel.go
component/discovery/relabel/relabel_test.go
component/loki/relabel/relabel.go
component/loki/relabel/relabel_test.go
component/prometheus/relabel/relabel.go
component/prometheus/relabel/relabel_test.go
docs/sources/flow/reference/components/discovery.relabel.md
docs/sources/flow/reference/components/loki.relabel.md
docs/sources/flow/reference/components/prometheus.relabel.md

This PR expands on the three relabeling components (`discovery.relabel`, `prometheus.relabel`, `loki.relabel`) to add a new Export field named Rules. The field value is a function that when it's called, it returns the currently-configured relabeling rules in place.
This will be useful for components that generate telemetry themselves instead of scraping it from a third-party source (such as the upcoming `loki.source.*` components), so that they can call into relabeling rules and process any 'internal' labels before discarding them.
To see this in action, here's how it would look as River configuration and component implementation for the upcoming `loki.source.syslog` component.
Wiring in the new field in another component: …

flow: Allow relabeling components to expose configured rules

---

component/phlare/scrape/scrape_loop_test.go

This PR adds a small delay in the httptest server in use by the scrape loop in `TestScrapeLoop` to fix a test that is flaky on Windows.
I've added a new Drone step to run this test 1000 times to verify this fixes the flakiness; I'll remove it if it works.
Nothing for now.

Fix flaky TestScrapeLoop in phlare.scrape

---

.github/workflows/publish-documentation-next.yml
.github/workflows/publish-documentation-versioned.yml

(cherry picked from commit 68ac5a9b7f9d567f045380ff6a9b7cb0bdc60e61)

Update publishing workflows to use PATs with fine-grained access control (#2684)

---

CHANGELOG.md
component/common/loki/types.go

Fix an issue where being unable to send logs to `loki.write` due to the client being permanently backlogged would deadlock the Flow controller.
The `loki.write` client may be permanently backlogged when:
* Limits are reached when sending logs to Loki, leading to endless request retries.
* Loki has an extended outage.
When an EntryHandler is stopped, it will wait for 5 seconds before forcibly stopping the goroutine which queues log entries. If this timeout is reached, any unqueued log entries are permanently lost, as the positions file will likely be updated past the point where the entry was read.
While losing logs is not ideal, it's unacceptable for any Flow component to be able to block the controller. This is a short-term solution to allow the Flow controller to continue working …

Flow: drop unqueued logs after 5 seconds when stopping tailer

---

CHANGELOG.md
pkg/operator/config/templates/component/metrics/pod_monitor.libsonnet
pkg/operator/config/templates/component/metrics/service_monitor.libsonnet

The PR fixes the use of the enableHttp2 field from optionals.string to optional.bool
No issue filed
Should I run anything else like `make crd` here?

operator: Use enableHttp2 field as boolean in libsonnet templates

---

component/loki/process/internal/stages/extensions.go
component/loki/process/internal/stages/extensions_test.go
component/loki/process/internal/stages/output.go
component/loki/process/internal/stages/output_test.go
component/loki/process/internal/stages/pipeline.go
component/loki/process/internal/stages/regex.go
component/loki/process/internal/stages/regex_test.go
component/loki/process/internal/stages/stage.go
component/loki/process/internal/stages/timestamp.go
component/loki/process/internal/stages/timestamp_test.go
component/loki/process/internal/stages/util.go
component/loki/process/internal/stages/util_test.go
component/loki/process/process_test.go
docs/sources/flow/reference/components/loki.process.md

This PR updates `loki.process` to port over some more Promtail stages, namely the `regex`, `timestamp` and `output` processing stages.
These stages are used to construct the pre-defined `docker` and `cri` stages which are syntactic sugar for pre-defined pipelines around the two formats.
Updates #2515

flow: Add support for more stages to `loki.process`

---

CHANGELOG.md
component/all/all.go
component/loki/source/syslog/internal/fake/client.go
component/loki/source/syslog/internal/syslogtarget/metrics.go
component/loki/source/syslog/internal/syslogtarget/syslogtarget.go
component/loki/source/syslog/internal/syslogtarget/syslogtarget_test.go
component/loki/source/syslog/internal/syslogtarget/transport.go
component/loki/source/syslog/syslog.go
component/loki/source/syslog/syslog_test.go
component/loki/source/syslog/types.go
docs/sources/flow/reference/components/loki.source.syslog.md

The PR adds a loki.source.syslog component that spins up listeners for RFC5424-formatted syslog messages over TCP and UDP connections and forwards them to other `loki.*` components.
Each `listener` block in the component's Arguments will start a receiver. Promtail used the term `receiver`, but I chose to use a different one to avoid confusion with the receivers that tie together components. As with other cases,  entries are fanned out to each receiver passed in `ForwardTo` in succession.
Most of the PR size is due to bringing over Promtail's `syslog` package, so that we can use our own `loki.Entry` instance.
Fixes #2505.
To test this component, I've used a configuration and a command like the ones presented below. I'm still …

Flow: add loki.source.syslog component

---

build-image/Dockerfile

Add the [helm-docs](https://github.com/norwoodj/helm-docs) tool into the Linux build image, which is needed for #2695.

build-image: add helm-docs for grafana/agent#2695

---

CHANGELOG.md
component/prometheus/relabel/relabel.go
component/prometheus/remotewrite/remote_write.go
component/prometheus/remotewrite/remote_write_test.go

Fixes #2216. The `prometheus.relabel` and  `prometheus.remote_write` components will now error if data is being sent to them while they are stopped. The reason they are in memory and stopped is that during a config refresh they got deleted, but a component which references them keeps a reference to them since it has to be preserved to be in the last good state (the state prior to the refresh). An issue has been raised to question this behaviour (#2709) - it may be better to preserve the last good state of the graph as a whole instead of the last good state of the individual components. If that were the case, we also would be less likely to see bugs such as this one.
1. An agent was ran locally with this river file:
```
prometheus.scrape "default" {
targets    = [{"__address__" = …
```

Do not action if the component is not running

---

CHANGELOG.md
component/all/all.go
component/otelcol/exporter/loki/internal/convert/convert.go
component/otelcol/exporter/loki/internal/convert/convert_loki.go
component/otelcol/exporter/loki/internal/convert/convert_test.go
component/otelcol/exporter/loki/internal/convert/metrics.go
component/otelcol/exporter/loki/loki.go
docs/sources/flow/reference/components/loki.write.md
docs/sources/flow/reference/components/otelcol.exporter.loki.md
go.mod
go.sum

The PR adds an `otelol.exporter.loki` component that received OTel-formatted log entries, transforms them to Loki log entries and forwards them to other loki comoonents.
The conversion is based on the OTel [loki translator](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/translator/loki) package that is also used by the opentelemetry-collector-contrib's [lokiexporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/lokiexporter), but is applied per-entry instead of per-request.
The conversion format defaults to json, but uses the OTel format hints (i.e. the `loki.format` resource or log attribute) to decide whether to use json or logfmt.
Fixes #2666, …

Flow: add otelcol.exporter.loki component

---

component/common/relabel/relabel.go
component/discovery/relabel/relabel.go
component/discovery/relabel/relabel_test.go
component/loki/relabel/relabel.go
component/loki/relabel/relabel_test.go
component/loki/source/syslog/syslog.go
component/loki/source/syslog/syslog_test.go
component/prometheus/relabel/relabel.go
component/prometheus/relabel/relabel_test.go

After we witnessed the recent introduction of the `Rules` export field for relabeling components drop the entire Agent's throughput, this PR makes it into a struct so it can be comparable and handled by things like `reflect.IsEqual` more gracefully.
I'm still looking into what caused the original issue, let me know if you have any ideas or objections to this.

Flow: rework Rules export of relabeling components into a struct

---

pkg/metrics/agent.go
pkg/metrics/agent_test.go
pkg/metrics/cluster/client/client.go
pkg/metrics/cluster/config.go
pkg/metrics/cluster/config_test.go
pkg/metrics/instance/global.go

- Scraping service related fields produce high amounts of noise when marshaling YAML. This affects both the `/-/config` in the agent itself, as well remote agent management solutions using the Agent as a dependency.
- This PR makes sure that configurations that do not explicitly enable scraping service or change its default configuration do not include such fields.
- These fields include the keys `scraping_service`, `scraping_service_client` under metrics, as well as internal subkeys like `lifecycler` and `kvstore`.
- Also excluded the `global` field under metrics, which is the only remaining top level field with nesting
Example YAML with an empty config:
```yaml
server:
log_level: debug
log_format: logfmt
metrics:
wal_directory: data-agent/
wal_cleanup_age: 12h0m0s
wal_cleanup_period: …
```

Do not marshal default or empty scraping service fields

---

production/kubernetes/agent-bare.yaml
production/kubernetes/agent-loki.yaml
production/kubernetes/agent-traces.yaml
production/tanka/grafana-agent/grafana-agent.libsonnet
production/tanka/grafana-agent/smoke/main.libsonnet
production/tanka/grafana-agent/v1/internal/agent.libsonnet
production/tanka/grafana-agent/v2/internal/base.libsonnet

Explicitly setting the command is not neccesary, but also currently won't work in the Jsonnet because the prefix name change (#2677) for the binaries hasn't been released yet, and the Jsonnet uses a stable release.
Removing an explicit setting of the command allows containers to use the Dockerfile default.

production/tanka: stop explicitly setting command

---

.drone/README.md
.drone/drone.jsonnet
.drone/drone.yml
.drone/pipelines/build_images.jsonnet
.drone/pipelines/check_containers.jsonnet
.drone/pipelines/publish.jsonnet
.drone/pipelines/test.jsonnet
.drone/secrets.jsonnet
.drone/util/build_image.jsonnet
.drone/util/pipelines.jsonnet
Makefile
tools/make/build-container.mk

This changes our Drone file to be generated from Jsonnet. This has some benefits, primarily around code-reuse (such as not having to keep the build image version up to date in many places at once).
The resulting Drone config has some differences from today:
* There are extra pipelines for checking that Docker containers can be built in PRs 
* Test and Lint no longer run commit to main (since they run against merged code in the PR anyway)
* The Release pipeline now waits for the Docker containers to be published first.
* There are extra pipelines for checking that the build images can be built in PRs which modify the build images (otherwise these pipelines are skipped).
The `make drone` target is extended to include converting the Jsonnet to YAML before linting and signing.

Switch Drone to be built with Jsonnet

---

CHANGELOG.md
component/all/all.go
component/otelcol/receiver/opencensus/opencensus.go
component/otelcol/receiver/opencensus/opencensus_test.go
docs/sources/flow/reference/components/otelcol.receiver.opencensus.md
docs/sources/shared/flow/reference/components/authorization-block.md

This adds `otelcol.receiver.opencensus` component to flow.
Fixes #2292

Add an `otelcol.receiver.opencensus` Flow component

---

component/loki/process/internal/stages/drop.go
component/loki/process/internal/stages/drop_test.go
component/loki/process/internal/stages/match.go
component/loki/process/internal/stages/match_test.go
component/loki/process/internal/stages/pipeline.go
component/loki/process/internal/stages/stage.go
docs/sources/flow/reference/components/loki.process.md

This PR updates loki.process to port the two 'filtering' stages available in Promtail, namely `match` and `drop`.
The first one can conditionally either drop, or  run a nested set of processing stages on entries that match a LogQL selector.
The second one can drop entries based on some predefined criteria, which are treated as AND clauses.
Updates #2515 
We're still trying to port these over in smaller batches, so we can review the code and documentation being brought in, as well as make any obvious improvements work.
For this PR, the main change from the upstream Promtail code is not using pointers to denote optional values but letting River handle those.
Finally, the `DropConfig` struct contains both an Expression string …

flow: Add support for filtering stages to loki.process component

---

go.mod
go.sum
pkg/operator/config/metrics_templates_test.go
pkg/operator/config/templates/component/metrics/pod_monitor.libsonnet
pkg/operator/config/templates/component/metrics/service_monitor.libsonnet
pkg/operator/config/templates/ext/optionals.libsonnet

The enable_http2 flag defaults to true in prometheus, so needs to be explicitly set to `false`. `optionals.bool`, was detecting false, and emitting null, but it should not. ADded a param to optionals.bool to supply the default value for cases where the default is true.

operator: fix enable_http2 flag that defaults to true.

---

CHANGELOG.md
pkg/config/instrumentation/remote_config_metrics.go
pkg/config/remote_config.go

Lazily registers `remote_config` metrics to avoid adding metrics unnecessarily when `remote-configs` and `agent-management` features are not enabled.

Lazy Initialize Remote Config Metrics

---

CHANGELOG.md
pkg/river/internal/value/number_value.go
pkg/river/vm/vm_test.go

The Number.Float function converted the uint64 representation directly to float64 for signed numbers. This incorrectly treats the sign flag as part of the number, leading to incorrect results.
For example, `42.0^-2` coerces `-2` to a float64, but doesn't properly handle the sign flag, instead causing `42.0^9223372036854775810` to be evaluated (resulting in `+Inf`).

river: fix an issue where negative numbers incorrectly converted to floats

---

CHANGELOG.md
docs/sources/configuration/logs-config.md
pkg/logs/config.go
pkg/logs/config_test.go
pkg/logs/gobal.go

- Similarly to how we allow setting default configurations for metrics (e.g. remote_writes), this change introduces a global field under the logs section of the config.
- It allows defining default clients for promtail.
- This is useful for agent management, where we only allow defining scrape_configs in the configuration snippets.
Example config:
```yaml
logs:
global:
clients:
- basic_auth:
password: password_default
username: username_default
url: https://default.com
configs:
- name: config1
clients:
- basic_auth:
password: password_override
username: username_override
url: https://override.com
```

Introduce global configuration for logs

---

pkg/config/config.go
pkg/config/config_test.go

Removes an inconsistency where if the remote config did not have a `logs` config element, but the initial config _did_, the logs config would remain.
Adds a test that checks two things for merging the initial and remote configs for agent management:
1. That the `agent_management` block of the initial config is _not_ overwritten by anything in the remote config.
2. That all other values of the initial config are overwritten by what is in the remote config.

[Agent Management] Add Test for Effective Config Merging

---

docs/developer/releasing.md

We usually forget to bump version of agent-operator helm chart after a release is
published. This PR adds instructions in `releasing.md` that helps to complete this
step after a new release is done.

Add instructions to update version of agent operator helm chart

---

pkg/runner/hash_map.go
pkg/runner/hash_map_test.go
pkg/runner/runner.go
pkg/runner/runner_test.go

Many of our Flow components share a behavior of managing goroutines, where they must synchronize the set of running goroutines with a set of tasks to perform:
* `loki.source.file` must manage tailer goroutines for each logs target.
* `phalre.scrape` must manager scraper goroutines for each profiling target.
* `prometheus.scrape` must manage scraper goroutines for each metrics target.
More components with this type of goroutine management will be added in the future (#2504, #2763). Even the Flow controller implements exactly the same goroutine management to manage the set of running components.
Throughout all of these uses, the goroutine management works the same way:
* Start new goroutines for tasks (e.g., targets) that have appeared.
* Shut down old goroutines for tasks that have gone …

pkg/runner: introduce common package for goroutine scheduling

---

.drone/drone.yml
.drone/pipelines/check_containers.jsonnet

Currently, it takes upwards of 40 minutes to run the "Check Windows containers" drone job for every push to a PR.
This change only runs jobs to check containers if the Dockerfile itself has changed, which should reduce the turnaround time on PRs.
Note that these rules come from a [Drone plugin which is being used on our runners](https://github.com/meltwater/drone-convert-pathschanged), so the specific syntax can't be seen in Drone's docs.

drone: only rebuild containers when Dockerfiles change

---

CHANGELOG.md
component/loki/source/file/file.go

Add a check to make sure an entry in c.readers is only created once per target (based on public labels).
Fixes #2803.

loki.source.file: fix tailer goroutine leak

---

CHANGELOG.md
pkg/river/encoding/attribute.go
pkg/river/encoding/attribute_test.go
pkg/river/encoding/encoding_test.go

The UI will now display the values of all River attributes unless they are nil.
Example UI screenshots:
<details>
<summary>remote_write exports</summary>
</details>
<details>
<summary>local_file exports</summary>
</details>
<details>
<summary>node_exporter exports</summary>
</details>
<details>
<summary>node_exporter arguments</summary>
</details>
Fixes #2205
Fixes #2206

Flow API: Display the values of all River attributes unless they are nil

---

component/phlare/scrape/scrape_loop_test.go
component/phlare/scrape/target.go
component/phlare/scrape/target_test.go

This PR decrease the profiling CPU period to interval-1second, we've seen some timeout in the agent because of that and we made the same change in Phlare. see https://github.com/grafana/phlare/commit/c5e677293d21424a444a147b217ddb4f7c150523

Decrease the CPU profiling period to avoid cancellations

---

CHANGELOG.md
component/common/relabel/relabel.go
component/discovery/relabel/relabel.go
component/discovery/relabel/relabel_test.go
component/loki/relabel/relabel.go
component/loki/relabel/relabel_test.go
component/loki/source/gelf/gelf.go
component/loki/source/syslog/syslog.go
component/loki/source/syslog/syslog_test.go
component/prometheus/relabel/relabel.go
component/prometheus/relabel/relabel_test.go
docs/sources/flow/reference/components/discovery.relabel.md
docs/sources/flow/reference/components/loki.relabel.md
docs/sources/flow/reference/components/loki.source.gelf.md
docs/sources/flow/reference/components/prometheus.relabel.md

This PR changes the common Rules export of relabeling components to expose a copy of the slice of configured rules directly. This fixes the propagating of updates to components that use this value.
cc @mattdurham I've also changed the way that we wire relabeling rules in the GELF source component for uniformity, and also updated its docs. Let me know how it works!

Fix Rules export of relabeling components to directly expose the rules

---

CHANGELOG.md
component/all/all.go
component/loki/source/gcplog/gcplog.go
component/loki/source/gcplog/gcplog_test.go
component/loki/source/gcplog/internal/fake/client.go
component/loki/source/gcplog/internal/gcplogtarget/formatter.go
component/loki/source/gcplog/internal/gcplogtarget/formatter_test.go
component/loki/source/gcplog/internal/gcplogtarget/metrics.go
component/loki/source/gcplog/internal/gcplogtarget/pull_target.go
component/loki/source/gcplog/internal/gcplogtarget/pull_target_test.go
component/loki/source/gcplog/internal/gcplogtarget/push_target.go
component/loki/source/gcplog/internal/gcplogtarget/push_target_test.go
component/loki/source/gcplog/internal/gcplogtarget/push_translation.go
component/loki/source/gcplog/internal/gcplogtarget/push_translation_test.go
component/loki/source/gcplog/internal/gcplogtarget/types.go
component/loki/source/syslog/syslog.go
docs/sources/flow/reference/components/loki.source.gcplog.md
go.mod

The PR adds a loki.source.gcplog component that can read logs from GCP cloud resources by making use of Pub/Sub subscriptions.
The component can define a 'pull' strategy where it scrapes a GCP Project ID and subscription given the correct credentials, or a 'pull' strategy where it starts a web server that accepts POST GCP PushRequests. Users must define exactly one strategy; if they want to use both, scrape multiple subscriptions or listen on different ports, then multiple components must be instantiated.
The log entries are then forwarded to other `loki.*` components.
Again, most of the PR size is due to bringing over Promtail's syslog package, so that we can use our own loki.Entry definition. This was also a chance to clean things up to _not_ use the Promtail Target interface and …

Flow: add loki.source.gcplog component

---

CHANGELOG.md
component/all/all.go
component/otelcol/receiver/loki/loki.go
component/otelcol/receiver/loki/loki_test.go
docs/sources/flow/reference/components/otelcol.receiver.loki.md
go.mod
go.sum

The PR adds an otelol.receiver.loki component that receives Loki log entries, transforms them to the OTLP format and forwards them to other `otelcol` components.
The conversion is straightforward and is what the `promtailreceiver` from the opentelemetry-collector-contrib repo [does](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/promtailreceiver/promtail.go) as well; basically just create a new OTLP Logs entry, add the log content and timestamp, append all labels as attributes and send it over.
We're adding one more attribute that keeps track of which attributes came from Loki labels, so it can be used when the opposite conversion happens, to promote this subset of resources back into …

Flow: add otelcol.receiver.loki component

---

pkg/config/agentmanagement.go
pkg/config/agentmanagement_test.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/instrumentation/remote_config_metrics.go

Refactors `agentmanagement.go` so `getRemoteConfig` accepts `remoteConfigProvider`s, which allows for more testing. Adds tests for some cases.
Also splits out the code that parses the flagset (the second time) and sets integrations version in `pkg/config/config.go`, specifically `load`, into a separate function which `getRemoteConfig` also calls. `getRemoteConfig` is also modified to take the parameters needed by this function (the `flagSet`, `args`, and the config `path`).
This is done in order to allow for semantic validation of the remote config inside the agent management code. Otherwise, if the API responds with a semantically invalid config (i.e. it's valid yaml, but it's not a valid agent management config) the _invalid_ remote config will be cached and any agents attempting to use …

[Agent Management] Add Remote Config Validation

---

component/loki/source/gcplog/gcplog_test.go
component/loki/source/heroku/heroku.go
component/loki/source/syslog/syslog.go

The previous condition would always be true, as Update would never get called if the Arguments weren't equal. We only want to restart the listeners if their config, or the relabel config we'd like to pass on to them change. 

flow: Fix bad merge; improve conditions under which heroku and syslog listeners are recreated

---

CHANGELOG.md
component/all/all.go
component/discovery/discovery.go
component/loki/source/kubernetes/kubernetes.go
component/loki/source/kubernetes/kubetail/container_utils.go
component/loki/source/kubernetes/kubetail/kubetail.go
component/loki/source/kubernetes/kubetail/tailer.go
component/loki/source/kubernetes/kubetail/tailer_test.go
component/loki/source/kubernetes/kubetail/target.go
docs/sources/flow/reference/components/loki.source.kubernetes.md
pkg/runner/runner.go

The `loki.source.kubernetes` component, when given a set of targets from `discovery.kubernetes`, tails logs from containers using the Kubernetes API.
One tailer is launched for each unique container. Tailers will reconnect to Kubernetes with exponential backoff if their connection to the Kubernetes API is closed. Tailers only exit if the target is removed from the input or if the tailer determines that the terminated container will not restart.
Closes #2504.

Flow: add loki.source.kubernetes component

---

cmd/grafana-agent/Dockerfile.windows
cmd/grafana-agentctl/Dockerfile.windows

Saving a large layer can be really slow on Windows, so here we clean up the caches after building the UI and binaries to speed up the container builds overall on Windows.

Clean up caches to speed up Windows Docker container builds

---

CHANGELOG.md
pkg/logs/logs.go
pkg/logs/logs_test.go

- Adding, removing and adding again log configuration instances seems to trigger an error due to double registration of metrics. This affects dynamically reloaded configs (for example, via `/-/reload` endpoint or agent management).
- This change makes sure that collectors are unregistered when a given instance is stopped.
- Any ideas on how to test potential side effects?
Co-authored-By: Mischa Thompson <mischabear@gmail.com>

Unregister collectors when stopping promtail instances

---

docs/Makefile

Use podman (https://podman.io) for running containers without a root Docker daemon if it is installed.

Prefer deamonless containers

---

CHANGELOG.md

Somehow mimir.rules.kubernetes was assigned to version v0.30.1 instead of v0.31.0

[release branch] Fix location of mimir.rules.kubernetes in changelog

---

CHANGELOG.md

Somehow mimir.rules.kubernetes was assigned to version v0.30.1 instead of v0.31.0

Fix location of mimir.rules.kubernetes in changelog

---

docs/sources/flow/_index.md

* Remove suggestion that Flow isn't suitable for production. Our testing has shown that it's stable in production, and the only thing people would need to be concerned about is breaking changes. 
* This suggestion probably should've been removed when Flow graduated to beta, I left it in by mistake. 
* Update list of limitations, which has fallen out of sync since the v0.28 release.
Once this is merged to main, I'll create a second PR to cherry pick it to release-v0.31.

docs: update landing page for Flow

---

docs/sources/flow/reference/components/mimir.rules.kubernetes.md

Quick update to the documentation for `mimir.rules.kubernetes` following a discussion with @Logiraptor

mimir.rules.kubernetes component: add RBAC information to the docs

---

CHANGELOG.md
component/prometheus/fanout.go
component/prometheus/scrape/scrape.go
docs/sources/flow/reference/components/prometheus.relabel.md
docs/sources/flow/reference/components/prometheus.scrape.md

Adding new metrics for prometheus components:
* `agent_prometheus_scrape_targets_gauge`
* `agent_prometheus_forwarded_samples_total`
I tested this locally by using a config file with a scrape -> relabel -> remote_write. The `/metrics` endpoint reported these new metrics:
```
agent_prometheus_scrape_targets_gauge{component_id="prometheus.scrape.default"} 1
agent_prometheus_forwarded_samples_total{component_id="prometheus.relabel.default"} 5368
agent_prometheus_forwarded_samples_total{component_id="prometheus.scrape.default"} 5368
```
Fixes #2407

Add extra metrics for prometheus.scrape and prometheus.relabel

---

CHANGELOG.md
cmd/grafana-agent/flow_run.go
component/prometheus/integration/node_exporter/config.go
packaging/deb/grafana-agent.service
packaging/rpm/grafana-agent.service

Three small changes:
* Flow will now reload when a SIGHUP is sent, matching the behavior of static mode.
* Update the deb and rpms to respond to `systemctl reload grafana-agent.service` by sending a SIHGUP to the agent process.
* Fix a broken River stanza introduced in #2629.

Flow: reload when SIGHUP is sent

---

Makefile

Only the main Grafana Agent binary needs CGO_ENABLED=1. This commit disables CGO for every other binary which doesn't needed it.
This fixes an issue where running
```
USE_CONTAINER=1 GOOS=linux GOARCH=arm GOARM=7 make agentctl
```
exited with an error.

Disable CGO when not needed

---

tools/release-note.md

After remaming the binary from `agent` to `grafana-agent` we forgot to update
`release-notes.md` which is the responsible to generate the docs after a release is made.
Changing it in this PR.
Fixes #2884 
I'm going to manually fix the release page.

Use grafana-agent in release-notes.md

---

production/grafana-agent-mixin/alerts.libsonnet

- Make sure the alert does not fire as soon as an agent reports a reload failure, but only after it has been failing consistently for the specified amount of time.
- See https://www.robustperception.io/alerting-on-gauges-in-prometheus-2-0/

Fix agent management alert

---

docs/Makefile

`&>/dev/null` appears to be a bash-ism.

Use more portable output redirection

---

docs/sources/configuration/integrations/cloudwatch-exporter-config.md
pkg/integrations/cloudwatch_exporter/docs/template.md

When reviewing the [PR](https://github.com/grafana/agent/pull/2740) that introduced the CW integration, some of the docs comments applied where not applied as well to the docs template, since a part of that integration's docs are generated.
This PR updates that template to make the check pass.
Also, this PR adds the missing title in the new docs header section.

Fix CloudWatch integration docs template and title

---

pkg/river/internal/rivertags/rivertags_test.go
tools/agentlint/internal/rivertags/rivertags.go
tools/agentlint/main.go

Extend tools/agentlint with a linter for `river` tags, which will help catch improper usages of tags where unit tests for unmarshaling aren't present (first seen in #2629).
Linting rules can be skipped when necessary by adding a `//nolint:rivertags` comment.

tools/agentlint: add linter for river tags

---

build-image/Dockerfile
build-image/windows/Dockerfile

Updates the build image to Go 1.20. I didn't update the changelog; I'll update that once we update the CI to use the new release.

build-image: update to Go 1.20

---

docs/sources/configuration/traces-config.md
pkg/traces/config.go
pkg/traces/config_test.go

otel: allow setting dimension cache size for spanmetrics processor

---

operations/helm/charts/grafana-agent/CHANGELOG.md
operations/helm/charts/grafana-agent/README.md
operations/helm/charts/grafana-agent/README.md.gotmpl

With the release of 0.31.0, there is now a new way to collect logs from containers running on a Kubernetes cluster that doesn't require as much security permissions. This PR seeks to update the README for the Helm chart to direct new users to this component.

(helm) Update helm readme to acknowledge new way of collecting pod logs

---

.github/workflows/test.yml

I removed running macOS tests on commits to main because I thought it wasn't necessary, but it turns out commits to main are responsible for storing the module and build cache which speed up CI runs on PRs.

CI: run macOS tests on commits to main again

---

CHANGELOG.md
docs/sources/flow/reference/stdlib/constants.md
pkg/flow/internal/controller/component_references.go
pkg/river/internal/stdlib/constants.go
pkg/river/internal/stdlib/stdlib.go
pkg/river/vm/vm.go

Add `constants` identifier to stdlib which returns an object of various constants exposing information about the system that Grafana Agent is running on. The initial set of constants is:
* `constants.hostname`: The hostname of the system that Grafana Agent is running on.
* `constants.os`: The operating system that Grafana Agent is running on. 
* `constants.arch`: The architecture of the system that Grafana Agent is running on.
Closes #2703.

flow: add `constants` to stdlib

---

CHANGELOG.md
docs/sources/upgrade-guide/_index.md
production/grafanacloud-install.ps1
tools/release

There are two problems with the documentation on the 0.31 branch:
* The upgrade guide was not updated to point to the latest version
* A change to not zip some release artifacts was not mentioned as a breaking change
Fixes #2887

Mention zip executable breaking change and update the upgrade guide

---

.github/workflows/publish-documentation-next.yml
.github/workflows/publish-documentation-versioned.yml

Update publishing workflows to use organization secret

---

.github/workflows/publish-documentation-next.yml
.github/workflows/publish-documentation-versioned.yml

(cherry picked from commit cdd9e93f5d3ff4c9049c59bdd298c807bae661cb)

[release-v0.30] Update publishing workflows to use organization secret (#2937)

---

.github/workflows/publish-documentation-next.yml
.github/workflows/publish-documentation-versioned.yml

(cherry picked from commit cdd9e93f5d3ff4c9049c59bdd298c807bae661cb)

[release-v0.28] Update publishing workflows to use organization secret (#2937)

---

.github/workflows/publish-documentation-next.yml
.github/workflows/publish-documentation-versioned.yml

(cherry picked from commit cdd9e93f5d3ff4c9049c59bdd298c807bae661cb)

[release-v0.29] Update publishing workflows to use organization secret (#2937)

---

.github/workflows/publish-documentation-next.yml
.github/workflows/publish-documentation-versioned.yml

[release-v0.31] Update publishing workflows to use organization secret (#2937)

---

CHANGELOG.md
pkg/operator/resources_pod_template.go

The Agent Operator currently uses version 0.47.0 of prometheus-config-reloader. This PR will upgrade it to version 0.62.0.
This upgrade was requested by a customer via a support escalation.

Operator: Update prometheus-config-reloader to v0.62.0

---

pkg/river/encoding/block.go
pkg/river/internal/reflectutil/walk.go
pkg/river/internal/reflectutil/walk_test.go
pkg/river/internal/rivertags/rivertags.go
pkg/river/internal/rivertags/rivertags_test.go
pkg/river/internal/value/decode.go
pkg/river/internal/value/decode_test.go
pkg/river/internal/value/value.go
pkg/river/internal/value/value_object.go
pkg/river/internal/value/value_object_test.go
pkg/river/river.go
pkg/river/token/builder/builder.go
pkg/river/types.go
pkg/river/vm/vm.go
pkg/river/vm/vm_block_test.go
tools/agentlint/internal/rivertags/rivertags.go

This PR adds support for adding a `,squash` tag to structs:
```go
type Example struct {
Squashed OtherStruct `river:",squash"` 
}
```
Fields denoted as `,squash` will have their inner attributes and blocks squashed and exposed as top-level attributes and blocks on the parent struct. 
As part of this change, nearly every usage of `reflect.Value.FieldByIndex` has been replaced with a call to a new function, `reflectutil.FieldWalk` which supports walking through intermediate nil fields, either allocating pointers or returning a zero value as appropriate. 
Sorry for the PR size, most of it is tests. 
Closes #2373. 
No existing component is updated to make use of this new feature; that can be done follow up PRs.

river: support squash tags

---

CHANGELOG.md
component/loki/source/podlogs/controller.go

This PR adds a timeout when configuring Informers in `loki.source.podlogs`, which had the potential to block forever if 
the Agent had insufficient RBAC permissions or flaky connection to the control plane. After 10 seconds the context is cancelled and if the error branch is hit due to this, a more informative error message is returned explaining possible causes.
Fixes #2866
Golang is an area I'm not the most fluent in, apologies if some aspects aren't idiomatic; feedback appreciated :)

Add timeout to loki.source.podlogs controller setup

---

docs/sources/about-agent/_index.md

Couldn't test the links that start with /docs until after building website, for example: [Get started with monitoring using an integration](/docs/grafana-cloud/data-configuration/get-started-integration/). We're supposed to use /docs/ links rather than "http" links but they can't be tested without a full website build. See [Links and cross references in the Writers' Toolkit ](https://grafana.com/docs/writers-toolkit/writing-guide/references/)for details.
https://github.com/grafana/agent/issues/2981

Remove latest from grafana cloud links

---

CHANGELOG.md
component/otelcol/processor/tail_sampling/types.go

Use river squash for otelcol.processor.tail_sampling. This doesn't impact the config or docs in any way.
Closes #2986

2986 squash otelcol processor tail sampling

---

.drone/drone.yml
.drone/pipelines/publish.jsonnet

If two jobs try to create the multiarch builder at the same time, it will fail:
https://drone.grafana.net/grafana/agent/6267

drone: use different multiarch builder names across different jobs

---

CHANGELOG.md
pkg/operator/config/metrics_templates_test.go
pkg/operator/config/templates/component/metrics/tls_config.libsonnet

Fixed a reconciliation error in Grafana Agent Operator when using `tlsConfig` on `Probe`.
https://github.com/grafana/agent/issues/3002

Fix TLS configuration for Probe

---

pkg/river/encoding/block.go
pkg/river/encoding/encoding.go
pkg/river/encoding/encoding_test.go
pkg/river/internal/reflectutil/walk.go
pkg/river/internal/reflectutil/walk_test.go
pkg/river/internal/rivertags/rivertags.go
pkg/river/internal/rivertags/rivertags_test.go
pkg/river/internal/value/decode.go
pkg/river/internal/value/decode_test.go
pkg/river/internal/value/value.go
pkg/river/internal/value/value_object.go
pkg/river/river.go
pkg/river/token/builder/builder.go
pkg/river/token/builder/builder_test.go
pkg/river/vm/struct_decoder.go
pkg/river/vm/tag_cache.go
pkg/river/vm/vm.go
pkg/river/vm/vm_block_test.go
tools/agentlint/internal/rivertags/rivertags.go

#2602 originally proposed the idea of squashing structs into slices to support a slice where each element had exactly one field set to a non-zero value. 
I tried implementing it as originally suggested in #2602, but found it unintuitive and hard to follow in the code. 
This PR implements an alternative approach to #2602, supporting a new field type called "enum." Enum fields behave as described above: they're slices of a set of blocks, where each element in the slice will have exactly one inner block set. 
Enum fields must be given a name which will be prepended to the set of all blocks in the enum slice. 
For example, given the following two types:
```go 
type Arguments struct {
Blocks []EnumBlock `river:"example,enum,optional"`  
}
type EnumBlock struct {
BlockA struct{...} …
```

river: support "enum" blocks

---

component/loki/process/process.go
component/loki/process/process_test.go
component/loki/source/file/decompresser_test.go
component/loki/source/file/file.go
component/loki/source/file/file_test.go

This PR fixes the issue where goroutines were leaking in the loki.process and loki.source.file components due to a) not properly shutting down the channels used to Wrap around a pipeline and b) not shutting down the positions file.
I originally believed that the input/output channels for the pipeline would be simply garbage collected, but I should have read it more closely.
This is a bit tedious and error prone. Should we make it easier for component authors by changing the types we ported over from Promtail in the `common/loki` package?

Avoid goroutine leaks in loki.process, loki.source.file components

---

CHANGELOG.md
component/remote/s3/types.go
docs/sources/flow/reference/components/remote.s3.md

Change `client_options` to `client` in code and documentation.
Closes #3001 

Change client_options to options in `remote.s3`

---

operations/helm/charts/grafana-agent/CHANGELOG.md
operations/helm/charts/grafana-agent/README.md
operations/helm/charts/grafana-agent/templates/configmap.yaml
operations/helm/charts/grafana-agent/values.yaml

[Due to previous conversations in this PR](https://github.com/grafana/agent/pull/2922) I propose the following change.  This allows us/users to provide references `{{ .Values.someAbitraryKey }}` inside their configMap string-block that will interpolate based on values provided rather than mergeOverwrite with a structured block.  
One specific use case this enables is the use of `helm secrets` whose secret values (integrations/basic, basic auth, etc) can be stored in a separate (encrypted) file but used inside the string configuration block

feat: adding template support into the configmap

---

CHANGELOG.md
cmd/grafana-agent/mode.go
component/otelcol/internal/featuregate/install.go
docs/sources/flow/getting_started.md

EXPERIMENTAL_ENABLE_FLOW was first deprecated in v0.30, and scheduled for removal for v0.32. To enable Flow mode, the `AGENT_MODE` environment variable must be set to `flow`.

Remove support for EXPERIMENTAL_ENABLE_FLOW environment variable 

---

docs/sources/flow/reference/components/loki.echo.md
docs/sources/flow/reference/components/loki.source.kubernetes.md
docs/sources/flow/reference/components/loki.source.podlogs.md
docs/sources/flow/reference/components/mimir.rules.kubernetes.md
docs/sources/flow/reference/components/otelcol.exporter.loki.md
docs/sources/flow/reference/components/otelcol.exporter.prometheus.md
docs/sources/flow/reference/components/otelcol.receiver.loki.md
docs/sources/flow/reference/components/otelcol.receiver.prometheus.md
docs/sources/flow/reference/components/phlare.scrape.md
docs/sources/flow/reference/components/phlare.write.md
docs/sources/operation-guide/_index.md
docs/sources/shared/flow/stability/beta.md
docs/sources/shared/flow/stability/experimental.md

Change description of experimental components to drop requirement about feature flags.

docs: add warning banner for beta/experimental components

---

docs/sources/flow/reference/components/loki.process.md
production/operator/templates/agent-operator.yaml
production/tanka/grafana-agent-operator/util/k8slogs.libsonnet

I noticed that using the out-of-the-box configuration that I didn't have any `container` label on logs.
From https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config
>  `__meta_kubernetes_pod_container_name`: Name of the container the target address points to.
The docs/samples in this repo were missing the `pod_` part of that.

Fix use of incorrect label for container name

---

docs/developer/releasing.md

Me and @tpaschalis did a release recently, and noticed that some things we normally do are not in the instructions. I hope this update will make them more complete and more clear.
To see the rendered markdown, please go to [docs/developer/releasing.md](https://github.com/grafana/agent/blob/update-rel-instructions/docs/developer/releasing.md)

Update release instructions

---

.drone/drone.yml
.drone/pipelines/crosscompile.jsonnet
CHANGELOG.md
tools/make/packaging.mk

When working on the v0.32.0-rc.0 release, we noticed the 32-bit ARMv6 build is broken and preventing us from releasing.
It seems that removing the embedded Flow UI for ARMv6 restores the builds. Since it doesn't seem like anyone on 32-bit ARM is using Flow, we are temporarily removing support while we wait for Go 1.20.2 which fixes the linker issue we're running into.

ci: have crosscompile jobs build with journald support

---

operations/helm/charts/grafana-agent/CHANGELOG.md
operations/helm/charts/grafana-agent/templates/rbac.yaml
operations/helm/tests/create-daemonset/grafana-agent/templates/rbac.yaml
operations/helm/tests/create-deployment/grafana-agent/templates/rbac.yaml
operations/helm/tests/create-statefulset/grafana-agent/templates/rbac.yaml
operations/helm/tests/custom-config/grafana-agent/templates/rbac.yaml
operations/helm/tests/default-values/grafana-agent/templates/rbac.yaml
operations/helm/tests/existing-config/grafana-agent/templates/rbac.yaml
operations/helm/tests/extra-ports/grafana-agent/templates/rbac.yaml
operations/helm/tests/faro-ingress/grafana-agent/templates/rbac.yaml
operations/helm/tests/static-mode/grafana-agent/templates/rbac.yaml

Add rbac value in order for eventhandler to read kubernets events. According to https://grafana.com/docs/agent/latest/configuration/integrations/integrations-next/eventhandler-config/, grafana-agent need to be able to read the `events` resources.

fix(helm): add rbac for eventhandler

---

docs/developer/releasing.md

Update tagging instructions to explicitly sign commits (to be safe) and only push the most recent tag rather than all local tags.

Update tagging instructions for releases

---

.drone/drone.yml
.drone/pipelines/publish.jsonnet

This PR separates out management of the QEMU container and buildx driver to tolerate the same runner building multiple containers in parallel.

ci: make parallelized publish job more resilient

---

component/loki/source/file/file_test.go
component/loki/source/journal/journal_test.go
component/loki/source/windowsevent/component_test.go
component/loki/source/windowsevent/component_windows.go
pkg/agentctl/walstats_test.go
pkg/config/dynamicloader_configs_test.go
pkg/config/dynamicloader_template_test.go
pkg/logs/logs_test.go
pkg/metrics/cleaner_test.go
pkg/metrics/instance/instance_integration_test.go
pkg/metrics/instance/instance_test.go
pkg/metrics/wal/wal_test.go

This pull request replaces `os.MkdirTemp` with `t.TempDir`. We can use the `t.TempDir` function from the `testing` package to create temporary directory. The directory created by `t.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := os.MkdirTemp("", "")
require.NoError(t, err)
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```

test: use `t.TempDir` to create temporary test directory

---

.github/pull_request_template.md

Many contributors (specially new ones) only add the issue id in `Which issue(s) this PR fixes`
and hoping that this will be close automatically. Hopefully, with this comment contributors will be
aware that they need to add Close or Fixes before the issue id.

Add clarification in PR template about closing issues

---

CHANGELOG.md
component/loki/source/kubernetes/kubetail/tailer.go
component/loki/source/kubernetes/kubetail/target.go

This adds a maximum lifetime (1 hour) for each tailing connection to a container. This fixes an issue where the connection between the agent, the Kubernetes API server, and the Kubelet can get disrupted without closing the TCP connection, leading to no logs being read.
This bug fix impacts `loki.source.kubernetes` and `loki.source.podlogs`, which both use the kubetail package. 
Closes #3093.

kubetail: add a max lifetime for tailing logs from a container

---

component/discovery/aws/ec2.go
tools/agentlint/internal/rivertags/rivertags.go

This adds a linting rule where if a struct has at least one field with a `river` tag, an error is emitted if there is a field with `json`/`yaml` tags but no `river` tags. 
I fixed the one instance which fails this check.

agentlint: alert when a Flow component uses the wrong field tag

---

build-image/Dockerfile

Viceroy v0.3.0 supports s390x.
Related to #3068.
I've also added Helm, which was missing to be able to run `make generate-helm-tests generate-helm-docs` via the build container without installing Helm or helm-docs.

Update build image to viceroy v0.3.0

---

CHANGELOG.md
component/phlare/scrape/manager.go
component/phlare/scrape/scrape_loop.go
component/phlare/scrape/scrape_loop_test.go
component/phlare/scrape/scrape_test.go
component/phlare/scrape/target.go
pkg/flow/internal/controller/loader.go

This PRs improves the target reloading in `phlare.scrape` component.
We basically only wait for the scraping loop to end when shutting down the component, but not anymore when reloading targets.
This means the target will gracefully finish and terminate asynchronously.
Finally @rfratto help me figure a second bug that was caused by a lock taken while retrying push to the backend but it was required only to update the status.
Fixes #2871 
Going to test this in dev.

Improve Phlare target reloading

---

CHANGELOG.md
component/all/all.go
component/otelcol/auth/oauth2/oauth2.go
component/otelcol/auth/oauth2/oauth2_test.go
docs/sources/flow/reference/components/otelcol.auth.oauth2.md
docs/sources/flow/reference/components/otelcol.receiver.kafka.md
docs/sources/shared/flow/reference/components/otelcol-tls-config-block.md

Add a `otelcol.auth.oauth2` component which ports over [oauth2client](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/oauth2clientauthextension)
Fixes #2357

Add a otelcol.auth.oauth2 component

---

operations/helm/charts/grafana-agent/CHANGELOG.md
operations/helm/charts/grafana-agent/README.md
operations/helm/charts/grafana-agent/templates/containers/_agent.yaml

hostPort is useful to set for UDP traffic from on-node tracers in a daemonset deployment.
Helm Chart: Adds hostPort to the extraPorts fields, along with documentation for same.
Fixes #3129  
Tested on a live cluster.  Not confident about running the helm test system in the repo.

fix #3129 - Support hostPort

---

CHANGELOG.md
component/loki/source/kubernetes/kubetail/tailer.go
component/loki/source/kubernetes/kubetail/target.go

* kubetail: add a max lifetime for tailing logs from a container
This adds a maximum lifetime (1 hour) for each tailing connection to a container. This fixes an issue where the connection between the agent, the Kubernetes API server, and the Kubelet can get disrupted without closing the TCP connection, leading to no logs being read.
* fix misassignment of UID for tailing container
* explain MinBackoff 0
(cherry picked from commit 6788e3f5c4e0ebe3186f003762f891c46221c22e)

Cherry-pick "kubetail: add a max lifetime for tailing logs from a container (#3087)" into release v0.31
